---@diagnostic disable: undefined-global -- emu/C/callbacks/console/socket are mGBA runtime globals (runner.c)
-- pc.lua — shared entry flow for the Bill's-PC box scenarios (bills_pc_ops /
-- box_change_roundtrip): boot → seeded new game → bedroom → Pallet Town →
-- Route 1 → Viridian City → the Pokémon Center → the PC in the top-right
-- corner → "SOMEONE's PC" → the Bill's PC box menu on screen.
--
-- This walks the REAL overworld (no warp seeding) so the scenario enters
-- BillsPC_ through the genuine PC main-menu handoff — the path that sets
-- BIT_USING_GENERIC_PC and BIT_NO_MENU_BUTTON_SOUND, the same state the
-- port's RunBillsPCTest harness mimics (see the sram-emulation memory's
-- harness-traps section).
--
-- NAVIGATION MODEL — target square + runtime re-planning, not fixed steps.
-- The passable grids below are derived from the pret map data (maps/*.blk +
-- gfx/blocksets/*.bst + the coll_tiles lists; a square is enterable iff the
-- bottom-left 8x8 tile of its 16x16 block is in the tileset's list — pret
-- collision reads exactly that tile, see engine/overworld/player_state.asm
-- _GetTileAndCoordsInFrontOfPlayer's per-facing lda_coord picks).
-- Regenerate with tools/mgba_harness/gen_walk_grids.py after any map edit.
-- Ledge tiles are absent from the lists, so ledges read as walls — correct
-- for this northbound walk.
--
-- Why re-planning: a fixed step list wedges when something parks on it. The
-- first bills_pc_ops runs deterministically hung at Viridian (30,21)→(30,20):
-- tile passable, no sprite at the square in ANY probe history — but in the
-- scenario's own input history a blocker (RNG-walked NPC or the slot-15
-- Pikachu sprite, which trails the player even pre-lab) parked there for
-- 6000+ frames, and retry-in-place replayed the same wall forever. goto_xy
-- marks the stalled square avoided, BFSes a fresh path from where it stands,
-- and only clears its avoid set once it actually moves. mGBA is
-- deterministic, so whatever detours a run takes, its golden reproduces
-- byte-identically.
--
-- Seeding: the full seed.debug_new_game happens INSIDE the Center, standing
-- at the PC — after all walking. battle.lua measured that seeding in the
-- bedroom broke the first walk step; nothing before the PC reads the
-- party/bag, and wGrassRate=0 (written on arrival at Route 1) is all the
-- walk itself needs (no wild encounters on the way).

local scenario = require("lib.scenario")
local input = require("lib.input")
local navigate = require("lib.navigate")
local seed = require("lib.seed")
local battle = require("lib.battle")

local pc = {}

local VIRIDIAN_CITY = 1        -- pret constants/map_constants.asm
local VIRIDIAN_POKECENTER = 41 -- $29

-- Passable grids ('.' enterable, '#' not), row = map y, col = map x.
-- DO NOT EDIT BY HAND — generated by tools/mgba_harness/gen_walk_grids.py.
local ROUTE1_GRID = {
	"...#.....#..#.....#.",
	"...#######..#######.",
	"...#..............#.",
	"...#..............#.",
	"...#.....#........#.",
	"...###########....#.",
	"...#.....#........#.",
	"...#.....#........#.",
	"...#.....#........#.",
	"...#######........#.",
	"...#..............#.",
	"...#..............#.",
	"...#..............#.",
	"...###########....#.",
	"...#..............#.",
	"...#..............#.",
	"...#..............#.",
	"...#..............#.",
	"...#..............#.",
	"...##.###.#########.",
	"...#..............#.",
	"...#..............#.",
	"...#..............#.",
	"...#########....###.",
	"...#..............#.",
	"...#..............#.",
	"...#..............#.",
	"...###...##########.",
	"...#..............#.",
	"...#..............#.",
	"...#..............#.",
	"...#..............#.",
	"...#######..#######.",
	"...#.....#..#.....#.",
	"...#.....#..#.....#.",
	"...#.....#..#.....#.",
}
local VIRIDIAN_GRID = {
	"#################...####################",
	"#################..#####################",
	"#################...####............####",
	"#################...####............####",
	"######........#.............######..####",
	"######..########............######..####",
	"######.##########...#.......######..####",
	"######.##########...#......#####.#..####",
	"######.##########...####............####",
	"######.##########...#.##################",
	"######.##########...................####",
	"######.##########...................####",
	"######.##########...................####",
	"######.##########...####################",
	".......##########...####............####",
	".......##########...#.##............####",
	"........########............####....####",
	".................#..####....####....####",
	"####........................####....####",
	"####........................#.##....####",
	"####................................####",
	"########............................####",
	"####....#.............####..........####",
	"####....##............####..........####",
	"####....######........####..........####",
	"####....######........#.##..........####",
	"####....######......................####",
	"###############.###.####################",
	"...#................................####",
	"...#.................#..............####",
	"...#................................####",
	"...#################..##################",
	".............#.....#..#.....#...........",
	".............#.....#..#.....#...........",
	".............#.....#..#.....#...........",
	".............#.....#..#.....#...........",
}
local CENTER_GRID = {
	"##########.#.#",
	"###..###......",
	"###########.##",
	"#............#",
	"#.............",
	"#.............",
	"##....##....##",
	"##....##....##",
}

local function passable(grid, x, y)
	local row = grid[y + 1]
	return row ~= nil and x >= 0 and x < #row and row:sub(x + 1, x + 1) == "."
end

-- BFS shortest path (x0,y0)→(tx,ty); returns a list of "UP"/"DOWN"/... steps,
-- or nil. `avoid` is a set of "x,y" keys treated as walls.
local DIRS = {
	{ 0, -1, "UP" }, { 0, 1, "DOWN" }, { -1, 0, "LEFT" }, { 1, 0, "RIGHT" },
}
local function bfs(grid, x0, y0, tx, ty, avoid)
	local tkey = tx .. "," .. ty
	local prev, q, head = { [x0 .. "," .. y0] = false }, { { x0, y0 } }, 1
	while q[head] do
		local x, y = q[head][1], q[head][2]
		head = head + 1
		if x == tx and y == ty then
			local steps, k = {}, tkey
			while prev[k] do
				table.insert(steps, 1, prev[k][3])
				k = prev[k][4]
			end
			return steps
		end
		for _, d in ipairs(DIRS) do
			local nx, ny = x + d[1], y + d[2]
			local nk = nx .. "," .. ny
			if prev[nk] == nil and passable(grid, nx, ny) and not avoid[nk] then
				prev[nk] = { nx, ny, d[3], x .. "," .. y }
				q[#q + 1] = { nx, ny }
			end
		end
	end
	return nil
end

-- Walk to (tx,ty) on `grid`, re-planning around anything that parks in the
-- way. navigate.walk stalls → the square ahead goes into the avoid set and
-- the path is re-BFSed from the current square; any actual movement clears
-- the set (the old blocker info is stale the moment we move).
local function goto_xy(grid, tx, ty, what)
	local avoid = {}
	for _ = 1, 40 do
		local y, x = navigate.coords()
		if x == tx and y == ty then
			return
		end
		local steps = bfs(grid, x, y, tx, ty, avoid)
		if not steps then
			-- every alternative is avoided: forget the stale blockers, give
			-- any wanderer time to move on, try again
			avoid = {}
			scenario.wait(120)
		else
			-- compress into direction runs and walk them
			local i = 1
			while i <= #steps do
				local dir, n = steps[i], 1
				while steps[i + n] == dir do
					n = n + 1
				end
				local ok = pcall(navigate.walk, dir, n)
				local ny, nx = navigate.coords()
				if not ok then
					local d
					for _, dd in ipairs(DIRS) do
						if dd[3] == dir then d = dd end
					end
					avoid[(nx + d[1]) .. "," .. (ny + d[2])] = true
					scenario.log(("pc: %s walk %s stalled at (%d,%d); avoiding the square ahead")
						:format(what, dir, ny, nx))
					break
				end
				if ny ~= y or nx ~= x then
					avoid = {}
				end
				y, x = ny, nx
				i = i + n
			end
		end
	end
	error(("pc: could not reach (%d,%d) [%s]"):format(tx, ty, what))
end

-- Bedroom → standing at (13,4) in the Viridian Pokémon Center, facing the PC,
-- with the full debug_new_game seed applied. Does NOT touch the PC yet.
function pc.to_viridian_center_pc(sym, text)
	battle.walk_to_route1(sym)

	-- No wild encounters on the Route 1 walk: rate 0 fails every grass roll.
	scenario.exec(function()
		emu:write8(sym:addr("wGrassRate"), 0)
	end)

	-- Route 1 exit column x=11 (the north opening), then cross.
	goto_xy(ROUTE1_GRID, 11, 0, "Route 1")
	navigate.walk_until_map("UP", VIRIDIAN_CITY)
	local y, x = navigate.coords()
	scenario.log(("pc: in Viridian City at (%d,%d)"):format(y, x))

	-- One square below the Pokécenter door (23,25), then cross the warp.
	goto_xy(VIRIDIAN_GRID, 23, 26, "Viridian")
	navigate.walk_until_map("UP", VIRIDIAN_POKECENTER)
	scenario.wait(30) -- map fade-in

	-- The square below the PC's hidden event at (13,3) (SPRITE_FACING_UP).
	goto_xy(CENTER_GRID, 13, 4, "Center")
	-- Face the PC: (13,3) is impassable (the PC itself), so a short press
	-- turns in place / bumps without moving.
	input.press_for("UP", 6)
	scenario.wait(10)

	-- Seed AFTER all walking (the battle.lua bedroom-seed lesson). The party
	-- must exist before the PC opens: the deposit flow lists it.
	scenario.exec(function()
		seed.debug_new_game(sym, text:encode(seed.PLAYER_NAME))
	end)
	scenario.log(("pc: at the Center PC, seeded, frame %d"):format(scenario.frame()))
end

-- Activate the PC and enter Bill's box UI as a generic-PC guest:
-- A on the PC → "turned on the PC" → PC main menu → SOMEONE's PC →
-- the WITHDRAW/DEPOSIT/RELEASE/CHANGE BOX/PRINT BOX/SEE YA menu.
-- ("SOMEONE" not "SOMEONE's": the 's is a single charmap ligature tile that
-- gbtext's one-glyph encoder cannot produce, and "SOMEONE" is unique here.)
function pc.open_someones_pc(text)
	-- "<PLAYER> turned on / the PC." — the needle must not span the line break
	navigate.tap_until("A", text:encode("turned on"))
	-- prompt ▼ → PC main menu ("SOMEONE's PC" is uppercase only in the menu)
	navigate.dialog_until_text(text:encode("SOMEONE"))
	scenario.wait(30) -- settle: a tap into a just-drawn menu is swallowed
	navigate.choose(text:encode("SOMEONE"))
	-- "Accessed someone's PC." para "Accessed #MON Storage System." (2 pages)
	navigate.dialog_until_text(text:encode("WITHDRAW"))
	scenario.wait(30)
end

return pc
