; pair_collision_tile_ids.asm — tileset id, tile 1, tile 2. $FF-terminated. The player may not cross
; between tile 1 and tile 2 (simulates elevation). Consumer: engine/overworld/ledges.asm.
;
; pret ref: data/tilesets/pair_collision_tile_ids.asm:TilePairCollisionsLand/Water
;
; Generated by tools/generators/gen_static_tables.py into assets/pair_collision_tile_ids.inc. This carrier sits at the
; mirrored path dos_port/src/data/tilesets/pair_collision_tile_ids.asm; it was part of src/data/tileset_data.asm until 2026-08-16
; (docs/current_plan_data_path_mirror.md).
;
; Embedded data goes in .data per the linker rule in docs/assembly.md (.rodata has
; no output-section rule and reads back as zero).
bits 32

%include "gb_constants.inc"
%include "assets/map_dims.inc"          ; tileset ids: OVERWORLD/FOREST/CAVERN/...

global TilePairCollisionsLand
global TilePairCollisionsWater

section .data
align 4

%include "assets/pair_collision_tile_ids.inc"
