; bills_house_pc.asm — Bill's House PC hidden-event handler and Eevee-evolution
; Pokémon list.
;
; Faithful translation of pret engine/events/hidden_events/bills_house_pc.asm.
; This is the hidden-object PC prop in Bill's house (data/events/hidden_events.asm:
; `hidden_event 1, 4, BillsHousePC, SPRITE_FACING_UP`) — the teleporter/cell-
; separator cutscene machine, NOT the box-storage PC UI
; (src/engine/pokemon/bills_pc.asm, a different pret file entirely reached from
; a different hidden-event handler, OpenBillsPCText/engine/pokemon/bills_pc.asm).
; BillsHousePC never calls into that box UI on either side, pret or port.
;
; Register map (SM83 -> x86): A->AL, BC->BX (B->BH, C->BL), HL->ESI.
; GB memory is [ebp + addr] (gb_memmap.inc).
;
; TWO-TIER RULE: BillsMonListText (Eevee/Flareon/Jolteon/Vaporeon/Cancel menu
; list) and the 2 pure `text_far _X / text_end` wrappers
; (BillsHousePokemonListText1/2) are Tier-1 data, generated by
; tools/generators/gen_bills_house_pc_text.py into
; assets/bills_house_pc_text.inc, %included below — NOT re-declared `global`
; here (see the note above the wrapper section).
;
; PREDEF_CODE / TEXT_ASM TRAP (src/data/text_predef_pointers.asm ids 48/49):
; BillsHouseInitiatedText and BillsHousePokemonList are both `predef_code` rows
; — DisplayTextID's TEXT_PREDEF branch does a bare `call esi` straight at the
; label (TEXT_ASM_ENTRY sentinel), so each label must be x86 CODE at offset 0.
; Both keep pret's own text_far/text_promptbutton/text_asm command bytes
; VERBATIM at a local `.stream` label instead of at the label's own offset 0,
; and the label itself becomes a three-instruction trampoline that does
; exactly what DisplayTextID's own `.notScriptEntry` path does with a stream
; (src/home/text_script.asm): select the overworld dialog projection, then
; PrintText_NoCreatingTextBox. TX_START_ASM inside `.stream` is dispatched by
; TextCommandProcessor's `.cmd_asm` (`push .next_cmd / jmp esi`), which is
; pret's `ld de, NextTextCommand / push de / jp hl` exactly, so each `.hook`
; runs under pret's own control-flow contract. Same pattern as
; src/engine/events/hidden_events/town_map.asm:TownMapText and
; vermilion_gym_trash.asm:VermilionGymTrashSuccessText1/Text3/
; VermilionGymTrashSuccessPlaySfx (the last one is the bare-text_asm shape,
; matching BillsHousePokemonList exactly).
;
; Build: nasm -f coff -I include/ -I . -D BUG_FIX_LEVEL=0 -o /dev/null \
;            src/engine/events/hidden_events/bills_house_pc.asm

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "coords.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/audio_constants.inc"
%include "assets/script_constants.inc"
%include "predef.inc"
%include "assets/predef_text_ids.inc"

; Tier-1 generated text data (assets/bills_house_pc_text.inc)
%include "assets/bills_house_pc_text.inc"

section .text

global BillsHousePC
global BillsHouseInitiatedText
global BillsHousePokemonList
; NOTE: BillsMonListText / BillsHousePokemonListText1 / BillsHousePokemonListText2
; are DEFINED (and `global`'d) in the generated assets/bills_house_pc_text.inc
; %included above — declaring them global here too would make the label DB
; resolve their provider to this .asm, where the body does not exist (same
; trap documented in cinnabar_gym_quiz.asm).

extern EnableAutoTextBoxDrawing         ; src/home/window.asm
extern PrintPredefTextID                ; src/home/predef_text.asm
extern DelayFrames                      ; src/home/delay.asm
extern PlaySound                        ; src/home/audio.asm
extern WaitForSoundToFinish             ; src/home/delay.asm
extern PlayDefaultMusic                 ; src/home/audio.asm
extern StopAllMusic                     ; src/home/audio.asm
extern TextScriptEnd                    ; src/home/overworld_text.asm
extern SaveScreenTilesToBuffer1         ; src/home/tilemap.asm
extern SaveScreenTilesToBuffer2         ; src/home/tilemap.asm
extern LoadScreenTilesFromBuffer2       ; src/home/tilemap.asm
extern PrintText                        ; src/home/window.asm
extern PrintText_NoCreatingTextBox      ; src/home/window.asm — ESI = flat TX stream
extern text_msgbox                      ; src/home/text.asm — active msgbox projection
extern msgbox_dialog                    ; src/home/text.asm — overworld dialog projection
extern TextBoxBorder                    ; src/home/text.asm
extern PlaceString                      ; src/home/text.asm
extern HandleMenuInput                  ; src/home/window.asm
extern DisplayPokedex                   ; src/home/map_objects.asm

; ─────────────────────────────────────────────────────────────────────────────
; BillsHousePC — pret engine/events/hidden_events/bills_house_pc.asm:BillsHousePC
; ─────────────────────────────────────────────────────────────────────────────
BillsHousePC:
    call EnableAutoTextBoxDrawing
    mov al, [ebp + wSpritePlayerStateData1FacingDirection]
    cmp al, SPRITE_FACING_UP
    jne .ret
    CheckEvent EVENT_LEFT_BILLS_HOUSE_AFTER_HELPING
    jnz .displayBillsHousePokemonList
    CheckEventReuseA EVENT_USED_CELL_SEPARATOR_ON_BILL
    jnz .displayBillsHouseMonitorText
    CheckEventReuseA EVENT_BILL_SAID_USE_CELL_SEPARATOR
    jnz .doCellSeparator
.displayBillsHouseMonitorText:
    tx_pre_id BillsHouseMonitorText
    jmp PrintPredefTextID
.doCellSeparator:
    mov byte [ebp + wDoNotWaitForButtonPressAfterDisplayingText], 1
    tx_pre BillsHouseInitiatedText
    mov cl, 32
    call DelayFrames
    mov al, SFX_TINK
    call PlaySound
    call WaitForSoundToFinish
    mov cl, 80
    call DelayFrames
    mov al, SFX_SHRINK
    call PlaySound
    call WaitForSoundToFinish
    mov cl, 48
    call DelayFrames
    mov al, SFX_TINK
    call PlaySound
    call WaitForSoundToFinish
    mov cl, 32
    call DelayFrames
    mov al, SFX_GET_ITEM_1
    call PlaySound
    call WaitForSoundToFinish
    call PlayDefaultMusic
    SetEvent EVENT_USED_CELL_SEPARATOR_ON_BILL
.ret:
    ret
.displayBillsHousePokemonList:
    mov byte [ebp + wDoNotWaitForButtonPressAfterDisplayingText], 1
    tx_pre BillsHousePokemonList
    ret

; ─────────────────────────────────────────────────────────────────────────────
; BillsHouseInitiatedText — pret engine/events/hidden_events/bills_house_pc.asm:BillsHouseInitiatedText
; TextPredefs id 48 ($30), predef_code row. See file header for why pret's
; `text_far _BillsHouseInitiatedText / text_promptbutton / text_asm` command
; bytes are kept verbatim at `.stream` and the label is a print+dispatch
; trampoline rather than data at offset 0.
; DEVIATION{class=projection; pret=engine/events/hidden_events/bills_house_pc.asm:BillsHouseInitiatedText; behavior=the pret label is a code trampoline that prints an embedded verbatim copy of pret's stream instead of naming the stream itself; evidence=the port's TextPredefs row for BillsHouseInitiatedText carries the TEXT_ASM_ENTRY sentinel and DisplayTextID calls the pointer rather than streaming it, src/home/text_script.asm, so a label naming db bytes would be executed as instructions; lifetime=permanent unless the port's predef table grows a stream-with-asm row kind}
; ─────────────────────────────────────────────────────────────────────────────
BillsHouseInitiatedText:
    mov dword [text_msgbox], msgbox_dialog   ; overworld dialog projection
    mov esi, .stream
    call PrintText_NoCreatingTextBox
    ret
.stream:
    text_far _BillsHouseInitiatedText
    text_promptbutton
    text_asm
.hook:
    call StopAllMusic
    mov cl, 16
    call DelayFrames
    mov al, SFX_SWITCH
    call PlaySound
    call WaitForSoundToFinish
    mov cl, 60
    call DelayFrames
    jmp TextScriptEnd

; ─────────────────────────────────────────────────────────────────────────────
; BillsHousePokemonList — pret engine/events/hidden_events/bills_house_pc.asm:BillsHousePokemonList
; TextPredefs id 49 ($31), predef_code row. pret opens this label with a bare
; `text_asm` (no text_far preamble to print) — same shape as
; vermilion_gym_trash.asm:VermilionGymTrashSuccessPlaySfx, so `.stream` holds
; only the TX_START_ASM byte.
; DEVIATION{class=projection; pret=engine/events/hidden_events/bills_house_pc.asm:BillsHousePokemonList; behavior=the pret label is a code trampoline that dispatches through an embedded verbatim copy of pret's stream instead of naming the stream itself; evidence=the port's TextPredefs row for BillsHousePokemonList carries the TEXT_ASM_ENTRY sentinel and DisplayTextID calls the pointer rather than streaming it, src/home/text_script.asm, so a label naming db bytes would be executed as instructions; lifetime=permanent unless the port's predef table grows a stream-with-asm row kind}
; ─────────────────────────────────────────────────────────────────────────────
BillsHousePokemonList:
    mov dword [text_msgbox], msgbox_dialog   ; overworld dialog projection
    mov esi, .stream
    call PrintText_NoCreatingTextBox
    ret
.stream:
    text_asm
.hook:
    call SaveScreenTilesToBuffer1
    mov esi, BillsHousePokemonListText1
    call PrintText
    xor al, al
    mov [ebp + wMenuItemOffset], al      ; not used
    mov [ebp + wCurrentMenuItem], al
    mov [ebp + wLastMenuItem], al
    mov byte [ebp + wMenuWatchedKeys], PAD_A | PAD_B
    mov byte [ebp + wMaxMenuItem], 4
    mov byte [ebp + wTopMenuItemY], 2
    mov byte [ebp + wTopMenuItemX], 1
.billsPokemonLoop:
    or byte [ebp + wStatusFlags5], (1 << BIT_NO_TEXT_DELAY)
    hlcoord 0, 0
    mov bh, 10
    mov bl, 9
    call TextBoxBorder
    hlcoord 2, 2
    mov eax, BillsMonListText
    call PlaceString
    mov esi, BillsHousePokemonListText2
    call PrintText
    call SaveScreenTilesToBuffer2
    call HandleMenuInput
    test al, PAD_B                       ; bit B_PAD_B, a
    jnz .cancel
    mov al, [ebp + wCurrentMenuItem]
    add al, EEVEE
    cmp al, EEVEE
    je .displayPokedex
    cmp al, FLAREON
    je .displayPokedex
    cmp al, JOLTEON
    je .displayPokedex
    cmp al, VAPOREON
    je .displayPokedex
    jmp .cancel
.displayPokedex:
    call DisplayPokedex
    call LoadScreenTilesFromBuffer2
    jmp .billsPokemonLoop
.cancel:
    and byte [ebp + wStatusFlags5], ~(1 << BIT_NO_TEXT_DELAY) & 0xFF
    call LoadScreenTilesFromBuffer2
    jmp TextScriptEnd
