; cinnabar_gym_quiz.asm — Cinnabar Gym's #MON quiz + gate gate/tile-block driver.
;
; Faithful translation of pret `engine/events/hidden_events/cinnabar_gym_quiz.asm`.
; This IS a real gameplay gate: right/wrong quiz answers set/leave the six
; EVENT_CINNABAR_GYM_GATEn_UNLOCKED flags, and UpdateCinnabarGymGateTileBlocks_
; repaints the six gate blocks in wOverworldMap between locked (gate) and open
; (floor) tile ids from those flags — the only place in this file that mutates
; the live map.
;
; Register map (SM83 -> x86): A->AL, BC->BX (B->BH, C->BL), DE->DX, HL->ESI.
; GB memory is [ebp + addr] (gb_memmap.inc); WRAM/HRAM symbols not already in
; gb_memmap.inc (wGymGateTileBlock, wd474, wOpponentAfterWrongAnswer,
; hGymGateIndex, hGymGateAnswer, hBackupGymGateIndex) resolve through
; assets/pret_ram.inc, which gb_memmap.inc %includes at its tail — every one of
; them is pret's OWN address (some, like hGymGateIndex/hGymGateAnswer at
; $FFDB/$FFDC, are pret hram UNIONS shared with hOaksAideResult &c.; see
; ram/hram.asm — check_ram_collisions.py recognises this as sanctioned, not an
; invented alias) run through the WRAM-growth formula
; (tools/wram_growth.json: port_addr = pret_addr + growth strictly below it).
; HRAM ($FF80-$FFFE) is verified UNSHIFTED (hMapWidth is $FF8C on both sides),
; matching the "addresses at/above $FE00 never shift" invariant.
;
; TEXT STRINGS ARE DATA: the 10 pure `text_far _X / text_end` wrappers
; (the two intro variants, the dummy intro, the 6 quiz questions, the
; wrong-answer line) are generated by
; tools/generators/gen_cinnabar_gym_quiz_text.py into
; assets/cinnabar_gym_quiz_text.inc, flattened under their own names (the
; port's flat TX_FAR model). CinnabarGymQuizCorrectText mixes a text_far intro
; with a real text_asm code tail (flag re-check + go-inside SFX), so its far
; body stays a separate underscore-prefixed label,
; `_CinnabarGymQuizCorrectText` (same generator, same .inc), referenced by a
; real `text_far` command byte here — exactly
; src/engine/battle/effects.asm:ChargeMoveEffectText's pattern.
;
; CinnabarGymGateCoords and CinnabarQuizQuestions are POINTER/COORDINATE
; tables, not strings (two-tier rule: "pointer/address tables are NOT
; strings"), so both are hand-written Tier-2 `dd`/`db` tables below.
; CinnabarQuizQuestions holds 32-bit flat pointers (pret's 2-byte `dw`, doubled
; to 4-byte `dd`) to the generated question-text labels.
;
; MAP_BORDER: CinnabarGym_ReplaceTileBlock recomputes pret's own
; `wOverworldMap + 3*(width+6) + 3 + y*(width+6) + x` (pret's MAP_BORDER=3, so
; "+6"="MAP_BORDER*2", "+3"="MAP_BORDER") using the PORT's MAP_BORDER=7
; (include/gb_memmap.inc) instead of the literal 3/6 pret's source shows —
; CLAUDE.md is explicit that every border-derived quantity must be re-derived
; through MAP_BORDER, never the literal it happens to equal. This is the same
; formula coords.inc's `owcoord` macro encodes
; (`wOverworldMap + (x+MAP_BORDER) + (y+MAP_BORDER)*(width+MAP_BORDER*2)`), but
; that macro takes a compile-time-constant map width; this routine's width is a
; runtime byte (`wCurMapWidth`, since it patches ANY of Cinnabar Gym's own
; blocks generically), so the arithmetic is spelled out by hand instead.
;
; predef calls: CinnabarGymQuiz_AskQuestion / CinnabarGymQuizCorrectText /
; UpdateCinnabarGymGateTileBlocks_ all reach FlagAction through pret's
; `predef`/`predef_jump FlagActionPredef` with every register (HL/B/C) already
; hand-set at the call site. Following the port's established convention
; (src/engine/overworld/toggleable_objects.asm: "call FlagAction directly when
; registers are hand-set — FlagActionPredef begins with GetPredefRegisters,
; which would clobber ESI/BH/CL"), these call FlagAction/CinnabarGymGateFlagAction
; directly rather than going through FlagActionPredef's GetPredefRegisters hop
; (which exists only to undo a GB ROM-bank switch — meaningless in a flat
; address space). FlagAction itself preserves ESI/EDX/EBX (push/pop at entry),
; matching pret's own `push hl/push de/push bc`.
;
; AdjustEventBit is a COMPILE-TIME macro (pret macros/scripts/events.asm): it
; emits `add a, (event%8 - fixedbit)` only when `event%8 != fixedbit`, else
; NOTHING. Both invocations in this file are no-ops, verified against
; assets/event_constants.inc:
;   EVENT_CINNABAR_GYM_GATE0_UNLOCKED = 680, 680%8 == 0  (passed fixed bit: 0)
;   EVENT_BEAT_CINNABAR_GYM_TRAINER_0 = 666, 666%8 == 2  (passed fixed bit: 2)
; so the runtime gate index is used directly as FlagAction's bit-index
; argument in both cases; there is nothing to translate at either call site.
;
; Build (check): nasm -f coff -I include/ -I . -D BUG_FIX_LEVEL=0 -o /dev/null \
;                     src/engine/events/hidden_events/cinnabar_gym_quiz.asm

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"                    ; EVENT_BYTE()
%include "predef.inc"                    ; tx_pre_id
%include "assets/predef_text_ids.inc"    ; CinnabarGymQuiz_id
%include "assets/event_constants.inc"    ; EVENT_CINNABAR_GYM_GATE*_UNLOCKED, EVENT_BEAT_CINNABAR_GYM_TRAINER_*
%include "assets/audio_constants.inc"    ; SFX_DENIED, SFX_GO_INSIDE
%include "assets/cinnabar_gym_quiz_text.inc"   ; the 10 flattened wrappers + _CinnabarGymQuizCorrectText

; wd474 has no gb_memmap.inc entry: gen_pret_ram.py skips emitting any symbol
; already declared locally in a src/**/*.asm file, and src/scripts/CinnabarGym.asm
; already carries `wd474 equ 0xE242` (its own comment: "[WRAM-expansion shifted]").
; NASM equ is FILE-LOCAL, so this file needs the same equ too. Value re-derived
; independently against tools/wram_growth.json: pret wd474 = 0xD474
; (pokeyellow.sym), every growth point below it (0xC3A0/0xC508/0xC5C4/0xC6E8/0xCD81)
; sums to 0xDCE, so port = 0xD474 + 0xDCE = 0xE242 — matches CinnabarGym.asm exactly.

global PrintCinnabarQuiz
global CinnabarGymQuiz
; NOTE: CinnabarGymQuizDummyIntroText / CinnabarGymQuizIntroText /
; CinnabarGymQuizShortIntroText / CinnabarQuizQuestionsText1..6 /
; CinnabarGymQuizIncorrectText are DEFINED (and `global`'d) in the generated
; assets/cinnabar_gym_quiz_text.inc %included above — declaring them global here
; too made the label DB resolve their provider to this .asm, where the body does
; not exist, and faithdiff then reported "body extraction failed (port=MISSING)".
global CinnabarQuizQuestions
global CinnabarGymQuiz_AskQuestion
global CinnabarGymQuizCorrectText
global CinnabarGymGateFlagAction
global UpdateCinnabarGymGateTileBlocks_
global CinnabarGymGateCoords
global CinnabarGym_ReplaceTileBlock

extern EnableAutoTextBoxDrawing         ; src/home/window.asm
extern PrintPredefTextID                ; src/home/predef_text.asm
extern PrintText                        ; src/home/window.asm
extern TextScriptEnd                    ; src/home/overworld_text.asm
extern YesNoChoice                      ; src/home/yes_no.asm
extern WaitForSoundToFinish             ; src/home/delay.asm
extern PlaySound                        ; src/home/audio.asm
extern FlagAction                       ; src/engine/flag_action.asm
extern RedrawMapView                    ; src/engine/overworld/update_map.asm

section .text

; ─────────────────────────────────────────────────────────────────────────────
; PrintCinnabarQuiz — pret cinnabar_gym_quiz.asm:PrintCinnabarQuiz.
; The hidden-event handler at the gym's #MON-quiz tile. Only fires facing up.
; ─────────────────────────────────────────────────────────────────────────────
PrintCinnabarQuiz:
    mov al, [ebp + wSpritePlayerStateData1FacingDirection]
    cmp al, SPRITE_FACING_UP
    jne .notFacingUp
    call EnableAutoTextBoxDrawing
    ; pret: `tx_pre_jump CinnabarGymQuiz`, spelled out (see include/predef.inc —
    ; a jump-out macro at a routine tail defeats the build-graph scanner).
    tx_pre_id CinnabarGymQuiz
    jmp PrintPredefTextID
.notFacingUp:
    ret

; ─────────────────────────────────────────────────────────────────────────────
; CinnabarGymQuiz — pret cinnabar_gym_quiz.asm:CinnabarGymQuiz.
; A text_asm predef body (CinnabarGymQuiz_id, resolved by the flat TextPredefs
; row instead of pret's TX_FAR-anchored predef dispatch — no behavior change).
; Splits the packed wHiddenEventFunctionArgument nibble into hGymGateIndex (low
; nibble, 1-6) and hGymGateAnswer (high nibble, swapped down), prints the right
; intro variant, prints the matching question, arms
; wDoNotWaitForButtonPressAfterDisplayingText, then runs the quiz state machine.
; ─────────────────────────────────────────────────────────────────────────────
CinnabarGymQuiz:
    ; NO `text_asm` COMMAND BYTE HERE — deliberate, and it is not a divergence in
    ; behavior. pret opens this label with `text_asm` ($08) because on the GB a
    ; TextPredefs row is always a STREAM, so TextCommandProcessor has to walk into
    ; the code through TX_START_ASM. The port's TextPredefs row for this label is a
    ; `predef_code` row (src/data/text_predef_pointers.asm, id $33): its size slot
    ; holds TEXT_ASM_ENTRY and text_script.asm:DisplayTextID does `call esi`
    ; STRAIGHT at the label. The label must therefore be CODE at offset 0 — a
    ; leading `db $08` would be executed as x86 (`or dh, al`) and desync the whole
    ; routine. Identical to the port's PickUpItemText (src/home/overworld_text.asm),
    ; which drops pret's text_asm byte for exactly this reason.
    ; (CinnabarGymQuizCorrectText below IS a genuine stream — PrintText walks it —
    ; so it keeps its text_asm byte.)
    mov byte [ebp + wOpponentAfterWrongAnswer], 0    ; xor a / ld [wOpponentAfterWrongAnswer], a
    and byte [ebp + wd474], (~(1 << 7)) & 0xFF       ; res 7, [hl]  (hl = wd474)
    mov al, [ebp + wHiddenEventFunctionArgument]
    mov dl, al                                        ; push af (save A across the two masks; F is not read afterward)
    and al, 0x0F
    mov [ebp + hGymGateIndex], al
    mov al, dl                                        ; pop af
    and al, 0xF0
    rol al, 4                                         ; swap a (nibble swap; low nibble is 0 after and $f0)
    mov [ebp + hGymGateAnswer], al

    movzx eax, byte [ebp + hGymGateIndex]
    mov esi, CinnabarGymQuizIntroText
    cmp al, 1
    je .onFirstQuestion
    mov esi, CinnabarGymQuizShortIntroText
.onFirstQuestion:
    call PrintText

    movzx eax, byte [ebp + hGymGateIndex]
    dec eax                                           ; ldh a,[hGymGateIndex] / dec a  (0-based index)
                                                      ; index is 1-6: the packed nibble comes from the
                                                      ; generated hidden-event rows (assets/hidden_events.inc,
                                                      ; HiddenEventsFor_CINNABAR_GYM: args $01 $12 $13 $14 $05 $16),
                                                      ; so the low nibble is never 0 and this never goes negative
    mov esi, [CinnabarQuizQuestions + eax * 4]         ; pret: word-index * 2 into a dw table;
                                                       ; the port's dd table takes the same 0-based
                                                       ; index scaled by 4 and reads the flat pointer
                                                       ; directly, collapsing pret's ld a,[hli]/ld h,[hl]/ld l,a
    call PrintText

    mov byte [ebp + wDoNotWaitForButtonPressAfterDisplayingText], 1
    call CinnabarGymQuiz_AskQuestion
    jmp TextScriptEnd

; ─────────────────────────────────────────────────────────────────────────────
; Pure text_far wrapper shells (Tier-1 data; byte content generated into
; assets/cinnabar_gym_quiz_text.inc). CinnabarGymQuizDummyIntroText is present
; in pret but never referenced by any pret label — ported verbatim regardless.
; ─────────────────────────────────────────────────────────────────────────────
; (CinnabarGymQuizDummyIntroText / CinnabarGymQuizIntroText /
;  CinnabarGymQuizShortIntroText / CinnabarQuizQuestionsText1..6 /
;  CinnabarGymQuizIncorrectText are all defined AND `global`'d as flattened data
;  labels in assets/cinnabar_gym_quiz_text.inc, %included at the top of this file
;  — they are deliberately NOT re-declared global here, see the note there.)

; ─────────────────────────────────────────────────────────────────────────────
; CinnabarQuizQuestions — pret cinnabar_gym_quiz.asm:CinnabarQuizQuestions.
; A pointer table, not a string (two-tier rule): pret's 2-byte `dw` doubled to
; a 4-byte flat `dd` per entry, keyed by the 0-based question index.
; ─────────────────────────────────────────────────────────────────────────────
section .data
CinnabarQuizQuestions:
    dd CinnabarQuizQuestionsText1
    dd CinnabarQuizQuestionsText2
    dd CinnabarQuizQuestionsText3
    dd CinnabarQuizQuestionsText4
    dd CinnabarQuizQuestionsText5
    dd CinnabarQuizQuestionsText6
section .text

; ─────────────────────────────────────────────────────────────────────────────
; CinnabarGymQuiz_AskQuestion — pret cinnabar_gym_quiz.asm:CinnabarGymQuiz_AskQuestion.
; Runs the yes/no prompt, checks it against hGymGateAnswer, and on a correct
; answer: sets BIT_CUR_MAP_LOADED_1 (forces this map's script to re-run),
; prints the correct-answer text, sets this gate's unlock flag, and tail-jumps
; into the gate/tile-block repaint. On a wrong answer: SFX_DENIED, the
; incorrect-answer text, then (unless the matching gym trainer is already
; beaten) engages that trainer via wOpponentAfterWrongAnswer + wd474 bit 7.
; ─────────────────────────────────────────────────────────────────────────────
CinnabarGymQuiz_AskQuestion:
    call YesNoChoice
    mov cl, [ebp + hGymGateAnswer]
    mov al, [ebp + wCurrentMenuItem]
    cmp al, cl
    jne .wrongAnswer

    or byte [ebp + wCurrentMapScriptFlags], (1 << BIT_CUR_MAP_LOADED_1)
    mov al, [ebp + hGymGateIndex]
    mov [ebp + hBackupGymGateIndex], al
    mov esi, CinnabarGymQuizCorrectText
    call PrintText

    ; AdjustEventBit EVENT_CINNABAR_GYM_GATE0_UNLOCKED, 0 — no-op (see header)
    movzx ecx, byte [ebp + hBackupGymGateIndex]
    mov bh, FLAG_SET
    call CinnabarGymGateFlagAction
    jmp UpdateCinnabarGymGateTileBlocks_

.wrongAnswer:
    call WaitForSoundToFinish
    mov al, SFX_DENIED
    call PlaySound
    call WaitForSoundToFinish
    mov esi, CinnabarGymQuizIncorrectText
    call PrintText

    movzx eax, byte [ebp + hGymGateIndex]
    add al, 2
    ; AdjustEventBit EVENT_BEAT_CINNABAR_GYM_TRAINER_0, 2 — no-op (see header)
    movzx ecx, al
    mov bh, FLAG_TEST
    mov esi, wEventFlags + EVENT_BYTE(EVENT_BEAT_CINNABAR_GYM_TRAINER_0)   ; EventFlagAddress hl, EVENT_BEAT_CINNABAR_GYM_TRAINER_0
    call FlagAction                     ; predef FlagActionPredef (regs hand-set; see header)
    test cl, cl
    jnz .ret

    movzx eax, byte [ebp + hGymGateIndex]
    add al, 2
    mov [ebp + wOpponentAfterWrongAnswer], al
    or byte [ebp + wd474], (1 << 7)     ; set 7, [hl]  (hl = wd474)
.ret:
    ret

; ─────────────────────────────────────────────────────────────────────────────
; CinnabarGymQuizCorrectText — pret cinnabar_gym_quiz.asm:CinnabarGymQuizCorrectText.
; text_far intro (its far body, `_CinnabarGymQuizCorrectText`, is generated
; into assets/cinnabar_gym_quiz_text.inc — same pattern as
; src/engine/battle/effects.asm:ChargeMoveEffectText / assets/battle_text.inc's
; `_ChargeMoveEffectText`) followed by a text_asm tail: re-check the gate's
; unlock flag (guards against a stale re-print) and, only the first time, play
; the go-inside SFX.
; ─────────────────────────────────────────────────────────────────────────────
CinnabarGymQuizCorrectText:
    sound_get_item_1
    text_far _CinnabarGymQuizCorrectText
    text_promptbutton
    text_asm                            ; TX_START_ASM → TextCommandProcessor jumps here

    ; AdjustEventBit EVENT_CINNABAR_GYM_GATE0_UNLOCKED, 0 — no-op (see header)
    movzx ecx, byte [ebp + hBackupGymGateIndex]
    mov bh, FLAG_TEST
    call CinnabarGymGateFlagAction
    test cl, cl
    jnz TextScriptEnd
    call WaitForSoundToFinish
    mov al, SFX_GO_INSIDE
    call PlaySound
    call WaitForSoundToFinish
    jmp TextScriptEnd

; ─────────────────────────────────────────────────────────────────────────────
; CinnabarGymGateFlagAction — pret cinnabar_gym_quiz.asm:CinnabarGymGateFlagAction.
; Fixed-address FlagAction wrapper over the 6 EVENT_CINNABAR_GYM_GATEn_UNLOCKED
; bits (all 7 constants 680-686 share one byte, so a compile-time EventFlagAddress
; is enough — the caller's runtime bit index (1-6) lands in the right byte
; because FlagAction itself splits index/8 (extra byte) + index%8 (bit), and
; every caller here passes an index < 8). Caller pre-sets CL=index, BH=action.
; ─────────────────────────────────────────────────────────────────────────────
CinnabarGymGateFlagAction:
    mov esi, wEventFlags + EVENT_BYTE(EVENT_CINNABAR_GYM_GATE0_UNLOCKED)  ; EventFlagAddress hl, EVENT_CINNABAR_GYM_GATE0_UNLOCKED
    jmp FlagAction                       ; predef_jump FlagActionPredef (regs hand-set; see header)

; ─────────────────────────────────────────────────────────────────────────────
; UpdateCinnabarGymGateTileBlocks_ — pret cinnabar_gym_quiz.asm:UpdateCinnabarGymGateTileBlocks_.
; Walks all 6 gates (index 6 down to 1, matching CinnabarGymGateCoords' 6
; entries), reads each gate's (x, y, locked-block-id) row, checks that gate's
; unlock flag, picks the locked block id (from the table) or $0E (open floor)
; accordingly, and patches the live map through CinnabarGym_ReplaceTileBlock.
; Finishes with a real map redraw.
; ─────────────────────────────────────────────────────────────────────────────
OPEN_GATE_FLOOR_BLOCK equ 0x0E

UpdateCinnabarGymGateTileBlocks_:
    mov byte [ebp + hGymGateIndex], 6
.loop:
    movzx eax, byte [ebp + hGymGateIndex]
    dec eax                                          ; 0-based index
    lea esi, [CinnabarGymGateCoords + eax * 4]        ; pret: index*4 byte offset (4-byte rows)
    movzx ebx, word [esi]                             ; bl = x (byte0), bh = y (byte1)
    mov al, [esi + 2]                                 ; blockid (byte2); byte3 is the macro's pad byte, unused
    mov [ebp + wGymGateTileBlock], al

    push ebx                                          ; push bc (x,y survive the FlagAction call below)
    mov al, [ebp + hGymGateIndex]
    mov [ebp + hBackupGymGateIndex], al
    ; AdjustEventBit EVENT_CINNABAR_GYM_GATE0_UNLOCKED, 0 — no-op (see header)
    movzx ecx, al
    mov bh, FLAG_TEST
    call CinnabarGymGateFlagAction
    test cl, cl
    jnz .unlocked
    mov al, [ebp + wGymGateTileBlock]
    jmp .next
.unlocked:
    mov al, OPEN_GATE_FLOOR_BLOCK
.next:
    pop ebx                                           ; pop bc
    mov [ebp + wNewTileBlockID], al
    call CinnabarGym_ReplaceTileBlock

    dec byte [ebp + hGymGateIndex]
    jnz .loop
    call RedrawMapView                                ; callfar RedrawMapView
    ret

; ─────────────────────────────────────────────────────────────────────────────
; CinnabarGymGateCoords — pret cinnabar_gym_quiz.asm:CinnabarGymGateCoords.
; A coordinate/blockid table, not a string (two-tier rule): x, y, locked-block
; id, pad (matches pret's `gym_gate_coord` macro's `db x,y,blockid,0` layout —
; the port never reads the pad byte, kept for byte-identical row layout).
; ─────────────────────────────────────────────────────────────────────────────
%macro gym_gate_coord 3
    db %1, %2, %3, 0
%endmacro

HORIZONTAL_GATE_BLOCK equ 0x54
VERTICAL_GATE_BLOCK   equ 0x5F

section .data
CinnabarGymGateCoords:
    ; x coord, y coord, block id
    gym_gate_coord 9, 3, HORIZONTAL_GATE_BLOCK
    gym_gate_coord 6, 3, HORIZONTAL_GATE_BLOCK
    gym_gate_coord 6, 6, HORIZONTAL_GATE_BLOCK
    gym_gate_coord 3, 8, VERTICAL_GATE_BLOCK
    gym_gate_coord 2, 6, HORIZONTAL_GATE_BLOCK
    gym_gate_coord 2, 3, HORIZONTAL_GATE_BLOCK
section .text

; ─────────────────────────────────────────────────────────────────────────────
; CinnabarGym_ReplaceTileBlock — pret cinnabar_gym_quiz.asm:CinnabarGym_ReplaceTileBlock.
; "basically a copy of the first half of ReplaceTileBlock before checking if it
; is necessary to redraw the map view" (pret's own comment). In: BH=y, BL=x
; (caller's BC). Writes wNewTileBlockID into wOverworldMap at (x, y), using the
; PORT's MAP_BORDER (7), not pret's literal 3/6 — see file header.
; ─────────────────────────────────────────────────────────────────────────────
CinnabarGym_ReplaceTileBlock:
    movzx eax, byte [ebp + wCurMapWidth]
    add eax, MAP_BORDER * 2                          ; stride = width + MAP_BORDER*2
    movzx edx, bh                                    ; edx = y
    add edx, MAP_BORDER
    imul edx, eax                                    ; edx = (y+MAP_BORDER) * stride
    movzx eax, bl                                    ; eax = x
    add eax, MAP_BORDER
    add eax, edx                                     ; eax = (x+MAP_BORDER) + (y+MAP_BORDER)*stride
    mov dl, [ebp + wNewTileBlockID]
    mov [ebp + wOverworldMap + eax], dl
    ret
