; school_blackboard.asm — Viridian City school hidden-event handlers.
;
; Faithful translation of pret `engine/events/hidden_events/school_blackboard.asm`:
; PrintBlackboardLinkCableText, LinkCableHelp, ViridianSchoolBlackboard, and every
; text label the two paged readers print.
;
; Two hidden-event map entries reach these (data/events/hidden_events.asm):
;   VIRIDIAN_SCHOOL_HOUSE   hidden_text_predef 3, 0, PrintBlackboardLinkCableText, ViridianSchoolBlackboard
;   CELADON_MANSION_ROOF_HOUSE hidden_text_predef 3/4, 0, PrintBlackboardLinkCableText, LinkCableHelp
; PrintBlackboardLinkCableText is TextPredefs' shared dispatcher (both predef ids
; $23 ViridianSchoolBlackboard and $36 LinkCableHelp resolve through it): it reads
; the predef id CheckForHiddenEvent left in wHiddenEventFunctionArgument and hands
; it straight to PrintPredefTextID, exactly as pret's PrintRedSNESText hands a
; FIXED id to the same routine (src/engine/events/hidden_events/reds_room.asm) —
; here the id is a runtime value instead of a compile-time constant, which is why
; pret writes `ld a, [wHiddenEventFunctionArgument]` instead of `tx_pre_id`.
;
; Both LinkCableHelp and ViridianSchoolBlackboard are `text_asm` PAGED READERS
; (Tier-2 code — a HandleMenuInput loop drives page selection), not plain text.
; Every string either of them prints is Tier-1 DATA, generated by
; tools/generators/gen_school_blackboard_text.py into
; assets/school_blackboard_text.inc:
;   * HowToLinkText, StatusAilmentText1, StatusAilmentText2 — inline `db`/`next`
;     PlaceString labels, GB-charmap encoded (gen_menu_strings.py's pattern).
;   * The twelve `text_far` wrapper bodies (LinkCableHelpText1/2,
;     LinkCableInfoText1-3, ViridianSchoolBlackboardText1/2,
;     ViridianBlackboard{Sleep,Poison,Prlz,Burn,Frozen}Text) — flattened via
;     gen_battle_text.collect_far, same machinery as gen_pikachu_text.py's single
;     wrapper. The wrappers themselves (`text_far _Foo` / `text_end`) stay Tier-2
;     code here, in pret's own order, exactly as src/scripts/BikeShop.asm keeps its
;     wrapper labels beside its generated bodies.
;
; LinkCableInfoTexts and ViridianBlackboardStatusPointers are pret 16-bit `dw`
; jump tables (index-by-menu-item dispatch, not strings) — Tier-2 code per the
; "pointer/address tables are not strings" rule, translated to flat `dd` tables
; and indexed with `[Table + eax*4]`, the same idiom already used by
; src/engine/menus/options.asm:OptionMenuJumpTable and
; src/engine/menus/save.asm:BoxSRAMPointerTable.
;
; The stray `db "@" ; unused` byte after StatusAilmentText2 in pret is dead data —
; unreferenced by anything, no label, no read site — and is not reproduced; nothing
; observable depends on its presence.
;
; Register map (CLAUDE.md): A=AL, BC=BX (B=BH,C=BL), DE=DX, HL=ESI, EBP = GB base.
; HandleMenuInput's return value is read in AL, exactly like every other menu-input
; caller in this tree (src/scripts/BikeShop.asm, src/engine/menus/options.asm, …):
; pret's `bit B_PAD_x, a` is `test al, PAD_x`.
;
; PROJ overworld-ui (blackboard / link-cable-help boxes): both boxes are drawn at
; GB `hlcoord 0, 0`, flush at column 0 — ruled the same way as the bike shop menu
; box (docs/ui_projection.md, "Bike Shop menu — ruled AS THE POKÉ MART"):
; anchor=top-LEFT, X+0, Y+0, same box size, no scaling. Every inner PlaceString
; INHERITS that anchor (offsets from the box origin are preserved verbatim), the
; same principle the mart quantity box and the bike shop menu text established.
;
; Build (standalone check):
;   nasm -f coff -I include/ -I . -D BUG_FIX_LEVEL=0 -o /dev/null \
;       src/engine/events/hidden_events/school_blackboard.asm

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_macros.inc"
%include "gb_text.inc"          ; text_far / text_end
%include "coords.inc"           ; hlcoord

global PrintBlackboardLinkCableText
global LinkCableHelp
global ViridianSchoolBlackboard

extern EnableAutoTextBoxDrawing         ; src/home/window.asm
extern PrintPredefTextID                ; src/home/predef_text.asm
extern SaveScreenTilesToBuffer1         ; src/home/tilemap.asm
extern LoadScreenTilesFromBuffer1       ; src/home/tilemap.asm
extern PrintText                        ; src/home/window.asm — In: ESI = text stream
extern PlaceString                      ; src/home/text.asm — In: EAX = flat src, ESI = dest
extern TextBoxBorder                    ; src/home/text.asm — In: ESI = top-left, BH = int_h, BL = int_w
extern HandleMenuInput                  ; src/home/window.asm — Out: AL = joypad-like result
extern TextScriptEnd                    ; src/home/overworld_text.asm

; ─────────────────────────────────────────────────────────────────────────────
; Tier-1 DATA: HowToLinkText / StatusAilmentText1 / StatusAilmentText2 and the
; twelve text_far stream bodies.
section .data
%include "assets/school_blackboard_text.inc"

section .text

; ─────────────────────────────────────────────────────────────────────────────
; PrintBlackboardLinkCableText — pret ref: school_blackboard.asm:1.
; Shared TextPredefs dispatcher for both blackboard-family predef ids: reads the
; runtime id CheckForHiddenEvent left in wHiddenEventFunctionArgument and hands it
; to PrintPredefTextID.
; ─────────────────────────────────────────────────────────────────────────────
PrintBlackboardLinkCableText:
    call EnableAutoTextBoxDrawing
    mov byte [ebp + wDoNotWaitForButtonPressAfterDisplayingText], 1  ; ld a,$1 / ld [...],a
    mov al, [ebp + wHiddenEventFunctionArgument]        ; ld a, [wHiddenEventFunctionArgument]
    call PrintPredefTextID
    ret

; ─────────────────────────────────────────────────────────────────────────────
; LinkCableHelp — pret ref: school_blackboard.asm:LinkCableHelp.
; Paged reader: page 0 is the fixed intro (HowToLinkText overlaid on
; LinkCableHelpText2), pages 1-3 are LinkCableInfoTexts[0..2], page 3 ("STOP
; READING") exits.
; ─────────────────────────────────────────────────────────────────────────────
LinkCableHelp:
    call SaveScreenTilesToBuffer1
    mov esi, LinkCableHelpText1
    call PrintText
    xor al, al                              ; xor a
    mov [ebp + wMenuItemOffset], al         ; not used
    mov [ebp + wCurrentMenuItem], al
    mov [ebp + wLastMenuItem], al
    mov al, PAD_A | PAD_B
    mov [ebp + wMenuWatchedKeys], al
    mov al, 3
    mov [ebp + wMaxMenuItem], al
    mov al, 2
    mov [ebp + wTopMenuItemY], al
    mov al, 1
    mov [ebp + wTopMenuItemX], al
.linkHelpLoop:
    or byte [ebp + wStatusFlags5], (1 << BIT_NO_TEXT_DELAY)      ; set BIT_NO_TEXT_DELAY,[hl]
    ; PROJ overworld-ui (link-cable-help box): GB(0,0) 15x10 --(anchor=top-LEFT, X+0, Y+0)--
    hlcoord 0, 0
    mov bh, 8                               ; lb bc, 8, 13
    mov bl, 13
    call TextBoxBorder
    ; PROJ overworld-ui (link-cable-help label): INHERITS the box, +2 col +2 row
    hlcoord 2, 2
    mov eax, HowToLinkText
    call PlaceString
    mov esi, LinkCableHelpText2
    call PrintText
    call HandleMenuInput
    test al, PAD_B
    jnz .exit
    mov al, [ebp + wCurrentMenuItem]
    cmp al, 3                               ; pressed a on "STOP READING"
    jz .exit
    and byte [ebp + wStatusFlags5], (~(1 << BIT_NO_TEXT_DELAY)) & 0xFF ; res BIT_NO_TEXT_DELAY,[hl]
    ; ld hl, LinkCableInfoTexts / add a / ld d,0 / ld e,a / add hl,de / ld a,[hli] / ld h,[hl] / ld l,a
    movzx eax, al
    mov esi, [LinkCableInfoTexts + eax * 4]
    call PrintText
    jmp .linkHelpLoop
.exit:
    and byte [ebp + wStatusFlags5], (~(1 << BIT_NO_TEXT_DELAY)) & 0xFF
    call LoadScreenTilesFromBuffer1
    jmp TextScriptEnd

LinkCableHelpText1:
    text_far _LinkCableHelpText1
    text_end

LinkCableHelpText2:
    text_far _LinkCableHelpText2
    text_end

; LinkCableInfoTexts — pret ref: school_blackboard.asm:LinkCableInfoTexts. pret's
; 16-bit `dw` jump table, flattened to `dd` (same idiom as OptionMenuJumpTable /
; BoxSRAMPointerTable): index-by-menu-item dispatch, not a string.
LinkCableInfoTexts:
    dd LinkCableInfoText1
    dd LinkCableInfoText2
    dd LinkCableInfoText3

LinkCableInfoText1:
    text_far _LinkCableInfoText1
    text_end

LinkCableInfoText2:
    text_far _LinkCableInfoText2
    text_end

LinkCableInfoText3:
    text_far _LinkCableInfoText3
    text_end

; ─────────────────────────────────────────────────────────────────────────────
; ViridianSchoolBlackboard — pret ref: school_blackboard.asm:ViridianSchoolBlackboard.
; Paged reader with a two-column menu: LEFT column (offset 0) picks SLP/PSN/PAR,
; RIGHT column (offset 3) picks BRN/FRZ/QUIT — HandleMenuInput's own cursor
; (0..2) plus wMenuItemOffset selects one of ViridianBlackboardStatusPointers'
; five rows, or exits on index 5 ("QUIT").
; ─────────────────────────────────────────────────────────────────────────────
ViridianSchoolBlackboard:
    call SaveScreenTilesToBuffer1
    mov esi, ViridianSchoolBlackboardText1
    call PrintText
    xor al, al
    mov [ebp + wMenuItemOffset], al
    mov [ebp + wCurrentMenuItem], al
    mov [ebp + wLastMenuItem], al
    mov al, PAD_LEFT | PAD_RIGHT | PAD_A | PAD_B
    mov [ebp + wMenuWatchedKeys], al
    mov al, 2
    mov [ebp + wMaxMenuItem], al
    mov al, 2
    mov [ebp + wTopMenuItemY], al
    mov al, 1
    mov [ebp + wTopMenuItemX], al
.blackboardLoop:
    or byte [ebp + wStatusFlags5], (1 << BIT_NO_TEXT_DELAY)
    ; PROJ overworld-ui (blackboard box): GB(0,0) 12x8 --(anchor=top-LEFT, X+0, Y+0)--
    hlcoord 0, 0
    mov bh, 6                               ; lb bc, 6, 10
    mov bl, 10
    call TextBoxBorder
    ; PROJ overworld-ui (blackboard column 1 label): INHERITS the box, +1 col +2 row
    hlcoord 1, 2
    mov eax, StatusAilmentText1
    call PlaceString
    ; PROJ overworld-ui (blackboard column 2 label): INHERITS the box, +6 col +2 row
    hlcoord 6, 2
    mov eax, StatusAilmentText2
    call PlaceString
    mov esi, ViridianSchoolBlackboardText2
    call PrintText
    call HandleMenuInput                    ; pressing up and down is handled in here
    test al, PAD_B                          ; pressed b
    jnz .exitBlackboard
    test al, PAD_RIGHT
    jz .didNotPressRight
    ; move cursor to right column
    mov al, 2
    mov [ebp + wMaxMenuItem], al
    mov al, 2
    mov [ebp + wTopMenuItemY], al
    mov al, 6
    mov [ebp + wTopMenuItemX], al
    mov al, 3                               ; in the right column, use an offset to prevent overlap
    mov [ebp + wMenuItemOffset], al
    jmp .blackboardLoop
.didNotPressRight:
    test al, PAD_LEFT
    jz .didNotPressLeftOrRight
    ; move cursor to left column
    mov al, 2
    mov [ebp + wMaxMenuItem], al
    mov al, 2
    mov [ebp + wTopMenuItemY], al
    mov al, 1
    mov [ebp + wTopMenuItemX], al
    xor al, al
    mov [ebp + wMenuItemOffset], al
    jmp .blackboardLoop
.didNotPressLeftOrRight:
    mov bh, [ebp + wCurrentMenuItem]        ; ld a,[wCurrentMenuItem] / ld b,a
    mov al, [ebp + wMenuItemOffset]         ; ld a,[wMenuItemOffset]
    add al, bh                              ; add b
    cmp al, 5                               ; cursor is pointing to "QUIT"
    jz .exitBlackboard
    ; we must have pressed a on a status condition, so print the text
    and byte [ebp + wStatusFlags5], (~(1 << BIT_NO_TEXT_DELAY)) & 0xFF
    ; ld hl, ViridianBlackboardStatusPointers / add a / ld d,0 / ld e,a / add hl,de
    ; / ld a,[hli] / ld h,[hl] / ld l,a
    movzx eax, al
    mov esi, [ViridianBlackboardStatusPointers + eax * 4]
    call PrintText
    jmp .blackboardLoop
.exitBlackboard:
    and byte [ebp + wStatusFlags5], (~(1 << BIT_NO_TEXT_DELAY)) & 0xFF
    call LoadScreenTilesFromBuffer1
    jmp TextScriptEnd

ViridianSchoolBlackboardText1:
    text_far _ViridianSchoolBlackboardText1
    text_end

ViridianSchoolBlackboardText2:
    text_far _ViridianSchoolBlackboardText2
    text_end

; ViridianBlackboardStatusPointers — pret ref:
; school_blackboard.asm:ViridianBlackboardStatusPointers. pret's 16-bit `dw` jump
; table, flattened to `dd`; index-by-status-slot dispatch, not a string.
ViridianBlackboardStatusPointers:
    dd ViridianBlackboardSleepText
    dd ViridianBlackboardPoisonText
    dd ViridianBlackboardPrlzText
    dd ViridianBlackboardBurnText
    dd ViridianBlackboardFrozenText

ViridianBlackboardSleepText:
    text_far _ViridianBlackboardSleepText
    text_end

ViridianBlackboardPoisonText:
    text_far _ViridianBlackboardPoisonText
    text_end

ViridianBlackboardPrlzText:
    text_far _ViridianBlackboardPrlzText
    text_end

ViridianBlackboardBurnText:
    text_far _ViridianBlackboardBurnText
    text_end

ViridianBlackboardFrozenText:
    text_far _ViridianBlackboardFrozenText
    text_end
