; tmhm_moves.asm — TM then HM move ids, 0xFF-terminated (CanLearnTM / TMToMove).
;
; pret ref: data/moves/tmhm_moves.asm:TechnicalMachines
;
; Generated by tools/generators/gen_items.py into assets/tmhm_moves.inc. This carrier sits at the
; mirrored path dos_port/src/data/moves/tmhm_moves.asm; it was part of src/data/item_data.asm until 2026-08-16
; (docs/current_plan_data_path_mirror.md).
;
; Embedded data goes in .data per the linker rule in docs/assembly.md (.rodata has
; no output-section rule and reads back as zero).
bits 32

global TechnicalMachines

section .data

%include "assets/tmhm_moves.inc"
