; battle_anims.asm — carrier for the generated battle move-animation data
; (battle-animations plan Stage 1; Tier-1, data layer).
;
; pret holds these tables in data/moves/animations.asm, data/battle_anims/
; {subanimations,frame_blocks,base_coords}.asm and data/moves/sfx.asm; the port's
; data-layer convention groups them here, generated by
; tools/generators/gen_battle_anim_data.py (ROM-cross-checked byte-identical
; against the golden ROM when the pinned worktree is present).
;
; Pointer tables are dd (flat DPMI addresses; pret dw). Every body byte is
; pret's GB-space value verbatim: the battle-frame projection (+80,+24 px OAM /
; BCOORD +10,+3 tilemap) is applied by the engine at publication, never baked
; into this data (docs/plans/battle_animations.md, HAL design).
;
; SFX_* names in MoveSoundTable resolve against the generated
; assets/audio_constants.inc.
bits 32

%include "assets/audio_constants.inc"

global AttackAnimationPointers
global SubanimationPointers
global FrameBlockPointers
global FrameBlockBaseCoords
global MoveSoundTable

section .data

%include "assets/battle_anim_data.inc"
