; card_key_data.asm — Silph Co. card-key door coordinate tables.
;
; pret ref: data/events/card_key_coords.asm
;           (CardKeyTable1 / CardKeyTable2 / CardKeyTable3)
;
; Created 2026-08-02. The three tables were hand-typed `db` rows inside
; src/engine/items/item_effects.asm, a CODE file, and `lint_pret_labels`
; reported each as [aux_misplaced]. They are now generated by
; tools/generators/gen_static_tables.py from the pret source, so the port's copy
; is a deterministic function of pret rather than a hand transcription.
;
; NOTE, carried over from pret's own comment: these tables are UNUSED. pret says
; they are "probably supposed to be door locations in Silph Co., but they are
; unused", and that "the reason there are 3 tables is unknown". They are ported
; for completeness and to keep the label set faithful — do not read their
; presence as evidence that a card-key door mechanic is wired up.
;
; Embedded data goes in .data per the linker rule in docs/assembly.md.
;
; Build: nasm -f coff -I include/ -I . -o card_key_data.o card_key_data.asm
; ---------------------------------------------------------------------------
bits 32

%include "gb_constants.inc"
%include "assets/map_dims.inc"          ; SILPH_CO_*F map ids

global CardKeyTable1
global CardKeyTable2
global CardKeyTable3

section .data
align 4

%include "assets/card_key_coords.inc"
