; growth_rates.asm — the six experience-curve coefficient rows.
;
; pret ref: data/growth_rates.asm:GrowthRateTable
;
; Generated by tools/generators/gen_growth_rates.py into assets/growth_rates.inc. This carrier sits at the
; mirrored path dos_port/src/data/growth_rates.asm; it was part of src/data/pokemon_data.asm until 2026-08-16
; (docs/current_plan_data_path_mirror.md).
;
; Embedded data goes in .data per the linker rule in docs/assembly.md (.rodata has
; no output-section rule and reads back as zero).
bits 32

global GrowthRateTable

section .data

%include "assets/growth_rates.inc"
