; hidden_events_data.asm — Gen-1 Yellow hidden-event data tables (overworld-events
; plan, Stage 3).
;
; Exposes the generated HiddenEventMaps flat dispatch table + every
; HiddenEventsFor_<map> list so CheckForHiddenEvent (src/home/hidden_events.asm)
; can scan them. Per the linker rule in docs/assembly.md, embedded data lives in
; .data (not .rodata). Generated by tools/gen_hidden_events.py from
; data/events/hidden_events.asm.
;
; The per-entry handler pointers (dd) resolve to the Tier-2 handler bodies in
; src/engine/overworld/hidden_object_stubs.asm (ret-stubs until each owning
; subsystem/map lands — see that file's retirement notes).
;
; Also exposes HiddenItemCoords (Stage 3 bullet 2), the flat map/y/x table the
; items plan's itemfinder (HiddenItemNear) scans. Generated by
; tools/gen_hidden_item_coords.py from data/events/hidden_item_coords.asm.
;
; Build: nasm -f coff -I include/ -I . -o hidden_events_data.o hidden_events_data.asm

bits 32

section .data
align 4

%include "assets/hidden_events.inc"
%include "assets/hidden_item_coords.inc"
