; map_script_tables.asm — port-only carrier for the generated map-script parameter
; tables (map-script fidelity plan, Stage 2).
;
; %includes assets/map_script_tables.inc (Tier-1 data generated by
; tools/generators/gen_map_script_tables.py from pret scripts/*.asm +
; ram/wram.asm + constants/map_constants.asm). The .inc holds MapScriptParams
; (one 12-byte row per map: trainer-header table, script-pointer table, the GB
; address of the map's persistent script byte) plus the per-map
; <Map>_ScriptPointers jumptables, and declares its own externs.
;
; Model: src/data/trainer_headers.asm / src/data/map_scripts.asm — a thin .data
; carrier for a generated .inc. Per the linker rule (docs/assembly.md / link.ld
; orphan-section trap) embedded data lives in .data. This file opens .data; the
; .inc does NOT self-open one.
;
; Build: nasm -f coff -I include/ -I . -o map_script_tables.o map_script_tables.asm

bits 32

global MapScriptParams

section .data
align 4

%include "assets/map_script_tables.inc"
