; pickup_text.asm — PickUpItem message command streams (overworld-events Stage 3
; bullet 3). Include shell for the generated .inc, mirroring src/data/item_text.asm.
;
; The generated streams live in .data (linker rule: embedded data goes in .data —
; see docs/assembly.md). assets/pickup_text.inc carries its own `section .data` +
; `global` per label. Generated by tools/generators/gen_pickup_text.py (pret
; engine/events/pick_up_item.asm text wrappers, text_far flattened). DO NOT
; hand-edit the .inc.
;
; Build: nasm -f coff -I include/ -I . -o pickup_text.o pickup_text.asm

bits 32

%include "assets/pickup_text.inc"
