; predef_text_data.asm — the generated TextPredefs message streams AND the
; hand-written TextPredefs dispatch table.
;
; pret's TextPredefs table (data/text_predef_pointers.asm) has 68 entries, ids
; $01..$44. 51 are pure printable streams and ARE generated here; the other 17 are
; Tier-2 code (14 `text_asm` wrappers) or script dispatch markers (3 `script_*`),
; each listed with its per-label reason in the generator's NOT_DATA table and
; standing in as a ret-stub in
; src/engine/events/hidden_events/hidden_events_stubs.asm.
;
; WHY THE TABLE IS HAND-WRITTEN AND YET LIVES IN THE DATA LAYER. This is the
; MoveEffectPointerTable situation exactly (src/data/move_effect_pointers.asm, see
; the project-conventions two-tier rule): no generator can derive the table,
; because 17 of its rows name PORT routines rather than pret data — but pret files
; it under data/, and the linter's aux_misplaced rule asks only that a pret data/
; label live under dos_port/src/data/ or a generated assets/*.inc. A hand-written
; dispatch table in the data layer satisfies both. Putting it in
; src/home/predef_text.asm beside PrintPredefTextID would ADD an aux_misplaced
; finding, and no class may grow.
;
; ROW FORMAT — the SAME {dd stream, dd size} rows the ordinary map text table uses
; (w_map_text_table_ptr, published by map_sprites.asm), so DisplayTextID has one
; lookup for both tables instead of two. `size` is only ever read to test the
; text_asm sentinel; the byte count in a data row comes from the generated
; <Label>_len constant, so it is exact and is not duplicated by hand.
;
; pret's `dw` (bank-relative) becomes `dd` (flat DPMI linear), as everywhere else.
; The table sits in section .data: it is only ever `lea`'d, never executed.
;
; Generated by tools/generators/gen_predef_text.py from the pret engine/ wrapper
; labels named by data/text_predef_pointers.asm, text_far flattened. DO NOT
; hand-edit the .inc.
;
; Build: nasm -f coff -I include/ -I . -o predef_text_data.o predef_text_data.asm

bits 32

%include "assets/predef_text.inc"

; A generated printable stream: flat pointer + its exact byte count.
%macro predef_data 1
    dd %1, %1 %+ _len
%endmacro

; A text_asm / script_* row: the message IS code. TEXT_ASM_ENTRY in the size slot
; is what DisplayTextID tests to decide to `call` the pointer instead of printing
; it — the same sentinel the ordinary map table uses for its script entries.
%macro predef_code 1
    extern %1
    dd %1, TEXT_ASM_ENTRY
%endmacro

TEXT_ASM_ENTRY equ 0xFFFFFFFF

section .data
align 4

; TextPredefs — pret data/text_predef_pointers.asm. Ids $01..$44; DisplayTextID
; indexes it as (id - 1), so row 0 below is id $01.
global TextPredefs
TextPredefs:
    predef_data CardKeySuccessText                 ; $01
    predef_data CardKeyFailText                    ; $02
    predef_code RedBedroomPCText                   ; $03
    predef_data RedBedroomSNESText                 ; $04
    predef_data PushStartText                      ; $05
    predef_data SaveOptionText                     ; $06
    predef_data StrengthsAndWeaknessesText         ; $07
    predef_data OakLabEmailText                    ; $08
    predef_data AerodactylFossilText               ; $09
    predef_data Route15UpstairsBinocularsText      ; $0A
    predef_data KabutopsFossilText                 ; $0B
    predef_data FanClubPicture1Text                ; $0C
    predef_data FanClubPicture2Text                ; $0D
    predef_data GymStatueText1                     ; $0E
    predef_data GymStatueText2                     ; $0F
    predef_data BookcaseText                       ; $10
    predef_data ViridianCityPokecenterBenchGuyText ; $11
    predef_data PewterCityPokecenterBenchGuyText   ; $12
    predef_data CeruleanCityPokecenterBenchGuyText ; $13
    predef_data LavenderCityPokecenterBenchGuyText ; $14
    predef_data VermilionCityPokecenterBenchGuyText ; $15
    predef_data CeladonCityPokecenterBenchGuyText  ; $16
    predef_data CeladonCityHotelText               ; $17
    predef_data FuchsiaCityPokecenterBenchGuyText  ; $18
    predef_data CinnabarIslandPokecenterBenchGuyText ; $19
    predef_code SaffronCityPokecenterBenchGuyText  ; $1A
    predef_data MtMoonPokecenterBenchGuyText       ; $1B
    predef_data RockTunnelPokecenterBenchGuyText   ; $1C
    predef_data UnusedBenchGuyText1                ; $1D
    predef_data UnusedBenchGuyText2                ; $1E
    predef_data UnusedBenchGuyText3                ; $1F
    predef_data UnusedPredefText                   ; $20
    predef_code PokemonCenterPCText                ; $21
    predef_code ViridianSchoolNotebook             ; $22
    predef_code ViridianSchoolBlackboard           ; $23
    predef_data JustAMomentText                    ; $24
    predef_code OpenBillsPCText                    ; $25
    predef_code FoundHiddenItemText                ; $26
    predef_data HiddenItemBagFullText              ; $27
    predef_data VermilionGymTrashText              ; $28
    predef_data IndigoPlateauHQText                ; $29
    predef_data GameCornerOutOfOrderText           ; $2A
    predef_data GameCornerOutToLunchText           ; $2B
    predef_data GameCornerSomeonesKeysText         ; $2C
    predef_data FoundHiddenCoinsText               ; $2D
    predef_data DroppedHiddenCoinsText             ; $2E
    predef_data BillsHouseMonitorText              ; $2F
    predef_code BillsHouseInitiatedText            ; $30
    predef_code BillsHousePokemonList              ; $31
    predef_data MagazinesText                      ; $32
    predef_code CinnabarGymQuiz                    ; $33
    predef_data GameCornerNoCoinsText              ; $34
    predef_data GameCornerCoinCaseText             ; $35
    predef_code LinkCableHelp                      ; $36
    predef_data TMNotebook                         ; $37
    predef_data FightingDojoText                   ; $38
    predef_data EnemiesOnEverySideText             ; $39
    predef_data WhatGoesAroundComesAroundText      ; $3A
    predef_data NewBicycleText                     ; $3B
    predef_code IndigoPlateauStatues               ; $3C
    predef_code VermilionGymTrashSuccessText1      ; $3D
    predef_data VermilionGymTrashSuccessText2      ; $3E
    predef_code VermilionGymTrashSuccessText3      ; $3F
    predef_code VermilionGymTrashFailText          ; $40
    predef_code TownMapText                        ; $41
    predef_code BookOrSculptureText                ; $42
    predef_data ElevatorText                       ; $43
    predef_data PokemonStuffText                   ; $44
TextPredefs_end:

PREDEF_TEXT_ROWS equ (TextPredefs_end - TextPredefs) / 8
%if PREDEF_TEXT_ROWS != 68
%error "TextPredefs must have exactly 68 rows (pret data/text_predef_pointers.asm)"
%endif
