; tileset_data.asm — pret data/tilesets/ static tables.
;
; pret refs:
;   TilePairCollisionsLand / TilePairCollisionsWater
;                        data/tilesets/pair_collision_tile_ids.asm
;   LedgeTiles           data/tilesets/ledge_tiles.asm
;   BikeRidingTilesets   data/tilesets/bike_riding_tilesets.asm
;
; Created 2026-08-02. All four tables were hand-typed `db` rows inside CODE
; files — the first three in src/engine/overworld/ledges.asm, BikeRidingTilesets
; in src/home/player_gfx.asm — and `lint_pret_labels` reported each as
; [aux_misplaced]. Two things were wrong and only one of them was placement:
; the rows had also been TRANSCRIBED BY HAND from pret (`$2C` retyped as `0x2C`,
; `db -1` as `db 0xFF`), so nothing regenerated them if pret changed and a typo
; would have been silent. They are now generated by
; tools/generators/gen_static_tables.py, which keeps pret's row order and its
; symbolic constant names and rewrites only the literal syntax.
;
; ledges.asm's own header had predicted this: "a future pass may promote these
; to a generated assets/*.inc under the two-tier rule (they are pure static
; tables)". This is that pass.
;
; Consumers (all extern these):
;   * src/engine/overworld/ledges.asm — TilePairCollisions*, LedgeTiles.
;   * src/home/player_gfx.asm         — BikeRidingTilesets.
;
; Embedded data goes in .data per the linker rule in docs/assembly.md.
;
; Build: nasm -f coff -I include/ -I . -o tileset_data.o tileset_data.asm
; ---------------------------------------------------------------------------
bits 32

%include "gb_constants.inc"
%include "gb_memmap.inc"                ; SPRITE_FACING_* / PAD_* (LedgeTiles rows)
%include "assets/map_dims.inc"          ; tileset ids: OVERWORLD/FOREST/CAVERN/...

global TilePairCollisionsLand
global TilePairCollisionsWater
global LedgeTiles
global BikeRidingTilesets

section .data
align 4

%include "assets/tileset_tables.inc"
