; trainer_pics.asm — Tier-2 wrapper for the generated trainer sprite data.
;
; The compressed trainer .pic blobs, the class->pic pointer table (TrainerPicPointers,
; indexed by trainer class - 1), and the base prize money (TrainerBaseMoney, bcd3) are
; all generated by tools/generators/gen_trainer_pics.py into assets/trainer_pics.inc (Tier 1,
; machine-owned). This wrapper just gives them a loaded .data section + globals so the
; trainer-battle code (Stage 4) can index a class's pic and feed it to the mon-pic
; decompressor (src/gfx/uncompress.asm), exactly like a wild mon's front pic.
;
; Build: nasm -f coff -I include/ -I . -o trainer_pics.o src/data/trainer_pics.asm

bits 32

global TrainerPicPointers
global TrainerBaseMoney
global PlayerPicFront
global PlayerPicBack

; pret names for the two trainer pics the Oak-speech intro displays (A4). The
; generator emits them as trnpic_<file>; keep pret's labels as the primary
; export the cutscene references, aliased onto the generated bodies.
global ProfOakPic
global Rival1Pic

section .data
align 4
%include "assets/trainer_pics.inc"

ProfOakPic equ trnpic_prof_oak
Rival1Pic  equ trnpic_rival1
