; trainer_pics.asm — Tier-2 wrapper for the generated trainer sprite data.
;
; The compressed trainer .pic blobs, the class->pic pointer table (TrainerPicPointers,
; indexed by trainer class - 1), and the base prize money (TrainerBaseMoney, bcd3) are
; all generated by tools/generators/gen_trainer_pics.py into assets/trainer_pics.inc (Tier 1,
; machine-owned). This wrapper just gives them a loaded .data section + globals so the
; trainer-battle code (Stage 4) can index a class's pic and feed it to the mon-pic
; decompressor (src/gfx/uncompress.asm), exactly like a wild mon's front pic.
;
; Build: nasm -f coff -I include/ -I . -o trainer_pics.o src/data/trainer_pics.asm

bits 32

global TrainerPicPointers
global TrainerBaseMoney
global PlayerPicFront
global PlayerPicBack

section .data
align 4
%include "assets/trainer_pics.inc"
