; grass_water.asm — NUM_MAPS flat (dd) pointers indexed by wCurMap, plus the per-map
; encounter blobs they point at (pret data/wild/maps/*.asm).
;
; pret ref: data/wild/grass_water.asm:WildDataPointers
;
; Generated by tools/generators/gen_wild_encounters.py into assets/wild_grass_water.inc. This carrier sits at the
; mirrored path dos_port/src/data/wild/grass_water.asm; it was part of src/data/wild_data.asm until 2026-08-16
; (docs/current_plan_data_path_mirror.md).
;
; Embedded data goes in .data per the linker rule in docs/assembly.md (.rodata has
; no output-section rule and reads back as zero).
bits 32

global WildDataPointers
global WildDataPointersEnd

section .data
align 4

%include "assets/wild_grass_water.inc"
