; draw_badges.asm — DrawBadges: the 4×2 gym-leader-face / badge grid on the
; player status (trainer-card) screen. Faithful port of pret
; engine/menus/draw_badges.asm (menus-port Session 6, package B).
;
; DrawBadges draws EIGHT cells in two rows of four. Each cell shows a gym
; leader's face; if the matching badge is owned the face is replaced by the
; badge graphic (the face's tile id + 4). The routine only writes tile ids into
; the stride-20 W_TILEMAP scratch — exactly as pret does; the surrounding
; trainer card (StartMenu_TrainerInfo, S9) owns the screen's window/mirror. The
; harness below stands in for that consumer this session.
;
; GFX: the 64-tile badge sheet (assets/badge_tiles.inc, generated by
; tools/gen_badge_tiles.py from pret gfx/trainer_card/badges.2bpp) is loaded by
; LoadBadgeTiles so that face 0 lands at VRAM tile $20 and a badge is its
; face+4 — the fixed tile ids DrawBadges writes. Under the port's $8800-signed
; addressing (LCDC_DEFAULT) a BG tile id T in $00-$7F resolves to VRAM
; $9000 + T*16, so tile $20 = GB_VCHARS2 + $20*TILE_SIZE ($9200). The badge
; range $20-$5F ($9200-$95FF) sits below the box-drawing tiles at vChars2+$60
; ($9600) and is otherwise the overworld tileset region, which the trainer card
; screen does not display — so it is free in this context.
;
; The Japanese-versions name-erasure note in pret is historical (EN behaviour
; only), so no name graphics are drawn above the faces.
;
; Register map (CLAUDE.md): A=AL, BC=BX, DE=DX, HL=ESI, EBP = GB base.
;
; Build (standalone check):
;   nasm -f coff -I include/ -I . -o /dev/null src/engine/menus/draw_badges.asm
; ---------------------------------------------------------------------------
bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_macros.inc"

%define UI_LAYOUT_EQUATES_ONLY 1
%include "assets/ui_layout_menus.inc"

global DrawBadges
global LoadBadgeTiles

extern CopyData                      ; home/copy_data.asm — ESI src off, EDX dst off, BX count
extern FillMemory                    ; home/fill_memory.asm — ESI dest, BX count, AL value
extern g_tilecache_dirty             ; ppu.asm — set on any VRAM tile-data write

%ifdef DEBUG_DRAWBADGES
extern LoadFontTilePatterns          ; gfx/load_font.asm
extern LoadTextBoxTilePatterns       ; gfx/load_font.asm
extern ClearSprites                  ; gfx/sprites.asm
extern set_single_window             ; ppu/ppu.asm
extern g_bg_whiteout                 ; ppu/ppu.asm
extern DelayFrame                    ; video/frame.asm
extern DumpBackbuffer                ; debug/debug_dump.asm
%endif

NUM_BADGES equ 8                     ; constants/ram_constants.asm
GBSCR_W    equ 20                    ; GB screen tile width = stride of the scratch
                                     ; (pret SCREEN_WIDTH; the port's stride-20 model)
BADGE_VRAM_TILE equ 0x20             ; VRAM tile id where face 0 is loaded

; --- badge scratch WRAM (pret ram/wram.asm; sym-pinned bank 00) --------------
; Union scratch in the $CD3D block; DrawBadges writes every byte before it is
; read, so these have no cross-section dependency. Guarded so root can promote
; them into gb_memmap.inc without a redefinition clash (rule 4: reported below).
%ifndef wBadgeNumberTile
wBadgeNumberTile            equ 0xCD3D   ; tile id of the badge number being drawn
%endif
%ifndef wBadgeNameTile
wBadgeNameTile             equ 0xCD3E   ; first tile id of the name being drawn
%endif
%ifndef wBadgeOrFaceTiles
wBadgeOrFaceTiles          equ 0xCD3F   ; ds NUM_BADGES+1 (extra byte read by the shift)
%endif
%ifndef wTempObtainedBadgesBooleans
wTempObtainedBadgesBooleans equ 0xCD49  ; ds NUM_BADGES (0 = not obtained, 1 = obtained)
%endif

section .data
align 4
%include "assets/badge_tiles.inc"        ; badge_face_tiles, BADGE_FACE_TILE_COUNT, BADGE_TILE_BYTES

; pret ref: draw_badges.asm:DrawBadges.FaceBadgeTiles — first tile id of each
; face (badge = face + 4). Held in code space; staged into GB RAM below.
FaceBadgeTiles:
    db 0x20, 0x28, 0x30, 0x38, 0x40, 0x48, 0x50, 0x58

section .text

; ---------------------------------------------------------------------------
; LoadBadgeTiles — copy the 64-tile face/badge sheet into vChars2 so tile id
; $20 = face 0. Port stand-in for the trainer card's graphics load (same shape
; as load_font.asm's tile loaders). Any VRAM tile-data write sets the dirty
; flag. In: EBP = GB base. All registers preserved.
; ---------------------------------------------------------------------------
LoadBadgeTiles:
    mov byte [g_tilecache_dirty], 1
    push eax
    push ecx
    push esi
    push edi
    mov esi, badge_face_tiles
    lea edi, [ebp + GB_VCHARS2 + BADGE_VRAM_TILE * TILE_SIZE]
    mov ecx, (BADGE_FACE_TILE_COUNT * BADGE_TILE_BYTES) / 4
    rep movsd
    pop edi
    pop esi
    pop ecx
    pop eax
    ret

; ---------------------------------------------------------------------------
; DrawBadges — pret ref: engine/menus/draw_badges.asm:DrawBadges.
; Writes the 4×2 badge grid into the stride-20 W_TILEMAP scratch at pret coords
; (2,11) and (2,14). In: EBP = GB base. Clobbers AL/BX/ECX/EDX/ESI/EDI.
; ---------------------------------------------------------------------------
DrawBadges:
; Tile ids for face/badge graphics.  (ld de,wBadgeOrFaceTiles / ld hl,.FaceBadgeTiles
; / ld bc,NUM_BADGES / call CopyData — the source is a code-space table here, not
; GB RAM, so the CopyData is expanded as a flat→GB copy of the same NUM_BADGES bytes.)
    mov esi, FaceBadgeTiles
    lea edi, [ebp + wBadgeOrFaceTiles]
    mov ecx, NUM_BADGES
    rep movsb

; Booleans for each badge.
    mov esi, wTempObtainedBadgesBooleans
    mov bx, NUM_BADGES
    xor al, al
    call FillMemory

; Alter these based on owned badges.
    mov edx, wTempObtainedBadgesBooleans   ; ld de,wTempObtainedBadgesBooleans
    mov esi, wBadgeOrFaceTiles              ; ld hl,wBadgeOrFaceTiles
    mov bh, [ebp + W_OBTAINED_BADGES]       ; ld a,[wObtainedBadges] / ld b,a
    mov bl, NUM_BADGES                      ; ld c,NUM_BADGES
.CheckBadge:
    shr bh, 1                               ; srl b — low bit → CF
    jnc .NextBadge
    add byte [ebp + esi], 4                 ; badge graphics are after each face
    mov byte [ebp + edx], 1
.NextBadge:
    inc esi                                 ; inc hl
    inc edx                                 ; inc de
    dec bl                                  ; dec c
    jnz .CheckBadge

; Draw two rows of badges.
    mov byte [ebp + wBadgeNumberTile], 0xD8 ; ld a,$d8 / ld [hli],a  ; [1]
    mov byte [ebp + wBadgeNameTile], 0x60   ; ld [hl],$60 — first name

    ; hlcoord 2,11
    mov esi, W_TILEMAP + 11 * GBSCR_W + 2
    mov edx, wTempObtainedBadgesBooleans    ; ld de,wTempObtainedBadgesBooleans
    call .DrawBadgeRow

    ; hlcoord 2,14
    mov esi, W_TILEMAP + 14 * GBSCR_W + 2
    mov edx, wTempObtainedBadgesBooleans + 4 ; ld de,wTempObtainedBadgesBooleans+4
    ; fallthrough

.DrawBadgeRow:
; Draw 4 badges.
    mov bl, 4                               ; ld c,4
.DrawBadge:
    push edx                                ; push de
    push esi                                ; push hl

; Badge no.
    mov al, [ebp + wBadgeNumberTile]        ; ld a,[wBadgeNumberTile]
    mov [ebp + esi], al                     ; ld [hli],a
    inc esi
    inc al                                  ; inc a
    mov [ebp + wBadgeNumberTile], al        ; ld [wBadgeNumberTile],a

; Names aren't printed if the badge is owned.
    mov al, [ebp + edx]                     ; ld a,[de]
    test al, al                             ; and a
    mov al, [ebp + wBadgeNameTile]          ; ld a,[wBadgeNameTile] (no flag change)
    jnz .SkipName
    call .PlaceTiles
    jmp .PlaceBadge

.SkipName:
    inc al                                  ; inc a
    inc al                                  ; inc a
    inc esi                                 ; inc hl

.PlaceBadge:
    mov [ebp + wBadgeNameTile], al          ; ld [wBadgeNameTile],a
    mov edx, GBSCR_W - 1                     ; ld de,SCREEN_WIDTH-1
    add esi, edx                            ; add hl,de
    mov al, [ebp + wBadgeOrFaceTiles]       ; ld a,[wBadgeOrFaceTiles]
    call .PlaceTiles
    add esi, edx                            ; add hl,de
    call .PlaceTiles

; Shift badge array back one byte.
    push ebx                                ; push bc
    mov esi, wBadgeOrFaceTiles + 1          ; ld hl,wBadgeOrFaceTiles+1
    mov edx, wBadgeOrFaceTiles              ; ld de,wBadgeOrFaceTiles
    mov bx, NUM_BADGES                      ; ld bc,NUM_BADGES (reads the +1 byte past the list)
    call CopyData
    pop ebx                                 ; pop bc

    pop esi                                 ; pop hl
    mov edx, 4                              ; ld de,4
    add esi, edx                            ; add hl,de

    pop edx                                 ; pop de
    inc edx                                 ; inc de
    dec bl                                  ; dec c
    jnz .DrawBadge
    ret

.PlaceTiles:
    mov [ebp + esi], al                     ; ld [hli],a
    inc esi
    inc al                                  ; inc a
    mov [ebp + esi], al                     ; ld [hl],a
    inc al                                  ; inc a
    ret

%ifdef DEBUG_DRAWBADGES
; ---------------------------------------------------------------------------
; RunDrawBadgesTest — menus S6 FRAME.BIN gate (docs/current_plan_menus.md).
; No live caller this session: seed a mixed badge set, load the tile graphics,
; draw the grid into the stride-20 scratch, then mirror the 16×6 badge rect
; into GB_TILEMAP1 and show it through UI_TRAINER_CARD_BADGES. Renders 3 frames,
; dumps FRAME.BIN, exits. Never returns. In: EBP = GB base.
; ---------------------------------------------------------------------------
global RunDrawBadgesTest
RunDrawBadgesTest:
    ; seed: badges 1,3,6,8 owned (bit i = badge i+1) = %10100101
    mov byte [ebp + W_OBTAINED_BADGES], 0xA5
    ; defined glyphs for the (unloaded-in-harness) number/name cells + box tiles
    or byte [ebp + W_FONT_LOADED], (1 << BIT_FONT_LOADED)
    call LoadFontTilePatterns
    call LoadTextBoxTilePatterns
    call LoadBadgeTiles
    ; clean, single-window render (mirrors RunTextBoxIDTest): no player OAM
    call ClearSprites
    mov byte [ebp + W_UPDATE_SPRITES_ENABLED], 0
    ; blank the stride-20 scratch (18 rows × 20)
    mov esi, W_TILEMAP
    mov bx, 18 * GBSCR_W
    mov al, 0x7F
    call FillMemory
    call DrawBadges
    call BadgesTestMirror
    ; whiteout the field around the window; show the 16×6 grid rect
    ; PROJ menus: window = UI_TRAINER_CARD_BADGES_(WX,WY,CLIP,MAXY) [GB(2,11) 16×6]
    mov dword [g_bg_whiteout], 1
    mov eax, UI_TRAINER_CARD_BADGES_WX
    mov ebx, UI_TRAINER_CARD_BADGES_WY
    mov ecx, UI_TRAINER_CARD_BADGES_CLIP
    mov edx, UI_TRAINER_CARD_BADGES_MAXY
    mov esi, GB_TILEMAP1
    xor edi, edi                            ; start_row = 0
    call set_single_window
    call DelayFrame
    call DelayFrame
    call DelayFrame
    call DumpBackbuffer                     ; writes FRAME.BIN + exits
.hang:
    jmp .hang

; BadgesTestMirror — copy the badge rect (scratch rows 11-16, cols 2-17) to
; GB_TILEMAP1 rows 0-5 cols 0-15 (the window's 32-stride source band).
; Preserves all registers.
BadgesTestMirror:
    pushad
    xor ebx, ebx                            ; rect row 0..5
.row:
    mov esi, ebx
    add esi, 11                             ; scratch row = 11 + i
    imul esi, esi, GBSCR_W
    add esi, 2                              ; cols 2..17
    lea esi, [ebp + esi + W_TILEMAP]
    mov edi, ebx
    shl edi, 5                              ; row * 32 tilemap stride
    lea edi, [ebp + edi + GB_TILEMAP1]
    mov ecx, 16                             ; 16-tile rect width
    rep movsb
    inc ebx
    cmp ebx, 6
    jb .row
    popad
    ret
%endif
