; draw_start_menu.asm — DrawStartMenu: render the overworld START menu box.
; Faithful port of pret engine/menus/draw_start_menu.asm (menus-port Session 4;
; replaces the bespoke start_menu.asm renderer).
;
; CANVAS MODEL + WINDOW BRIDGE (docs/ui_projection.md):
; The box and item labels are drawn at UI_*-projected coordinates into the
; 40-wide W_TILEMAP canvas (stride 40, same model as DisplayTextBoxID_), then
; StartMenuShowWindow blits the box rect → GB_TILEMAP1 rows 0..H-1 and defines
; the window descriptor from the UI_START_MENU_* equates, so the box composites
; over the live overworld map. sm_canvas_mirror re-blits each HandleMenuInput
; iteration (menu_redraw_cb) so the ▶ cursor reaches the compositor.
;
; ; PROJ menus: GB(10,0) 10x16 --(anchor=right/top, X+20, Y+0)--> wx=247 wy=0
;   clip=80 max_y=128 [UI_START_MENU_*]; without the Pokédex the box is 14 rows
;   (max_y = 112, derived from the same equates).
;
; Register map (CLAUDE.md): A=AL, BC=BX, DE=DX, HL=ESI, EBP = GB base.
;
; Build (standalone check):
;   nasm -f coff -I include/ -I . -o /dev/null src/engine/menus/draw_start_menu.asm
; ---------------------------------------------------------------------------
bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "assets/event_constants.inc"
%include "events.inc"

global DrawStartMenu
global StartMenuShowWindow              ; home/start_menu.asm re-arms it after sub-menus
global sm_canvas_mirror                 ; menu_redraw_cb while the START menu has focus

extern TextBoxBorder                    ; text.asm — ESI=top-left, BL=int_w, BH=int_h
extern PlaceString                      ; text.asm — ESI=dest, EAX=flat src
extern set_single_window                ; ppu.asm — g_windows[] = one descriptor
extern text_row_stride                  ; text.asm — active W_TILEMAP row stride
extern menu_item_step                   ; home/window.asm — cursor per-item row step
extern menu_redraw_cb                   ; home/window.asm — per-frame redraw callback

; START-menu geometry from the frozen layout (assets/ui_layout_menus.inc is
; %included once by text_box.asm; the equates needed here are mirrored via the
; generated file — include it under a guard-free unique-labels scheme is not
; possible twice, so this file %includes it too; it holds only equates + one
; table label, which would collide. Instead: the UI_* values are equ-only in
; the generated file EXCEPT UI_TextBoxCoordTable_menus (a data label), so a
; second %include would duplicate that label. We therefore re-derive nothing
; and %include with the table masked out via the UI_LAYOUT_EQUATES_ONLY guard
; emitted by gen_ui_layout.py.
%define UI_LAYOUT_EQUATES_ONLY 1
%include "assets/ui_layout_menus.inc"

; Item-label strings (Tier 1, generated by tools/gen_menu_strings.py through the
; unicode_converter charmap). pret names alias the generated labels.
%include "assets/menu_strings.inc"
StartMenuPokedexText equ sm_str_pokedex
StartMenuPokemonText equ sm_str_pokemon
StartMenuItemText    equ sm_str_item
StartMenuSaveText    equ sm_str_save
StartMenuResetText   equ sm_str_reset
StartMenuOptionText  equ sm_str_option
StartMenuExitText    equ sm_str_exit

SM_SROW         equ 0                   ; GB_TILEMAP1 start row for the box mirror
SM_TOTAL_W      equ UI_START_MENU_X2 - UI_START_MENU_COL + 1   ; 10 tiles

section .bss
align 4
sm_box_rows:    resd 1                  ; total box rows incl. borders (14 or 16)

section .text

; ---------------------------------------------------------------------------
; DrawStartMenu — pret ref: engine/menus/draw_start_menu.asm:DrawStartMenu.
; Draws the box + labels, seeds the HandleMenuInput state, then (port) bridges
; the canvas rect to a window descriptor. In: EBP = GB base.
; ---------------------------------------------------------------------------
DrawStartMenu:
    ; port: the START menu session runs on the 40-wide canvas
    mov dword [text_row_stride], SCREEN_TILES_W
    mov dword [menu_item_step], 2 * SCREEN_TILES_W

    ; CheckEvent EVENT_GOT_POKEDEX / hlcoord 10,0 / lb bc,14,8 (else 12,8)
    ; PROJ menus: box top-left = UI_START_MENU_(COL,ROW), canvas stride 40
    CheckEvent EVENT_GOT_POKEDEX        ; ZF=0 → have the Pokédex
    mov esi, W_TILEMAP + UI_START_MENU_ROW * SCREEN_TILES_W + UI_START_MENU_COL
    mov bx, (14 << 8) | 8               ; b = 14 interior rows, c = 8 interior cols
    mov dword [sm_box_rows], 16
    jnz .drawTextBoxBorder
    mov bx, (12 << 8) | 8               ; shorter menu without the Pokédex
    mov dword [sm_box_rows], 14
.drawTextBoxBorder:
    call TextBoxBorder

    ; ld a, PAD_DOWN|PAD_UP|PAD_START|PAD_B|PAD_A / ld [wMenuWatchedKeys],a
    mov byte [ebp + wMenuWatchedKeys], PAD_DOWN | PAD_UP | PAD_START | PAD_B | PAD_A
    ; wTopMenuItemY = 2 ; wTopMenuItemX = $0b — projected onto the canvas
    ; PROJ menus: cursor = (UI_START_MENU_COL+1, UI_START_MENU_ROW+2)
    mov byte [ebp + wTopMenuItemY], UI_START_MENU_ROW + 2
    mov byte [ebp + wTopMenuItemX], UI_START_MENU_COL + 1
    ; remembered selection from last time
    mov al, [ebp + wBattleAndStartSavedMenuItem]
    mov [ebp + wCurrentMenuItem], al
    mov [ebp + wLastMenuItem], al
    xor al, al
    mov [ebp + wMenuWatchMovingOutOfBounds], al
    ; set BIT_NO_TEXT_DELAY, [wStatusFlags5]
    or byte [ebp + W_STATUS_FLAGS_5], (1 << BIT_NO_TEXT_DELAY)

    ; hlcoord 12,2 → canvas (COL+2, ROW+2); items every 2 rows
    mov esi, W_TILEMAP + (UI_START_MENU_ROW + 2) * SCREEN_TILES_W + UI_START_MENU_COL + 2
    CheckEvent EVENT_GOT_POKEDEX
    mov al, 0x06                        ; menu item count without the Pokédex
    jz .storeMenuItemCount
    mov eax, StartMenuPokedexText
    call PrintStartMenuItem
    mov al, 0x07                        ; one more with the Pokédex
.storeMenuItemCount:
    mov [ebp + wMaxMenuItem], al        ; pret stores the COUNT (one past the max
                                        ; index) — the phantom-row quirk is handled
                                        ; by RedisplayStartMenu's wrap checks
    mov eax, StartMenuPokemonText
    call PrintStartMenuItem
    mov eax, StartMenuItemText
    call PrintStartMenuItem
    lea eax, [ebp + W_PLAYER_NAME]      ; ld de, wPlayerName (flat for PlaceString)
    call PrintStartMenuItem
    ; SAVE, or RESET while a link session is active
    mov al, [ebp + W_STATUS_FLAGS_4]
    test al, (1 << BIT_LINK_CONNECTED)
    mov eax, StartMenuSaveText
    jz .printSaveOrResetText
    mov eax, StartMenuResetText
.printSaveOrResetText:
    call PrintStartMenuItem
    mov eax, StartMenuOptionText
    call PrintStartMenuItem
    mov eax, StartMenuExitText
    call PlaceString                    ; last item: no row advance (pret PlaceString)
    ; res BIT_NO_TEXT_DELAY, [wStatusFlags5]
    and byte [ebp + W_STATUS_FLAGS_5], ~(1 << BIT_NO_TEXT_DELAY) & 0xFF

    ; port: expose the canvas rect as the single window over the map
    jmp StartMenuShowWindow             ; tail — returns to DrawStartMenu's caller

; ---------------------------------------------------------------------------
; PrintStartMenuItem — pret ref: draw_start_menu.asm:PrintStartMenuItem.
; In: ESI = dest, EAX = flat string. Out: ESI += 2 canvas rows.
; ---------------------------------------------------------------------------
PrintStartMenuItem:
    push esi                            ; push hl
    call PlaceString                    ; (returns ESI = line start)
    pop esi                             ; pop hl
    add esi, SCREEN_TILES_W * 2         ; ld de, SCREEN_WIDTH*2 / add hl,de (canvas)
    ret

; ---------------------------------------------------------------------------
; StartMenuShowWindow — port plumbing: mirror the canvas box → GB_TILEMAP1 and
; define the window list as exactly the START menu box. Also arms the
; per-frame mirror callback for HandleMenuInput.
; ; PROJ menus: window = UI_START_MENU_(WX,WY,CLIP); max_y = box_rows*8
;   (UI_START_MENU_MAXY when the Pokédex row is present).
; ---------------------------------------------------------------------------
StartMenuShowWindow:
    call sm_canvas_mirror
    mov eax, UI_START_MENU_WX
    mov ebx, UI_START_MENU_WY
    mov ecx, UI_START_MENU_CLIP
    mov edx, [sm_box_rows]
    shl edx, 3                          ; max_y = rows*8 (=UI_START_MENU_MAXY w/ dex)
    mov esi, GB_TILEMAP1
    mov edi, SM_SROW
    call set_single_window
    mov dword [menu_redraw_cb], sm_canvas_mirror
    ret

; ---------------------------------------------------------------------------
; sm_canvas_mirror — copy the box rect from the canvas (stride 40, at
; UI_START_MENU_(COL,ROW)) to GB_TILEMAP1 rows SM_SROW.. cols 0..9. Preserves
; all registers (doubles as menu_redraw_cb inside HandleMenuInput).
; ---------------------------------------------------------------------------
sm_canvas_mirror:
    pushad
    xor ebx, ebx                        ; row
.row:
    mov esi, ebx
    imul esi, esi, SCREEN_TILES_W
    lea esi, [ebp + esi + W_TILEMAP + UI_START_MENU_ROW * SCREEN_TILES_W + UI_START_MENU_COL]
    mov edi, ebx
    shl edi, 5                          ; row * 32
    lea edi, [ebp + edi + GB_TILEMAP1 + SM_SROW * 32]
    mov ecx, SM_TOTAL_W
    rep movsb
    inc ebx
    cmp ebx, [sm_box_rows]
    jb .row
    popad
    ret
