; ===========================================================================
; oaks_pc.asm — OPEN OAK's PC. Faithful port of pret engine/menus/oaks_pc.asm.
;
; pret flow: SaveScreenTilesToBuffer2 / PrintText AccessedOaksPCText /
; PrintText GetDexRatedText / YesNoChoice / if NO skip / predef DisplayDexRating
; / PrintText ClosedOaksPCText / jp LoadScreenTilesFromBuffer2.
;
; The three dialogs are pret's own text_far streams (Tier-1 data in
; assets/oaks_pc_text.inc, generated by tools/gen_menu_strings.py from
; data/text/text_3.asm) printed by PrintText — the `para` page break, the
; terminal `prompt` and ClosedOaksPCText's text_waitbutton are executed by the
; text engine, not re-implemented here. (Until menu-fidelity row 17 part 3 this
; file drew the pages itself out of hand-encoded charmap bytes and re-implemented
; the prompt wait; its header claimed that was forced by "the far-text streams
; aren't GB-space assets yet" — untrue: they are exactly as printable as
; pc.asm's. See ledger M-87.)
;
; DEVIATION{class=projection; pret=engine/menus/oaks_pc.asm:OaksPC; behavior=hide the dialog descriptor after LoadScreenTilesFromBuffer2 restores wTileMap; evidence=pret OaksPC restore tail plus port window-list ownership; lifetime=permanent window-compositor boundary}
; pret's LoadScreenTilesFromBuffer2 restores wTileMap
; and the GB's single hardware window follows; the port's dialogs are entries in a
; window-descriptor list that a WRAM restore cannot drop, so the restore is followed
; by hide_window (the pc.asm:ActivatePC precedent, same reason).
;
; Register map (CLAUDE.md): A=AL, BC=BX, DE=DX, HL=ESI, EBP = GB base.
;
; Build (standalone check):
;   nasm -f coff -I include/ -I . -o /dev/null src/engine/menus/oaks_pc.asm
; ---------------------------------------------------------------------------
bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_macros.inc"
%include "gb_text.inc"                  ; text_far / text_end / text_waitbutton

global OpenOaksPC
global AccessedOaksPCText
global GetDexRatedText
global ClosedOaksPCText

extern PrintText                        ; home/window.asm — In: ESI = text stream
extern text_msgbox                      ; home/text.asm — the active msgbox projection
extern msgbox_dialog                    ; home/text.asm — the standard bottom dialog box
extern YesNoChoice                      ; home/yes_no.asm — sets [wCurrentMenuItem]
extern SaveScreenTilesToBuffer2         ; movie/title.asm — wTileMap → wTileMapBackup2
extern LoadScreenTilesFromBuffer2       ; movie/title.asm — wTileMapBackup2 → wTileMap
extern hide_window                      ; ppu/ppu.asm — drop the dialog window layer
extern DisplayDexRating                 ; oaks_pc_stubs.asm SEAM (pokédex package)

%ifdef DEBUG_OAKSPC
global RunOaksPCTest
extern LoadFontTilePatterns             ; gfx/load_font.asm
%endif

; ===========================================================================
; Tier-1 DATA: the three message streams, generated from pret data/text/text_3.asm.
%include "assets/oaks_pc_text.inc"

; ===========================================================================
section .text

; ---------------------------------------------------------------------------
; OpenOaksPC — pret ref: engine/menus/oaks_pc.asm:OpenOaksPC.
; In: EBP = GB base.
; ---------------------------------------------------------------------------
OpenOaksPC:
    call SaveScreenTilesToBuffer2
    mov dword [text_msgbox], msgbox_dialog    ; port: publish the box projection
    mov esi, AccessedOaksPCText               ; ld hl, AccessedOaksPCText
    call PrintText
    mov dword [text_msgbox], msgbox_dialog
    mov esi, GetDexRatedText                  ; ld hl, GetDexRatedText
    call PrintText                            ; ends in `done` — stays up under YES/NO
    call YesNoChoice
    mov al, [ebp + wCurrentMenuItem]
    and al, al
    jnz .closePC                              ; jr nz — NO chosen, skip the rating
    call DisplayDexRating                     ; predef DisplayDexRating (SEAM — stub)
.closePC:
    mov dword [text_msgbox], msgbox_dialog
    mov esi, ClosedOaksPCText                 ; ld hl, ClosedOaksPCText
    call PrintText
    call LoadScreenTilesFromBuffer2           ; jp LoadScreenTilesFromBuffer2
    call hide_window                          ; structured projection deviation above: the WRAM
                                              ; restore cannot drop the dialog WINDOW.
    ret

; --- the three OAK's-PC dialogs (pret ref: engine/menus/oaks_pc.asm, same
; position). Tier-2 wrappers over the Tier-1 streams in assets/oaks_pc_text.inc,
; keeping pret's text_far indirection.
AccessedOaksPCText:
    text_far _AccessedOaksPCText
    text_end

GetDexRatedText:
    text_far _GetDexRatedText
    text_end

ClosedOaksPCText:
    text_far _ClosedOaksPCText
    text_waitbutton
    text_end

%ifdef DEBUG_OAKSPC
; ---------------------------------------------------------------------------
; RunOaksPCTest — FRAME.BIN gate for OAK's PC (menu-fidelity row 17 part 3).
; No golden covers this screen and nothing in the linked game reaches OpenOaksPC
; yet, so this is how the dialog gets observed. OpenOaksPC prints
; AccessedOaksPCText and blocks in the stream's page-break prompt; the harness
; runs with AUTOKEY_QUIET (no presses), so AutoKeyDrive photographs the open
; dialog at AUTOKEY_DUMP_FRAME and exits. (The RunPCTest pattern; the previous
; harness dumped from a hook spliced into the middle of OpenOaksPC itself.)
; In: EBP = GB base. Called from EnterMap after the overworld is set up.
; ---------------------------------------------------------------------------
RunOaksPCTest:
    or byte [ebp + W_FONT_LOADED], (1 << BIT_FONT_LOADED)
    call LoadFontTilePatterns
    call OpenOaksPC
.hang:
    jmp .hang
%endif
