; start_menu.asm — overworld START menu (DisplayStartMenu).
;
; Faithful port subset of home/start_menu.asm + engine/menus/draw_start_menu.asm.
; Renders the corner menu box via the GB window layer (exactly like the dialog
; box) and runs a blocking navigation loop. All sub-menus are no-op stubs for
; now: SAVE is an intentional dead-end (no save system yet) and the others are
; hooks for the upcoming item / party / options UIs. EXIT / B / START close it.
; The point is a real, navigable, dispatching menu so the item and event work
; has something concrete to hang off.
;
; Rendering: the box + item labels are drawn into wTileMap (the text engine's
; 20-wide scratch grid, which is NOT the BG source in the overworld) with
; TextBoxBorder / place_flat_str, then the 10×{14,16} box rect is copied into the
; window tilemap (GB_TILEMAP1) and shown via the window descriptor list. A single
; descriptor (set_single_window) bounds the window to the box rect so it does not
; paint over the rest of the overworld.
; Window placement mirrors the dialog box's "center the 20-tile GB screen in the
; 320px viewport" convention (see src/engine/overworld/map_sprites.asm).
;
; Input: H_JOY_PRESSED is reliable here because this loop calls DelayFrame (→ one
; joypad_update) exactly once per iteration, unlike OverworldLoop's double-delay
; idle path that forced it onto H_JOY_HELD.
;
; Pret ref: home/start_menu.asm:DisplayStartMenu, engine/menus/draw_start_menu.asm
; ---------------------------------------------------------------------------
bits 32

%include "gb_memmap.inc"
%include "gb_macros.inc"
%include "assets/event_constants.inc"
%include "events.inc"

global DisplayStartMenu

extern TextBoxBorder         ; src/text/text.asm — ESI=top-left, BL=width, BH=height
extern PlaceString           ; src/text/text.asm — ESI=dest, EDX=src ptr (EBP-rel)
extern place_flat_str        ; src/text/text.asm — ESI=dest, EAX=flat src ptr
extern DelayFrame            ; src/video/frame.asm — one frame: render + input
extern LoadFontTilePatterns  ; src/gfx/load_font.asm — swap font glyphs into vFont
extern LoadNPCSpriteTiles    ; map_sprites.asm — restore NPC walk tiles to vFont
extern LoadPlayerSpriteGraphics ; overworld.asm — restore player walk tiles to vFont
extern DisplayBagMenu        ; src/engine/menus/bag_menu.asm — START→ITEM bag list
extern DisplayPartyMenu      ; src/engine/menus/party_menu.asm — START→POKéMON party list
extern set_single_window     ; src/ppu/ppu.asm — define g_windows[] as one descriptor
extern hide_window           ; src/ppu/ppu.asm — empty the window list (count=0)
%ifdef DEBUG_STARTMENU
extern DumpBackbuffer        ; src/debug/debug_dump.asm — dump FRAME.BIN + exit
%endif

; --- layout constants (GB 20-wide logical screen coords) ---
SM_BOX_COL        equ 10      ; box top-left column (right portion of GB screen)
SM_BOX_W          equ 8       ; interior width (cols 11-18)
SM_TEXT_COL       equ 12      ; menu-item text column
SM_CURSOR_COL     equ 11      ; ▶ cursor column
SM_FIRST_ROW      equ 2       ; first item row (pret wTopMenuItemY)
SM_ROW_STEP       equ 2       ; rows between items
SM_BOX_NCOLS      equ 10      ; TL..TR inclusive (SM_BOX_W + 2 borders)

; Window placement: the original renders the menu flush to the top-right of the
; 20-tile GB screen. Our viewport is wider (40 tiles / 320px), so we translate the
; box to the right EDGE of the actual viewport rather than the centered GB screen.
; The box is 10 tiles (80px) wide; flush-right puts its left edge at px 320-80=240
; (col 30). render_window's left edge is WX-7, so WX = 247 → left at px 240, and
; the 80px blit fills px 240-319 exactly (clipped at the right edge, no overflow).
SM_WIN_WX         equ 247
SM_WIN_CLIP_W     equ 80       ; 10 tiles

CHAR_CURSOR       equ 0xED     ; ▶  (constants/charmap.asm)
TILE_SPC          equ 0x7F     ; blank space tile

; logical item ids — pret's dispatch numbering (Pokédex present). When the dex is
; absent the displayed index is shifted up by 1 to land on this same scale.
ITEM_POKEMON      equ 1
ITEM_ITEM         equ 2
ITEM_EXIT         equ 6

section .data
align 4
sm_saved_item: db 0          ; remembered cursor position across opens (pret: wBattleAndStartSavedMenuItem)

; Menu-item labels (sm_str_*), GB-charmap encoded and '@'-terminated. Generated by
; tools/gen_menu_strings.py, which routes each label through the unicode_converter
; submodule (gb_text.encode) rather than hand-written hex. All labels use single-
; char glyphs only (incl. 'é' $BA), so place_flat_str — which skips control codes
; below $60 — renders them verbatim.
%include "assets/menu_strings.inc"

section .bss
align 4
sm_has_dex:   resd 1          ; 1 = Pokédex slot present (7 items), 0 = absent (6)
sm_num_items: resd 1          ; displayed item count (6 or 7)
sm_box_rows:  resd 1          ; total box rows incl borders (14 or 16)
sm_cur_esi:   resd 1          ; running wTileMap write offset for item text

section .text

; ---------------------------------------------------------------------------
; DisplayStartMenu — draw the START menu, run it until EXIT/B/START, then hide.
; In:  EBP = GB memory base. All registers preserved (pushad/popad).
; ---------------------------------------------------------------------------
DisplayStartMenu:
    pushad

    ; --- swap the text font into vFont ($8800) ---
    ; vFont is time-shared with the player's/NPCs' walk tiles in the overworld, so
    ; the glyphs are NOT resident until loaded. Mirror the dialog path exactly
    ; (map_sprites.asm:CheckNPCInteraction): force the player to a standing pose
    ; first (a frozen walk image index points into vFont and would otherwise render
    ; the player sprite as font glyphs), set BIT_FONT_LOADED (freezes NPC movement),
    ; then load the font. Restored on close. See [[project_phase2_title]].
    mov al, [ebp + W_SPRITE_PLAYER_FACING_DIR]
    mov [ebp + W_SPRITE_PLAYER_IMAGE_INDEX], al
    mov byte [ebp + W_SPRITE_PLAYER_ANIM_FRAME], 0
    mov byte [ebp + W_SPRITE_PLAYER_INTRA_ANIM], 0
    or byte [ebp + W_FONT_LOADED], (1 << BIT_FONT_LOADED)
    call LoadFontTilePatterns

    ; --- Pokédex presence → item count / box interior height ---
    CheckEvent EVENT_GOT_POKEDEX        ; ZF=1 → flag clear → no Pokédex
    jz .no_dex
    mov dword [sm_has_dex], 1
    mov dword [sm_num_items], 7
    mov dword [sm_box_rows], 16         ; interior 14 + 2 borders
    jmp .state_done
.no_dex:
    mov dword [sm_has_dex], 0
    mov dword [sm_num_items], 6
    mov dword [sm_box_rows], 14         ; interior 12 + 2 borders

.state_done:
    ; --- restore saved cursor, clamp to the current max index (initial open) ---
    movzx eax, byte [sm_saved_item]
    mov edx, [sm_num_items]
    dec edx                             ; max valid index
    cmp eax, edx
    jbe .sel_ok
    xor eax, eax
.sel_ok:
    mov [ebp + W_CURRENT_MENU_ITEM], al

    call .draw_full                     ; box + items + window bounds + cursor

%ifdef DEBUG_STARTMENU
    call DelayFrame                     ; render one frame with the menu window shown
    call DumpBackbuffer                 ; dump FRAME.BIN + exit (never returns)
%endif

    ; --- swallow the opening press: wait for START/A release first ---
.wait_open_release:
    call DelayFrame
    test byte [ebp + H_JOY_HELD], PAD_START | PAD_A
    jnz .wait_open_release
    jmp .loop

; --- draw_full: (re)draw the whole box + items + window bounds + cursor. ret. ---
; Used on initial open and to restore the menu after a sub-menu (e.g. the bag).
.draw_full:
    mov esi, W_TILEMAP + SM_BOX_COL     ; (col 10, row 0)
    mov bl, SM_BOX_W
    mov eax, [sm_box_rows]
    sub eax, 2                          ; interior height (rows - 2 borders)
    mov bh, al
    call TextBoxBorder

    ; --- place item labels (text col 12, rows 2,4,...) ---
    mov dword [sm_cur_esi], W_TILEMAP + SM_FIRST_ROW * 20 + SM_TEXT_COL

    cmp dword [sm_has_dex], 0
    je .skip_dex
    mov eax, sm_str_pokedex
    call .place_flat_item
.skip_dex:
    mov eax, sm_str_pokemon
    call .place_flat_item
    mov eax, sm_str_item
    call .place_flat_item
    ; TRAINER INFO entry = the player's name (EBP-relative → PlaceString)
    mov esi, [sm_cur_esi]
    mov edx, W_PLAYER_NAME
    call PlaceString
    add dword [sm_cur_esi], SM_ROW_STEP * 20
    mov eax, sm_str_save
    call .place_flat_item
    mov eax, sm_str_option
    call .place_flat_item
    mov eax, sm_str_exit
    call .place_flat_item

    ; --- copy box rect (wTileMap cols 10-19) → GB_TILEMAP1 (cols 0-9) ---
    xor ecx, ecx                        ; row
.copy_row:
    imul esi, ecx, 20
    lea esi, [ebp + esi + W_TILEMAP + SM_BOX_COL]
    mov edi, ecx
    shl edi, 5                          ; row * 32 (window tilemap stride)
    lea edi, [ebp + edi + GB_TILEMAP1]
    push ecx
    mov ecx, SM_BOX_NCOLS
    rep movsb
    pop ecx
    inc ecx
    cmp ecx, [sm_box_rows]
    jb .copy_row

    ; --- position + bound the window over the box (single descriptor) ---
    ; PROJ overworld-ui: GB(10,0) 10xN --(anchor=top-right, X+20, Y+0)--> wx=247 wy=0 clip=80 max_y=rows*8
    mov eax, SM_WIN_WX                  ; wx = 247 (flush-right)
    xor ebx, ebx                        ; wy = 0 (top)
    mov ecx, SM_WIN_CLIP_W              ; clip_w = 80px (10 tiles)
    mov edx, [sm_box_rows]
    shl edx, 3                          ; max_y = rows * 8 px → box bottom
    mov esi, GB_TILEMAP1                ; menu box source tilemap
    xor edi, edi                        ; start_row = 0
    call set_single_window              ; count=1; mirrors wy→H_WY, wx→IO_WX

    call .draw_cursor
    ret

    ; ======================= navigation loop =======================
.loop:
    call DelayFrame
    movzx eax, byte [ebp + H_JOY_PRESSED]
    test al, PAD_DOWN
    jnz .move_down
    test al, PAD_UP
    jnz .move_up
    test al, PAD_A
    jnz .select
    test al, PAD_B | PAD_START
    jnz .close
    jmp .loop

.move_down:
    call .erase_cursor
    movzx eax, byte [ebp + W_CURRENT_MENU_ITEM]
    inc eax
    cmp eax, [sm_num_items]
    jb .store_sel
    xor eax, eax                        ; past bottom → wrap to top
    jmp .store_sel
.move_up:
    call .erase_cursor
    movzx eax, byte [ebp + W_CURRENT_MENU_ITEM]
    test eax, eax
    jnz .up_dec
    mov eax, [sm_num_items]             ; at top → wrap to bottom
.up_dec:
    dec eax
.store_sel:
    mov [ebp + W_CURRENT_MENU_ITEM], al
    call .draw_cursor
    jmp .loop

.select:
    movzx eax, byte [ebp + W_CURRENT_MENU_ITEM]
    ; Map displayed index → logical id: shift up by 1 when the Pokédex is absent
    ; (display 0 = Pokémon = logical 1), so EXIT is logical 6 in both layouts.
    cmp dword [sm_has_dex], 0
    jne .have_logical
    inc eax
.have_logical:
    cmp eax, ITEM_EXIT
    je .close
    cmp eax, ITEM_ITEM
    je .open_item
    cmp eax, ITEM_POKEMON
    je .open_party
    ; Pokédex / Trainer / Save / Option: no-op stubs for now. SAVE is an intentional
    ; dead-end (no save system); the rest are hooks for upcoming UIs. Each just
    ; returns to the menu; the edge-triggered read keeps A from re-firing.
    jmp .loop

.open_item:
    call DisplayBagMenu                 ; bag list (its own loop); font stays loaded
    call .draw_full                     ; restore START menu box + window bounds + cursor
    jmp .loop

.open_party:
    call DisplayPartyMenu               ; party list (its own loop); font stays loaded
    call .draw_full                     ; restore START menu box + window bounds + cursor
    jmp .loop

.close:
    movzx eax, byte [ebp + W_CURRENT_MENU_ITEM]
    mov [sm_saved_item], al             ; remember selection for next open
    ; Hide the window (count=0). The next box owner fully redefines the list.
    call hide_window
    ; Swap the walk tiles back into vFont (font was loaded for the menu).
    and byte [ebp + W_FONT_LOADED], ~(1 << BIT_FONT_LOADED)
    call LoadNPCSpriteTiles
    call LoadPlayerSpriteGraphics
.close_release:
    call DelayFrame
    test byte [ebp + H_JOY_HELD], PAD_A | PAD_B | PAD_START
    jnz .close_release
    popad
    ret

; --- helpers (called only via `call`; main flow never falls through) ----------

; place flat '@'-string (EAX = src ptr) at [sm_cur_esi], then advance 2 rows.
.place_flat_item:
    mov esi, [sm_cur_esi]
    call place_flat_str
    add dword [sm_cur_esi], SM_ROW_STEP * 20
    ret

; EAX ← GB_TILEMAP1 cursor offset for the current selection (clobbers EAX only).
.cursor_offset:
    movzx eax, byte [ebp + W_CURRENT_MENU_ITEM]
    imul eax, eax, SM_ROW_STEP          ; sel * 2
    add eax, SM_FIRST_ROW               ; + first item row
    shl eax, 5                          ; row * 32
    add eax, GB_TILEMAP1 + (SM_CURSOR_COL - SM_BOX_COL)   ; window col 1
    ret

.draw_cursor:
    call .cursor_offset
    mov byte [ebp + eax], CHAR_CURSOR
    ret

.erase_cursor:
    call .cursor_offset
    mov byte [ebp + eax], TILE_SPC
    ret
