; evos_moves.asm — flat dd pointers to each species' evolution + learnset blob.
;
; pret ref: data/pokemon/evos_moves.asm:EvosMovesPointerTable
;
; Generated by tools/generators/gen_evos_moves.py into assets/evos_moves.inc. This carrier sits at the
; mirrored path dos_port/src/data/pokemon/evos_moves.asm; it was part of src/data/pokemon_data.asm until 2026-08-16
; (docs/current_plan_data_path_mirror.md).
;
; Embedded data goes in .data per the linker rule in docs/assembly.md (.rodata has
; no output-section rule and reads back as zero).
bits 32

global EvosMovesPointerTable

section .data

%include "assets/evos_moves.inc"
