#!/usr/bin/env python3
"""gen_move_names.py — generate dos_port/assets/move_names.inc from pret.

Emits MoveNames: NUM_ATTACKS (165) **variable-length**, '@'-terminated ($50)
records in move-id order, GB-charmap encoded — exactly as pret's `li` macro over
data/moves/names.asm (which expands to `db <text>, "@"`).

Unlike MonsterNames (fixed-width, indexed by AddNTimes), move names are walked by
the shared GetName dispatcher counting $50 terminators, so they are NOT padded.
Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"
NUM_ATTACKS = 165
TERM = 0x50               # '@' terminator
MOVE_NAME_MAX = 12        # MOVE_NAME_LENGTH - 2 (in-battle text fit; pret list_start)


def load_charmap(path: Path) -> list:
    cm = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s+charmap\s+"((?:[^"\\]|\\.)*)",\s*\$([0-9a-fA-F]+)', line)
        if m:
            cm.append((m.group(1), int(m.group(2), 16)))
    cm.sort(key=lambda x: -len(x[0]))      # longest-match first
    return cm


def encode(s: str, charmap: list) -> bytes:
    out, i = [], 0
    while i < len(s):
        for key, val in charmap:
            if key and s[i:].startswith(key):
                out.append(val)
                i += len(key)
                break
        else:
            raise ValueError(f"Unrecognised char at {i}: {s[i:i+4]!r}")
    return bytes(out)


def main() -> int:
    charmap = load_charmap(ROOT / "constants/charmap.asm")
    names = []
    for line in (ROOT / "data/moves/names.asm").read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s*li\s+"((?:[^"\\]|\\.)*)"', line)
        if m:
            names.append(m.group(1))
    if len(names) != NUM_ATTACKS:
        print(f"expected {NUM_ATTACKS} names, got {len(names)}", file=sys.stderr)
        return 1

    out = [
        "; move_names.inc — generated by tools/gen_move_names.py. DO NOT EDIT BY HAND.",
        f"; MoveNames: {NUM_ATTACKS} variable-length '@'-terminated names, move-id order.",
        "; Walked by GetName (counts $50 terminators); NOT fixed-width.",
        "",
        "MoveNames:",
    ]
    total = 0
    for i, nm in enumerate(names):
        enc = encode(nm, charmap)
        if len(enc) > MOVE_NAME_MAX:
            print(f"name too long ({len(enc)} > {MOVE_NAME_MAX}): {nm!r}", file=sys.stderr)
            return 1
        rec = enc + bytes([TERM])
        total += len(rec)
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in rec) + f"    ; move {i + 1}  {nm}")
    out += ["MoveNames_end:", ""]

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "move_names.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} (MoveNames {len(names)} names, {total} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
