#!/usr/bin/env python3
"""gen_menu_strings.py — generate dos_port/assets/menu_strings.inc + menu_text.inc.

Two kinds of Tier-1 menu data, both from pret:

  * menu_strings.inc — the START-menu item LABELS, encoded through the
    unicode_converter submodule (gb_text.encode) instead of hand-written charmap
    hex, emitted as NASM `db` lines with the '@' terminator ($50). Consumed by
    src/engine/menus/draw_start_menu.asm, which aliases each generated label to
    the pret name (StartMenuPokemonText equ sm_str_pokemon, ...).

  * menu_text.inc — the START-sub-menu MESSAGE STREAMS (full TX_* command
    streams, not bare glyph runs), flattened out of pret's data/text/*.asm by
    gen_battle_text.collect_far — the same authoritative parser the battle/item/
    overworld text generators use. These are the bodies behind the `text_far`
    wrappers in engine/menus/start_sub_menus.asm; the wrappers themselves stay
    Tier-2 code in the .asm (text_far + text_end), exactly as pret writes them.

The two are separate files because they are different data: a label is a glyph
run PlaceString draws, a message is a command stream PrintText executes.

The source column below is pret's `db` string VERBATIM, not the rendered text.
That distinction is load-bearing: pret writes "#MON@", where '#' is charmap $54 —
a text COMMAND that PlaceNextChar expands to "POKé" at print time (home/text.asm:
`dict '#', PlacePOKe`), not four literal glyphs. Encoding the rendered string
"POKéMON" instead produces the same seven tiles on screen but a different byte
stream, silently bypassing the $54 handler the port implements
(src/home/text.asm:.handle_poke → str_poke). Keep these strings as pret spells
them and let the engine expand them; gb_text.encode maps '#' → $54 for us.

Run from repo root or dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text  # noqa: E402
import gen_battle_text  # noqa: E402  (reuse its pret data/text parser)

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"
TERMINATOR = 0x50

# FAR message streams printed by engine/menus/start_sub_menus.asm. pret defs:
# data/text/text_8.asm. The `_`-prefixed name is pret's own; the wrapper label
# (CannotUseItemsHereText) lives in the .asm as text_far + text_end.
MENU_FAR = [
    "_CannotUseItemsHereText",      # StartMenu_Item, inside a Cable Club room
    "_CannotGetOffHereText",        # the BICYCLE, while BIT_ALWAYS_ON_BIKE is set
    # StartMenu_Pokemon's field-move dispatch (.outOfBattleMovePointers):
    "_NewBadgeRequiredText",        # every badge-gated move, gate closed
    "_CannotFlyHereText",           # FLY, indoors
    "_FlashLightsAreaText",         # FLASH
    "_WarpToLastPokemonCenterText",  # TELEPORT
    "_CannotUseTeleportNowText",    # TELEPORT, indoors
    "_NotHealthyEnoughText",        # SOFTBOILED, HP <= maxHP/5
]

# --- raw control/graphic tiles that are not single-char charmap glyphs ---
NEXT = 0x4E     # "<NEXT>" — line break (double-spaced by default in PlaceString)
TERM = 0x50     # "@"      — string terminator
CIRCLE = 0x76   # "○"      — a raw TILE id, NOT a charmap glyph. pret writes this one
                #            as a byte too: `db $76,"BADGES",$76,"@"`.

# TRAINER CARD labels (pret engine/menus/start_sub_menus.asm — the DrawTrainerInfo
# section the port hosts in engine/menus/trainer_card.asm). Same (label, [parts])
# shape as gen_status_strings.py: a part is a str (→ gb_text.encode) or an int (a raw
# tile byte), mirroring pret's `db`/`next` sequence.
#
# These were HAND-ENCODED charmap `db` bytes in trainer_card.asm until 2026-07-13 —
# a Tier-1 violation (CLAUDE.md: "Text strings are DATA — never hand-encode charmap
# bytes"). The generated bytes are byte-identical to the hand-written ones, verified
# against the old literals; '/' encodes to $F3 through the charmap, it is not special.
TRAINER_CARD = [
    ("TrainerInfo_NameMoneyTimeText",
     ["NAME/", NEXT, "MONEY/", NEXT, "TIME/", TERM]),   # pret: db "NAME/" next "MONEY/" next "TIME/@"
    ("TrainerInfo_BadgesText",
     [CIRCLE, "BADGES", CIRCLE, TERM]),                 # pret: db $76,"BADGES",$76,"@"
]


def encode_parts(parts):
    """str → charmap-encoded run; int → one raw tile byte. (gen_status_strings.py)"""
    out = []
    for p in parts:
        if isinstance(p, int):
            out.append(p)
        else:
            out.extend(gb_text.encode(p))
    return out


# (NASM label, pret's `db` string verbatim, pret label) — the strings are copied
# from engine/menus/draw_start_menu.asm; see the module docstring on '#' ($54).
LABELS = [
    ("sm_str_pokedex", "POKéDEX", "StartMenuPokedexText"),
    ("sm_str_pokemon", "#MON",    "StartMenuPokemonText"),
    ("sm_str_item",    "ITEM",    "StartMenuItemText"),
    ("sm_str_save",    "SAVE",    "StartMenuSaveText"),
    ("sm_str_reset",   "RESET",   "StartMenuResetText"),
    ("sm_str_option",  "OPTION",  "StartMenuOptionText"),
    ("sm_str_exit",    "EXIT",    "StartMenuExitText"),
]


def main() -> int:
    out = [
        "; menu_strings.inc — generated by tools/gen_menu_strings.py. DO NOT EDIT BY HAND.",
        "; START-menu item labels, GB-charmap encoded via the unicode_converter",
        "; submodule (gb_text.encode) and '@'-terminated ($50). The comment on each",
        "; line is pret's `db` string verbatim — '#' is $54, the POKé text command,",
        "; expanded by PlaceNextChar at print time (NOT four literal glyphs).",
        "",
    ]
    for label, text, pret_label in LABELS:
        b = gb_text.encode(text) + [TERMINATOR]
        hexs = ", ".join(f"0x{x:02X}" for x in b)
        out.append(f'{label}: db {hexs}   ; {pret_label} "{text}@"')
    out.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "menu_strings.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} ({len(LABELS)} labels)")

    # --- flattened FAR message streams (start_sub_menus.asm) -----------------
    far = gen_battle_text.collect_far(
        gen_battle_text.load_charmap(), gen_battle_text.load_memmap()
    )
    fout = [
        "; menu_text.inc — generated by tools/gen_menu_strings.py. DO NOT EDIT BY HAND.",
        "; START-sub-menu FAR message streams (data/text/text_8.asm), pret's text_far",
        "; indirection flattened via gen_battle_text.collect_far. section .data so the",
        "; labels never land in an orphaned section (see link.ld).",
        "",
        "section .data",
        "",
    ]
    for label in MENU_FAR:
        if label not in far:
            sys.stderr.write(f"gen_menu_strings: missing far label {label}\n")
            return 1
        rows = [
            "    db " + ", ".join(f"0x{b:02X}" for b in far[label][k:k + 16])
            for k in range(0, len(far[label]), 16)
        ]
        fout.append(f"{label}:\n" + "\n".join(rows))
    fout.append("")
    fdst = ASSETS / "menu_text.inc"
    fdst.write_text("\n".join(fout))
    print(f"wrote {fdst} ({len(MENU_FAR)} far labels)")

    # --- TRAINER CARD PlaceString labels (trainer_card.asm) -------------------
    tout = [
        "; trainer_card_strings.inc — generated by tools/gen_menu_strings.py. DO NOT EDIT BY HAND.",
        "; TRAINER CARD PlaceString labels (pret start_sub_menus.asm's DrawTrainerInfo",
        "; section). GB-charmap encoded via gb_text.encode (unicode_converter submodule);",
        "; <NEXT> $4E, '@' $50 and the ○ circle TILE $76 inserted as raw bytes, mirroring",
        "; pret's own `db $76,\"BADGES\",$76,\"@\"`. section .data so the labels land in a",
        "; loaded section (see link.ld).",
        "",
        "section .data",
        "",
    ]
    for label, parts in TRAINER_CARD:
        b = encode_parts(parts)
        hexs = ", ".join(f"0x{x:02X}" for x in b)
        tout.append(f"{label}: db {hexs}")
    tout.append("")
    tdst = ASSETS / "trainer_card_strings.inc"
    tdst.write_text("\n".join(tout))
    print(f"wrote {tdst} ({len(TRAINER_CARD)} labels)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
