#!/usr/bin/env python3
"""Generate dos_port/assets/emotes.inc — the overworld emotion-bubble tiles.

Faithful to pret engine/overworld/emotion_bubbles.asm:
  EmotionBubbles:
  ShockEmote:    INCBIN "gfx/emotes/shock.2bpp"
  QuestionEmote: INCBIN "gfx/emotes/question.2bpp"
  HappyEmote:    INCBIN "gfx/emotes/happy.2bpp"
  SkullEmote:    INCBIN "gfx/emotes/skull.2bpp"
  HeartEmote:    INCBIN "gfx/emotes/heart.2bpp"
  BoltEmote:     INCBIN "gfx/emotes/bolt.2bpp"
  ZzzEmote:      INCBIN "gfx/emotes/zzz.2bpp"
  FishEmote:     INCBIN "gfx/emotes/fish.2bpp"

Each emote is a 2x2 = 4-tile 2bpp graphic (64 bytes); EmotionBubble copies 4 tiles
(CopyVideoData) at flat offset (wWhichEmotionBubble & $f) * 64 into the sheet — i.e.
pret's `swap a` (*16) followed by four `add hl,bc` = *64. The port routine indexes
this blob by that same stride (EMOTE_BUBBLE_BYTES).

This is Tier-1 machine output: a deterministic passthrough of pret's .2bpp emote
tiles, no hand-authored information. Rerunning is idempotent.

Output (NASM, placed in .data by the includer):
  EmotionBubbles: / EmotionBubbleGfx:  (pret label + port alias, same address)
    per-emote sub-labels (ShockEmote ... FishEmote), then the raw 2bpp bytes.
  EMOTE_TILE_BYTES        equ 16   ; bytes per 2bpp 8x8 tile
  EMOTE_TILES_PER_BUBBLE  equ 4    ; 2x2 tiles per emote
  EMOTE_BUBBLE_BYTES      equ 64   ; stride between emotes (4 * 16)
  NUM_EMOTES              equ 8

Run from the repo root:
  python3 dos_port/tools/gen_emotes.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRCDIR = ROOT / "gfx" / "emotes"
DST = ROOT / "dos_port" / "assets" / "emotes.inc"

TILE = 16                 # bytes per 2bpp 8x8 tile
TILES_PER_BUBBLE = 4      # 2x2
BUBBLE_BYTES = TILE * TILES_PER_BUBBLE

# pret INCBIN order in engine/overworld/emotion_bubbles.asm (label, file stem).
EMOTES = [
    ("ShockEmote",    "shock"),
    ("QuestionEmote", "question"),
    ("HappyEmote",    "happy"),
    ("SkullEmote",    "skull"),
    ("HeartEmote",    "heart"),
    ("BoltEmote",     "bolt"),
    ("ZzzEmote",      "zzz"),
    ("FishEmote",     "fish"),
]


def main():
    out = []
    out.append("; emotes.inc — generated by dos_port/tools/gen_emotes.py.")
    out.append("; DO NOT EDIT BY HAND.  Overworld emotion-bubble tiles (2bpp),")
    out.append("; pret gfx/emotes/*.2bpp via engine/overworld/emotion_bubbles.asm:EmotionBubbles.")
    out.append(f"EMOTE_TILE_BYTES        equ {TILE}")
    out.append(f"EMOTE_TILES_PER_BUBBLE  equ {TILES_PER_BUBBLE}")
    out.append(f"EMOTE_BUBBLE_BYTES      equ {BUBBLE_BYTES}")
    out.append(f"NUM_EMOTES              equ {len(EMOTES)}")
    out.append("")
    out.append("EmotionBubbles:")
    out.append("EmotionBubbleGfx:      ; port alias (EmotionBubble routine references this name)")

    total = 0
    for label, stem in EMOTES:
        src = SRCDIR / f"{stem}.2bpp"
        data = src.read_bytes()
        if len(data) != BUBBLE_BYTES:
            raise SystemExit(
                f"{src}: expected {BUBBLE_BYTES} bytes ({TILES_PER_BUBBLE} tiles), got {len(data)}")
        out.append(f"{label}:")
        for t in range(TILES_PER_BUBBLE):
            row = data[t * TILE:(t + 1) * TILE]
            out.append("    db " + ", ".join(f"0x{b:02X}" for b in row))
        total += len(data)
    out.append("")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out) + "\n")
    print(f"wrote {DST}: {len(EMOTES)} emotes ({total} bytes)")


if __name__ == "__main__":
    main()
