#!/usr/bin/env python3
"""Generate dos_port/assets/pokedex_tiles.inc — the pokédex interface tiles.

Faithful to pret engine/gfx/load_pokedex_tiles.asm:LoadPokedexTilePatterns:
  PokedexTileGraphics ($12 = 18 tiles, gfx/pokedex/pokedex.2bpp)
      -> vChars2 tile $60   (the dex frame/line tiles + the ' " height glyphs)
  PokeballTileGraphics (1 tile: the FIRST tile of gfx/battle/balls.2bpp,
      pret engine/battle/draw_hud_pokeball_gfx.asm:PokeballTileGraphics)
      -> vChars2 tile $72   (marks caught mons in the CONTENTS list)

Tier-1 machine output: a deterministic passthrough of the rgbgfx-rendered
.2bpp build artifacts (rendered by the root `make`; the PNGs are the committed
sources). Same pattern as gen_emotes.py / gen_badge_tiles.py.

Run from anywhere: python3 dos_port/tools/gen_pokedex_tiles.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
DEX_2BPP = ROOT / "gfx" / "pokedex" / "pokedex.2bpp"
BALLS_2BPP = ROOT / "gfx" / "battle" / "balls.2bpp"
DST = ROOT / "dos_port" / "assets" / "pokedex_tiles.inc"

TILE_SIZE = 16
DEX_TILES = 18          # (PokedexTileGraphicsEnd - PokedexTileGraphics) / 16


def db_lines(data: bytes) -> list[str]:
    return ["    db " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
            for i in range(0, len(data), 16)]


def main() -> None:
    dex = DEX_2BPP.read_bytes()
    if len(dex) != DEX_TILES * TILE_SIZE:
        raise SystemExit(f"{DEX_2BPP}: expected {DEX_TILES * TILE_SIZE} bytes "
                         f"({DEX_TILES} tiles), got {len(dex)} — rerun the root make")
    balls = BALLS_2BPP.read_bytes()
    if len(balls) < TILE_SIZE:
        raise SystemExit(f"{BALLS_2BPP}: expected >= {TILE_SIZE} bytes, got {len(balls)}")
    pokeball = balls[:TILE_SIZE]    # pret copies exactly 1 tile from the blob start

    out = [
        "; pokedex_tiles.inc — generated by dos_port/tools/gen_pokedex_tiles.py.",
        "; DO NOT EDIT BY HAND.",
        "; PokedexTileGraphics: 18 tiles (gfx/pokedex/pokedex.2bpp) -> vChars2 $60.",
        "; PokeballTileGraphics: 1 tile (gfx/battle/balls.2bpp tile 0) -> vChars2 $72.",
        "; pret ref: engine/gfx/load_pokedex_tiles.asm:LoadPokedexTilePatterns.",
        "",
        "PokedexTileGraphics:",
        *db_lines(dex),
        "PokedexTileGraphicsEnd:",
        "POKEDEX_TILE_GFX_SIZE equ PokedexTileGraphicsEnd - PokedexTileGraphics",
        "",
        "PokeballTileGraphics:",
        *db_lines(pokeball),
        "POKEBALL_TILE_SIZE equ 16",
        "",
    ]
    DST.write_text("\n".join(out) + "\n")
    print(f"wrote {DST} ({len(dex)} + {len(pokeball)} bytes)")


if __name__ == "__main__":
    main()
