#!/usr/bin/env python3
"""Generate small runtime-owned rendered strings formerly embedded in .asm files."""
from pathlib import Path

from gen_battle_text import encode, load_charmap

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"


def db(label, parts, cm):
    data = []
    for part in parts:
        data.extend(encode(part, cm) if isinstance(part, str) else part)
    return f"{label}: db " + ", ".join(f"0x{x:02X}" for x in data)


FILES = {
    "battle_menu_runtime_strings.inc": [
        ("BattleMenuText", ["FIGHT ", "<PK><MN>", [0x4E], "ITEM  RUN", [0x50]]),
        ("str_excl", ["!", [0x50]]),
        ("str_gotaway", ["Got away safely!", [0x50]]),
        ("str_cantesc", ["Can't escape!", [0x50]]),
        ("str_norun1", ["No! There's no", [0x50]]),
        ("str_norun2", ["running from a", [0x50]]),
        ("str_norun3", ["trainer battle!", [0x50]]),
        ("str_gained", [" gained", [0x50]]),
        ("str_exppts", [" EXP. Points!", [0x50]]),
        ("str_grew", [" grew", [0x50]]),
        ("str_tolevel", ["to level ", [0x50]]),
        ("str_attack", ["ATTACK", [0x50]]), ("str_defense", ["DEFENSE", [0x50]]),
        ("str_speed", ["SPEED", [0x50]]), ("str_special", ["SPECIAL", [0x50]]),
    ],
    "battle_core_runtime_strings.inc": [
        ("str_used_grammar", [[0x4F], "used ", [0x50]]),
        ("str_miss_text", [[0x00], "Attack got no way!", [0x50, 0x50]]),
        ("str_rose", [" rose!", [0x58]]),
        ("str_greatly_rose", [[0x4C], "greatly rose!", [0x58]]),
        ("str_fell", [" fell!", [0x58]]),
        ("str_greatly_fell", [[0x4C], "greatly fell!", [0x58]]),
    ],
    "effectiveness_runtime_strings.inc": [
        ("SuperEffectiveText", [[0x00], "It's super", [0x4F], "effective!", [0x58]]),
        ("NotVeryEffectiveText", [[0x00], "It's not very", [0x4F], "effective...", [0x58]]),
    ],
    "battle_intro_runtime_strings.inc": [
        ("intro_line1", ["Wild "]), ("intro_line2", ["appeared!"]),
    ],
    "stat_mod_runtime_strings.inc": [
        ("StatModTextStrings", ["ATTACK", [0x50], "DEFENSE", [0x50], "SPEED", [0x50],
                                "SPECIAL", [0x50], "ACCURACY", [0x50], "EVADE", [0x50]]),
    ],
    "item_runtime_strings.inc": [
        ("ti_msg_threw", ["Threw away", [0x50]]),
        ("ti_msg_isok", ["Is it OK to toss", [0x50]]),
        ("ti_msg_imp1", ["That's too impor-", [0x50]]),
        ("ti_msg_imp2", ["tant to toss!", [0x50]]),
    ],
    "status_ailment_runtime_strings.inc": [
        ("sa_psn", ["PSN"]), ("sa_brn", ["BRN"]), ("sa_frz", ["FRZ"]),
        ("sa_par", ["PAR"]), ("sa_slp", ["SLP"]),
    ],
    "home_names_runtime_strings.inc": [
        ("TechnicalPrefix", ["TM"]), ("HiddenPrefix", ["HM"]),
    ],
    "home_text_runtime_strings.inc": [
        ("str_poke", ["POKé", [0x50]]), ("str_pc", ["PC", [0x50]]),
        ("str_tm", ["TM", [0x50]]), ("str_trainer", ["TRAINER", [0x50]]),
        ("str_rocket", ["ROCKET", [0x50]]), ("str_dots6", [[0x75, 0x75, 0x50]]),
        ("str_pkmn", ["<PK><MN>", [0x50]]), ("str_dot", [".", [0x50]]),
        ("str_enemy", ["Enemy ", [0x50]]),
    ],
    "pallet_runtime_strings.inc": [
        ("oak_got_text", [[0x00], "OAK: That was", [0x4F], "close!", [0x57, 0x50]]),
        ("oak_default_text", [[0x00], "OAK: Hey! Wait!", [0x4F], "Don't go out!", [0x57, 0x50]]),
        ("oak_whew_text", [[0x00], "OAK: Whew!", [0x4F], "That was close!", [0x57, 0x50]]),
        ("oak_come_with_me_text", [[0x00], "OAK: It's unsafe!", [0x4F], "Come with me!", [0x57, 0x50]]),
    ],
}


def main():
    cm = load_charmap()
    for name, rows in FILES.items():
        lines = ["; DO NOT EDIT BY HAND — generated by tools/gen_runtime_strings.py."]
        for label, parts in rows:
            lines.append(db(label, parts, cm))
            if label == "intro_line1":
                lines.append("INTRO_LINE1_LEN equ $ - intro_line1")
            elif label == "intro_line2":
                lines.append("INTRO_LINE2_LEN equ $ - intro_line2")
            elif label.startswith("oak_"):
                lines.append(f"{label}_end:")
        (ASSETS / name).write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
