#!/usr/bin/env python3
"""Generate ``assets/colors/palettes.inc`` from pret data plus sidecar deltas."""
from __future__ import annotations

from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from colors import schema
from gfx_core import palettes

ASSETS = HERE.parent / "assets" / "colors"
SIDECAR = ASSETS / "palettes.json"
OUT = ASSETS / "palettes.inc"


def emit() -> str:
    sidecar = schema.load(SIDECAR)
    rgb = palettes.parse_cgb_base_palettes()
    rgb.update(sidecar.pal_overrides)
    pals, _ = palettes.palette_enums()
    rows = sorted(pals.items(), key=lambda item: item[1])
    # Per-species RGB deltas receive deterministic port-only palette ids after
    # pret's PAL_* range. The runtime consumes ids, not their provenance.
    custom = []
    for species in sorted(sidecar.species_overrides):
        override = sidecar.species_overrides[species]
        if "colors" in override:
            custom.append((f"PAL_OVERRIDE_{species}", override["colors"]))
    rgb_rows = [(name, rgb[name]) for name, _ in rows] + custom
    palette_ids = {name: i for i, (name, _) in enumerate(rgb_rows)}

    mon_source = palettes.parse_monster_palettes()
    mon_rows = []
    for species, source_pal in mon_source.items():
        override = sidecar.species_overrides.get(species, {})
        pal = f"PAL_OVERRIDE_{species}" if "colors" in override else override.get("pal", source_pal)
        mon_rows.append(palette_ids[pal])

    # SetPal_Battle starts with PalPacket_Empty then patches all four slots.
    # These defaults make the generated table usable by previews before R1.
    battle_slots = [palette_ids["PAL_GREENBAR"], palette_ids["PAL_GREENBAR"],
                    palette_ids["PAL_MEWMON"], palette_ids["PAL_MEWMON"]]
    for slot, pal in sidecar.screen_overrides.get("SET_PAL_BATTLE", {}).items():
        battle_slots[int(slot[4:])] = palette_ids[pal]

    # Physical tile_cache order is $8000..$97ff. Battle signed-BG tile IDs map
    # vFrontPic $9000+$00..$30 to cache 256..304 and vBackPic $9000+$31..$61
    # to 305..353. BlkPacket_Battle is the source for the slot order below.
    battle_blocks = palettes.parse_blk_packets()["BlkPacket_Battle"]
    if [b["pal0"] for b in battle_blocks] != [2, 1, 0, 2, 3]:
        raise ValueError("BlkPacket_Battle layout no longer matches colorization design")
    battle_tile_pal = [0] * 384
    battle_tile_pal[128:256] = [2] * 128     # font/message-box tile band
    battle_tile_pal[256:305] = [3] * 49      # enemy front pic
    battle_tile_pal[305:354] = [2] * 49      # player back pic
    # $62..$7f currently share player/ enemy HP patterns. R1 duplicates the
    # enemy fill band, allowing this baseline player-slot mapping to coexist.
    battle_tile_pal[354:384] = [0] * 30
    lines = [
        "; palettes.inc — generated by tools/gen_palettes.py. DO NOT EDIT BY HAND.",
        "; Source: pret CGBBasePalettes plus assets/colors/palettes.json deltas.",
        "; RGB values are VGA DAC six-bit R,G,B triples.", "",
        f"PAL_RGB_COUNT equ {len(rgb_rows)}", "pal_rgb_table:",
    ]
    for name, colors in rgb_rows:
        flat = ", ".join(str(v) for color in colors for v in color)
        lines.append(f"    db {flat}  ; {name}")
    lines += ["", "; Pokédex order: MISSINGNO then #001..#151.",
              "mon_pal_table:"]
    for start in range(0, len(mon_rows), 16):
        lines.append("    db " + ", ".join(str(v) for v in mon_rows[start:start + 16]))
    lines += ["", "; SET_PAL_BATTLE slots: player HP, enemy HP, player pic, enemy pic.",
              "battle_slot_pal:", "    db " + ", ".join(map(str, battle_slots)),
              "", "; physical cache tile ($8000-based) -> battle BG palette slot.",
              "battle_tile_pal:"]
    for start in range(0, len(battle_tile_pal), 32):
        lines.append("    db " + ", ".join(str(v) for v in battle_tile_pal[start:start + 32]))
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(emit())


if __name__ == "__main__":
    main()
