#!/usr/bin/env python3
"""Generate dos_port/assets/mon_pics.inc — every pokémon front + back battle
sprite (compressed .pic) + the dex-ordered MonFrontPics / MonBackPics tables.

The port's front-sprite loader (src/gfx/pics.asm LoadFrontSpriteByMonIndex ->
LoadMonFrontSprite) converts the internal species index to a national dex number
(IndexToPokedex), then indexes MonFrontPics by (dex - 1). Each record is
{ dd flat_ptr, dd blob_len } — LoadMonFrontSprite reads the length from +4 and
the flat pointer from +0. The .pic blobs are the SAME compressed format the mon
decompressor (src/gfx/uncompress.asm) decodes.

MonBackPics mirrors it for the player send-out sprite (LoadMonBackPic ->
LoadMonBackPicToVRAM, which scales the 4x4 back pic 2x). Every back pic is 4x4
(dims byte $44), so ScaleSpriteByTwo handles them all uniformly. The back pic for
species N sits at gfx/pokemon/back/<frontstem>b.pic (pret's naming convention).

Sources (read-only pret):
  data/pokemon/base_stats.asm           — dex-ordered INCLUDE list (dex 1..151)
  data/pokemon/base_stats/<name>.asm    — line: INCBIN "gfx/pokemon/front/<f>.pic"
  gfx/pokemon/back/<frontstem>b.pic     — the matching back sprite

Emits (data only; a Tier-2 wrapper .asm supplies section/globals):
  monfp_<name>:   incbin "../gfx/pokemon/front/<name>.pic"   (one per dex mon)
  MonFrontPics:   151 records of `dd monfp_<name>, (monfp_<name>_end - monfp_<name>)`
  monbp_<name>:   incbin "../gfx/pokemon/back/<name>b.pic"   (one per dex mon)
  MonBackPics:    151 records of `dd monbp_<name>, (monbp_<name>_end - monbp_<name>)`

DO NOT EDIT the generated .inc by hand.  Run from repo root (or dos_port/):
  python3 dos_port/tools/gen_mon_pics.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASE_STATS_ASM = ROOT / "data" / "pokemon" / "base_stats.asm"
DST = ROOT / "dos_port" / "assets" / "mon_pics.inc"

NUM_POKEMON = 151


def label(pic_rel: str) -> str:
    stem = Path(pic_rel).name[:-4]                       # strip ".pic"
    return "monfp_" + re.sub(r"[^a-z0-9]", "_", stem.lower())


def back_label(pic_rel: str) -> str:
    stem = Path(pic_rel).name[:-4]                       # front stem (strip ".pic")
    return "monbp_" + re.sub(r"[^a-z0-9]", "_", stem.lower())


def back_path(front_rel: str) -> str:
    # pret back sprite = front stem + "b" under gfx/pokemon/back/.
    stem = Path(front_rel).name[:-4]
    return f"gfx/pokemon/back/{stem}b.pic"


def main() -> None:
    # base_stats.asm INCLUDE order == national dex order (dex 1..151).
    species_files = [
        m.group(1)
        for line in BASE_STATS_ASM.read_text().splitlines()
        if (m := re.search(r'INCLUDE\s+"(data/pokemon/base_stats/[^"]+)"', line))
    ]
    if len(species_files) != NUM_POKEMON:
        sys.exit(f"expected {NUM_POKEMON} dex species, got {len(species_files)}")

    # each species base-stats file names its front pic via the sprite-dim INCBIN.
    pics = []                                            # dex-ordered .pic rel paths
    for rel in species_files:
        text = (ROOT / rel).read_text()
        m = re.search(r'INCBIN\s+"(gfx/pokemon/front/[^"]+\.pic)"', text)
        if not m:
            sys.exit(f"{rel}: no front-pic INCBIN found")
        pic = m.group(1)
        if not (ROOT / pic).is_file():
            sys.exit(f"{rel}: pic file missing: {pic}")
        pics.append(pic)

    # matching back sprite per dex mon (front stem + "b").
    backs = []                                           # dex-ordered back .pic rel paths
    for pic in pics:
        back = back_path(pic)
        if not (ROOT / back).is_file():
            sys.exit(f"back pic missing: {back} (for front {pic})")
        backs.append(back)

    out = [
        "; mon_pics.inc — generated by dos_port/tools/gen_mon_pics.py.",
        "; DO NOT EDIT BY HAND.  Pokémon front + back battle sprites (compressed .pic,",
        "; decoded by src/gfx/uncompress.asm) + the dex-ordered MonFrontPics/MonBackPics",
        f"; tables. {NUM_POKEMON} pics each; record = {{ dd ptr, dd len }}, index = dex-1.",
        "",
    ]
    for pic in pics:
        lbl = label(pic)
        out.append(f'{lbl}: incbin "../{pic}"')
        out.append(f'{lbl}_end:')
    out += ["", "MonFrontPics:   ; { dd flat_ptr, dd blob_len } per dex mon (index = dex-1)"]
    for pic in pics:
        lbl = label(pic)
        out.append(f"    dd {lbl}, {lbl}_end - {lbl}")
    out.append("")
    for back in backs:
        lbl = back_label(back)
        out.append(f'{lbl}: incbin "../{back}"')
        out.append(f'{lbl}_end:')
    out += ["", "MonBackPics:    ; { dd flat_ptr, dd blob_len } per dex mon (index = dex-1)"]
    for back in backs:
        lbl = back_label(back)
        out.append(f"    dd {lbl}, {lbl}_end - {lbl}")
    out.append("")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out) + "\n")
    print(f"wrote {DST} ({len(pics)} front + {len(backs)} back pics)")


if __name__ == "__main__":
    main()
