#!/usr/bin/env python3
"""gen_overworld_strings.py — generate dos_port/assets/overworld_strings.inc.

Overworld-engine field / HUD text strings, GB-charmap encoded through the
unicode_converter submodule (gb_text.encode) instead of hand-written charmap
hex, then emitted as '@'-terminated ($50) NASM `db` lines. Consumed via
%include by src/engine/overworld/player_state.asm (PrintSafariZoneSteps).

This is the Tier-1 home for overworld field/HUD strings (per project-conventions:
human-rendered text is DATA, never hand-encoded charmap bytes in a .asm). Seeded
with the Safari Zone step/ball-count HUD strings; the later overworld field-message
strings (Strength/Surf/boulder text — OW-4.x) belong here too.

Run from repo root or dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"
TERMINATOR = 0x50  # '@'

# (NASM label, Unicode text) — pret: engine/overworld/player_state.asm.
# The trailing '@' terminator is appended as $50; do NOT put it in the text.
# '×' is U+00D7 (charmap $F1); the trailing space in SafariBallText is significant.
LABELS = [
    ("SafariSteps",    "/500"),                # pret: db "/500@"
    ("SafariBallText", "BALL×× "),    # pret: db "BALL×× @"
]


def main() -> int:
    out = [
        "; overworld_strings.inc — generated by tools/gen_overworld_strings.py. DO NOT EDIT BY HAND.",
        "; Overworld-engine field/HUD strings, GB-charmap encoded via the",
        "; unicode_converter submodule (gb_text.encode) and '@'-terminated ($50).",
        "; pret ref: engine/overworld/player_state.asm.",
        "",
    ]
    for label, text in LABELS:
        b = gb_text.encode(text) + [TERMINATOR]
        hexs = ", ".join(f"0x{x:02X}" for x in b)
        out.append(f'{label}: db {hexs}   ; "{text}@"')
    out.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "overworld_strings.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} ({len(LABELS)} labels)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
