#!/usr/bin/env python3
"""gen_type_names.py — generate assets/type_names.inc.

WideTypeNames: a flat `dd` pointer table indexed by RAW Gen-1 type id (0x00..0x1A),
with the unused 0x09-0x13 gap pointing at the NORMAL string (faithful to pret's
data/types/names.asm `REPT UNUSED_TYPES_END - UNUSED_TYPES / dw .Normal`), followed by
the 16 unique '@'-terminated, charmap-encoded type-name strings.

Source of truth (read-only): data/types/names.asm + constants/type_constants.asm
(for the gap width) + constants/charmap.asm (encoding). Drop-in replacement for the
former hand-authored src/data/type_names.asm data; consumed by PrintMoveInfoBox via
`[WideTypeNames + type_id*4]`.
"""
import re
import sys
from pathlib import Path

DOS = Path(__file__).resolve().parent.parent          # dos_port/
ROOT = DOS.parent                                      # repo root (pret)
NAMES = ROOT / "data" / "types" / "names.asm"
TYPECONST = ROOT / "constants" / "type_constants.asm"
CHARMAP = ROOT / "constants" / "charmap.asm"
OUT = DOS / "assets" / "type_names.inc"


def load_charmap():
    cm = {}
    for line in CHARMAP.read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s*charmap\s+"((?:[^"\\]|\\.)*)"\s*,\s*(\$[0-9A-Fa-f]+|-?\d+)', line)
        if m:
            key = m.group(1).replace('\\"', '"')
            v = m.group(2)
            cm[key] = int(v[1:], 16) if v.startswith("$") else int(v)
    return cm


def encode(s, cm):
    keys = sorted(cm, key=len, reverse=True)  # longest match first
    out, i = bytearray(), 0
    while i < len(s):
        for k in keys:
            if s.startswith(k, i):
                out.append(cm[k]); i += len(k); break
        else:
            raise KeyError(f"unmapped char {s[i]!r} in {s!r}")
    return out


def gap_width():
    """Simulate const_value to get UNUSED_TYPES_END - UNUSED_TYPES (the gap size)."""
    cv, defs = 0, {}
    for raw in TYPECONST.read_text(encoding="utf-8").splitlines():
        s = raw.split(";")[0].strip()
        if not s:
            continue
        m = re.match(r'const\s+\w+$', s)
        if m:
            cv += 1; continue
        m = re.match(r'const_next\s+(\d+)$', s)
        if m:
            cv = int(m.group(1)); continue
        m = re.match(r'(?:DEF\s+)?(\w+)\s+EQU\s+const_value$', s, re.I)
        if m:
            defs[m.group(1)] = cv; continue
    return defs["UNUSED_TYPES_END"] - defs["UNUSED_TYPES"]


def parse_names():
    """Return (order, strings): order = list of label keys per raw type id (gap expanded);
    strings = {label: text}. Labels are pret's `.Normal` etc., normalised to `tn_<lower>`."""
    text = NAMES.read_text(encoding="utf-8").splitlines()
    order, strings = [], {}
    i, gap = 0, gap_width()
    while i < len(text):
        s = text[i].split(";")[0].strip()
        m = re.match(r'dw\s+\.(\w+)$', s)
        if m:
            order.append("tn_" + m.group(1).lower())
        elif s.startswith("REPT"):
            # expand `REPT <expr> / dw .X / ENDR` using the computed gap width
            inner = text[i + 1].split(";")[0].strip()
            mm = re.match(r'dw\s+\.(\w+)$', inner)
            if not mm:
                raise ValueError(f"unexpected REPT body: {inner!r}")
            order += ["tn_" + mm.group(1).lower()] * gap
            while not text[i].strip().startswith("ENDR"):
                i += 1
        else:
            m = re.match(r'\.(\w+):\s*db\s+"([^"@]*)@"$', s)
            if m:
                strings["tn_" + m.group(1).lower()] = m.group(2)
        i += 1
    return order, strings


def main():
    cm = load_charmap()
    order, strings = parse_names()
    out = [
        "; type_names.inc — generated by tools/gen_type_names.py. DO NOT EDIT BY HAND.",
        "; WideTypeNames[type_id] = dd ptr to a '@'-terminated charmap type name.",
        f"; {len(order)} entries (raw Gen-1 type ids 0x00-0x{len(order)-1:02X}); the unused",
        "; 0x09-0x13 gap points at NORMAL, matching pret data/types/names.asm.",
        "",
        "global WideTypeNames",
        "",
        "WideTypeNames:",
    ]
    for idx, key in enumerate(order):
        out.append(f"    dd {key}    ; {idx:02X}")
    out.append("")
    # emit each unique string once, in first-appearance order
    for key in dict.fromkeys(order):
        enc = encode(strings[key], cm)
        body = ", ".join(f"0x{b:02X}" for b in enc)
        out.append(f"{key}: db {body}, 0x50    ; \"{strings[key]}\"")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT} (WideTypeNames {len(order)} entries, {len(strings)} unique names)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
