#!/usr/bin/env python3
"""Generate all dos_port/assets/*.inc files from pret binary sources.

Supersedes tools/gen_overworld_assets.py — run this instead.

Sources required (built by 'make' in repo root):
  gfx/tilesets/*.2bpp       — built by rgbgfx from .png files
  gfx/blocksets/*.bst       — checked-in binary blockset data
  maps/*.blk                — checked-in binary map block layouts
  gfx/sprites/red.2bpp      — built by rgbgfx
  gfx/sprites/*.2bpp        — NPC sprite sheets

Run from the repo root:
    python3 tools/gen_all_assets.py

Or via make:
    make -C dos_port assets
"""
import sys
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
ASSETS = ROOT / "dos_port" / "assets"
GFX_TILESETS = ROOT / "gfx" / "tilesets"
GFX_BLOCKSETS = ROOT / "gfx" / "blocksets"
MAPS_DIR = ROOT / "maps"
GFX_SPRITES = ROOT / "gfx" / "sprites"
GFX_SPRITES_ASM = ROOT / "gfx" / "sprites.asm"
SPRITE_SHEET_TABLE_SRC = ROOT / "data" / "sprites" / "sprites.asm"
COLL_SRC = ROOT / "data" / "tilesets" / "collision_tile_ids.asm"
SPRITE_CONSTANTS = ROOT / "constants" / "sprite_constants.asm"
MAPS_OBJECTS_DIR = ROOT / "data" / "maps" / "objects"
NPC_SPRITES_DIR = ASSETS / "npc_sprites"

# ---------------------------------------------------------------------------
# Tileset table: (id, canonical_name, gfx_stem, blocks_stem, coll_label)
#   canonical_name   — used for inc file labels (e.g. "reds_house" → reds_house_gfx)
#   gfx_stem         — stem of .2bpp file in gfx/tilesets/
#   blocks_stem      — stem of .bst file in gfx/blocksets/
#   coll_label       — label prefix in collision_tile_ids.asm (without _Coll::)
# Shared tilesets (same gfx/blocks/coll) are listed with the canonical name of
# the primary tileset; the dispatch tables in gen_map_headers.py reuse the label.
# ---------------------------------------------------------------------------
TILESETS = [
    # id  canonical_name  gfx_stem      blocks_stem   coll_label
    ( 0, "overworld",    "overworld",   "overworld",  "Overworld"),
    ( 1, "reds_house",   "reds_house",  "reds_house",  "RedsHouse1"),
    ( 2, "pokecenter",   "pokecenter",  "pokecenter",  "Mart"),
    ( 3, "forest",       "forest",      "forest",      "Forest"),
    ( 4, "reds_house",   "reds_house",  "reds_house",  "RedsHouse2"),  # same GFX as RedsHouse1
    ( 5, "gym",          "gym",         "gym",         "Dojo"),
    ( 6, "pokecenter",   "pokecenter",  "pokecenter",  "Pokecenter"),  # same GFX as Mart
    ( 7, "gym",          "gym",         "gym",         "Gym"),         # same GFX as Dojo
    ( 8, "house",        "house",       "house",       "House"),
    ( 9, "gate",         "gate",        "gate",        "ForestGate"),
    (10, "gate",         "gate",        "gate",        "Museum"),      # same GFX as Gate
    (11, "underground",  "underground", "underground", "Underground"),
    (12, "gate",         "gate",        "gate",        "Gate"),        # same GFX as ForestGate
    (13, "ship",         "ship",        "ship",        "Ship"),
    (14, "ship_port",    "ship_port",   "ship_port",   "ShipPort"),
    (15, "cemetery",     "cemetery",    "cemetery",    "Cemetery"),
    (16, "interior",     "interior",    "interior",    "Interior"),
    (17, "cavern",       "cavern",      "cavern",      "Cavern"),
    (18, "lobby",        "lobby",       "lobby",       "Lobby"),
    (19, "mansion",      "mansion",     "mansion",     "Mansion"),
    (20, "lab",          "lab",         "lab",         "Lab"),
    (21, "club",         "club",        "club",        "Club"),
    (22, "facility",     "facility",    "facility",    "Facility"),
    (23, "plateau",      "plateau",     "plateau",     "Plateau"),
    (24, "beach_house",  "beach_house", "beach_house", "BeachHouse"),
]


def write_inc(dst: Path, label: str, data: bytes, comment: str = ""):
    lines = [f"; {dst.name} — generated by tools/gen_all_assets.py. DO NOT EDIT BY HAND."]
    if comment:
        lines.append(f"; {comment}")
    lines += ["", f"{label}:"]
    for i in range(0, len(data), 16):
        lines.append("    db " + ", ".join(f"0x{b:02X}" for b in data[i:i+16]))
    lines += [
        f"{label}_end:",
        f"{label.upper()}_SIZE equ {label}_end - {label}",
        "",
    ]
    dst.write_text("\n".join(lines) + "\n")
    print(f"  wrote {dst} ({len(data)} bytes)")


def apply_map_overrides(pascal: str, data: bytearray) -> int:
    """Merge assets/map_overrides/<Pascal>.json into the blk bytes (C5).

    Cells are map-local [y, x, block]; dimensions come from
    constants/map_constants.asm via gen_map_headers. Errors abort the build
    (a bad sidecar must never silently corrupt a map)."""
    ov = ASSETS / "map_overrides" / f"{pascal}.json"
    if not ov.exists():
        return 0
    import json
    import gen_map_headers as gmh
    dims = {gmh.const_to_pascal(c): (w, h)
            for c, (_i, w, h) in gmh.parse_map_constants().items()}
    if pascal not in dims:
        sys.exit(f"{ov}: no map_const dimensions found for {pascal}")
    w, h = dims[pascal]
    cells = json.loads(ov.read_text())["cells"]
    for y, x, b in cells:
        if not (0 <= x < w and 0 <= y < h and 0 <= b <= 0xFF):
            sys.exit(f"{ov}: cell ({y},{x},0x{b:02X}) out of range "
                     f"for {w}x{h}")
        data[y * w + x] = b
    return len(cells)


def parse_coll_list(label_prefix: str) -> bytes:
    """Extract <label_prefix>_Coll:: coll_tiles ... from collision_tile_ids.asm."""
    want = f"{label_prefix}_Coll::"
    lines = COLL_SRC.read_text().splitlines()
    seen = False
    for line in lines:
        s = line.strip()
        if s.startswith(want):
            seen = True
        if seen and "coll_tiles" in s:
            args = s.split("coll_tiles", 1)[1]
            ids = [int(tok.strip().replace("$", "0x"), 16)
                   for tok in args.split(",") if tok.strip()]
            return bytes(ids) + b"\xff"
    raise SystemExit(f"ERROR: {want} not found in {COLL_SRC}")


def to_snake(pascal: str) -> str:
    """PascalCase → snake_case: OaksLab → oaks_lab, Route1 → route1."""
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", pascal)
    return s.lower()


def parse_sprite_constants() -> dict:
    """Parse constants/sprite_constants.asm → {SPRITE_FOO: id} (sequential const_def)."""
    result = {}
    sprite_id = 0
    for line in SPRITE_CONSTANTS.read_text().splitlines():
        m = re.match(r'\s*const\s+(SPRITE_\w+)', line)
        if m:
            result[m.group(1)] = sprite_id
            sprite_id += 1
    return result


def enumerate_npc_sprites() -> list:
    """Scan all data/maps/objects/*.asm for object_event SPRITE_* tokens.

    Returns a sorted list of (sprite_id, stem, const_name) tuples for every
    unique sprite constant used on any map.  stem is the .2bpp filename stem
    (SPRITE_COOLTRAINER_F → cooltrainer_f).
    """
    sprite_map = parse_sprite_constants()
    used: set = set()
    for obj_file in sorted(MAPS_OBJECTS_DIR.glob("*.asm")):
        for line in obj_file.read_text().splitlines():
            m = re.search(r'\bobject_event\b[^;]*(SPRITE_\w+)', line)
            if m:
                name = m.group(1)
                if name in sprite_map:
                    used.add(name)
                else:
                    print(f"WARNING: unknown sprite constant {name!r} in {obj_file.name}",
                          file=sys.stderr)
    result = []
    for name in used:
        sid = sprite_map[name]
        stem = name[len("SPRITE_"):].lower()
        result.append((sid, stem, name))
    result.sort()
    return result


def parse_sprite_label_stems() -> dict:
    """gfx/sprites.asm → {gfx label: .2bpp stem}.

    e.g. `RedSprite:: INCBIN "gfx/sprites/red.2bpp"` → {"RedSprite": "red"}.
    Used to resolve the *shared* gfx labels in pret's SpriteSheetPointerTable
    (SPRITE_UNUSED_RED_1/2/3 all map to RedSprite → red.2bpp), which the
    SPRITE_* name → stem convention cannot express.
    """
    result = {}
    pat = re.compile(r'^\s*(\w+)::\s*INCBIN\s*"gfx/sprites/([\w/]+)\.2bpp"')
    for line in GFX_SPRITES_ASM.read_text().splitlines():
        m = pat.match(line)
        if m:
            result[m.group(1)] = m.group(2)
    return result


def parse_sprite_sheet_table() -> list:
    """pret data/sprites/sprites.asm SpriteSheetPointerTable → ordered
    [(gfx label, tile count)], one row per sprite id in id order (SPRITE_RED
    first). Index i corresponds to sprite id (i + 1); pret's ReadSpriteSheetData
    does `dec a` before indexing, so sprite id 1 (RED) → table index 0.
    """
    rows = []
    on = False
    pat = re.compile(r'^\s*overworld_sprite\s+(\w+)\s*,\s*(\d+)')
    for line in SPRITE_SHEET_TABLE_SRC.read_text().splitlines():
        s = line.strip()
        if s.startswith("SpriteSheetPointerTable:"):
            on = True
            continue
        if on and s.startswith("assert_table_length"):
            break
        if on:
            m = pat.match(line)
            if m:
                rows.append((m.group(1), int(m.group(2))))
    return rows


def generate_sprite_sheet_pointers():
    """Generate assets/sprite_sheet_pointers.inc (OW-A.2 P3a, Tier-1 data).

    Faithful port of pret data/sprites/sprites.asm SpriteSheetPointerTable, but
    covering the FULL sprite list (all NUM_SPRITES) — including outside-map
    fillers (SNORLAX, FOSSIL, SEEL, CHANSEY, UNUSED_GAMBLER_ASLEEP_2, …) that no
    map object_event references, because any SpriteSet can select them. The
    map-object-only npc_sprite_data_table.inc (used by the bespoke loader) does
    NOT cover these; the faithful map_sprites.asm sprite-set machinery needs
    every id 1..NUM_SPRITES resolvable.

    Self-contained: %includes every referenced npc_<stem>.inc once, then defines
    SpriteSheetPointerTable, so it can be %included alone (3c swaps it in for the
    npc_sprite_data_table.inc include). Not linked in 3a (byte-identical).

    ; DIVERGENCE (asset-model, per OW-A.1 precedent): pret's entry is
    {dw graphics, db tilecount, db bank}; the flat 32-bit port stores
    {dd flat_ptr, dd tilecount} (8 bytes, index (id-1)*8) and drops the bank
    (flat model). The port npc_<stem>.inc sheets are the pret .2bpp bytes,
    already [0-11]=still / [12-23]=walk (same layout pret loads at src+0 / src+$c0).
    """
    label_stems = parse_sprite_label_stems()
    table = parse_sprite_sheet_table()
    sprite_map = parse_sprite_constants()
    id_to_name = {sid: name for name, sid in sprite_map.items()}

    num = len(table)
    assert num == max(sprite_map.values()), \
        f"SpriteSheetPointerTable has {num} rows, expected NUM_SPRITES={max(sprite_map.values())}"

    FULL_SHEET = 384  # 24 tiles × 16 bytes (still [0-11] + walk [12-23])

    # Resolve each id → (stem, tilecount); collect the unique stems to emit once.
    per_id = []           # (sprite_id, stem, tilecount, name)
    stems_seen = {}       # stem -> tilecount (for the per-sheet file emission)
    for i, (glabel, tiles) in enumerate(table):
        sid = i + 1
        if glabel not in label_stems:
            sys.exit(f"ERROR: gfx label {glabel!r} (sprite id 0x{sid:02X}) has no "
                     f"INCBIN in {GFX_SPRITES_ASM}")
        stem = label_stems[glabel]
        name = id_to_name.get(sid, f"SPRITE_0x{sid:02X}")
        per_id.append((sid, stem, tiles, name))
        stems_seen.setdefault(stem, tiles)

    # Emit a per-sprite sheet .inc for every referenced stem (full coverage).
    # Overlaps with the map-used sheets written above are byte-identical data
    # under the same npc_<stem> label — harmless idempotent overwrite.
    NPC_SPRITES_DIR.mkdir(parents=True, exist_ok=True)
    missing = set()
    for stem in sorted(stems_seen):
        src = GFX_SPRITES / f"{stem}.2bpp"
        if not src.exists():
            print(f"WARNING: {src} missing — SpriteSheetPointerTable entry → dd 0",
                  file=sys.stderr)
            missing.add(stem)
            continue
        data = src.read_bytes()
        note = ""
        if len(data) < FULL_SHEET:
            note = f", padded from {len(data)} bytes"
            data = data + bytes(FULL_SHEET - len(data))
        write_inc(
            NPC_SPRITES_DIR / f"{stem}.inc",
            f"npc_{stem}",
            data,
            f"{stem}.2bpp sprite sheet (24 tiles: [0-11]=still, [12-23]=walk{note})",
        )

    # Emit the self-contained table file.
    lines = [
        "; sprite_sheet_pointers.inc — generated by tools/gen_all_assets.py. DO NOT EDIT BY HAND.",
        "; Faithful port of pret data/sprites/sprites.asm SpriteSheetPointerTable, full",
        "; sprite coverage (OW-A.2 P3a). Indexed by (sprite_id - 1): entry = dd flat_ptr,",
        "; dd tile_count (8 bytes). Self-contained — %includes its own sheets once.",
        "",
    ]
    for stem in sorted(stems_seen):
        if stem not in missing:
            lines.append(f'%include "assets/npc_sprites/{stem}.inc"')
    lines += [
        "",
        f"NUM_SPRITE_SHEETS equ {num}",
        "",
        "SpriteSheetPointerTable:",
    ]
    for sid, stem, tiles, name in per_id:
        ptr = "0" if stem in missing else f"npc_{stem}"
        lines.append(f"    dd {ptr}, {tiles}  ; 0x{sid:02X} {name} ({stem}.2bpp, {tiles} tiles)")
    lines.append("")
    (ASSETS / "sprite_sheet_pointers.inc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {ASSETS / 'sprite_sheet_pointers.inc'} "
          f"({num} sprites, {len(stems_seen) - len(missing)} unique sheets)")


def main():
    ASSETS.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # 1. Tileset GFX / blocks / coll — one inc file per unique source
    # ------------------------------------------------------------------
    seen_canonical = set()
    for tid, canonical, gfx_stem, blocks_stem, coll_label in TILESETS:
        if canonical in seen_canonical:
            continue
        seen_canonical.add(canonical)

        gfx_src    = GFX_TILESETS / f"{gfx_stem}.2bpp"
        blocks_src = GFX_BLOCKSETS / f"{blocks_stem}.bst"

        if not gfx_src.exists():
            print(f"WARNING: {gfx_src} missing — run 'make' in repo root first",
                  file=sys.stderr)
            continue

        write_inc(
            ASSETS / f"{canonical}_gfx.inc",
            f"{canonical}_gfx",
            gfx_src.read_bytes(),
            f"{gfx_stem}.2bpp → [EBP+OW_GFX_GBADDR] (active tileset slot)",
        )
        write_inc(
            ASSETS / f"{canonical}_blocks.inc",
            f"{canonical}_blocks",
            blocks_src.read_bytes(),
            f"{blocks_stem}.bst → [EBP+OW_BLOCKS_GBADDR] (active blockset slot)",
        )
        write_inc(
            ASSETS / f"{canonical}_coll.inc",
            f"{canonical}_coll",
            parse_coll_list(coll_label),
            f"{coll_label}_Coll (passable tiles, $FF-terminated) → [EBP+OW_COLL_GBADDR]",
        )

    # ------------------------------------------------------------------
    # 2. Map block layouts — one inc file per .blk file. Authored block
    #    edits from assets/map_overrides/<Pascal>.json (painted in
    #    tools/map_editor/editor.py, map-tool plan C5) are merged here so
    #    the pret maps/*.blk stay read-only and regen is idempotent.
    # ------------------------------------------------------------------
    for blk_file in sorted(MAPS_DIR.glob("*.blk")):
        pascal = blk_file.stem        # e.g. "OaksLab"
        snake  = to_snake(pascal)     # e.g. "oaks_lab"
        label  = f"{snake}_blk"
        data = bytearray(blk_file.read_bytes())
        n_over = apply_map_overrides(pascal, data)
        note = f" (+{n_over} authored override cells)" if n_over else ""
        write_inc(
            ASSETS / f"{label}.inc",
            label,
            bytes(data),
            f"{blk_file.name} block map{note} → [EBP+INDOOR_BLK_GBADDR] "
            f"(indoor) or fixed outdoor slot",
        )

    # ------------------------------------------------------------------
    # 3. Player sprite
    # ------------------------------------------------------------------
    player_src = GFX_SPRITES / "red.2bpp"
    if player_src.exists():
        write_inc(
            ASSETS / "player_sprite.inc",
            "player_sprite",
            player_src.read_bytes(),
            "Red overworld sprite 2bpp → [EBP+GB_VCHARS0] ($8000)",
        )

    # ------------------------------------------------------------------
    # 4. NPC sprite assets — all sprites used in any map's object_event lines.
    #
    # Per-sprite:  assets/npc_sprites/<stem>.inc  (full 24-tile sheet)
    # Master table: assets/npc_sprite_data_table.inc
    #    — %includes all per-sprite files then defines npc_sprite_data_table:
    #      a flat dd array indexed by sprite_id (0x00 … max_id).
    # ------------------------------------------------------------------
    NPC_SPRITES_DIR.mkdir(parents=True, exist_ok=True)
    used_sprites = enumerate_npc_sprites()

    if not used_sprites:
        print("WARNING: no SPRITE_* constants found in map object files", file=sys.stderr)

    max_id = max(sid for sid, _, _ in used_sprites) if used_sprites else 0
    table_size = max_id + 1

    # Map sprite_id → stem for used sprites
    by_id: dict = {sid: (stem, name) for sid, stem, name in used_sprites}

    FULL_SHEET = 384  # 24 tiles × 16 bytes; LoadNPCSpriteTiles always copies this much

    # Per-sprite full-sheet inc files
    missing: set = set()
    for sid, stem, name in used_sprites:
        src = GFX_SPRITES / f"{stem}.2bpp"
        if not src.exists():
            print(f"WARNING: {src} missing for {name} (id=0x{sid:02X}), "
                  "emitting dd 0 in table", file=sys.stderr)
            missing.add(sid)
            continue
        data = src.read_bytes()
        note = ""
        if len(data) < FULL_SHEET:
            # Sprites smaller than 24 tiles (items, single-pose NPCs): pad with
            # zeros so LoadNPCSpriteTiles's two rep movsb calls always find
            # FULL_SHEET bytes.  Walk tiles will be zeroed (invisible) which is
            # correct for STAY-only sprites.
            note = f", padded from {len(data)} bytes"
            data = data + bytes(FULL_SHEET - len(data))
        write_inc(
            NPC_SPRITES_DIR / f"{stem}.inc",
            f"npc_{stem}",
            data,
            f"{name} (0x{sid:02X}) sprite sheet (24 tiles: [0-11]=still, "
            f"[12-23]=walk{note})",
        )

    # Master data table: %includes + flat pointer array
    table_lines = [
        "; npc_sprite_data_table.inc — generated by tools/gen_all_assets.py. DO NOT EDIT BY HAND.",
        "; Flat dd array indexed by sprite_id (0 = no asset / not used on any map).",
        "; Included from map_sprites.asm in section .data.",
        "",
    ]
    for sid, stem, name in used_sprites:
        if sid not in missing:
            table_lines.append(f'%include "assets/npc_sprites/{stem}.inc"')
    table_lines += [
        "",
        f"NPC_SPRITE_TABLE_SIZE equ {table_size}",
        "",
        "npc_sprite_data_table:",
    ]
    for i in range(table_size):
        if i in by_id and i not in missing:
            stem, name = by_id[i]
            table_lines.append(f"    dd npc_{stem}  ; 0x{i:02X} {name}")
        else:
            comment = f"; 0x{i:02X} {by_id[i][1]}" if i in by_id else f"; 0x{i:02X} (unused)"
            table_lines.append(f"    dd 0  {comment}")
    table_lines.append("")
    (ASSETS / "npc_sprite_data_table.inc").write_text("\n".join(table_lines) + "\n")
    print(f"  wrote {ASSETS / 'npc_sprite_data_table.inc'} "
          f"({table_size} entries, {len(used_sprites) - len(missing)} sprites)")

    # ------------------------------------------------------------------
    # 4b. Full-coverage sprite sheet pointer table (OW-A.2 P3a).
    #     Covers all NUM_SPRITES (incl. outside-map fillers the map-object
    #     scan above never sees) for the faithful map_sprites.asm sprite-set
    #     machinery. Self-contained; not linked until P3c swaps the include.
    # ------------------------------------------------------------------
    generate_sprite_sheet_pointers()

    # ------------------------------------------------------------------
    # 5. Chain the dependent generators so a single run of this script
    #    regenerates EVERYTHING consistently.  These three were previously
    #    only run by separate Makefile targets, so running this script
    #    directly left map headers, NPC dialogs, and toggleable-object
    #    flags stale (the classic "regenerated assets but bug persists").
    #    map_headers must run first: gen_npc_dialogs / gen_toggleable_objects
    #    derive slot counts from the same parse it uses.
    # ------------------------------------------------------------------
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import gen_map_headers
    import gen_npc_dialogs
    import gen_toggleable_objects
    import gen_battle_text
    import gen_trainer_parties
    import gen_trainer_names
    import gen_move_grammar
    import gen_type_names

    print("chaining gen_map_headers ...")
    gen_map_headers.main(debug_warps=False)
    print("chaining gen_npc_dialogs ...")
    gen_npc_dialogs.generate_all()
    print("chaining gen_toggleable_objects ...")
    gen_toggleable_objects.generate_all()
    print("chaining gen_battle_text ...")
    gen_battle_text.main()
    print("chaining gen_trainer_parties ...")
    gen_trainer_parties.main()
    print("chaining gen_trainer_names ...")
    gen_trainer_names.main()
    print("chaining gen_move_grammar ...")
    gen_move_grammar.main()
    print("chaining gen_type_names ...")
    gen_type_names.main()

    print("done.")


if __name__ == "__main__":
    main()
