#!/usr/bin/env python3
"""gen_item_text.py — generate dos_port/assets/item_text.inc (Tier 1 data).

The item-use layer (src/engine/items/item_use.asm) prints its refusal/usage
messages through the same text engine as everything else (TextCommandProcessor
over a TX_* command stream). pret holds those messages as `text_far`-wrapped
labels in engine/items/item_effects.asm and engine/menus/party_menu.asm, with
the bodies in data/text/*.asm.

Rather than duplicate the stream encoder, this reuses gen_battle_text.py's
charmap / memmap / text-macro parser verbatim (same TX_RAM / TX_NUM / text_far
handling) and just points it at the item + party-menu sources.

Emits, in section .data:
  * the ItemUse* guard/usage texts (ItemUseNoEffectText, ItemUseNotTimeText, …)
  * the nine party-menu item-use result texts (AntidoteText … RareCandyText),
    which RedrawPartyMenu_ selects by wPartyMenuTypeOrMessageID.

Labels already emitted by gen_battle_text.py are skipped (a duplicate `global`
is a link error). DO NOT EDIT the output by hand — re-run this generator.

Run from repo root or dos_port/.
"""
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "dos_port" / "assets" / "item_text.inc"

# pret sources holding the wrapper labels we want.
ITEM_SRC = [
    "engine/items/item_effects.asm",
    "engine/menus/party_menu.asm",
    # AlreadyKnowsText ("<MON> knows <MOVE>!") — CheckIfMoveIsKnown, the ItemUseTMHM
    # already-knows refusal (items plan, Stage 7).
    "engine/items/tmhm.asm",
]

# Emitted by gen_battle_text.py already — skip so the two .inc files don't
# define the same global twice.
def battle_labels() -> set:
    inc = ROOT / "dos_port" / "assets" / "battle_text.inc"
    if not inc.exists():
        return set()
    return set(re.findall(r"^global (\w+)$", inc.read_text(), re.M))


def main() -> int:
    charmap = gbt.load_charmap()
    memmap = gbt.load_memmap()
    far_db = gbt.collect_far(charmap, memmap)

    gbt.BATTLE_SRC = ITEM_SRC          # retarget the wrapper collector
    wrappers = gbt.collect_wrappers(charmap, memmap, far_db)

    skip = battle_labels()
    labels = sorted(k for k in wrappers if k not in skip)

    out = [
        "; item_text.inc — generated by tools/gen_item_text.py. DO NOT EDIT BY HAND.",
        "; Item-use message command streams (pret engine/items/item_effects.asm +",
        f"; engine/menus/party_menu.asm wrappers), text_far flattened. {len(labels)} labels.",
        "; section .data so labels never land in an orphaned section (see link.ld).",
        "",
        "section .data",
        "",
    ]
    # A consumer in another .o cannot compute `Label_end - Label` (not relocatable),
    # and the port must know a stream's length to stage it in GB space before
    # TextCommandProcessor can read it. So every label also gets a {ptr, len} pair
    # emitted here, where the length IS an assembly-time constant.
    for label in labels:
        b = wrappers[label]
        out.append(f"global {label}")
        out.append(f"{label}:")
        for i in range(0, len(b), 16):
            out.append("    db " + ", ".join(f"0x{x:02X}" for x in b[i:i + 16]))
        out.append(f"global {label}_ref")
        out.append(f"{label}_ref: dd {label}, {len(b)}   ; flat ptr + byte count")
    out.append("")

    # pret PartyMenuItemUseMessagePointers (engine/menus/party_menu.asm:226) —
    # RedrawPartyMenu_ indexes it with (wPartyMenuTypeOrMessageID & $0F). Same
    # {ptr, len} pairs, so the entry stride is 8, not pret's 2.
    PARTY_MSGS = ["AntidoteText", "BurnHealText", "IceHealText", "AwakeningText",
                  "ParlyzHealText", "PotionText", "FullHealText", "ReviveText",
                  "RareCandyText"]
    missing = [m for m in PARTY_MSGS if m not in wrappers]
    if missing:
        raise SystemExit(f"party-menu item-use texts missing from the scan: {missing}")
    out += [
        "; PartyMenuItemUseMessagePointers — the nine item-use result texts, in",
        "; ANTIDOTE_MSG..RARE_CANDY_MSG order. Entries are {dd stream, dd length}.",
        "global PartyMenuItemUseMessagePointers",
        "PartyMenuItemUseMessagePointers:",
    ]
    for m in PARTY_MSGS:
        out.append(f"    dd {m}, {len(wrappers[m])}")
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({len(labels)} labels)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
