#!/usr/bin/env python3
"""gen_moves.py — generate dos_port/assets/moves.inc from pret source.

Emits the `Moves` table consumed by AddPartyMon_WriteMovePP / WriteMonMoves
(and, later, the battle engine). One MOVE_LENGTH(6)-byte record per move, in
move-id order (data/moves/moves.asm):

  +0 MOVE_ANIM   (= move id)
  +1 MOVE_EFFECT
  +2 MOVE_POWER
  +3 MOVE_TYPE
  +4 MOVE_ACC    (accuracy: the rgbds `percent` macro is `* $ff / 100`)
  +5 MOVE_PP

Run from repo root or dos_port/; paths resolve relative to the repo root.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"
MOVE_LENGTH = 6


def parse_consts(rel_path: str) -> dict:
    """Parse an rgbds const_def/const enum file into {NAME: value}."""
    out, val = {}, 0
    for line in (ROOT / rel_path).read_text().splitlines():
        s = line.split(";", 1)[0].strip()
        if not s:
            continue
        m = re.match(r"const_def(?:\s+(-?\w+))?$", s)
        if m:
            val = int(m.group(1)) if m.group(1) else 0
            continue
        m = re.match(r"const_next\s+(-?\w+)$", s)
        if m:
            val = int(m.group(1), 0)
            continue
        m = re.match(r"const_skip(?:\s+(\w+))?$", s)
        if m:
            val += int(m.group(1), 0) if m.group(1) else 1
            continue
        m = re.match(r"const\s+(\w+)$", s)
        if m:
            out[m.group(1)] = val
            val += 1
    return out


def resolve(tok: str, consts: dict) -> int:
    tok = tok.strip()
    if tok in consts:
        return consts[tok]
    if tok.startswith("$"):
        return int(tok[1:], 16)
    return int(tok, 0)


def main() -> int:
    moves = parse_consts("constants/move_constants.asm")
    effects = parse_consts("constants/move_effect_constants.asm")
    types = parse_consts("constants/type_constants.asm")

    rows = bytearray()
    count = 0
    for line in (ROOT / "data/moves/moves.asm").read_text().splitlines():
        s = line.split(";", 1)[0].strip()
        m = re.match(r"move\s+(.+)$", s)
        if not m:
            continue
        f = [t.strip() for t in m.group(1).split(",")]
        if len(f) != 6:
            print(f"bad move line: {line!r}", file=sys.stderr)
            return 1
        anim   = resolve(f[0], moves)
        effect = resolve(f[1], effects)
        power  = resolve(f[2], {})
        typ    = resolve(f[3], types)
        acc    = resolve(f[4], {}) * 0xFF // 100      # `percent` macro
        pp     = resolve(f[5], {})
        rows += bytes((anim & 0xFF, effect & 0xFF, power & 0xFF,
                       typ & 0xFF, acc & 0xFF, pp & 0xFF))
        count += 1

    out = [
        "; moves.inc — generated by tools/gen_moves.py. DO NOT EDIT BY HAND.",
        f"; Moves: {count} x {MOVE_LENGTH}-byte records (anim,effect,power,type,acc,pp), move-id order.",
        "",
        "Moves:",
    ]
    for i in range(0, len(rows), MOVE_LENGTH):
        rec = rows[i:i + MOVE_LENGTH]
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in rec)
                    + f"    ; move {i // MOVE_LENGTH + 1}")
    out += ["Moves_end:", ""]

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "moves.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} (Moves {count} moves x {MOVE_LENGTH} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
