#!/usr/bin/env python3
"""gen_ui_layout.py — sidecar JSON -> assets/ui_layout_<subsystem>.inc (Tier 1).

Subsystem-generic. The sidecar (assets/ui_layout_<subsystem>_sidecar.json) is
hand-positioned via tools/ui_layout/editor.py; this generator emits:

  1. Per-element equates  UI_<ID>_{GBX,GBY,GBW,GBH,COL,ROW,X2,Y2,WX,WY,CLIP,MAXY}
     (+ _TX/_TY projected text coords where the element carries a label), for
     direct set_single_window/TextBoxBorder call sites.
  2. UI_TextBoxCoordTable — pret-shaped `db id,x1,y1,x2,y2` rows (projected
     coords) for elements sourced from pret's TextBoxCoordTable. Rows for
     TextBoxTextAndCoordTable are NOT emitted as bytes because those rows carry
     text POINTERS (Tier-2 code); the hand-written table in
     src/engine/menus/text_box.asm composes them from the per-element equates.

Projection math comes from tools/ui_layout/canvas.py — the same module the
editor previews with, so output cannot drift from what was seen in the tool.

Usage (repo root or dos_port/):
  python3 tools/gen_ui_layout.py menus            # write the .inc
  python3 tools/gen_ui_layout.py menus --check    # validate + print, no write
  python3 tools/gen_ui_layout.py menus --atlas /tmp/atlas.png
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from ui_layout import canvas as cv        # noqa: E402
from ui_layout import schema              # noqa: E402

ASSETS = HERE.parent / "assets"


def emit(lay: schema.Layout) -> str:
    sub = lay.subsystem
    out = [
        f"; ui_layout_{sub}.inc — generated by tools/gen_ui_layout.py from",
        f"; assets/ui_layout_{sub}_sidecar.json. DO NOT EDIT BY HAND.",
        "; Edit the layout with: python3 tools/ui_layout/editor.py "
        f"assets/ui_layout_{sub}_sidecar.json",
        ";",
        "; COL/ROW/X2/Y2 are projected tile coords on the "
        f"{lay.canvas['cols']}x{lay.canvas['rows']} canvas;",
        "; WX/WY/CLIP/MAXY are the window-descriptor form "
        "(set_single_window/add_window).",
        "",
    ]
    coord_rows = []
    for el in lay.elements:
        p = cv.project(el)
        out.append(f"; {cv.proj_tag(sub, el)[2:]}")
        if el.pret_ref:
            out.append(f"; pret ref: {el.pret_ref} ({el.source})")
        pre = f"UI_{el.id}"
        for name, val in (("GBX", el.gb_x), ("GBY", el.gb_y),
                          ("GBW", el.gb_w), ("GBH", el.gb_h),
                          ("COL", p.col), ("ROW", p.row),
                          ("X2", p.x2), ("Y2", p.y2),
                          ("WX", p.wx), ("WY", p.wy),
                          ("CLIP", p.clip), ("MAXY", p.max_y)):
            out.append(f"{pre}_{name:<4} equ {val}")
        if p.text_col is not None:
            out.append(f"{pre}_TX   equ {p.text_col}")
            out.append(f"{pre}_TY   equ {p.text_row}")
        out.append("")
        if el.pret_id is not None and el.source == "TextBoxCoordTable":
            coord_rows.append(
                f"    db 0x{el.pret_id:02X}, {pre}_COL, {pre}_ROW, "
                f"{pre}_X2, {pre}_Y2  ; {el.id}")

    out += [
        "; pret data/text_boxes.asm:TextBoxCoordTable — projected. JP_* rows",
        "; omitted (DEVIATION: JP-only templates not shipped in the EN port).",
        "; Guarded so secondary consumers can %include just the UI_* equates",
        "; (define UI_LAYOUT_EQUATES_ONLY first) without duplicating the table.",
        "%ifndef UI_LAYOUT_EQUATES_ONLY",
        f"UI_TextBoxCoordTable_{sub}:",
        *coord_rows,
        "    db 0xFF  ; end",
        "%endif",
        "",
    ]
    return "\n".join(out) + "\n"


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    sub = sys.argv[1]
    sidecar = ASSETS / f"ui_layout_{sub}_sidecar.json"
    lay = schema.load(sidecar)
    if lay.subsystem != sub:
        sys.exit(f"{sidecar} declares subsystem {lay.subsystem!r}, not {sub!r}")
    text = emit(lay)
    if "--check" in sys.argv:
        print(text)
        return
    if "--atlas" in sys.argv:
        from ui_layout import render
        dst = sys.argv[sys.argv.index("--atlas") + 1]
        render.render_layout(lay).save(dst)
        print(f"wrote {dst}")
        return
    dst = ASSETS / f"ui_layout_{sub}.inc"
    dst.write_text(text)
    print(f"wrote {dst} ({len(lay.elements)} elements)")


if __name__ == "__main__":
    main()
