#!/usr/bin/env python3
"""gen_items.py — generate dos_port/assets/items.inc from pret source.

Emits two item data tables (no UI; the mart/bag screens that consume them are
deferred):

  ItemNames  — data/items/names.asm `li "NAME"`: each name GB-charmap encoded and
               '@'-terminated ($50), concatenated (variable length, as pret).
  ItemPrices — data/items/prices.asm `bcd3 N`: 3-byte BCD price per item id.

Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"


def load_charmap(path: Path) -> list:
    cm = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s+charmap\s+"((?:[^"\\]|\\.)*)",\s*\$([0-9a-fA-F]+)', line)
        if m:
            cm.append((m.group(1), int(m.group(2), 16)))
    cm.sort(key=lambda x: -len(x[0]))
    return cm


def encode(s: str, charmap: list) -> bytes:
    out, i = [], 0
    while i < len(s):
        for key, val in charmap:
            if key and s[i:].startswith(key):
                out.append(val)
                i += len(key)
                break
        else:
            raise ValueError(f"Unrecognised char at {i}: {s[i:i+4]!r}")
    return bytes(out)


def bcd3(v: int) -> bytes:
    """3-byte BCD, matching pret's bcd3 macro (dn packs two nibbles)."""
    digits = [(v // 10**e) % 10 for e in (5, 4, 3, 2, 1, 0)]
    return bytes(((digits[0] << 4) | digits[1],
                  (digits[2] << 4) | digits[3],
                  (digits[4] << 4) | digits[5]))


def main() -> int:
    charmap = load_charmap(ROOT / "constants/charmap.asm")

    names, namebytes = [], bytearray()
    for line in (ROOT / "data/items/names.asm").read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s*li\s+"((?:[^"\\]|\\.)*)"', line)
        if m:
            names.append(m.group(1))
            namebytes += encode(m.group(1), charmap) + b"\x50"

    prices = []
    for line in (ROOT / "data/items/prices.asm").read_text().splitlines():
        s = line.split(";", 1)[0].strip()
        m = re.match(r"bcd3\s+(\d+)$", s)
        if m:
            prices.append(int(m.group(1)))

    pricebytes = bytearray()
    for p in prices:
        pricebytes += bcd3(p)

    out = [
        "; items.inc — generated by tools/gen_items.py. DO NOT EDIT BY HAND.",
        f"; ItemNames: {len(names)} '@'-terminated charmap names (variable length).",
        f"; ItemPrices: {len(prices)} x 3-byte BCD prices, item-id order.",
        "",
        "ItemNames:",
    ]
    o = 0
    for nm in names:
        enc = encode(nm, charmap)
        rec = namebytes[o:o + len(enc) + 1]
        o += len(enc) + 1
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in rec) + f'    ; {nm}')
    out += ["ItemNames_end:", "", "ItemPrices:"]
    for i, p in enumerate(prices):
        rec = pricebytes[i * 3:i * 3 + 3]
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in rec) + f"    ; item {i+1}: {p}")
    out += ["ItemPrices_end:", ""]

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "items.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} (ItemNames {len(names)} names / {len(namebytes)} bytes, "
          f"ItemPrices {len(prices)} x 3 = {len(pricebytes)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
