#!/usr/bin/env python3
"""gen_field_moves.py — generate dos_port/assets/field_moves.inc from pret.

Two faithful tables for the overworld party-menu field-move pop-up
(pret DisplayFieldMoveMonMenu / GetMonFieldMoves):

  FieldMoveDisplayData : 3-byte records (move id, FieldMoveNames index, leftmost
                         tile column), $FF-terminated — from data/moves/field_moves.asm.
  FieldMoveNames       : variable-length '@'-terminated names ($50), 1-based index
                         order — from data/moves/field_move_names.asm.

Move ids are resolved from constants/move_constants.asm (so the table stays in
sync with the enum); names are GB-charmap encoded exactly as the source `db`
strings (the '@' terminator is literal in the source, like pret). Entry 3 is the
unused ANIM_B4 slot, whose name is the empty string (just '@').

Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"
TERM = 0x50               # '@' terminator


def load_move_constants(path: Path) -> dict:
    vals, val = {}, 0
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        m = re.match(r'const_def\s*(-?\d+)?$', s)
        if m:
            val = int(m.group(1)) if m.group(1) else 0
            continue
        m = re.match(r'const\s+(\w+)', s)
        if m:
            vals[m.group(1)] = val
            val += 1
    return vals


def load_charmap(path: Path) -> list:
    cm = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s+charmap\s+"((?:[^"\\]|\\.)*)",\s*\$([0-9a-fA-F]+)', line)
        if m:
            cm.append((m.group(1), int(m.group(2), 16)))
    cm.sort(key=lambda x: -len(x[0]))      # longest-match first
    return cm


def encode(s: str, charmap: list) -> bytes:
    out, i = [], 0
    while i < len(s):
        for key, val in charmap:
            if key and s[i:].startswith(key):
                out.append(val)
                i += len(key)
                break
        else:
            raise ValueError(f"Unrecognised char at {i}: {s[i:i+4]!r}")
    return bytes(out)


def parse_display_data(path: Path, consts: dict) -> list:
    entries = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s*db\s+(\w+),\s*(\d+),\s*\$([0-9a-fA-F]+)', line)
        if not m:
            continue
        name, idx, col = m.group(1), int(m.group(2)), int(m.group(3), 16)
        if name not in consts:
            raise ValueError(f"unknown move constant {name!r}")
        entries.append((consts[name], name, idx, col))
    return entries


def parse_names(path: Path) -> list:
    names = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s*db\s+"((?:[^"\\]|\\.)*)"', line)
        if m:
            names.append(m.group(1))
    return names


def main() -> int:
    consts = load_move_constants(ROOT / "constants/move_constants.asm")
    charmap = load_charmap(ROOT / "constants/charmap.asm")
    entries = parse_display_data(ROOT / "data/moves/field_moves.asm", consts)
    names = parse_names(ROOT / "data/moves/field_move_names.asm")

    out = [
        "; field_moves.inc — generated by tools/gen_field_moves.py. DO NOT EDIT BY HAND.",
        "; FieldMoveDisplayData: db move-id, FieldMoveNames index, leftmost tile col; $FF end.",
        "; FieldMoveNames: variable-length '@'($50)-terminated names, 1-based index order.",
        "",
        "FieldMoveDisplayData:",
    ]
    for mid, name, idx, col in entries:
        out.append(f"    db 0x{mid:02X}, {idx}, 0x{col:02X}    ; {name}")
    out.append("    db 0xFF    ; end")
    out += ["", "FieldMoveNames:"]
    total = 0
    for i, nm in enumerate(names):
        enc = encode(nm, charmap)       # '@' terminator is literal in the source
        if not enc or enc[-1] != TERM:
            raise ValueError(f"name {nm!r} (index {i + 1}) is not '@'-terminated")
        total += len(enc)
        body = nm[:-1] if nm.endswith("@") else nm
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in enc)
                   + f"    ; {i + 1}  {body or '(unused)'}")
    out += ["FieldMoveNames_end:", ""]

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "field_moves.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} ({len(entries)} display entries, {len(names)} names, "
          f"{total} name bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
