#!/usr/bin/env python3
"""gen_overworld_strings.py — generate dos_port/assets/overworld_strings.inc.

Overworld-engine field / HUD text strings, GB-charmap encoded through the
unicode_converter submodule (gb_text.encode) instead of hand-written charmap
hex, then emitted as '@'-terminated ($50) NASM `db` lines. Consumed via
%include by src/engine/overworld/player_state.asm (PrintSafariZoneSteps).

This is the Tier-1 home for overworld field/HUD strings (per project-conventions:
human-rendered text is DATA, never hand-encoded charmap bytes in a .asm). Seeded
with the Safari Zone step/ball-count HUD strings.

Two outputs:
  * overworld_strings.inc  — simple '@'-terminated HUD strings (Safari Zone),
    %included by src/engine/overworld/player_state.asm (PrintSafariZoneSteps).
  * field_move_text.inc    — the OW-4.x field-message FAR text streams
    (Strength/Surf/boulder), %included by
    src/engine/overworld/field_move_messages.asm. These are full pret text
    command streams (text_ram/line/prompt/text_end), so instead of re-deriving
    the parser we reuse gen_battle_text's authoritative pret-text parser
    (collect_far scans data/text/text_*.asm) and emit just the labels we want,
    with text_far indirection flattened for the flat model.

Run from repo root or dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text  # noqa: E402
import gen_battle_text  # noqa: E402  (reuse its pret data/text parser)

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"
TERMINATOR = 0x50  # '@'

# (NASM label, Unicode text) — pret: engine/overworld/player_state.asm.
# The trailing '@' terminator is appended as $50; do NOT put it in the text.
# '×' is U+00D7 (charmap $F1); the trailing space in SafariBallText is significant.
LABELS = [
    ("SafariSteps",    "/500"),                # pret: db "/500@"
    ("SafariBallText", "BALL×× "),    # pret: db "BALL×× @"
]

# Far-text streams for engine/overworld/field_move_messages.asm (OW-4.4).
# Kept in their own .inc so they don't land in player_state.asm's TU (which
# %includes overworld_strings.inc) — avoids a duplicate-symbol at final link.
# pret defs live in data/text/text_8.asm.
FIELD_MOVE_FAR = [
    "_UsedStrengthText",
    "_CanMoveBouldersText",
    "_CurrentTooFastText",
    "_CyclingIsFunText",
]

# Far-text streams for engine/overworld/cut.asm (OW-3.4). Own .inc for the same
# TU-isolation reason as FIELD_MOVE_FAR. pret defs: data/text/text_9.asm.
CUT_FAR = [
    "_NothingToCutText",
    "_UsedCutText",
]


def fmt_bytes(label: str, data: list) -> str:
    rows = []
    for k in range(0, len(data), 16):
        rows.append("    db " + ", ".join(f"0x{b:02X}" for b in data[k:k + 16]))
    return f"{label}:\n" + "\n".join(rows)


def main() -> int:
    out = [
        "; overworld_strings.inc — generated by tools/gen_overworld_strings.py. DO NOT EDIT BY HAND.",
        "; Overworld-engine field/HUD strings, GB-charmap encoded via the",
        "; unicode_converter submodule (gb_text.encode) and '@'-terminated ($50).",
        "; pret ref: engine/overworld/player_state.asm.",
        "",
    ]
    for label, text in LABELS:
        b = gb_text.encode(text) + [TERMINATOR]
        hexs = ", ".join(f"0x{x:02X}" for x in b)
        out.append(f'{label}: db {hexs}   ; "{text}@"')
    out.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "overworld_strings.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} ({len(LABELS)} labels)")

    # --- flattened FAR text streams (OW-4.4 / OW-3.4) ------------------------
    cm = gen_battle_text.load_charmap()
    mem = gen_battle_text.load_memmap()
    far = gen_battle_text.collect_far(cm, mem)

    # (output basename, label list, one-line description) — each its own .inc so
    # the streams stay isolated to their single consuming TU (no duplicate-symbol
    # at final link; player_state.asm already %includes overworld_strings.inc).
    far_files = [
        ("field_move_text", FIELD_MOVE_FAR,
         "Field-move message FAR text streams (Strength/Surf/boulder; data/text/text_8.asm)"),
        ("cut_text", CUT_FAR,
         "Cut field-move FAR text streams (data/text/text_9.asm)"),
    ]
    for base, labels, desc in far_files:
        fout = [
            f"; {base}.inc — generated by tools/gen_overworld_strings.py. DO NOT EDIT BY HAND.",
            f"; {desc}, pret text_far indirection flattened via",
            "; gen_battle_text.collect_far. section .data so labels never land in an",
            "; orphaned section (see link.ld).",
            "",
            "section .data",
            "",
        ]
        for label in labels:
            if label not in far:
                sys.stderr.write(f"gen_overworld_strings: missing far label {label}\n")
                return 1
            fout.append(fmt_bytes(label, far[label]))
        fout.append("")
        fdst = ASSETS / f"{base}.inc"
        fdst.write_text("\n".join(fout))
        print(f"wrote {fdst} ({len(labels)} far labels)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
