#!/usr/bin/env python3
"""gen_type_matchups.py — generate dos_port/assets/type_matchups.inc from pret.

Emits the TypeEffects table consumed by the damage pipeline
(AdjustDamageForMoveType in src/engine/battle/core_damage.asm). Each entry is
3 bytes: attacker type, defender type, effectiveness factor (scaled by 10).
The table is terminated by a single $FF byte.

Source: data/types/type_matchups.asm (repo root, pret spec). Per the project
rule, static data is generated from the disassembly, never hand-authored, so it
stays in sync.

Run from repo root or dos_port/; paths resolve relative to the repo root.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]          # repo root
ASSETS = ROOT / "dos_port" / "assets"
SRC = ROOT / "data" / "types" / "type_matchups.asm"

# Mirror constants/type_constants.asm + battle_constants.asm effectiveness.
TYPES = {
    "NORMAL": 0x00, "FIGHTING": 0x01, "FLYING": 0x02, "POISON": 0x03,
    "GROUND": 0x04, "ROCK": 0x05, "BIRD": 0x06, "BUG": 0x07, "GHOST": 0x08,
    "FIRE": 0x14, "WATER": 0x15, "GRASS": 0x16, "ELECTRIC": 0x17,
    "PSYCHIC_TYPE": 0x18, "ICE": 0x19, "DRAGON": 0x1A,
}
EFF = {
    "SUPER_EFFECTIVE": 20, "MORE_EFFECTIVE": 15, "EFFECTIVE": 10,
    "NOT_VERY_EFFECTIVE": 5, "NO_EFFECT": 0,
}


def main() -> int:
    rows = []
    saw_end = False
    for line in SRC.read_text().splitlines():
        s = line.split(";", 1)[0].strip()
        if not s.startswith("db"):
            continue
        body = s[2:].strip()
        if body == "-1":
            saw_end = True
            break
        parts = [p.strip() for p in body.split(",")]
        if len(parts) != 3:
            print(f"bad matchup line: {line!r}", file=sys.stderr)
            return 1
        atk, dfn, eff = parts
        if atk not in TYPES or dfn not in TYPES or eff not in EFF:
            print(f"unknown symbol in: {line!r}", file=sys.stderr)
            return 1
        rows.append((TYPES[atk], TYPES[dfn], EFF[eff], atk, dfn, eff))

    if not saw_end:
        print("table not terminated by 'db -1'", file=sys.stderr)
        return 1

    out = [
        "; type_matchups.inc — generated by tools/gen_type_matchups.py. DO NOT EDIT BY HAND.",
        "; TypeEffects: 3-byte entries {attacker type, defender type, factor*10},",
        "; terminated by $FF. Scanned by AdjustDamageForMoveType.",
        "",
        "TypeEffects:",
    ]
    for a, d, e, an, dn, en in rows:
        out.append(f"    db 0x{a:02X}, 0x{d:02X}, {e:<2}    ; {an} vs {dn} = {en}")
    out.append("    db 0xFF    ; end")
    out.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "type_matchups.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} ({len(rows)} matchups)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
