#!/usr/bin/env python3
"""gen_status_strings.py — generate dos_port/assets/status_strings.inc.

The status/summary-screen UI label strings, which pret keeps as inline `db`/`next`
data in engine/pokemon/status_screen.asm. Encoded through the unicode_converter
submodule (gb_text.encode) instead of hand-written charmap hex — same pattern as
gen_menu_strings.py — with the pret control tiles (<NEXT> $4E line break, <ID> $73)
inserted as named raw bytes between encoded text runs. Consumed by
src/engine/pokemon/status_screen.asm via %include.

pret ref (all file-local in engine/pokemon/status_screen.asm):
  TypesIDNoOTText, StatusText, OKText, PrintStatsBox.StatsText, StatusScreenExpText.
(The OTPointers / NamePointers2 address tables are NOT here — they are port-specific
WRAM-offset pointer tables, kept hand-written in the .asm like any jump table.)

Run from repo root or dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"

# pret charmap control tiles that are not single-char-encodable.
NEXT = 0x4E   # "<NEXT>" — line break (double-spaced by default in PlaceString)
ID_ = 0x73    # "<ID>"   — the "№" ID-label prefix tile
TERM = 0x50   # "@"      — string terminator

# (NASM label, [parts]) where a part is either a str (→ gb_text.encode, single-char
# charmap) or an int (a raw control-tile byte). Mirrors pret's db/next sequence.
LABELS = [
    ("TypesIDNoOTText", ["TYPE1/", NEXT, "TYPE2/", NEXT, ID_, "№/", NEXT, "OT/", NEXT, TERM]),
    ("StatusText",       ["STATUS/", TERM]),
    ("OKText",           ["OK", TERM]),
    ("StatsText",        ["ATTACK", NEXT, "DEFENSE", NEXT, "SPEED", NEXT, "SPECIAL", TERM]),
    ("StatusScreenExpText", ["EXP POINTS", NEXT, "LEVEL UP", TERM]),
]


def encode_parts(parts):
    out = []
    for p in parts:
        if isinstance(p, int):
            out.append(p)
        else:
            out.extend(gb_text.encode(p))
    return out


def main() -> int:
    lines = [
        "; status_strings.inc — generated by tools/gen_status_strings.py. DO NOT EDIT BY HAND.",
        "; Status/summary-screen PlaceString labels, GB-charmap encoded via gb_text.encode",
        "; (unicode_converter submodule); <NEXT> $4E / <ID> $73 / '@' $50 inserted as raw tiles.",
        "",
    ]
    for label, parts in LABELS:
        b = encode_parts(parts)
        hexs = ", ".join(f"0x{x:02X}" for x in b)
        lines.append(f"{label}: db {hexs}")
    lines.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "status_strings.inc"
    dst.write_text("\n".join(lines))
    print(f"wrote {dst} ({len(LABELS)} labels)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
