#!/usr/bin/env python3
"""gen_monster_names.py — generate dos_port/assets/monster_names.inc from pret.

Emits MonsterNames: NUM_POKEMON_INDEXES (190) fixed-width (NAME_LENGTH-1 = 10)
records, internal-index order, GB-charmap encoded and '@'-padded ($50) — exactly
as pret's `dname` macro over data/pokemon/names.asm.

This is the species-name table used to default a freshly-created mon's nickname
(and, later, name display in menus/the Pokédex). Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"
NUM_POKEMON_INDEXES = 190
NAME_WIDTH = 10          # NAME_LENGTH - 1
PAD = 0x50               # '@' terminator/pad


def load_charmap(path: Path) -> list:
    cm = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s+charmap\s+"((?:[^"\\]|\\.)*)",\s*\$([0-9a-fA-F]+)', line)
        if m:
            cm.append((m.group(1), int(m.group(2), 16)))
    cm.sort(key=lambda x: -len(x[0]))      # longest-match first
    return cm


def encode(s: str, charmap: list) -> bytes:
    out, i = [], 0
    while i < len(s):
        for key, val in charmap:
            if key and s[i:].startswith(key):
                out.append(val)
                i += len(key)
                break
        else:
            raise ValueError(f"Unrecognised char at {i}: {s[i:i+4]!r}")
    return bytes(out)


def main() -> int:
    charmap = load_charmap(ROOT / "constants/charmap.asm")
    names = []
    for line in (ROOT / "data/pokemon/names.asm").read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s*dname\s+"((?:[^"\\]|\\.)*)"', line)
        if m:
            names.append(m.group(1))
    if len(names) != NUM_POKEMON_INDEXES:
        print(f"expected {NUM_POKEMON_INDEXES} names, got {len(names)}", file=sys.stderr)
        return 1

    data = bytearray()
    for nm in names:
        enc = encode(nm, charmap)
        if len(enc) > NAME_WIDTH:
            print(f"name too long: {nm!r}", file=sys.stderr)
            return 1
        data += enc + bytes([PAD]) * (NAME_WIDTH - len(enc))

    out = [
        "; monster_names.inc — generated by tools/gen_monster_names.py. DO NOT EDIT BY HAND.",
        f"; MonsterNames: {NUM_POKEMON_INDEXES} x {NAME_WIDTH}-byte '@'-padded names, internal-index order.",
        "",
        "MonsterNames:",
    ]
    for i, nm in enumerate(names):
        rec = data[i * NAME_WIDTH:(i + 1) * NAME_WIDTH]
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in rec) + f"    ; {nm}")
    out += ["MonsterNames_end:", ""]

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "monster_names.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} (MonsterNames {len(names)} x {NAME_WIDTH} = {len(data)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
