#!/usr/bin/env python3
"""gen_menu_strings.py — generate dos_port/assets/menu_strings.inc.

Encodes the START-menu item labels through the unicode_converter submodule
(gb_text.encode) instead of hand-written charmap hex, then emits NASM `db` lines
with the '@' string terminator ($50). Consumed by
src/engine/menus/draw_start_menu.asm via %include, which aliases each generated
label to the pret name (StartMenuPokemonText equ sm_str_pokemon, ...).

The source column below is pret's `db` string VERBATIM, not the rendered text.
That distinction is load-bearing: pret writes "#MON@", where '#' is charmap $54 —
a text COMMAND that PlaceNextChar expands to "POKé" at print time (home/text.asm:
`dict '#', PlacePOKe`), not four literal glyphs. Encoding the rendered string
"POKéMON" instead produces the same seven tiles on screen but a different byte
stream, silently bypassing the $54 handler the port implements
(src/home/text.asm:.handle_poke → str_poke). Keep these strings as pret spells
them and let the engine expand them; gb_text.encode maps '#' → $54 for us.

Run from repo root or dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"
TERMINATOR = 0x50

# (NASM label, pret's `db` string verbatim, pret label) — the strings are copied
# from engine/menus/draw_start_menu.asm; see the module docstring on '#' ($54).
LABELS = [
    ("sm_str_pokedex", "POKéDEX", "StartMenuPokedexText"),
    ("sm_str_pokemon", "#MON",    "StartMenuPokemonText"),
    ("sm_str_item",    "ITEM",    "StartMenuItemText"),
    ("sm_str_save",    "SAVE",    "StartMenuSaveText"),
    ("sm_str_reset",   "RESET",   "StartMenuResetText"),
    ("sm_str_option",  "OPTION",  "StartMenuOptionText"),
    ("sm_str_exit",    "EXIT",    "StartMenuExitText"),
]


def main() -> int:
    out = [
        "; menu_strings.inc — generated by tools/gen_menu_strings.py. DO NOT EDIT BY HAND.",
        "; START-menu item labels, GB-charmap encoded via the unicode_converter",
        "; submodule (gb_text.encode) and '@'-terminated ($50). The comment on each",
        "; line is pret's `db` string verbatim — '#' is $54, the POKé text command,",
        "; expanded by PlaceNextChar at print time (NOT four literal glyphs).",
        "",
    ]
    for label, text, pret_label in LABELS:
        b = gb_text.encode(text) + [TERMINATOR]
        hexs = ", ".join(f"0x{x:02X}" for x in b)
        out.append(f'{label}: db {hexs}   ; {pret_label} "{text}@"')
    out.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "menu_strings.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} ({len(LABELS)} labels)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
