#!/usr/bin/env python3
"""gen_move_grammar.py — generate dos_port/assets/move_grammar.inc from pret.

Emits the `MoveGrammar` table consumed by the (hand-authored) GetMoveGrammar
battle routine — the move-use sentence-grammar grouping table. Vestigial in
the English ROM (every group renders the same "<MON> used <MOVE>!" sentence),
but the base game still ships and walks it, so we generate it for faithfulness.

Source of truth: data/moves/grammar.asm — a sequence of move ids organized
into groups; within a group the move ids are listed, each group terminated by
a 0 byte, and the whole table terminated by -1 ($FF). Move 4 (any move not
listed) has no explicit byte run -- GetMoveGrammar falls through to it after
exhausting the table, so it is NOT itself emitted as a group of ids; only the
final $FF terminator follows the last explicit group's 0.

Reproduces pret's grouping byte-for-byte: same move ids, same order, same
group boundaries, same 0 separators, same final $FF terminator.

Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"


def parse_consts(rel_path: str) -> dict:
    """Parse an rgbds const_def/const enum file into {NAME: value}."""
    out, val = {}, 0
    for line in (ROOT / rel_path).read_text().splitlines():
        s = line.split(";", 1)[0].strip()
        if not s:
            continue
        m = re.match(r"const_def(?:\s+(-?\w+))?$", s)
        if m:
            val = int(m.group(1)) if m.group(1) else 0
            continue
        m = re.match(r"const_next\s+(-?\w+)$", s)
        if m:
            val = int(m.group(1), 0)
            continue
        m = re.match(r"const_skip(?:\s+(\w+))?$", s)
        if m:
            val += int(m.group(1), 0) if m.group(1) else 1
            continue
        m = re.match(r"const\s+(\w+)$", s)
        if m:
            out[m.group(1)] = val
            val += 1
    return out


def main() -> int:
    moves = parse_consts("constants/move_constants.asm")

    rows = []          # list of ("comment", byte) pairs in emission order
    groups = []         # list of list of move-id ints, for verification
    cur_group = []
    group_idx = 0
    saw_terminator = False

    src = ROOT / "data/moves/grammar.asm"
    for raw in src.read_text().splitlines():
        line = raw.strip()
        if not line.startswith("db"):
            continue
        s = line.split(";", 1)[0].strip()
        m = re.match(r"db\s+(.+)$", s)
        if not m:
            continue
        tok = m.group(1).strip()
        if tok == "-1":
            rows.append((0xFF, f"; end of MoveGrammar (group {group_idx})"))
            saw_terminator = True
            break
        if tok == "0":
            rows.append((0x00, f"; end of group {group_idx}"))
            groups.append(cur_group)
            cur_group = []
            group_idx += 1
            continue
        if tok not in moves:
            print(f"unrecognised move constant in grammar.asm: {tok!r}", file=sys.stderr)
            return 1
        move_id = moves[tok]
        if not (1 <= move_id <= 0xFE):
            print(f"move id out of byte range for {tok}: {move_id}", file=sys.stderr)
            return 1
        rows.append((move_id, f"; {tok} (group {group_idx})"))
        cur_group.append(move_id)

    if not saw_terminator:
        print("did not find -1 terminator in data/moves/grammar.asm", file=sys.stderr)
        return 1

    out = [
        "; move_grammar.inc — generated by tools/gen_move_grammar.py. DO NOT EDIT BY HAND.",
        "; MoveGrammar: move ids grouped by sentence-grammar id (0-3 explicit; any move",
        "; not listed implicitly uses grammar 4). Format: <ids of group 0>, 0,",
        "; <ids of group 1>, 0, ... <ids of group N>, 0, -1 ($FF table terminator).",
        f"; {len(groups)} explicit groups, {sum(len(g) for g in groups)} move ids total.",
        "; Walked by GetMoveGrammar (engine/battle/used_move_text.asm): cp -1 -> end,",
        "; cp c -> match (this group), else (byte==0) -> advance to next group.",
        "",
        "global MoveGrammar",
        "",
        "MoveGrammar:",
    ]
    for val, comment in rows:
        # Mirror pret's literal text for the sentinels (identical bytes): the table
        # terminator is `db -1` and group separators are `db 0`; move ids stay hex.
        if val == 0xFF:
            tok = "db -1"
        elif val == 0x00:
            tok = "db 0 "
        else:
            tok = f"db 0x{val:02X}"
        out.append(f"    {tok}    {comment}")
    out += ["MoveGrammar_end:", ""]

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "move_grammar.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} ({len(groups)} groups, "
          f"{sum(len(g) for g in groups)} move ids, {len(rows)} table bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
