#!/usr/bin/env python3
"""gen_map_borders.py — map_borders/*.json -> assets/map_border_overrides.inc.

Tier-1 generator (docs/current_plan_map_tool.md C3). Reads the editor-owned
border sidecars (assets/map_borders/<MAP_CONST>.json, painted in
tools/map_editor/editor.py paint mode), validates every cell against the
editable ring (border minus connection strips — connections always win, and
the runtime also applies overrides BEFORE the strip copies), and emits:

  MapBorderOverridePointers:  dd per map id (0 = no overrides)
  map_border_<CONST>:         runs of `db row, col, len` + len block bytes,
                              terminated by db 0xFF

Row/col are PADDED-grid block coords; the runtime resolves the destination
as wOverworldMap + row*(width+2*MAP_BORDER) + col (ApplyMapBorderOverrides,
src/engine/overworld/overworld.asm).

Run from dos_port/: python3 tools/gen_map_borders.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from gfx_core import pret_maps as pm           # noqa: E402
from map_editor import borders, view           # noqa: E402

ASSETS = HERE.parent / "assets"
OUT = ASSETS / "map_border_overrides.inc"


def runs_for(cells: dict[tuple[int, int], int]) -> list[tuple[int, int, list[int]]]:
    """Sorted cells -> (row, col, [blocks]) runs of consecutive columns."""
    runs = []
    for (r, c), b in sorted(cells.items()):
        if runs and runs[-1][0] == r and runs[-1][1] + len(runs[-1][2]) == c:
            runs[-1][2].append(b)
        else:
            runs.append((r, c, [b]))
    return runs


def main() -> None:
    consts = pm._constants()
    max_id = max(mid for mid, _, _ in consts.values())
    ptr = {}                     # map_id -> label
    chunks = []
    total = 0
    for p in sorted(borders.BORDERS_DIR.glob("*.json")) \
            if borders.BORDERS_DIR.exists() else []:
        const = p.stem
        if const not in consts:
            sys.exit(f"{p}: unknown map const {const!r}")
        cells = borders.load(const)
        if not cells:
            continue
        cm = view.compose_padded(const)          # pre-override composition
        errs = borders.validate(cells, cm)
        if errs:
            sys.exit(f"{p}: invalid cells:\n  " + "\n  ".join(errs))
        label = f"map_border_{const}"
        ptr[consts[const][0]] = label
        lines = [f"{label}:"]
        for r, c, blocks in runs_for(cells):
            lines.append(f"    db {r}, {c}, {len(blocks)}")
            lines.append("    db " + ", ".join(f"0x{b:02X}" for b in blocks))
        lines.append("    db 0xFF  ; end")
        chunks.append("\n".join(lines))
        total += len(cells)

    out = [
        "; map_border_overrides.inc — generated by tools/gen_map_borders.py",
        "; from assets/map_borders/*.json. DO NOT EDIT BY HAND.",
        "; Paint with: python3 tools/map_editor/editor.py <MAP_CONST>  (P)",
        "",
        "MapBorderOverridePointers:",
    ]
    for mid in range(max_id + 1):
        name = next((c for c, v in consts.items() if v[0] == mid), "?")
        out.append(f"    dd {ptr.get(mid, 0)}  ; 0x{mid:02X} {name}")
    out.append("")
    out.extend(chunks)
    out.append("")
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT} ({len(ptr)} maps, {total} cells)")


if __name__ == "__main__":
    main()
