#!/usr/bin/env python3
"""gen_hidden_item_coords.py — generate dos_port/assets/hidden_item_coords.inc.

Emits the Gen-1 Yellow HiddenItemCoords table (overworld-events plan, Stage 3
bullet 2 — the data interface the items plan's itemfinder consumes).

pret keeps this table in data/events/hidden_item_coords.asm, where the
`hidden_item` macro is `db \\1, \\3, \\2` — i.e. it SWAPS the source x,y args and
stores each 3-byte row as `db map_id, y, x`. HiddenItemNear
(src/engine/items/itemfinder.asm, pret engine/items/itemfinder.asm) scans it with
IsInRestOfArray stride 3, matching `wCurMap`, then reads d=[hl] (y), e=[hl+1] (x).
So this generator preserves the stored byte order map_id, y, x exactly.

The table is a FLAT program-.data array (IsInRestOfArray does a flat [ESI] read),
`db -1` terminated. Map consts are resolved to numeric ids here (reusing
gen_hidden_events.parse_map_ids) because the port's includes do not define the
pret map constant set.

Run from repo root (or dos_port/); paths resolve relative to the repo root.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_hidden_events as ghe  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "dos_port" / "assets"
SRC = ROOT / "data/events/hidden_item_coords.asm"


def parse_coords():
    """Return [(map_name, y, x), ...] in source (= flag-bit) order.

    Source line: `hidden_item MAP, x, y` (comment says "map id, x, y"); the pret
    macro stores map, y, x — we keep the source args labelled x,y and emit in the
    stored map,y,x order below.
    """
    rows = []
    for line in SRC.read_text().splitlines():
        m = re.match(r"\s*hidden_item\s+(\w+)\s*,\s*(\d+)\s*,\s*(\d+)", line)
        if m:
            name, x, y = m.group(1), int(m.group(2)), int(m.group(3))
            rows.append((name, y, x))
    return rows


def main():
    map_ids = ghe.parse_map_ids()
    rows = parse_coords()

    unknown = [n for (n, _y, _x) in rows if n not in map_ids]
    if unknown:
        sys.exit(f"gen_hidden_item_coords: unknown maps: {sorted(set(unknown))}")

    out = []
    out.append("; AUTO-GENERATED by tools/gen_hidden_item_coords.py — do not edit.")
    out.append("; Gen-1 Yellow HiddenItemCoords table (overworld-events plan, Stage 3).")
    out.append("; Source: data/events/hidden_item_coords.asm (read-only pret spec).")
    out.append(";")
    out.append("; Row = db map_id, y, x  (3-byte stride; pret's `hidden_item` macro swaps")
    out.append(";       the source x,y args to store map,y,x). `db -1` terminates.")
    out.append("; HiddenItemNear (itemfinder.asm) scans it with IsInRestOfArray stride 3.")
    out.append("")
    out.append("global HiddenItemCoords")
    out.append("HiddenItemCoords:")
    for (name, y, x) in rows:
        out.append(f"    db 0x{map_ids[name]:02X}, {y:>3}, {x:>3}   ; {name}")
    out.append("    db 0xFF                         ; -1 end")
    out.append("")

    dst = ASSETS / "hidden_item_coords.inc"
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(out) + "\n")
    print(f"wrote {dst} (HiddenItemCoords {len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
