#!/usr/bin/env python3
"""gen_growth_rates.py — generate dos_port/assets/growth_rates.inc from pret.

Emits the GrowthRateTable consumed by CalcExperience (experience.asm). The
table was previously hand-translated, but dos_port/assets/ is gitignored, so a
fresh checkout had no way to (re)create it. Generating it from the pret source
(data/growth_rates.asm) keeps it reproducible and matches the project rule that
static data is generated, never hand-authored.

Each GROWTH_* entry expands the rgbds `growth_rate` macro:
  growth_rate num, den, c2, c1, c0   ; num/den*n^3 + c2*n^2 + c1*n - c0
    byte0 = dn num, den            -> (num << 4) | den
    byte1 = c2, or (-c2) | $80 if c2 < 0  (signed magnitude)
    byte2 = c1
    byte3 = c0

Run from repo root or dos_port/; paths resolve relative to the repo root.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]          # repo root
ASSETS = ROOT / "dos_port" / "assets"
SRC = ROOT / "data" / "growth_rates.asm"


def main() -> int:
    rows = []
    for line in SRC.read_text().splitlines():
        s = line.split(";", 1)[0].strip()
        m = re.match(r"growth_rate\s+(.+)$", s)
        if not m:
            continue
        nums = [int(t.strip(), 0) for t in m.group(1).split(",")]
        if len(nums) != 5:
            print(f"bad growth_rate line: {line!r}", file=sys.stderr)
            return 1
        num, den, c2, c1, c0 = nums
        b0 = ((num & 0xF) << 4) | (den & 0xF)
        b1 = ((-c2) | 0x80) if c2 < 0 else c2
        rows.append((b0 & 0xFF, b1 & 0xFF, c1 & 0xFF, c0 & 0xFF))

    if len(rows) != 6:
        print(f"expected 6 growth rates, got {len(rows)}", file=sys.stderr)
        return 1

    labels = ["Medium Fast", "Slightly Fast", "Slightly Slow",
              "Medium Slow", "Fast", "Slow"]
    out = [
        "; growth_rates.inc — generated by tools/gen_growth_rates.py. DO NOT EDIT BY HAND.",
        "; GrowthRateTable: 6 x 4-byte entries indexed by GROWTH_* (CalcExperience).",
        "; entry: byte0=(num<<4)|den ; byte1=±n^2 coef (sign-magnitude) ; byte2=n ; byte3=const.",
        "",
        "GrowthRateTable:",
    ]
    for (b0, b1, b2, b3), name in zip(rows, labels):
        out.append(
            f"    db 0x{b0:02X}, 0x{b1:02X}, 0x{b2:02X}, 0x{b3:02X}    ; {name}")
    out.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "growth_rates.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} ({len(rows)} growth rates)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
