#!/usr/bin/env python3
"""gen_pickup_text.py — generate dos_port/assets/pickup_text.inc (Tier 1 data).

PickUpItem (the visible item-ball handler, overworld-events Stage 3 bullet 3)
prints one of two messages through the ordinary text engine:

  FoundItemText        -> _FoundItemText        ("<PLAYER> found <ITEM>!") + jingle
  NoMoreRoomForItemText -> _NoMoreRoomForItemText ("No more room for items!")

pret holds these as `text_far`-wrapped labels in engine/events/pick_up_item.asm,
with the bodies in data/text/text_1.asm. `FoundItemText` also carries a
`sound_get_item_1` command. This reuses gen_battle_text.py's charmap/memmap/macro
parser (same TX_RAM / text_far / sound handling) and points it at the pickup
source, emitting each label as a flattened, self-terminating stream plus a
`{ptr, len}` `<Label>_ref` pair (the item layer's PrintText idiom — a cross-object
label is not a link-time immediate, so the pointer is loaded, not `mov`d).

DO NOT EDIT the output by hand — re-run this generator. Run from repo root or
dos_port/.
"""
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "dos_port" / "assets" / "pickup_text.inc"

# pret source holding the wrapper labels we want.
PICKUP_SRC = ["engine/events/pick_up_item.asm"]

# Labels already emitted by the battle/item generators — skip so two .inc files
# do not define the same global twice.
def existing_labels() -> set:
    out = set()
    for name in ("battle_text.inc", "item_text.inc"):
        inc = ROOT / "dos_port" / "assets" / name
        if inc.exists():
            out |= set(re.findall(r"^global (\w+)$", inc.read_text(), re.M))
    return out


def main() -> int:
    charmap = gbt.load_charmap()
    memmap = gbt.load_memmap()
    far_db = gbt.collect_far(charmap, memmap)

    gbt.BATTLE_SRC = PICKUP_SRC          # retarget the wrapper collector
    wrappers = gbt.collect_wrappers(charmap, memmap, far_db)

    skip = existing_labels()
    labels = sorted(k for k in wrappers if k not in skip)

    want = {"FoundItemText", "NoMoreRoomForItemText"}
    missing = want - set(labels)
    if missing:
        raise SystemExit(f"gen_pickup_text: expected labels missing from scan: {sorted(missing)}")

    out = [
        "; pickup_text.inc — generated by tools/gen_pickup_text.py. DO NOT EDIT BY HAND.",
        "; PickUpItem message streams (pret engine/events/pick_up_item.asm wrappers),",
        f"; text_far flattened. {len(labels)} labels. section .data (see link.ld).",
        "",
        "section .data",
        "",
    ]
    for label in labels:
        b = wrappers[label]
        out.append(f"global {label}")
        out.append(f"{label}:")
        for i in range(0, len(b), 16):
            out.append("    db " + ", ".join(f"0x{x:02X}" for x in b[i:i + 16]))
        out.append(f"global {label}_ref")
        out.append(f"{label}_ref: dd {label}, {len(b)}   ; flat ptr + byte count")
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({len(labels)} labels: {', '.join(labels)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
