#!/usr/bin/env bash
# Launch the MCP-patched DOSBox-X with PKMN.EXE + start the MCP server.
#
# Usage:
#   tools/run_with_mcp.sh
#
# Steps:
#   1. This script does NOT build. Build PKMN.EXE yourself first (e.g.
#      `make -C dos_port SKIP_TITLE=1`); this script launches whatever binary
#      is already there. It also takes no make flags -- the "[extra make flags]"
#      usage line and the "1. Build PKMN.EXE" step documented here until
#      2026-08-02 described behaviour this script has never had.
#   2. Write the launch handshake (/tmp/dosbox-mcp.launch) recording WHICH
#      build is being launched, so the long-lived MCP server resolves symbols
#      against this checkout instead of the one it was started in.
#   3. Launch tools/dosbox-x-mcp/dosbox-x with a dosbox-x.conf that enables
#      the heavy debugger and the MCP socket.
#   4. Print instructions to connect Claude Code.
#
# The MCP server (tools/dosbox_mcp/server.py) is registered via
# .claude/settings.json and started automatically by Claude Code.
# You don't need to start it manually.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DOSPORT="$(cd "$SCRIPT_DIR/.." && pwd)"
# dosbox-x-mcp: the Happyarch/dosbox-x fork (submodule tools/dosbox-x, branch
# mcp-debug), deliberately named so it never collides with the system dosbox-x.
BINARY="${SCRIPT_DIR}/dosbox-x-mcp/dosbox-x-mcp"
SOCK_PATH="/tmp/dosbox-mcp.sock"
LAUNCH_FILE="${DOSBOX_MCP_LAUNCH:-/tmp/dosbox-mcp.launch}"

if [ ! -x "$BINARY" ]; then
    echo "ERROR: patched binary not found at $BINARY"
    echo "Run: dos_port/tools/build_dosbox_mcp.sh"
    exit 1
fi

# Write a temporary dosbox-x.conf with MCP socket enabled.
# We use the user's existing dosbox-x conf as a base and override [log] section.
CONF="/tmp/dosbox-mcp-$$.conf"
CAPTURE_DIR="${DOSBOX_MCP_CAPTURE_DIR:-/tmp/dosbox-mcp-capture}"
mkdir -p "$CAPTURE_DIR"
cat > "$CONF" <<EOF
# Auto-generated by run_with_mcp.sh — do not edit
# Mirrors dos_port/dosbox-x.conf (the tracked test config); without these the
# generated conf fell back to DOSBox-X defaults (~3000 cycles → far too slow).
[dosbox]
machine=vgaonly
# Where the debugger's SCREENSHOT command drops its PNGs. Pinned explicitly:
# the default ("capture") is relative to the emulator's CWD, i.e. it would
# litter dos_port/ with an untracked capture/ directory. The MCP screenshot()
# tool copies the file to its own output path anyway, so this is scratch.
captures=${CAPTURE_DIR}
# No quit-confirmation dialog while a guest program runs — unattended agent
# sessions must be able to close DOSBox-X promptlessly (CheckQuit() returns
# true when this is false).
quit warning=false

[video]
# Required: VGA writes are broken when this optimization is on (see CLAUDE.md).
memory io optimization 1 = false

[cpu]
cputype=386_prefetch
core=normal
# 386SX @ ~20 MHz baseline (matches dos_port/dosbox-x.conf).
cycles=fixed 23880
cycleup=500
cycledown=500

[log]
# MCP debug socket — lets Claude Code drive the debugger live
mcp_socket=${SOCK_PATH}

[autoexec]
mount c "${DOSPORT}"
c:
PKMN.EXE
EOF

# Launch handshake — tells the MCP server WHICH BUILD it is now debugging.
# The server (tools/dosbox_mcp/server.py) is long-lived and started by Claude
# Code from whatever checkout it was registered in; without this it resolved
# pkmn.sym from ITS OWN directory, so a worktree build got main-checkout
# addresses (right symbol name, plausible address, breakpoint never fires).
# This script is the only party that knows the answer, so it records it here.
# Written atomically (temp + mv) because the server re-reads it on mtime
# change and must never see a half-written path.
cat > "${LAUNCH_FILE}.$$" <<EOF
# Written by run_with_mcp.sh — the build the emulator is currently running.
# Consumed by tools/dosbox_mcp/server.py (KEY=VALUE, DOSPORT is load-bearing).
DOSPORT=${DOSPORT}
REPO=${REPO_ROOT}
SOCKET=${SOCK_PATH}
LAUNCH_PID=$$
EOF
mv -f "${LAUNCH_FILE}.$$" "${LAUNCH_FILE}"

echo ""
echo "Starting MCP-patched DOSBox-X..."
echo "  Socket:  ${SOCK_PATH}"
echo "  Build:   ${DOSPORT}  (recorded in ${LAUNCH_FILE})"
echo "  Binary:  ${BINARY}"
echo "  PKMN.EXE boots and free-runs; pause it from MCP to set breakpoints."
echo ""
echo "From Claude Code: pause_exec() once in-game, then set_breakpoint('OverworldLoop'),"
echo "  continue_exec(), gb_read(), dump_frame() etc."
echo ""

# No -break-start: breakpoints need the game's runtime CS/DS selectors, which
# only exist once PKMN.EXE is loaded — the MCP flow is pause_exec() →
# set_breakpoint() → continue_exec().  (At BIOS entry there is nothing to
# target, and a paused emulator can't service the socket BREAK request.)
# The socket is started from DEBUG_Init so it is ready as soon as DOSBox-X opens.
# cd: the debugger writes MEMDUMP.BIN to its CWD; keep that next to PKMN.EXE
# where the MCP server (DOSBOX_MCP_DIR) expects it.
cd "$DOSPORT"
exec "$BINARY" \
    -defaultdir "$DOSPORT" \
    -conf "$CONF"
