; marts.asm — port-only carrier for the generated Poke Mart inventory text
; scripts (pret data/items/marts.asm).
;
; %includes assets/marts.inc (Tier-1 data generated by
; tools/generators/gen_marts.py from pret data/items/marts.asm +
; macros/scripts/text.asm's `script_mart` macro). Each of the 16 labels below
; is a TX_SCRIPT_MART (0xFE) text-command stream — db TX_SCRIPT_MART,
; db <item count>, db <item id>..., db -1 — run by a mart clerk's dialog text
; and dispatched at runtime by TX_SCRIPT_MART handling in
; src/home/text_script.asm. Two labels (UnusedBikeShopClerkText,
; UnusedMartClerkText) are marked `; unreferenced` in pret itself; they are
; carried here verbatim per the project's "Preserve pret Labels" rule even
; though nothing in the port calls them.
;
; Model: src/data/map_script_tables.asm — a thin .data carrier for a generated
; .inc. Per the linker rule (docs/assembly.md / link.ld orphan-section trap)
; embedded data lives in .data. This file opens .data and declares every
; `global`; the .inc does NOT self-open a section and does NOT `global`
; anything (map_script_tables.inc / map_script_tables.asm pattern).
;
; Build: nasm -f coff -I include/ -I . -o marts.o marts.asm

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "assets/script_constants.inc"

global ViridianMartClerkText
global PewterMartClerkText
global CeruleanMartClerkText
global UnusedBikeShopClerkText
global VermilionMartClerkText
global LavenderMartClerkText
global CeladonMart2FClerk1Text
global CeladonMart2FClerk2Text
global CeladonMart4FClerkText
global CeladonMart5FClerk1Text
global CeladonMart5FClerk2Text
global FuchsiaMartClerkText
global UnusedMartClerkText
global CinnabarMartClerkText
global SaffronMartClerkText
global IndigoPlateauLobbyClerkText

section .data

%include "assets/marts.inc"
