; tm_prices.asm — TM prices in thousands, two nybbles per byte (GetMachinePrice).
;
; pret ref: data/items/tm_prices.asm:TechnicalMachinePrices
;
; Generated by tools/generators/gen_items.py into assets/tm_prices.inc. This carrier sits at the
; mirrored path dos_port/src/data/items/tm_prices.asm; it was part of src/data/item_data.asm until 2026-08-16
; (docs/current_plan_data_path_mirror.md).
;
; Embedded data goes in .data per the linker rule in docs/assembly.md (.rodata has
; no output-section rule and reads back as zero).
bits 32

global TechnicalMachinePrices

section .data

%include "assets/tm_prices.inc"
