---@diagnostic disable: undefined-global -- mGBA Lua runtime globals
-- route17_trainer_battle -- ROUTE_17 / ForceBikeDown witness (map-script
-- fidelity plan, third attempt at wiring ROUTE_17).
--
-- THE FIRST TWO ATTEMPTS both used route17_sight (RunMapScriptSightTest,
-- src/debug/debug_dump.asm): batch 3 (overworld-events Stage 5a) found the
-- divergence (wYCoord $79 vs $78, wTrainerScreenY $0C vs $1C) and correctly
-- diagnosed it as pret's ForceBikeDown -- which auto-scrolls the player one
-- tile south on Cycling Road whenever no button is held -- missing from the
-- port. Batch 4 PORTED ForceBikeDown (faithdiff clean) and re-wired ROUTE_17
-- with the SAME sight scenario, and got the IDENTICAL two divergences, byte for
-- byte. The reason was the HARNESS, not the routine: RunMapScriptSightTest is
-- UpdateSprites -> RunMapScript -> DelayFrame and deliberately never enters
-- OverworldLoopLessDelay, where ForceBikeDown lives -- no sight golden can ever
-- witness it (regression-overworld-forcebikedown-missing).
--
-- THIS SCENARIO drives the port's REAL OverworldLoop instead, the same shape
-- trainer_battle_route.lua uses for Route 3 (battle plan Stage 1b): warp onto
-- Route 17 standing in ROUTE17_BIKER10's line of sight, let the map script
-- engage on its own, and stop as soon as the trainer battle is CONFIRMED
-- STARTED. "Engage a trainer" is the acceptance bar this scenario exists to
-- clear -- it deliberately does NOT fight the battle out (trainer_battle_route
-- already proves the live menu/turn-loop/return choreography end to end on
-- Route 3; re-deriving a lethal move for a different roster buys nothing here).
--
-- ROUTE17_BIKER10 (data/maps/objects/Route17.asm) stands at (x=10, y=118)
-- facing DOWN with view range 4 (scripts/Route17.asm Route17TrainerHeader9),
-- so the player is seeded at (x=10, y=120) -- exactly the tile BOTH earlier
-- attempts measured. Chosen deliberately for magnitude too: Route 17 is the
-- game's tallest map (10 x 72 blocks), so the view-pointer term
-- (width + 6) * (y >> 1) reaches 960 here, still the largest of any wired map.
--
-- COMPARED SURFACE: choreography only, joined by NAME with the port's
-- DEBUG_TRAINER_ROUTE17 gbregion list (src/debug/debug_dump.asm). No damage/HP
-- (the battle is not fought), no reward bytes (nothing has been won yet). The
-- direct ForceBikeDown witness is wPlayerMapPos's wYCoord: ground truth drifts
-- the player south while waiting for TrainerEngage's approach sequence, and the
-- measured value here (Y=$79) is exactly the byte that diverged in both earlier
-- attempts.

local here = debug.getinfo(1, "S").source:match("^@(.*)$")
local root = here and here:match("^(.*)[/\\]scenarios[/\\][^/\\]+$") or "."
package.path = root .. "/?.lua;" .. package.path

local symbols = require("lib.symbols")
local gbtext = require("lib.gbtext")
local input = require("lib.input")
local dump = require("lib.dump")
local scenario = require("lib.scenario")
local navigate = require("lib.navigate")
local seed = require("lib.seed")

local sym = symbols.load()
local text = gbtext.load()
navigate.init(sym, text)

local REDS_HOUSE_1F, PALLET_TOWN, ROUTE_17 = 37, 0, 0x1C
local ROUTE_17_WIDTH, SIGHT_Y, SIGHT_X = 10, 120, 10
local BIT_WARP_FROM_CUR_SCRIPT = 3
-- EVENT_BEAT_ROUTE_17_TRAINER_9 = event index 1242 (assets/event_constants.inc,
-- generated by tools/generators/gen_event_constants.py from pret's
-- constants/event_constants.asm const/const_skip stream) -> byte
-- W_EVENT_FLAGS(0xD746) + 1242/8 = 0xD7E1, bit 1242%8 = 2. Verified against the
-- same macros/scripts/events.asm CheckEvent formula that gives Route 3 trainer 0
-- 0xD7C2 bit 2 (trainer_battle_route.lua's ROUTE3_EVENT_BYTE).
local ROUTE17_EVENT_BYTE = 0xD7E1
local ROUTE17_EVENT_MASK = 1 << 2
local ROUTE17_CUR_SCRIPT = 0xD61B  -- wRoute17CurScript (ram/wram.asm walk, cross-
                                    -- checked against wRoute3CurScript = 0xD5F7)

-- Mirrors the port's DEBUG_TRAINER_ROUTE17 gbregion list, joined by NAME.
local function regions()
	local out = dump.standard_regions(sym)
	local function one(name, label, size)
		out[#out + 1] = { name = name, addr = sym:addr(label), size = size }
	end
	local function raw(name, addr, size)
		out[#out + 1] = { name = name, addr = addr, size = size }
	end
	one("wPlayerMapPos",  "wCurMap", 5)
	one("wIsInBattle",    "wIsInBattle", 1)
	one("wCurOpponent",   "wCurOpponent", 1)
	one("wEnemyMonSpc",   "wEnemyMonSpecies", 1)
	one("wCurMapScript",  "wCurMapScript", 1)
	raw("wRoute17Script", ROUTE17_CUR_SCRIPT, 1)
	raw("wRoute17Event",  ROUTE17_EVENT_BYTE, 1)
	one("wStatusFlags3",  "wStatusFlags3", 1)
	one("wStatusFlags4",  "wStatusFlags4", 1)
	one("wStatusFlags7",  "wStatusFlags7", 1)
	return out
end

-- Same entry technique as trainer_battle_route.lua: a real new game walked out
-- of Red's house, then a scripted warp onto Route 17 standing in the biker's
-- sight line. The warp is how both sides reach an identical starting state
-- without depending on a long cross-map walk (Route 17 is far from Pallet
-- Town) staying deterministic.
local function enter_route17()
	navigate.boot_to_main_menu()
	navigate.new_game_to_bedroom()
	navigate.walk("RIGHT", 1)
	navigate.walk("UP", 5)
	navigate.walk_until_map("RIGHT", REDS_HOUSE_1F)
	navigate.walk("DOWN", 6)
	navigate.walk("LEFT", 4)
	navigate.walk_until_map("DOWN", PALLET_TOWN)
	navigate.walk("DOWN", 1)
	scenario.wait(60)

	scenario.exec(function()
		seed.debug_new_game(sym, text:encode(seed.PLAYER_NAME))
		local view = sym:addr("wOverworldMap") + 7 + ROUTE_17_WIDTH
			+ (ROUTE_17_WIDTH + 6) * (SIGHT_Y >> 1) + (SIGHT_X >> 1)
		local ptr = sym:addr("wCurrentTileBlockMapViewPointer")
		emu:write8(ptr, view & 0xFF)
		emu:write8(ptr + 1, (view >> 8) & 0xFF)
		emu:write8(sym:addr("wYCoord"), SIGHT_Y)
		emu:write8(sym:addr("wXCoord"), SIGHT_X)
		emu:write8(sym:addr("wDestinationWarpID"), 0xFF)
		emu:write8(sym:addr("hWarpDestinationMap"), ROUTE_17)
		local flags = sym:addr("wStatusFlags3")
		emu:write8(flags, emu:read8(flags) | (1 << BIT_WARP_FROM_CUR_SCRIPT))
		-- Arm the trainer exactly as the port's RunTrainerRoute17TestSeed does:
		-- beaten bit clear, map script at its DEFAULT handler.
		emu:write8(ROUTE17_EVENT_BYTE, emu:read8(ROUTE17_EVENT_BYTE) & ~ROUTE17_EVENT_MASK)
		emu:write8(ROUTE17_CUR_SCRIPT, 0)
		emu:write8(sym:addr("wCurMapScript"), 0)
	end)

	local deadline = scenario.frame() + 900
	while navigate.read8("wCurMap") ~= ROUTE_17 do
		assert(scenario.frame() < deadline, "route17_trainer_battle: Route 17 warp never fired")
		scenario.wait(1)
	end
end

scenario.run(function()
	enter_route17()

	-- The map script engages on its own from here, driven by ForceBikeDown's
	-- forced southward drift; we only answer whatever pre-battle text appears
	-- (the biker's approach line). Nothing here selects a target or forces a
	-- move -- this scenario stops at engagement, it does not fight the battle.
	local function trace(tag)
		scenario.log(string.format(
			"route17_trainer_battle[%s] f=%d map=%d y=%d x=%d inBattle=%d opp=%d "
			.. "enemySpc=%d curScript=%d r17Script=%d event=%02x",
			tag, scenario.frame(), navigate.read8("wCurMap"),
			navigate.read8("wYCoord"), navigate.read8("wXCoord"),
			navigate.read8("wIsInBattle"), navigate.read8("wCurOpponent"),
			navigate.read8("wEnemyMonSpecies"), navigate.read8("wCurMapScript"),
			scenario.read_range(ROUTE17_CUR_SCRIPT, 1):byte(1),
			scenario.read_range(ROUTE17_EVENT_BYTE, 1):byte(1)))
	end
	trace("on-route17")

	-- STATE-GATED A, not just sparse (MEASURED 2026-08-15, two frame-scheduled
	-- cadences tried first and both left the two sides disagreeing on
	-- wStatusFlags7 -- see the port's matching comment on AUTOKEY_TRAINER_ROUTE17
	-- in src/debug/debug_dump.asm for the full trace). The root cause: pret's
	-- per-frame NPC-dialog dispatch (src/engine/overworld/map_sprites.asm TALK
	-- sentinel on the port; the golden runs the real ROM path) calls
	-- home/trainers.asm TalkToTrainer for ANY A press that lands while the player
	-- faces an adjacent trainer sprite -- not just a deliberate "talk" -- and
	-- TalkToTrainer sets wStatusFlags7 BIT_USE_CUR_MAP_SCRIPT unconditionally,
	-- before it checks whether the trainer is already sight-engaged (it only
	-- skips the ENGAGE call itself, via wMiscFlags BIT_SEEN_BY_TRAINER). During
	-- TrainerWalkUpToPlayer's approach (wStatusFlags5 BIT_SCRIPTED_NPC_MOVEMENT
	-- set) an A press on exactly the wrong frame fires it; no fixed frame
	-- schedule can safely dodge a window whose length depends on how far the
	-- trainer has to walk. DisplayEnemyTrainerTextAndStartBattle will not print
	-- (and so needs no A to dismiss) until that bit clears, so withholding A for
	-- its whole duration costs nothing.
	local BIT_SCRIPTED_NPC_MOVEMENT = 1 << 0
	local function trainer_still_walking()
		return (navigate.read8("wStatusFlags5") & BIT_SCRIPTED_NPC_MOVEMENT) ~= 0
	end
	local deadline = scenario.frame() + 7200
	local next_press = scenario.frame() + 60
	while navigate.read8("wIsInBattle") ~= 2 or navigate.read8("wEnemyMonSpecies") == 0 do
		if scenario.frame() % 600 < 12 then trace("await-battle") end
		assert(scenario.frame() < deadline, "route17_trainer_battle: trainer battle never started")
		if scenario.frame() >= next_press and not trainer_still_walking() then
			input.press_for("A", 8)
			next_press = scenario.frame() + 82  -- 90-frame period (8 held + 82 idle)
		else
			scenario.wait(1)
		end
	end
	trace("battle-started")

	-- Let the intro slide settle before the dump so both sides compare a
	-- resting state rather than one mid-animation -- same reasoning as the
	-- port's AUTOKEY_R17_DUMP_DELAY.
	scenario.wait(60)

	scenario.exec(function()
		assert(emu:read8(sym:addr("wIsInBattle")) == 2,
			"route17_trainer_battle: not a trainer battle at dump time")
		dump.write("route17_trainer_battle", regions(), {
			frame = scenario.frame(),
			description = "Route 17 / ForceBikeDown witness: map-script sight " ..
				"engagement, battle entry through the REAL overworld loop with " ..
				"ForceBikeDown's forced southward drift, stopped at battle start",
		})
	end)
end)
