; ===========================================================================
; cinnabar_lab.asm — faithful port of pret engine/events/cinnabar_lab.asm
; (Pokemon Yellow)
;
; Implements GiveFossilToCinnabarLab (the fossil-choice menu that lets the
; player hand over a Dome/Helix Fossil), its helper PrintFossilsInBag (prints
; each fossil in the bag on its own line of that menu), and
; LoadFossilItemAndMonName (loads the resulting mon name + item name into
; wNameBuffer/wStringBuffer for the "Oh! That is a KABUTO fossil!" text).
;
; Register map (SM83 -> x86): A=AL, HL=ESI, BC=BX (B=BH, C=BL), DE=EDX (D=DH, E=DL);
; EBP = GB base. GB memory is [ebp + addr].
;
; UI PROJECTION (docs/ui_projection.md):
;   overworld-ui (fossil list box): GB(0,0) 15x(dynamic) --(anchor=top-LEFT, X+0, Y+0)--> wx=7 wy=0 clip=120 max_y=8*(3+2*(N-1))
;   (N = wFilteredBagItemsCount; the box grows by 2 rows per extra fossil, same
;   as pret's own AddNTimes-computed height)
;
; Build: nasm -f coff -I include/ -I . -o cinnabar_lab.o src/engine/events/cinnabar_lab.asm
; ===========================================================================

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "coords.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"

section .text

global GiveFossilToCinnabarLab
global PrintFossilsInBag
global LoadFossilItemAndMonName

; --- External routines ---
extern AddNTimes                        ; src/home/array.asm
extern TextBoxBorder                    ; src/home/text.asm
extern UpdateSprites                    ; src/home/update_sprites.asm
extern HandleMenuInput                  ; src/home/window.asm
extern PrintText                        ; src/home/window.asm
extern YesNoChoice                      ; src/home/yes_no.asm
extern RemoveItemByID                   ; src/engine/menus/pc.asm
extern GetItemName                      ; src/home/names.asm
extern GetMonName                       ; src/home/names.asm
extern CopyToStringBuffer               ; src/home/copy_string.asm
extern PlaceString                      ; src/home/text.asm

; Far text streams this file uses — pret text/CinnabarLabFossilRoom.asm, generated by
; tools/generators/gen_map_text.py (event_<stem>.inc namespace, so this file's
; "cinnabar_lab" stem never collides with src/scripts/cinnabar_lab.asm's own
; assets/map_text/cinnabar_lab.inc).
section .data
%include "assets/map_text/event_cinnabar_lab.inc"

section .text

; ---------------------------------------------------------------------------
; GiveFossilToCinnabarLab — pret ref: engine/events/cinnabar_lab.asm:1-72.
; In: wFilteredBagItems/wFilteredBagItemsCount already populated by the caller
;     (Lab4Script_GetFossilsInBag, scripts/cinnabar_lab_fossil_room.asm).
; ---------------------------------------------------------------------------
GiveFossilToCinnabarLab:
    or byte [ebp + wStatusFlags5], (1 << BIT_NO_TEXT_DELAY) ; ld hl, wStatusFlags5 / set BIT_NO_TEXT_DELAY, [hl]
    xor al, al                                    ; xor a
    mov [ebp + wCurrentMenuItem], al              ; ld [wCurrentMenuItem], a
    mov byte [ebp + wMenuWatchedKeys], PAD_A | PAD_B ; ld a, PAD_A | PAD_B / ld [wMenuWatchedKeys], a
    mov al, [ebp + wFilteredBagItemsCount]        ; ld a, [wFilteredBagItemsCount]
    dec al                                        ; dec a
    mov [ebp + wMaxMenuItem], al                  ; ld [wMaxMenuItem], a
    mov byte [ebp + wTopMenuItemY], 2             ; ld a, 2 / ld [wTopMenuItemY], a
    mov byte [ebp + wTopMenuItemX], 1             ; ld a, 1 / ld [wTopMenuItemX], a

    mov al, [ebp + wFilteredBagItemsCount]        ; ld a, [wFilteredBagItemsCount]
    dec al                                        ; dec a
    mov bx, 2                                     ; ld bc, 2
    mov esi, 3                                    ; ld hl, 3 — a plain scratch counter, NOT a coordinate
    call AddNTimes                                ; call AddNTimes — esi = 3 + 2*(count-1)
    mov eax, esi                                  ; dec l — ESI has no 8-bit sub-register in 32-bit mode,
    dec al                                        ;   so truncate through AL (reproduces pret's 8-bit wrap)
    mov bh, al                                    ; ld b, l
    mov bl, 0x0d                                  ; ld c, $d
    ; PROJ overworld-ui (fossil list box): GB(0,0) 15x(dynamic) --(anchor=top-LEFT, X+0, Y+0)--> wx=7 wy=0 clip=120 max_y=8*(3+2*(N-1))
    hlcoord 0, 0                                  ; hlcoord 0, 0
    call TextBoxBorder                            ; call TextBoxBorder
    call UpdateSprites                            ; call UpdateSprites
    call PrintFossilsInBag                        ; call PrintFossilsInBag
    and byte [ebp + wStatusFlags5], ~(1 << BIT_NO_TEXT_DELAY) & 0xFF ; ld hl, wStatusFlags5 / res BIT_NO_TEXT_DELAY, [hl]
    call HandleMenuInput                          ; call HandleMenuInput
    test al, PAD_B                                ; bit B_PAD_B, a
    jnz .cancelledGivingFossil                    ; jr nz, .cancelledGivingFossil

    movzx edx, byte [ebp + wCurrentMenuItem]      ; ld a, [wCurrentMenuItem] / ld d, 0 / ld e, a
    lea esi, [wFilteredBagItems + edx]            ; ld hl, wFilteredBagItems / add hl, de
    mov al, [ebp + esi]                           ; ld a, [hl]
    mov [ebp + hItemToRemoveID], al               ; ldh [hItemToRemoveID], a
    cmp al, DOME_FOSSIL                           ; cp DOME_FOSSIL
    jz .choseDomeFossil                           ; jr z, .choseDomeFossil
    cmp al, HELIX_FOSSIL                          ; cp HELIX_FOSSIL
    jz .choseHelixFossil                          ; jr z, .choseHelixFossil
    mov bh, AERODACTYL                            ; ld b, AERODACTYL
    jmp .fossilSelected                           ; jr .fossilSelected
.choseHelixFossil:
    mov bh, OMANYTE                               ; ld b, OMANYTE
    jmp .fossilSelected                           ; jr .fossilSelected
.choseDomeFossil:
    mov bh, KABUTO                                ; ld b, KABUTO
.fossilSelected:
    mov [ebp + wFossilItem], al                   ; ld [wFossilItem], a
    mov al, bh                                    ; ld a, b
    mov [ebp + wFossilMon], al                    ; ld [wFossilMon], a
    call LoadFossilItemAndMonName                 ; call LoadFossilItemAndMonName
    mov esi, .ScientistSeesFossilText             ; ld hl, .ScientistSeesFossilText
    call PrintText                                ; call PrintText
    call YesNoChoice                              ; call YesNoChoice
    mov al, [ebp + wCurrentMenuItem]              ; ld a, [wCurrentMenuItem]
    test al, al                                   ; and a
    jnz .cancelledGivingFossil                    ; jr nz, .cancelledGivingFossil
    mov esi, .ScientistTakesFossilText            ; ld hl, .ScientistTakesFossilText
    call PrintText                                ; call PrintText
    mov al, [ebp + wFossilItem]                   ; ld a, [wFossilItem]
    mov [ebp + hItemToRemoveID], al               ; ldh [hItemToRemoveID], a
; DEVIATION{class=banking; pret=engine/events/cinnabar_lab.asm:GiveFossilToCinnabarLab; behavior=call RemoveItemByID directly instead of the pret farcall; evidence=the DPMI model is flat so every routine is always addressable and Bankswitch has no port counterpart, same convention every other farcall/farjp site in this tree uses; lifetime=permanent flat-memory boundary}
    call RemoveItemByID                           ; farcall RemoveItemByID
    mov esi, .GoForAWalkText                      ; ld hl, .GoForAWalkText
    call PrintText                                ; call PrintText
    SetEvents EVENT_GAVE_FOSSIL_TO_LAB, EVENT_LAB_STILL_REVIVING_FOSSIL
    ret
.cancelledGivingFossil:
    mov esi, .ComeAgainText                       ; ld hl, .ComeAgainText
    call PrintText                                ; call PrintText
    ret

; ---------------------------------------------------------------------------
; Text wrappers — pret engine/events/cinnabar_lab.asm:74-91.
; Local labels: the four streams are generated into
; assets/map_text/event_cinnabar_lab.inc (tools/generators/gen_map_text.py).
; ---------------------------------------------------------------------------
.ScientistSeesFossilText:
    text_far _CinnabarLabFossilRoomScientist1SeesFossilText
    text_end

.ScientistTakesFossilText:
    text_far _CinnabarLabFossilRoomScientist1TakesFossilText
    text_end

.GoForAWalkText:
    text_far _CinnabarLabFossilRoomScientist1GoForAWalkText2
    text_end

.ComeAgainText:
    text_far _CinnabarLabFossilRoomScientist1ComeAgainText
    text_end

; ---------------------------------------------------------------------------
; PrintFossilsInBag — pret ref: engine/events/cinnabar_lab.asm:94-113.
; Prints each fossil in the player's bag on a separate line of the menu.
; ---------------------------------------------------------------------------
PrintFossilsInBag:
    mov esi, wFilteredBagItems                   ; ld hl, wFilteredBagItems
    xor al, al                                    ; xor a
    mov [ebp + hItemCounter], al                  ; ldh [hItemCounter], a
.loop:
    mov al, [ebp + esi]                           ; ld a, [hli]
    lea esi, [esi + 1]
    cmp al, 0xff                                  ; cp $ff
    jnz .continue                                 ; ret z (inverted)
    ret
.continue:
    push esi                                      ; push hl
    mov [ebp + wNamedObjectIndex], al             ; ld [wNamedObjectIndex], a
    call GetItemName                              ; call GetItemName
    ; PROJ overworld-ui (fossil list box entries): GB(2,2) --(anchor=top-LEFT, X+0, Y+0)--> unchanged
    hlcoord 2, 2                                  ; hlcoord 2, 2
    movzx eax, byte [ebp + hItemCounter]          ; ldh a, [hItemCounter]
    mov bx, SCREEN_WIDTH * 2                      ; ld bc, SCREEN_WIDTH * 2
    call AddNTimes                                ; call AddNTimes
    lea eax, [ebp + wNameBuffer]                  ; ld de, wNameBuffer — PlaceString takes a flat ptr in EAX
    call PlaceString                              ; call PlaceString
    inc byte [ebp + hItemCounter]                 ; ld hl, hItemCounter / inc [hl]
    pop esi                                       ; pop hl
    jmp .loop                                     ; jr .loop

; ---------------------------------------------------------------------------
; LoadFossilItemAndMonName — pret ref: engine/events/cinnabar_lab.asm:115-123.
; Loads the names of the fossil item and the resulting mon.
; Out: wNameBuffer = mon name, wStringBuffer = mon name copy, wNameBuffer = item name
;      (matches pret: GetMonName+CopyToStringBuffer save the mon name into
;      wStringBuffer, then GetItemName overwrites wNameBuffer with the item name).
; ---------------------------------------------------------------------------
LoadFossilItemAndMonName:
    mov al, [ebp + wFossilMon]                    ; ld a, [wFossilMon]
    mov [ebp + wNamedObjectIndex], al             ; ld [wNamedObjectIndex], a
    call GetMonName                               ; call GetMonName
    ; Not a divergence from pret (output is identical either way): GetMonName
    ; (src/home/names.asm) has no documented EDX-out contract the way
    ; GetItemName/GetPartyMonName do (both state EDX=wNameBuffer on exit), so
    ; the port sets EDX explicitly here rather than relying on an incidental
    ; register value — matching the explicit-EDX pattern list_menu.asm already
    ; uses at its own GetXName / CopyToStringBuffer call site.
    mov edx, wNameBuffer                          ; ld de, wNameBuffer
    call CopyToStringBuffer                       ; call CopyToStringBuffer
    mov al, [ebp + wFossilItem]                   ; ld a, [wFossilItem]
    mov [ebp + wNamedObjectIndex], al             ; ld [wNamedObjectIndex], a
    call GetItemName                              ; call GetItemName
    ret
