; ===========================================================================
; cinnabar_lab.asm — faithful port of pret engine/events/cinnabar_lab.asm
; (Pokemon Yellow)
;
; Implements GiveFossilToCinnabarLab (the fossil-choice menu that lets the
; player hand over a Dome/Helix Fossil), its helper PrintFossilsInBag (prints
; each fossil in the bag on its own line of that menu), and
; LoadFossilItemAndMonName (loads the resulting mon name + item name into
; wNameBuffer/wStringBuffer for the "Oh! That is a KABUTO fossil!" text).
;
; Register map (SM83 -> x86): A=AL, HL=ESI, BC=BX (B=BH, C=BL), DE=EDX (D=DH, E=DL);
; EBP = GB base. GB memory is [ebp + addr].
;
; UI PROJECTION (docs/ui_projection.md):
;   overworld-ui (fossil list box): GB(0,0) 15x(dynamic) --(anchor=top-LEFT, X+0, Y+0)--> wx=7 wy=0 clip=120 max_y=8*(4+2*(N-1))
;   (N = wFilteredBagItemsCount; the box grows by 2 rows per extra fossil, same
;   as pret's own AddNTimes-computed height)
;
; Build: nasm -f coff -I include/ -I . -o cinnabar_lab.o src/engine/events/cinnabar_lab.asm
; ===========================================================================

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "coords.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"

section .text

global GiveFossilToCinnabarLab
global PrintFossilsInBag
global LoadFossilItemAndMonName

; --- External routines ---
extern AddNTimes                        ; src/home/array.asm
extern TextBoxBorder                    ; src/home/text.asm
extern UpdateSprites                    ; src/home/update_sprites.asm
extern HandleMenuInput                  ; src/home/window.asm
extern PrintText                        ; src/home/window.asm
extern YesNoChoice                      ; src/home/yes_no.asm
extern RemoveItemByID                   ; src/engine/menus/pc.asm
extern GetItemName                      ; src/home/names.asm
extern GetMonName                       ; src/home/names.asm
extern CopyToStringBuffer               ; src/home/copy_string.asm
extern PlaceString                      ; src/home/text.asm
extern text_row_stride                  ; src/home/text.asm — active wTileMap row stride
extern add_window                       ; src/ppu/ppu.asm — publish a window descriptor
extern g_windows                        ; src/ppu/ppu.asm — window descriptor array
extern g_window_count                   ; src/ppu/ppu.asm — active window-descriptor count
extern menu_redraw_cb                   ; src/home/window.asm — per-frame side-info redraw cb
extern menu_item_step                   ; src/home/window.asm — per-item row step (bytes)
extern g_dialog_preserve_windows        ; src/home/text.asm — 1 = dialog pauses keep windows (mart pattern)

; Port-only presentation (mart class, prize pattern): the fossil list drawn on
; the 40-wide canvas is invisible until mirrored into GB_TILEMAP0 and published
; as a window descriptor (the compositor reads the window source, not wTileMap).
; The list shares no geometry with money (srow 20) or the prize menu (srow 1),
; so it gets a fresh slot; YN (srow 11) opens during the confirm.
FOSSIL_SROW equ 2            ; GB_TILEMAP0 mirror rows 2..9 (list 15xH, H<=8)
FOSSIL_LIST_W equ 15         ; box width in tiles (matches TextBoxBorder bl=13 + borders)
FOSSIL_MENU_WX equ 7         ; left-projected, same anchor as the prize menu
FOSSIL_MENU_WY equ 0
FOSSIL_MENU_CLIP equ 120     ; 15 tiles * 8
FOSSIL_MENU_MAXY equ 64      ; 8 rows * 8 (max height: 3 fossils -> bh+2 rows)

; Far text streams this file uses — pret text/CinnabarLabFossilRoom.asm, generated by
; tools/generators/gen_map_text.py (event_<stem>.inc namespace, so this file's
; "cinnabar_lab" stem never collides with src/scripts/cinnabar_lab.asm's own
; assets/map_text/CinnabarLab.inc).
section .data
%include "assets/map_text/event_cinnabar_lab.inc"

section .text

; ---------------------------------------------------------------------------
; GiveFossilToCinnabarLab — pret ref: engine/events/cinnabar_lab.asm:1-72.
; In: wFilteredBagItems/wFilteredBagItemsCount already populated by the caller
;     (Lab4Script_GetFossilsInBag, scripts/cinnabar_lab_fossil_room.asm).
; ---------------------------------------------------------------------------
GiveFossilToCinnabarLab:
    or byte [ebp + wStatusFlags5], (1 << BIT_NO_TEXT_DELAY) ; ld hl, wStatusFlags5 / set BIT_NO_TEXT_DELAY, [hl]
    xor al, al                                    ; xor a
    mov [ebp + wCurrentMenuItem], al              ; ld [wCurrentMenuItem], a
    mov byte [ebp + wMenuWatchedKeys], PAD_A | PAD_B ; ld a, PAD_A | PAD_B / ld [wMenuWatchedKeys], a
    mov al, [ebp + wFilteredBagItemsCount]        ; ld a, [wFilteredBagItemsCount]
    dec al                                        ; dec a
    mov [ebp + wMaxMenuItem], al                  ; ld [wMaxMenuItem], a
    mov byte [ebp + wTopMenuItemY], 2             ; ld a, 2 / ld [wTopMenuItemY], a
    mov byte [ebp + wTopMenuItemX], 1             ; ld a, 1 / ld [wTopMenuItemX], a

    mov al, [ebp + wFilteredBagItemsCount]        ; ld a, [wFilteredBagItemsCount]
    dec al                                        ; dec a
    mov bx, 2                                     ; ld bc, 2
    mov esi, 3                                    ; ld hl, 3 — a plain scratch counter, NOT a coordinate
    call AddNTimes                                ; call AddNTimes — esi = 3 + 2*(count-1)
    mov eax, esi                                  ; dec l — ESI has no 8-bit sub-register in 32-bit mode,
    dec al                                        ;   so truncate through AL (reproduces pret's 8-bit wrap)
    mov bh, al                                    ; ld b, l
    mov bl, 0x0d                                  ; ld c, $d
    ; PROJ overworld-ui (fossil list box): GB(0,0) 15x(dynamic) --(anchor=top-LEFT, X+0, Y+0)--> wx=7 wy=0 clip=120 max_y=8*(3+2*(N-1))
    ; Canvas list drawing runs at the 40-wide canvas stride: force it around
    ; the border + entries (same trap the mart mirrors were built for).
    push dword [text_row_stride]
    mov dword [text_row_stride], SCREEN_TILES_W
    hlcoord 0, 0                                  ; hlcoord 0, 0
    call TextBoxBorder                            ; call TextBoxBorder
    call UpdateSprites                            ; call UpdateSprites
    call PrintFossilsInBag                        ; call PrintFossilsInBag
    pop dword [text_row_stride]
    call fossil_show_list_window                   ; mirror + idempotent publish (mart class)
    and byte [ebp + wStatusFlags5], ~(1 << BIT_NO_TEXT_DELAY) & 0xFF ; ld hl, wStatusFlags5 / res BIT_NO_TEXT_DELAY, [hl]
    ; Mart pattern (pokemart.asm): dialog pauses reset the window list via
    ; set_single_window unless this flag is set — without it the Sees/Takes
    ; prompts below tear down the fossil list mid-flow.
    mov byte [g_dialog_preserve_windows], 1
    ; PlaceMenuCursor addresses Y*stride+X: entries are double-spaced canvas
    ; rows, so drive input at the canvas stride with the two-row canvas step
    ; (prize pattern).
    mov dword [menu_item_step], 2 * SCREEN_TILES_W
    push dword [text_row_stride]
    mov dword [text_row_stride], SCREEN_TILES_W
    mov dword [menu_redraw_cb], fossil_list_mirror ; re-mirror per input frame (cursor moves)
    call HandleMenuInput                          ; call HandleMenuInput
    mov dword [menu_redraw_cb], 0
    pop dword [text_row_stride]
    test al, PAD_B                                ; bit B_PAD_B, a
    jnz .cancelledGivingFossil                    ; jr nz, .cancelledGivingFossil

    movzx edx, byte [ebp + wCurrentMenuItem]      ; ld a, [wCurrentMenuItem] / ld d, 0 / ld e, a
    lea esi, [wFilteredBagItems + edx]            ; ld hl, wFilteredBagItems / add hl, de
    mov al, [ebp + esi]                           ; ld a, [hl]
    mov [ebp + hItemToRemoveID], al               ; ldh [hItemToRemoveID], a
    cmp al, DOME_FOSSIL                           ; cp DOME_FOSSIL
    jz .choseDomeFossil                           ; jr z, .choseDomeFossil
    cmp al, HELIX_FOSSIL                          ; cp HELIX_FOSSIL
    jz .choseHelixFossil                          ; jr z, .choseHelixFossil
    mov bh, AERODACTYL                            ; ld b, AERODACTYL
    jmp .fossilSelected                           ; jr .fossilSelected
.choseHelixFossil:
    mov bh, OMANYTE                               ; ld b, OMANYTE
    jmp .fossilSelected                           ; jr .fossilSelected
.choseDomeFossil:
    mov bh, KABUTO                                ; ld b, KABUTO
.fossilSelected:
    mov [ebp + wFossilItem], al                   ; ld [wFossilItem], a
    mov al, bh                                    ; ld a, b
    mov [ebp + wFossilMon], al                    ; ld [wFossilMon], a
    call LoadFossilItemAndMonName                 ; call LoadFossilItemAndMonName
    mov esi, .ScientistSeesFossilText             ; ld hl, .ScientistSeesFossilText
    call PrintText                                ; call PrintText
    call YesNoChoice                              ; call YesNoChoice
    mov al, [ebp + wCurrentMenuItem]              ; ld a, [wCurrentMenuItem]
    test al, al                                   ; and a
    jnz .cancelledGivingFossil                    ; jr nz, .cancelledGivingFossil
    mov esi, .ScientistTakesFossilText            ; ld hl, .ScientistTakesFossilText
    call PrintText                                ; call PrintText
    mov al, [ebp + wFossilItem]                   ; ld a, [wFossilItem]
    mov [ebp + hItemToRemoveID], al               ; ldh [hItemToRemoveID], a
; DEVIATION{class=banking; pret=engine/events/cinnabar_lab.asm:GiveFossilToCinnabarLab; behavior=call RemoveItemByID directly instead of the pret farcall; evidence=the DPMI model is flat so every routine is always addressable and Bankswitch has no port counterpart, same convention every other farcall/farjp site in this tree uses; lifetime=permanent flat-memory boundary}
    call RemoveItemByID                           ; farcall RemoveItemByID
    mov esi, .GoForAWalkText                      ; ld hl, .GoForAWalkText
    call PrintText                                ; call PrintText
    SetEvents EVENT_GAVE_FOSSIL_TO_LAB, EVENT_LAB_STILL_REVIVING_FOSSIL
    ; Spec: teardown happens here — after the choice resolves, never earlier.
    ; Drops exactly the fossil list window; the dialog stays for
    ; HoldTextDisplayOpen, closed by CloseTextDisplay's hide_window.
    call fossil_drop_windows
    mov byte [g_dialog_preserve_windows], 0
    ret
.cancelledGivingFossil:
    mov esi, .ComeAgainText                       ; ld hl, .ComeAgainText
    call PrintText                                ; call PrintText
    call fossil_drop_windows
    mov byte [g_dialog_preserve_windows], 0
    ret

; ---------------------------------------------------------------------------
; Text wrappers — pret engine/events/cinnabar_lab.asm:74-91.
; Local labels: the four streams are generated into
; assets/map_text/event_cinnabar_lab.inc (tools/generators/gen_map_text.py).
; ---------------------------------------------------------------------------
.ScientistSeesFossilText:
    text_far _CinnabarLabFossilRoomScientist1SeesFossilText
    text_end

.ScientistTakesFossilText:
    text_far _CinnabarLabFossilRoomScientist1TakesFossilText
    text_end

.GoForAWalkText:
    text_far _CinnabarLabFossilRoomScientist1GoForAWalkText2
    text_end

.ComeAgainText:
    text_far _CinnabarLabFossilRoomScientist1ComeAgainText
    text_end

; ---------------------------------------------------------------------------
; PrintFossilsInBag — pret ref: engine/events/cinnabar_lab.asm:94-113.
; Prints each fossil in the player's bag on a separate line of the menu.
; ---------------------------------------------------------------------------
PrintFossilsInBag:
    mov esi, wFilteredBagItems                   ; ld hl, wFilteredBagItems
    xor al, al                                    ; xor a
    mov [ebp + hItemCounter], al                  ; ldh [hItemCounter], a
.loop:
    mov al, [ebp + esi]                           ; ld a, [hli]
    lea esi, [esi + 1]
    cmp al, 0xff                                  ; cp $ff
    jnz .continue                                 ; ret z (inverted)
    ret
.continue:
    push esi                                      ; push hl
    mov [ebp + wNamedObjectIndex], al             ; ld [wNamedObjectIndex], a
    call GetItemName                              ; call GetItemName
    ; PROJ overworld-ui (fossil list box entries): GB(2,2) --(anchor=top-LEFT, X+0, Y+0)--> unchanged
    hlcoord 2, 2                                  ; hlcoord 2, 2
    movzx eax, byte [ebp + hItemCounter]          ; ldh a, [hItemCounter]
    mov bx, SCREEN_WIDTH * 2                      ; ld bc, SCREEN_WIDTH * 2
    call AddNTimes                                ; call AddNTimes
    lea eax, [ebp + wNameBuffer]                  ; ld de, wNameBuffer — PlaceString takes a flat ptr in EAX
    call PlaceString                              ; call PlaceString
    inc byte [ebp + hItemCounter]                 ; ld hl, hItemCounter / inc [hl]
    pop esi                                       ; pop hl
    jmp .loop                                     ; jr .loop

; ---------------------------------------------------------------------------
; LoadFossilItemAndMonName — pret ref: engine/events/cinnabar_lab.asm:115-123.
; Loads the names of the fossil item and the resulting mon.
; Out: wNameBuffer = mon name, wStringBuffer = mon name copy, wNameBuffer = item name
;      (matches pret: GetMonName+CopyToStringBuffer save the mon name into
;      wStringBuffer, then GetItemName overwrites wNameBuffer with the item name).
; ---------------------------------------------------------------------------
LoadFossilItemAndMonName:
    mov al, [ebp + wFossilMon]                    ; ld a, [wFossilMon]
    mov [ebp + wNamedObjectIndex], al             ; ld [wNamedObjectIndex], a
    call GetMonName                               ; call GetMonName
    ; Not a divergence from pret (output is identical either way): GetMonName
    ; (src/home/names.asm) has no documented EDX-out contract the way
    ; GetItemName/GetPartyMonName do (both state EDX=wNameBuffer on exit), so
    ; the port sets EDX explicitly here rather than relying on an incidental
    ; register value — matching the explicit-EDX pattern list_menu.asm already
    ; uses at its own GetXName / CopyToStringBuffer call site.
    mov edx, wNameBuffer                          ; ld de, wNameBuffer
    call CopyToStringBuffer                       ; call CopyToStringBuffer
    mov al, [ebp + wFossilItem]                   ; ld a, [wFossilItem]
    mov [ebp + wNamedObjectIndex], al             ; ld [wNamedObjectIndex], a
    call GetItemName                              ; call GetItemName
    ret

; ---------------------------------------------------------------------------
; Port-only presentation (mart class, prize pattern): mirror the fossil list
; from the 40-wide canvas into GB_TILEMAP0 and publish it as a window
; descriptor (the compositor reads the window source, not wTileMap).
; Source rows 0..h-1 where h = bh+2 (TextBoxBorder draws top + bh middles +
; bottom); dest is FOSSIL_SROW. All registers preserved.
; ---------------------------------------------------------------------------
fossil_list_mirror:
    pushad
    mov al, [ebp + wFilteredBagItemsCount]        ; row count = 3+2*(count-1)
    dec al
    mov bx, 2
    mov esi, 3
    call AddNTimes
    lea ecx, [esi + 1]              ; drawn rows = bh+2 (top + middles + bottom)
    xor ebx, ebx
.row:
    cmp ebx, ecx
    jae .done
    mov esi, ebx
    imul esi, esi, SCREEN_TILES_W
    lea esi, [ebp + esi + wTileMap]
    mov edi, ebx
    shl edi, 5
    lea edi, [ebp + edi + GB_TILEMAP0 + FOSSIL_SROW * 32]
    push ecx
    mov ecx, FOSSIL_LIST_W
    rep movsb
    pop ecx
    inc ebx
    jmp .row
.done:
    popad
    ret

fossil_show_list_window:
    pushad
    mov ecx, [g_window_count]
    xor ebx, ebx
.check:
    cmp ebx, ecx
    jge .notfound
    imul eax, ebx, WIN_DESC_SIZE
    mov edx, [g_windows + eax + WIN_START_ROW]
    cmp edx, FOSSIL_SROW
    je .found
    inc ebx
    jmp .check
.found:
    call fossil_list_mirror
    popad
    ret
.notfound:
    popad
    call fossil_list_mirror
    mov eax, FOSSIL_MENU_WX
    mov ebx, FOSSIL_MENU_WY
    mov ecx, FOSSIL_MENU_CLIP
    mov edx, FOSSIL_MENU_MAXY
    mov esi, GB_TILEMAP0
    mov edi, FOSSIL_SROW
    call add_window
    ret

; ---------------------------------------------------------------------------
; fossil_drop_windows — port-only presentation: remove exactly the fossil
; list window descriptor, compacting the list. Template: prize_drop_windows
; (prize_menu.asm) — same scan by WIN_START_ROW, shift-down removal. Called
; at both GiveFossilToCinnabarLab exits (teardown-after-choice spec);
; CloseTextDisplay's hide_window remains the final backstop.
; All registers preserved.
; ---------------------------------------------------------------------------
fossil_drop_windows:
    pushad
    mov ecx, [g_window_count]
    test ecx, ecx
    jz .done
    xor ebx, ebx
.scan:
    cmp ebx, ecx
    jge .done
    imul eax, ebx, WIN_DESC_SIZE
    mov edx, [g_windows + eax + WIN_START_ROW]
    cmp edx, FOSSIL_SROW
    je .found
    inc ebx
    jmp .scan
.found:
    mov edi, ebx
    imul edi, edi, WIN_DESC_SIZE
    add edi, g_windows
.shift_loop:
    inc ebx
    cmp ebx, ecx
    jge .shifted
    mov esi, ebx
    imul esi, esi, WIN_DESC_SIZE
    add esi, g_windows
    push ecx
    mov ecx, WIN_DESC_SIZE / 4
    rep movsd
    pop ecx
    jmp .shift_loop
.shifted:
    dec dword [g_window_count]
.done:
    popad
    ret
