; ===========================================================================
; diploma2.asm — pret mirror of engine/events/diploma2.asm (screen half).
;
; DisplayDiplomaTop: draws the Hall-of-Fame diploma screen on the 40x25 canvas.
;
; SCREEN PROJECTION RULING (maintainer, 2026-08-17):
; A simple center projection: add +10 columns and +3 rows to every pret hlcoord
; coordinate, placing the 20x18 certificate centered in the 40x25 canvas.
;
; TWO-TIER RULE (CLAUDE.md):
; Text strings (DiplomaText, DiplomaPlayer, DiplomaCongrats, DiplomaGameFreak)
; and tile graphics (DiplomaGraphics) are Tier-1 DATA generated by
; tools/generators/gen_diploma.py into assets/diploma_text.inc and
; assets/diploma_tiles.inc (%included below in section .data).
;
; Register map (CLAUDE.md): A->AL, BC->BX (B=BH, C=BL), DE->DX/EDX, HL->ESI;
; GB memory = [ebp + SYM]. Text strings and tile blobs are flat .data pointers.
; ===========================================================================

bits 32

%include "gb_memmap.inc"
%include "coords.inc"

%ifndef SET_PAL_GENERIC
SET_PAL_GENERIC equ 0x08
%endif

global DisplayDiplomaTop
global DiplomaDrawHorizontalBorder
global DiplomaDrawVerticalBorder
global DiplomaGraphics
global DiplomaGraphicsEnd
global DiplomaText
global DiplomaPlayer
global DiplomaCongrats
global DiplomaGameFreak

extern GBPalWhiteOutWithDelay3  ; src/home/palettes.asm
extern ClearScreen              ; src/home/copy2.asm
extern CopyVideoData            ; src/home/copy2.asm
extern PlaceString              ; src/home/text.asm
extern RunPaletteCommand        ; src/home/palettes.asm
extern Delay3                   ; src/home/palettes.asm
extern GBPalNormal              ; src/home/palettes.asm

section .text

; ---------------------------------------------------------------------------
; DisplayDiplomaTop — pret engine/events/diploma2.asm:DisplayDiplomaTop.
;
; DEVIATION{class=projection; pret=engine/events/diploma2.asm:DisplayDiplomaTop; behavior=the diploma layout is centered on the 40x25 canvas by adding 10 columns and 3 rows to pret hlcoords; evidence=pret 20x18 layout centered on port 40x25 canvas per maintainer screen projection ruling; lifetime=permanent while the port renders a 40x25 canvas}
; ---------------------------------------------------------------------------
DisplayDiplomaTop:
    call GBPalWhiteOutWithDelay3
    call ClearScreen
    mov edx, DiplomaGraphics
    mov esi, vChars2
    mov bl, (DiplomaGraphicsEnd - DiplomaGraphics) / 16
    call CopyVideoData

    hlcoord 10, 3                       ; PROJ — pret hlcoord 0, 0
    call DiplomaDrawHorizontalBorder
    hlcoord 10, 3                       ; PROJ — pret hlcoord 0, 0
    call DiplomaDrawVerticalBorder
    hlcoord 29, 3                       ; PROJ — pret hlcoord 19, 0
    call DiplomaDrawVerticalBorder
    xor al, al                          ; ld a, $00
    hlcoord 10, 3                       ; PROJ — pret hlcoord 0, 0
    mov byte [ebp + esi], al            ; ld [hl], a
    hlcoord 29, 3                       ; PROJ — pret hlcoord 19, 0
    mov byte [ebp + esi], al            ; ld [hl], a

    mov eax, DiplomaText                ; ld de, DiplomaText
    hlcoord 15, 5                       ; PROJ — pret hlcoord 5, 2
    call PlaceString

    mov eax, DiplomaPlayer              ; ld de, DiplomaPlayer
    hlcoord 13, 7                       ; PROJ — pret hlcoord 3, 4
    call PlaceString

    lea eax, [ebp + wPlayerName]        ; ld de, wPlayerName
    hlcoord 20, 7                       ; PROJ — pret hlcoord 10, 4
    call PlaceString

    mov eax, DiplomaCongrats            ; ld de, DiplomaCongrats
    hlcoord 12, 9                       ; PROJ — pret hlcoord 2, 6
    call PlaceString

    mov eax, DiplomaGameFreak            ; ld de, DiplomaGameFreak
    hlcoord 19, 19                      ; PROJ — pret hlcoord 9, 16
    call PlaceString

    mov bh, SET_PAL_GENERIC             ; ld b, SET_PAL_GENERIC
    call RunPaletteCommand
    mov byte [ebp + hAutoBGTransferEnabled], 1  ; ld a, $01 / ldh [hAutoBGTransferEnabled], a
    call Delay3
    call GBPalNormal
    ret

; ---------------------------------------------------------------------------
; DiplomaDrawHorizontalBorder — draw top horizontal border tiles.
; Pret extent: SCREEN_WIDTH / 2 = 20 / 2 = 10 iterations (20 tiles).
; ---------------------------------------------------------------------------
DiplomaDrawHorizontalBorder:
    mov cl, 20 / 2                      ; ld c, SCREEN_WIDTH / 2 (pret extent = 10)
.loop:
    mov byte [ebp + esi], 0x02          ; ld [hl], $02
    inc esi                             ; inc hl
    mov byte [ebp + esi], 0x01          ; ld [hl], $01
    inc esi                             ; inc hl
    dec cl                              ; dec c
    jnz .loop                           ; jr nz, .loop
    ret

; ---------------------------------------------------------------------------
; DiplomaDrawVerticalBorder — draw vertical border tiles.
;
; DEVIATION{class=projection; pret=engine/events/diploma2.asm:DiplomaDrawVerticalBorder; behavior=the row stride DE is the port tilemap stride SCREEN_WIDTH=40 while the iteration extent C remains pret 18/2=9; evidence=pret row stride advances 1 tilemap row on a 20-wide screen while the port tilemap has stride 40, and the diploma height is 18 tiles; lifetime=permanent while the port renders a 40x25 canvas}
; ---------------------------------------------------------------------------
DiplomaDrawVerticalBorder:
    mov cl, 18 / 2                      ; ld c, SCREEN_HEIGHT / 2 (pret extent = 9)
    mov edx, SCREEN_WIDTH               ; ld de, SCREEN_WIDTH (port row stride = 40)
.loop:
    mov byte [ebp + esi], 0x04          ; ld [hl], $04
    add esi, edx                        ; add hl, de
    mov byte [ebp + esi], 0x03          ; ld [hl], $03
    add esi, edx                        ; add hl, de
    dec cl                              ; dec c
    jnz .loop                           ; jr nz, .loop
    ret

; ---------------------------------------------------------------------------
section .data

%include "assets/diploma_text.inc"
%include "assets/diploma_tiles.inc"
