; hidden_items.asm — hidden ground items and hidden Game Corner coins.
;
; Faithful translation of pret `engine/events/hidden_items.asm`. All pret labels
; land here, retiring their ret-stubs:
;   HiddenItems              — was in src/engine/overworld/hidden_object_stubs.asm.
;   HiddenCoins               — was in src/engine/overworld/hidden_object_stubs.asm.
;   FoundHiddenItemText       — was in
;                               src/engine/events/hidden_events/hidden_events_stubs.asm.
;   FindHiddenItemOrCoinsIndex — was UNPORTED (no prior stub; a private helper).
;
; HiddenItemCoords is pret data/events/hidden_item_coords.asm, already generated
; as Tier-1 data and LINKED via src/data/hidden_events_data.asm (consumed there
; by the itemfinder's HiddenItemNear) — see tools/generators/gen_hidden_item_coords.py.
; It is `extern`ed here rather than re-included, to avoid a duplicate `global`
; definition across two objects.
;
; HiddenCoinCoords has no prior generator (only the item table existed). This
; change adds tools/generators/gen_hidden_coin_coords.py, the sibling generator,
; emitting assets/hidden_coin_coords.inc — %included directly below, mirroring
; how pret's hidden_items.asm textually INCLUDEs
; data/events/hidden_coins.asm at that point (same precedent as
; src/engine/events/card_key.asm inlining assets/card_key_maps.inc for
; SilphCoMapList).
;
; FoundHiddenItemText is a predef_code TextPredefs row ($26,
; src/data/text_predef_pointers.asm) — DisplayTextID's TEXT_PREDEF branch does a
; bare `call esi` straight at this label (TEXT_ASM_ENTRY sentinel), so the label
; must be x86 CODE at offset 0. pret's FoundHiddenItemText is a printable
; `text_far _FoundHiddenItemText` intro followed by a text_asm code tail; since
; the label is called directly as code here, the far intro is printed explicitly
; via PrintText instead of being a leading stream byte TextCommandProcessor would
; otherwise walk into — same reasoning as CinnabarGymQuiz dropping its text_asm
; byte (src/engine/events/hidden_events/cinnabar_gym_quiz.asm), extended to also
; cover the far text ahead of it (same shape as that file's
; CinnabarGymQuizCorrectText, whose far body is a standalone label printed
; explicitly before its own text_asm tail runs). The far body,
; `_FoundHiddenItemText`, is generated by the new
; tools/generators/gen_hidden_items_text.py into assets/hidden_items_text.inc.
;
; HiddenItemBagFullText / FoundHiddenCoinsText / DroppedHiddenCoinsText are pure
; text_far wrappers ($27/$2D/$2E) already generated as Tier-1 predef_data rows in
; assets/predef_text.inc (via tools/generators/gen_predef_text.py) and LINKED in
; src/data/text_predef_pointers.asm — `extern`ed here.
;
; predef bypasses (registers hand-set at the call site, so the predef wrapper's
; GetPredefRegisters would only clobber): FlagActionPredef -> FlagAction and
; AddBCDPredef -> AddBCD, following the established port pattern
; (src/engine/overworld/toggleable_objects.asm, cinnabar_gym_quiz.asm,
; src/home/inventory.asm:AddAmountSoldToMoney). `predef GetQuantityOfItemInBag`
; keeps going through the normal call (its own body already opens with
; GetPredefRegisters — same convention as home/map_objects.asm:IsItemInBag).
;
; Register map (SM83 -> x86): A->AL, BC->BX (B->BH, C->BL), DE->DX (D->DH, E->DL),
; HL->ESI. GB memory is [ebp + addr] (gb_memmap.inc).
;
; Build: nasm -f coff -I include/ -I . -D BUG_FIX_LEVEL=0 -o /dev/null \
;            src/engine/events/hidden_items.asm

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "predef.inc"                    ; tx_pre_id
%include "assets/predef_text_ids.inc"    ; FoundHiddenItemText_id
%include "assets/script_constants.inc"   ; COIN
%include "assets/audio_constants.inc"    ; SFX_GET_ITEM_2

section .text

global HiddenItems
global FoundHiddenItemText
global HiddenCoins
global FindHiddenItemOrCoinsIndex

extern EnableAutoTextBoxDrawing         ; src/home/window.asm
extern PrintPredefTextID                ; src/home/predef_text.asm
extern PrintText                        ; src/home/window.asm
extern GetItemName                      ; src/home/names.asm
extern GiveItem                         ; src/home/give.asm
extern FlagAction                       ; src/engine/flag_action.asm
extern GetQuantityOfItemInBag           ; src/engine/items/get_bag_item_quantity.asm (predef)
extern AddBCD                           ; src/engine/math/bcd.asm
extern PlaySoundWaitForCurrent          ; src/home/delay.asm
extern WaitForSoundToFinish             ; src/home/delay.asm
extern WaitForTextScrollButtonPress     ; src/home/joypad2.asm
extern TextScriptEnd                    ; src/home/overworld_text.asm
extern HiddenItemCoords                 ; assets/hidden_item_coords.inc (generated data,
                                         ; %included by src/data/hidden_events_data.asm)
extern HiddenItemBagFullText            ; assets/predef_text.inc (generated data,
                                         ; %included by src/data/text_predef_pointers.asm)
extern FoundHiddenCoinsText              ; assets/predef_text.inc (generated data,
                                         ; %included by src/data/text_predef_pointers.asm)
extern DroppedHiddenCoinsText           ; assets/predef_text.inc (generated data,
                                         ; %included by src/data/text_predef_pointers.asm)

; ─────────────────────────────────────────────────────────────────────────────
; HiddenItems — pret engine/events/hidden_items.asm:HiddenItems.
; The per-map hidden-event handler for a hidden ground item.
; ─────────────────────────────────────────────────────────────────────────────
HiddenItems:
    mov esi, HiddenItemCoords
    call FindHiddenItemOrCoinsIndex
    mov [ebp + wHiddenItemOrCoinsIndex], al

    mov esi, wObtainedHiddenItemsFlags
    movzx ecx, byte [ebp + wHiddenItemOrCoinsIndex]
    mov bh, FLAG_TEST
    ; pret: `predef FlagActionPredef` (see file header — direct call, regs hand-set).
    ; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by direct call to FlagAction; evidence=flat memory model, FlagAction called directly across the port (toggleable_objects.asm, cinnabar_gym_quiz.asm); lifetime=permanent}
    call FlagAction
    test cl, cl
    jnz .itemAlreadyFound

    call EnableAutoTextBoxDrawing
    mov byte [ebp + wDoNotWaitForButtonPressAfterDisplayingText], 1
    mov al, [ebp + wHiddenEventFunctionArgument]  ; item ID
    mov [ebp + wNamedObjectIndex], al
    call GetItemName
    ; pret: `tx_pre_jump FoundHiddenItemText`, spelled out (see include/predef.inc).
    tx_pre_id FoundHiddenItemText
    jmp PrintPredefTextID

.itemAlreadyFound:
    mov byte [ebp + hItemAlreadyFound], 0xFF
    ret

; ─────────────────────────────────────────────────────────────────────────────
; FoundHiddenItemText — pret engine/events/hidden_items.asm:FoundHiddenItemText.
; See file header for why the far intro is printed explicitly and no leading
; text_asm byte is kept.
; ─────────────────────────────────────────────────────────────────────────────
FoundHiddenItemText:
    mov esi, _FoundHiddenItemText
    call PrintText
    mov al, [ebp + wHiddenEventFunctionArgument]  ; item ID
    mov bh, al
    mov bl, 1
    call GiveItem
    jnc .bagFull
    mov esi, wObtainedHiddenItemsFlags
    movzx ecx, byte [ebp + wHiddenItemOrCoinsIndex]
    mov bh, FLAG_SET
    call FlagAction
    mov al, SFX_GET_ITEM_2
    call PlaySoundWaitForCurrent
    call WaitForSoundToFinish
    jmp TextScriptEnd
.bagFull:
    call WaitForTextScrollButtonPress    ; wait for button press
    mov byte [ebp + wDoNotWaitForButtonPressAfterDisplayingText], 0
    mov esi, HiddenItemBagFullText
    call PrintText
    jmp TextScriptEnd

; ─────────────────────────────────────────────────────────────────────────────
; HiddenCoins — pret engine/events/hidden_items.asm:HiddenCoins.
; The per-map hidden-event handler for hidden Game Corner coins.
; ─────────────────────────────────────────────────────────────────────────────
HiddenCoins:
    mov byte [ebp + wPredefBC], COIN_CASE   ; ld b, COIN_CASE (GetPredefRegisters input)
    call GetQuantityOfItemInBag             ; predef — its own body calls GetPredefRegisters
    test bh, bh
    jz .doNotPickUpCoins

    mov esi, HiddenCoinCoords
    call FindHiddenItemOrCoinsIndex
    mov [ebp + wHiddenItemOrCoinsIndex], al

    mov esi, wObtainedHiddenCoinsFlags
    movzx ecx, byte [ebp + wHiddenItemOrCoinsIndex]
    mov bh, FLAG_TEST
    ; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by direct call to FlagAction; evidence=flat memory model, FlagAction called directly across the port (toggleable_objects.asm, cinnabar_gym_quiz.asm); lifetime=permanent}
    call FlagAction
    test cl, cl
    jnz .doNotPickUpCoins

    mov byte [ebp + hUnusedCoinsByte], 0
    mov byte [ebp + hCoins], 0
    mov byte [ebp + hCoins + 1], 0
    mov al, [ebp + wHiddenEventFunctionArgument]
    sub al, COIN
    cmp al, 10
    je .bcd10
    cmp al, 20
    je .bcd20
    cmp al, 40
    je .bcd20            ; due to a typo in pret, .bcd40 is never reached — kept verbatim
    jmp .bcd100

.bcd10:
    mov byte [ebp + hCoins + 1], 0x10
    jmp .bcdDone
.bcd20:
    mov byte [ebp + hCoins + 1], 0x20
    jmp .bcdDone
.bcd40:                   ; unreachable in pret too (see the .bcd20 fallthrough above)
    mov byte [ebp + hCoins + 1], 0x40
    jmp .bcdDone
.bcd100:
    mov byte [ebp + hCoins], 1
.bcdDone:
    mov esi, hCoins + 1
    mov edx, wPlayerCoins + 1
    mov cl, 2
    ; pret: `predef AddBCDPredef` (see file header — direct call, regs hand-set).
    ; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by direct call to AddBCD; evidence=flat memory model, AddBCD called directly elsewhere in the port (src/home/inventory.asm:AddAmountSoldToMoney); lifetime=permanent}
    call AddBCD

    mov esi, wObtainedHiddenCoinsFlags
    movzx ecx, byte [ebp + wHiddenItemOrCoinsIndex]
    mov bh, FLAG_SET
    call FlagAction

    call EnableAutoTextBoxDrawing
    mov al, [ebp + wPlayerCoins]
    cmp al, 0x99
    jne .roomInCoinCase
    mov al, [ebp + wPlayerCoins + 1]
    cmp al, 0x99
    jne .roomInCoinCase
    tx_pre_id DroppedHiddenCoinsText
    jmp .done
.roomInCoinCase:
    tx_pre_id FoundHiddenCoinsText
.done:
    jmp PrintPredefTextID

.doNotPickUpCoins:
    mov byte [ebp + hItemAlreadyFound], 0xFF
    ret

; ─────────────────────────────────────────────────────────────────────────────
; FindHiddenItemOrCoinsIndex — pret engine/events/hidden_items.asm:FindHiddenItemOrCoinsIndex.
; In: ESI = flat pointer to a {map, y, x} triple table (HiddenItemCoords or
;     HiddenCoinCoords), 0xFF-terminated.
; Out: AL = 0-based row index of the matching entry. If no entry matches, pret
;      returns with A = the terminator byte ($FF) it just read — preserved
;      verbatim (not "fixed"; every real caller's table always matches, since
;      the calling map always has an entry).
; Clobbers: EAX, EBX (bh), ECX (cl), EDX (dh/dl), ESI.
; ─────────────────────────────────────────────────────────────────────────────
FindHiddenItemOrCoinsIndex:
    mov dh, [ebp + wHiddenEventY]        ; ld a,[wHiddenEventY] / ld d,a
    mov dl, [ebp + wHiddenEventX]        ; ld a,[wHiddenEventX] / ld e,a
    mov bh, [ebp + wCurMap]              ; ld a,[wCurMap] / ld b,a
    mov cl, 0xFF                         ; ld c, -1
.loop:
    inc cl                               ; inc c
    mov al, [esi]                        ; ld a, [hli]
    inc esi
    cmp al, 0xFF                         ; cp -1 (end of the list?)
    je .ret                              ; ret z
    cmp al, bh                           ; cp b
    jne .next1
    mov al, [esi]                        ; ld a, [hli]
    inc esi
    cmp al, dh                           ; cp d
    jne .next2
    mov al, [esi]                        ; ld a, [hli]
    inc esi
    cmp al, dl                           ; cp e
    jne .loop
    mov al, cl                           ; ld a, c
.ret:
    ret
.next1:
    inc esi                              ; inc hl
.next2:
    inc esi                              ; inc hl
    jmp .loop

section .data

%include "assets/hidden_items_text.inc"  ; _FoundHiddenItemText (generated)
%include "assets/hidden_coin_coords.inc" ; HiddenCoinCoords (generated)
