; ===========================================================================
; in_game_trades.asm — pret mirror of engine/events/in_game_trades.asm.
;
; DoInGameTradeDialogue drives the six NPC trades (ROUTE_11_GATE_2F,
; ROUTE_2_TRADE_HOUSE, CINNABAR_LAB_TRADE_ROOM, CINNABAR_LAB_FOSSIL_ROOM,
; ROUTE_18_GATE_2F, UNDERGROUND_PATH_ROUTE_5): it reads the TradeMons row
; selected by wWhichTrade, asks YES/NO, runs the party menu, swaps the mon and
; prints the dialogset's message.
;
; TWO-TIER RULE (CLAUDE.md):
;   * TradeMons and InGameTrade_TrainerString are pret `npctrade` / `dname`
;     rows — charmap-encoded names, i.e. Tier-1 DATA, generated by
;     tools/generators/gen_trades.py. They land in DIFFERENT files because pret
;     defines them in different files: TradeMons is a data/events/ label and
;     lives in src/data/events/trades.asm (externed here), while
;     InGameTrade_TrainerString is defined in this file and is %included below
;     from assets/trade_trainer_string.inc.
;   * The 17 far text streams are generated by
;     tools/generators/gen_overworld_strings.py into
;     assets/in_game_trade_text.inc. This file holds only the Tier-2 code and
;     pret's `text_far` wrappers.
;
; Register map (CLAUDE.md): A->AL, B->BH, C->BL, DE->EDX, HL->ESI, EBP = GB
; base. GB memory is [ebp + SYM]; flat program-image data (TradeMons, the text
; streams, the pointer tables) is addressed as [label] / [esi] with no EBP bias.
;
; THE ADDRESS-SPACE SPLIT IS THE WHOLE STORY OF THIS FILE. On the GB, TradeMons
; and InGameTrade_TrainerString live in a ROM bank mapped INSIDE the 16-bit GB
; address space, so pret's `call CopyData` is a GB->GB copy. In the port those
; tables are flat program-image .data outside the EBP window, and
; home/copy.asm:CopyData does `lea esi,[ebp+esi]` on its source, so it
; structurally cannot express a flat->GB copy. Every such site below is an
; inline `rep movsb` under a DEVIATION, following the precedent in
; src/engine/battle/draw_hud_pokeball_gfx.asm and
; src/engine/menus/draw_badges.asm. The GB->GB copies still go through
; CopyData / InGameTrade_CopyData exactly as pret does.
; ===========================================================================

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"             ; NAME_LENGTH, PARTYMON_STRUCT_LENGTH,
                                        ; FLAG_TEST/FLAG_SET, LINK_STATE_TRADING, KADABRA
%include "assets/script_constants.inc"  ; species + TRADE_DIALOGSET_* constants
%include "gb_text.inc"                  ; text_far / text_end / text_pause / sound_get_key_item

; TradeTextPointers1-3 indexes (pret engine/events/in_game_trades.asm head)
TRADETEXT_WANNA_TRADE   equ 0
TRADETEXT_NO_TRADE      equ 1
TRADETEXT_WRONG_MON     equ 2
TRADETEXT_THANKS        equ 3
TRADETEXT_AFTER_TRADE   equ 4
NUM_TRADE_TEXTS         equ 5

global DoInGameTradeDialogue
global InGameTrade_GetMonName
global InGameTrade_DoTrade
global InGameTrade_RestoreScreen
global InGameTrade_PrepareTradeData
global InGameTrade_CopyData
global InGameTrade_CopyDataToReceivedMon
global InGameTrade_GetReceivedMonPointer
global InGameTrade_FlagActionPredef
global InGameTrade_CheckForTradeEvo
global InGameTrade_TrainerString
global InGameTradeTextPointers
global TradeTextPointers1
global TradeTextPointers2
global TradeTextPointers3
global ConnectCableText
global TradedForText
global WannaTrade1Text, NoTrade1Text, WrongMon1Text, Thanks1Text, AfterTrade1Text
global WannaTrade2Text, NoTrade2Text, WrongMon2Text, Thanks2Text, AfterTrade2Text
global WannaTrade3Text, NoTrade3Text, WrongMon3Text, Thanks3Text, AfterTrade3Text

extern TradeMons                                ; src/data/events/trades.asm
extern SaveScreenTilesToBuffer2                 ; src/home/tilemap.asm
extern LoadScreenTilesFromBuffer2               ; src/home/tilemap.asm
extern AddNTimes                                ; src/home/array.asm
extern CopyData                                 ; src/home/copy.asm
extern GetMonName                               ; src/home/names.asm
extern YesNoChoice                              ; src/home/yes_no.asm
extern PrintText                                ; src/home/window.asm
extern DisplayPartyMenu                         ; src/home/pokemon.asm
extern FlagAction                               ; src/engine/flag_action.asm
extern LoadHpBarAndStatusTilePatterns           ; src/home/load_font.asm
extern RemovePokemon                            ; src/home/move_mon.asm
extern AddPartyMon                              ; src/home/move_mon.asm
extern ClearScreen                              ; src/home/copy2.asm
extern RedrawMapView                            ; src/engine/overworld/update_map.asm
extern GBPalWhiteOutWithDelay3                  ; src/home/palettes.asm
extern RestoreScreenTilesAndReloadTilePatterns  ; src/home/palettes.asm
extern ReloadTilesetTilePatterns                ; src/home/reload_tiles.asm
extern Delay3                                   ; src/home/palettes.asm
extern LoadGBPal                                ; src/home/fade.asm
extern DelayFrames                              ; src/home/delay.asm
extern LoadWildData                             ; src/engine/overworld/wild_mons.asm
extern Random                                   ; src/home/random.asm
extern TryEvolvingMon                           ; src/engine/pokemon/evos_moves.asm
extern PlayDefaultMusic                         ; src/home/audio.asm
extern InternalClockTradeAnim                   ; src/engine/movie/trade.asm

section .text

; ---------------------------------------------------------------------------
; DoInGameTradeDialogue — trigger the trade offer/action specified by wWhichTrade.
;
; DEVIATION{class=data-model; pret=engine/events/in_game_trades.asm:DoInGameTradeDialogue; behavior=the selected TradeMons nickname is copied to wInGameTradeMonNick by an inline rep movsb instead of by CopyData, and the chosen TradeTextPointersN table address is held in the port-local 32-bit slot wInGameTradeTextPointerTablePointer32 instead of the two GB bytes at wInGameTradeTextPointerTablePointer CD10; evidence=TradeMons is a flat program-image label outside the EBP window while home/copy.asm CopyData biases its source with lea esi ebp+esi so the two address spaces cannot meet through it, and a 32-bit flat table address does not fit in the two WRAM bytes pret uses for a 16-bit ROM pointer - those bytes are read only by this routine; lifetime=permanent while ROM data lives outside the emulated GB address space}
; ---------------------------------------------------------------------------
DoInGameTradeDialogue:
    call SaveScreenTilesToBuffer2
    mov esi, TradeMons                          ; ld hl, TradeMons (FLAT program-image data)
    mov al, [ebp + wWhichTrade]                 ; ld a, [wWhichTrade]
    mov bx, 0xe                                 ; ld bc, $e  (3 + NAME_LENGTH row stride)
    call AddNTimes                              ; esi += $e * al (address-space agnostic)

    mov al, [esi]                               ; ld a, [hli]
    inc esi
    mov [ebp + wInGameTradeGiveMonSpecies], al
    mov al, [esi]                               ; ld a, [hli]
    inc esi
    mov [ebp + wInGameTradeReceiveMonSpecies], al
    mov al, [esi]                               ; ld a, [hli] — the dialogset
    inc esi
    push eax                                    ; push af

    ; ld de, wInGameTradeMonNick / ld bc, NAME_LENGTH / call CopyData
    ; Flat source -> GB destination: inline (see the file header DEVIATION).
    push edi
    mov bx, NAME_LENGTH                         ; ld bc, NAME_LENGTH
    mov edx, wInGameTradeMonNick                ; ld de, wInGameTradeMonNick
    lea edi, [ebp + edx]
    mov ecx, NAME_LENGTH
    rep movsb                                   ; ESI advances as pret's HL does
    pop edi

    pop eax                                     ; pop af — al = dialogset

    ; ld l,a / ld h,0 / ld de, InGameTradeTextPointers / add hl,hl / add hl,de
    ; / ld a,[hli] -> ptr lo / ld a,[hl] -> ptr hi.  pret's dw table becomes dd
    ; here, so the *2 index becomes *4 and the pointer is one dword.
    movzx eax, al
    mov eax, [InGameTradeTextPointers + eax*4]
    mov [wInGameTradeTextPointerTablePointer32], eax

    mov al, [ebp + wInGameTradeGiveMonSpecies]
    mov edx, wInGameTradeGiveMonName            ; ld de, wInGameTradeGiveMonName
    call InGameTrade_GetMonName
    mov al, [ebp + wInGameTradeReceiveMonSpecies]
    mov edx, wInGameTradeReceiveMonName
    call InGameTrade_GetMonName

    mov byte [ebp + wInGameTradeTextPointerTableIndex], TRADETEXT_AFTER_TRADE
    mov bh, FLAG_TEST                           ; ld b, FLAG_TEST
    call InGameTrade_FlagActionPredef
    mov al, cl                                  ; ld a, c  (FlagAction returns the bit in CL)
    test al, al                                 ; and a
    jnz .printText

; if the trade hasn't been done yet
    mov byte [ebp + wInGameTradeTextPointerTableIndex], TRADETEXT_WANNA_TRADE
    call .printText
    mov byte [ebp + wInGameTradeTextPointerTableIndex], TRADETEXT_NO_TRADE
    call YesNoChoice
    mov al, [ebp + wCurrentMenuItem]
    test al, al                                 ; and a
    jnz .printText
    call InGameTrade_DoTrade
    jc .printText                               ; jr c, .printText
    mov esi, TradedForText                      ; ld hl, TradedForText (flat)
    call PrintText

.printText:
    ; pret walks wInGameTradeTextPointerTableIndex downwards with two `ld a,[hld]`
    ; to pick up the 16-bit table pointer at wInGameTradeTextPointerTablePointer,
    ; then `add hl,de` twice (index * 2) and loads the 16-bit text pointer.
    ; Flat model: one dword slot, stride 4.
    movzx edx, byte [ebp + wInGameTradeTextPointerTableIndex] ; ld e,a / ld d,0
    mov esi, [wInGameTradeTextPointerTablePointer32]
    mov esi, [esi + edx*4]
    jmp PrintText                               ; jp PrintText

; ---------------------------------------------------------------------------
; InGameTrade_GetMonName — copies the name of species AL to EDX (pret's comment
; says "to hl", but the routine writes to de).
; ---------------------------------------------------------------------------
InGameTrade_GetMonName:
    push edx                                    ; push de
    mov [ebp + wNamedObjectIndex], al           ; ld [wNamedObjectIndex], a
    call GetMonName
    mov esi, wNameBuffer                        ; ld hl, wNameBuffer (GB offset)
    pop edx                                     ; pop de
    mov bx, NAME_LENGTH                         ; ld bc, NAME_LENGTH
    jmp CopyData                                ; jp CopyData — GB -> GB

; ---------------------------------------------------------------------------
; InGameTrade_DoTrade — run the party menu, verify the offered mon, swap it.
; Returns CF set on failure (with wInGameTradeTextPointerTableIndex set to the
; message to print), CF clear on success.
; ---------------------------------------------------------------------------
InGameTrade_DoTrade:
    xor al, al                                  ; xor a ; NORMAL_PARTY_MENU
    mov [ebp + wPartyMenuTypeOrMessageID], al
    dec al                                      ; dec a -> $FF
    mov [ebp + wUpdateSpritesEnabled], al
    call DisplayPartyMenu
    pushfd                                      ; push af — only F is live (A is
                                                ; overwritten below before any read)
    call InGameTrade_RestoreScreen
    popfd                                       ; pop af
    mov al, TRADETEXT_NO_TRADE                  ; ld a, TRADETEXT_NO_TRADE (no flag change)
    jc .tradeFailed                             ; jp c, .tradeFailed — no mon selected

    mov al, [ebp + wInGameTradeGiveMonSpecies]
    mov bh, al                                  ; ld b, a
    mov al, [ebp + wCurPartySpecies]
    cmp al, bh                                  ; cp b
    mov al, TRADETEXT_WRONG_MON                 ; (mov imm preserves flags)
    jnz .tradeFailed                            ; jr nz, .tradeFailed

    mov al, [ebp + wWhichPokemon]
    mov esi, wPartyMon1Level                    ; ld hl, wPartyMon1Level (GB offset)
    mov bx, PARTYMON_STRUCT_LENGTH
    call AddNTimes
    mov al, [ebp + esi]                         ; ld a, [hl]
    mov [ebp + wCurEnemyLevel], al

    mov bh, FLAG_SET                            ; ld b, FLAG_SET
    call InGameTrade_FlagActionPredef
    mov esi, ConnectCableText                   ; ld hl, ConnectCableText (flat)
    call PrintText

    movzx eax, byte [ebp + wWhichPokemon]
    push eax                                    ; push af (data, not flags)
    movzx eax, byte [ebp + wCurEnemyLevel]
    push eax                                    ; push af
    call LoadHpBarAndStatusTilePatterns
    call InGameTrade_PrepareTradeData
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus the two values popped immediately after this site are read back from the stack not from A; lifetime=retired when PredefPointers is ported}
    call InternalClockTradeAnim                 ; predef InternalClockTradeAnim
    pop eax                                     ; pop af
    mov [ebp + wCurEnemyLevel], al
    pop eax                                     ; pop af
    mov [ebp + wWhichPokemon], al

    mov al, [ebp + wInGameTradeReceiveMonSpecies]
    mov [ebp + wCurPartySpecies], al
    xor al, al
    mov [ebp + wMonDataLocation], al            ; not used
    mov [ebp + wRemoveMonFromBox], al
    call RemovePokemon
    mov al, 0x80                                ; ld a, $80 ; prevent naming the mon
    mov [ebp + wMonDataLocation], al
    call AddPartyMon
    call InGameTrade_CopyDataToReceivedMon
    call InGameTrade_CheckForTradeEvo
    call ClearScreen
    call InGameTrade_RestoreScreen
    call RedrawMapView                          ; farcall RedrawMapView (bank switch is a flat no-op)
    and al, al                                  ; and a — clears CF for the success return
    mov al, TRADETEXT_THANKS                    ; (mov imm preserves flags)
    jmp .tradeSucceeded                         ; jr .tradeSucceeded

.tradeFailed:
    stc                                         ; scf
.tradeSucceeded:
    mov [ebp + wInGameTradeTextPointerTableIndex], al
    ret

; ---------------------------------------------------------------------------
; InGameTrade_RestoreScreen — restore the pre-party-menu screen and tilesets.
; ---------------------------------------------------------------------------
InGameTrade_RestoreScreen:
    call GBPalWhiteOutWithDelay3
    call RestoreScreenTilesAndReloadTilePatterns
    call ReloadTilesetTilePatterns
    call LoadScreenTilesFromBuffer2
    call Delay3
    call LoadGBPal
    mov bl, 10                                  ; ld c, 10 — DelayFrames' counter is
                                                ; 8 bits on the GB and stays 8 bits here
    call DelayFrames
    jmp LoadWildData                            ; farjp LoadWildData (flat no-op bank switch)

; ---------------------------------------------------------------------------
; InGameTrade_PrepareTradeData — fill the wTraded* mirror the trade animation
; and the received mon read back.
;
; DEVIATION{class=data-model; pret=engine/events/in_game_trades.asm:InGameTrade_PrepareTradeData; behavior=the two copies out of InGameTrade_TrainerString are inline rep movsb instead of InGameTrade_CopyData-CopyData; evidence=InGameTrade_TrainerString is a flat program-image label from the generated assets-trades.inc while home/copy.asm CopyData biases its source with lea esi ebp+esi so a flat source cannot be passed to it, the same split already taken in engine/battle/draw_hud_pokeball_gfx.asm and engine/menus/draw_badges.asm, and the byte sequence written is identical; lifetime=permanent while ROM data lives outside the emulated GB address space}
; ---------------------------------------------------------------------------
InGameTrade_PrepareTradeData:
    mov esi, wTradedPlayerMonSpecies            ; ld hl, wTradedPlayerMonSpecies
    mov al, [ebp + wInGameTradeGiveMonSpecies]
    mov [ebp + esi], al                         ; ld [hli], a — wTradedPlayerMonSpecies
    inc esi
    mov al, [ebp + wInGameTradeReceiveMonSpecies]
    mov [ebp + esi], al                         ; ld [hl], a  — wTradedEnemyMonSpecies

    mov esi, wPartyMonOT                        ; ld hl, wPartyMonOT
    mov bx, NAME_LENGTH
    mov al, [ebp + wWhichPokemon]
    call AddNTimes
    mov edx, wTradedPlayerMonOT                 ; ld de, wTradedPlayerMonOT
    mov bx, NAME_LENGTH
    call InGameTrade_CopyData                   ; GB -> GB

    ; ld hl, InGameTrade_TrainerString (FLAT) / ld de, wTradedEnemyMonOT
    ; / call InGameTrade_CopyData  — inlined, see the DEVIATION above.
    push edi
    mov esi, InGameTrade_TrainerString
    mov ecx, NAME_LENGTH
    lea edi, [ebp + wTradedEnemyMonOT]
    rep movsb
    ; ld de, wLinkEnemyTrainerName / call InGameTrade_CopyData — the second copy
    ; reuses the same flat source, exactly as pret's preserved hl does.
    mov esi, InGameTrade_TrainerString
    mov ecx, NAME_LENGTH
    lea edi, [ebp + wLinkEnemyTrainerName]
    rep movsb
    pop edi

    mov esi, wPartyMon1OTID                     ; ld hl, wPartyMon1OTID
    mov bx, PARTYMON_STRUCT_LENGTH
    mov al, [ebp + wWhichPokemon]
    call AddNTimes
    mov edx, wTradedPlayerMonOTID               ; ld de, wTradedPlayerMonOTID
    mov bx, 2                                   ; ld bc, $2
    call InGameTrade_CopyData                   ; GB -> GB (BX survives it)

    call Random
    mov esi, hRandomAdd                         ; ld hl, hRandomAdd (HRAM, GB offset)
    mov edx, wTradedEnemyMonOTID                ; ld de, wTradedEnemyMonOTID
    jmp CopyData                                ; jp CopyData — BX is still 2

; ---------------------------------------------------------------------------
; InGameTrade_CopyData — CopyData with HL/BC preserved.
; ---------------------------------------------------------------------------
InGameTrade_CopyData:
    push esi                                    ; push hl
    push ebx                                    ; push bc
    call CopyData
    pop ebx                                     ; pop bc
    pop esi                                     ; pop hl
    ret

; ---------------------------------------------------------------------------
; InGameTrade_CopyDataToReceivedMon — nickname / OT name / OT ID of the mon just
; added to the party.
;
; DEVIATION{class=data-model; pret=engine/events/in_game_trades.asm:InGameTrade_CopyDataToReceivedMon; behavior=the OT-name copy out of InGameTrade_TrainerString is an inline rep movsb instead of CopyData; evidence=InGameTrade_TrainerString is a flat program-image label from the generated assets-trades.inc and home/copy.asm CopyData biases its source with lea esi ebp+esi so it cannot take a flat source, while the destination and the 11 bytes written are unchanged; lifetime=permanent while ROM data lives outside the emulated GB address space}
; ---------------------------------------------------------------------------
InGameTrade_CopyDataToReceivedMon:
    mov esi, wPartyMonNicks                     ; ld hl, wPartyMonNicks
    mov bx, NAME_LENGTH
    call InGameTrade_GetReceivedMonPointer      ; -> edx = &nick of the new mon
    mov esi, wInGameTradeMonNick                ; ld hl, wInGameTradeMonNick
    mov bx, NAME_LENGTH
    call CopyData                               ; GB -> GB

    mov esi, wPartyMonOT                        ; ld hl, wPartyMonOT
    mov bx, NAME_LENGTH
    call InGameTrade_GetReceivedMonPointer      ; -> edx = &OT name of the new mon
    ; ld hl, InGameTrade_TrainerString (FLAT) / ld bc, NAME_LENGTH / call CopyData
    push edi
    mov esi, InGameTrade_TrainerString
    mov ecx, NAME_LENGTH
    movzx edi, dx
    lea edi, [ebp + edi]
    rep movsb
    pop edi

    mov esi, wPartyMon1OTID                     ; ld hl, wPartyMon1OTID
    mov bx, PARTYMON_STRUCT_LENGTH
    call InGameTrade_GetReceivedMonPointer      ; -> edx = &OT ID of the new mon
    mov esi, wTradedEnemyMonOTID                ; ld hl, wTradedEnemyMonOTID
    mov bx, 2                                   ; ld bc, 2
    jmp CopyData                                ; jp CopyData — GB -> GB

; ---------------------------------------------------------------------------
; InGameTrade_GetReceivedMonPointer — the received mon's index is
; (partyCount - 1), so this adds BX to ESI (partyCount - 1) times and moves the
; result to EDX.
; ---------------------------------------------------------------------------
InGameTrade_GetReceivedMonPointer:
    mov al, [ebp + wPartyCount]
    dec al                                      ; dec a
    call AddNTimes
    mov edx, esi                                ; ld e,l / ld d,h  (ESI is a GB offset < $10000)
    ret

; ---------------------------------------------------------------------------
; InGameTrade_FlagActionPredef — test/set this trade's completion flag.
;
; DEVIATION{class=banking; pret=macros/predef.asm:predef_jump; behavior=Predef dispatch replaced by a direct jmp to the FlagAction leaf, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus FlagActionPredef's own first act is GetPredefRegisters which would overwrite ESI and EBX from the stale wPredefHL and wPredefBC slots - the same direct-leaf convention already used by home/trainers.asm TrainerFlagAction and engine/pokemon/evos_moves.asm; lifetime=retired when PredefPointers is ported}
;
; In:  BH = FLAG_TEST / FLAG_SET.   Out: CL = flag value (FLAG_TEST).
; ---------------------------------------------------------------------------
InGameTrade_FlagActionPredef:
    mov esi, wCompletedInGameTradeFlags         ; ld hl, wCompletedInGameTradeFlags
    mov al, [ebp + wWhichTrade]                 ; ld a, [wWhichTrade]
    mov cl, al                                  ; ld c, a
    jmp FlagAction                              ; predef_jump FlagActionPredef

; ---------------------------------------------------------------------------
; InGameTrade_CheckForTradeEvo — the four trade-evolution species.
; ---------------------------------------------------------------------------
InGameTrade_CheckForTradeEvo:
    mov al, [ebp + wInGameTradeReceiveMonSpecies]
    cmp al, KADABRA
    jz .tradeEvo
    cmp al, GRAVELER
    jz .tradeEvo
    cmp al, MACHOKE
    jz .tradeEvo
    cmp al, HAUNTER
    jz .tradeEvo
    ret

.tradeEvo:
    mov al, [ebp + wPartyCount]
    dec al                                      ; dec a
    mov [ebp + wWhichPokemon], al
    mov al, 1                                   ; ld a, $1
    mov [ebp + wForceEvolution], al
    mov al, LINK_STATE_TRADING
    mov [ebp + wLinkState], al
    call TryEvolvingMon                         ; callfar TryEvolvingMon (flat no-op bank switch)
    xor al, al                                  ; xor a ; LINK_STATE_NONE
    mov [ebp + wLinkState], al
    jmp PlayDefaultMusic                        ; jp PlayDefaultMusic

; ---------------------------------------------------------------------------
section .bss
align 4
; Port-local 32-bit flat cursor — see the DEVIATION on DoInGameTradeDialogue.
; pret keeps the same value in the two GB bytes at wInGameTradeTextPointerTablePointer
; ($CD10); a flat program-image address does not fit there.
wInGameTradeTextPointerTablePointer32: resd 1

; ---------------------------------------------------------------------------
section .data

;
; pret writes `INCLUDE "data/events/trades.asm"` here, pulling TradeMons into
; this file. The port does NOT: TradeMons is a pret data/events/ label, so the
; mirror rule puts it in src/data/events/trades.asm (its own .data carrier over
; assets/trades.inc). Including it here instead is an `aux_misplaced` violation.
; This file externs it, above.
;
; InGameTrade_TrainerString DOES belong here — pret defines that one in this
; file, not in the data file — so its generated bytes come in on their own.
%include "assets/trade_trainer_string.inc"

%include "assets/in_game_trade_text.inc"

; entries correspond to TRADE_DIALOGSET_* constants.
; pret `dw` (bank-relative) -> `dd` (flat DPMI linear).
InGameTradeTextPointers:
    dd TradeTextPointers1
    dd TradeTextPointers2
    dd TradeTextPointers3

TradeTextPointers1:
    dd WannaTrade1Text
    dd NoTrade1Text
    dd WrongMon1Text
    dd Thanks1Text
    dd AfterTrade1Text

TradeTextPointers2:
    dd WannaTrade2Text
    dd NoTrade2Text
    dd WrongMon2Text
    dd Thanks2Text
    dd AfterTrade2Text

TradeTextPointers3:
    dd WannaTrade3Text
    dd NoTrade3Text
    dd WrongMon3Text
    dd Thanks3Text
    dd AfterTrade3Text

ConnectCableText:
    text_far _ConnectCableText
    text_end

TradedForText:
    text_far _TradedForText
    sound_get_key_item
    text_pause
    text_end

WannaTrade1Text:
    text_far _WannaTrade1Text
    text_end

NoTrade1Text:
    text_far _NoTrade1Text
    text_end

WrongMon1Text:
    text_far _WrongMon1Text
    text_end

Thanks1Text:
    text_far _Thanks1Text
    text_end

AfterTrade1Text:
    text_far _AfterTrade1Text
    text_end

WannaTrade2Text:
    text_far _WannaTrade2Text
    text_end

NoTrade2Text:
    text_far _NoTrade2Text
    text_end

WrongMon2Text:
    text_far _WrongMon2Text
    text_end

Thanks2Text:
    text_far _Thanks2Text
    text_end

AfterTrade2Text:
    text_far _AfterTrade2Text
    text_end

WannaTrade3Text:
    text_far _WannaTrade3Text
    text_end

NoTrade3Text:
    text_far _NoTrade3Text
    text_end

WrongMon3Text:
    text_far _WrongMon3Text
    text_end

Thanks3Text:
    text_far _Thanks3Text
    text_end

AfterTrade3Text:
    text_far _AfterTrade3Text
    text_end
