; ===========================================================================
; pokedex_rating.asm — pret mirror of engine/events/pokedex_rating.asm.
;
; DisplayDexRating — Oak's PC / OaksLabOak1Text pokédex-rating cutscene.
; Counts owned/seen species via CountSetBits, looks up DexRatingsTable (an
; owned-count-banded threshold table) for the matching rating band text, then:
;   - first viewing (EVENT_HALL_OF_FAME_DEX_RATING clear): prints
;     DexCompletionText + the matched band text and plays the fanfare
;     (PlayPokedexRatingSfx), then waits for a button press; or
;   - subsequent viewing (event already set): copies
;     {seen, owned, ratingText-up-to-terminator} into
;     wDexRatingNumMonsSeen/wDexRatingNumMonsOwned/wDexRatingText, which
;     HallOfFame's own printout reads later (that routine is out of this
;     file's scope).
;
; TWO-TIER RULE (CLAUDE.md / project-conventions): the 17 text streams
; (DexCompletionText + the 16 DexRatingText_Own<N>To<M> bands) are Tier-1
; DATA, generated by tools/generators/gen_pokedex_rating_text.py from pret's
; text/pokedex_ratings.asm into assets/pokedex_rating_text.inc (%included
; below, section .data). DexRatingsTable is Tier-2: it is a hand-written
; threshold+pointer DISPATCH table, not rendered text — project-conventions'
; own example is exactly this shape ("a dw/dd table of ... routine addresses
; is code (Tier 2), hand-written in the .asm").
;
; Register map (CLAUDE.md): A=AL, HL=ESI, BC=BX (B=BH), DE=DX, EBP=GB base.
; TWO ADDRESS SPACES SHARE ESI IN THIS ROUTINE, and mixing them is the defect
; this header exists to prevent:
;   * emulated GB memory (wPokedexSeen, wDexRating*, hDexRating*) is
;     [ebp + SYM] — gb_memmap.inc symbols are GB offsets;
;   * DexRatingsTable and every text-stream label are FLAT program-image
;     .data addresses (this port's flat TX_FAR model — PrintText's own
;     `In: ESI = flat pointer` contract, src/home/window.asm:110), so they
;     are loaded with `mov esi, Label` and dereferenced as [esi] with NO ebp.
; pret has one address space and cannot express the distinction, so every
; `[hli]` below is annotated with which space it reads.
;
; Build (standalone check):
;   nasm -f coff -I include/ -I . -D BUG_FIX_LEVEL=0 -o /dev/null pokedex_rating.asm
; ===========================================================================

bits 32

%include "gb_memmap.inc"
%include "gb_text.inc"                  ; TX_END ('@' charmap terminator, constants/charmap.asm: charmap "@", $50)
%include "events.inc"
%include "assets/event_constants.inc"   ; EVENT_HALL_OF_FAME_DEX_RATING

global DisplayDexRating
global DexRatingsTable

extern CountSetBits                     ; src/home/count_set_bits.asm — In: ESI=addr, BH=len; Out: [wNumSetBits]
extern PrintText                        ; src/home/window.asm — In: ESI = flat text-stream pointer
extern WaitForTextScrollButtonPress     ; src/home/joypad2.asm
extern PlayPokedexRatingSfx             ; src/audio/pokedex_rating_sfx.asm

; ===========================================================================
; Tier-1 DATA: the 17 rating/completion text streams (pret
; text/pokedex_ratings.asm, wrapped by this file's text_far labels).
%include "assets/pokedex_rating_text.inc"

; ===========================================================================
section .text

; ---------------------------------------------------------------------------
; DisplayDexRating — pret ref: engine/events/pokedex_rating.asm:DisplayDexRating.
; In: EBP = GB base. No arguments; no caller reads a return value from it
; (OpenOaksPC falls straight through to ClosedOaksPCText, OaksLabOak1Text
; falls through to .done — matches the ret-stub contract this replaces; see
; the deleted DisplayDexRating block formerly in oaks_pc_stubs.asm).
; ---------------------------------------------------------------------------
DisplayDexRating:
    mov esi, wPokedexSeen                    ; ld hl, wPokedexSeen
    mov bh, wPokedexSeenEnd - wPokedexSeen   ; ld b, wPokedexSeenEnd - wPokedexSeen
    call CountSetBits
    mov al, [ebp + wNumSetBits]               ; ld a, [wNumSetBits]
    mov [ebp + hDexRatingNumMonsSeen], al     ; ldh [hDexRatingNumMonsSeen], a

    mov esi, wPokedexOwned                    ; ld hl, wPokedexOwned
    mov bh, wPokedexOwnedEnd - wPokedexOwned ; ld b, wPokedexOwnedEnd - wPokedexOwned
    call CountSetBits
    mov al, [ebp + wNumSetBits]               ; ld a, [wNumSetBits]
    mov [ebp + hDexRatingNumMonsOwned], al    ; ldh [hDexRatingNumMonsOwned], a

    mov esi, DexRatingsTable                  ; ld hl, DexRatingsTable
.findRating:
    mov al, [esi]                             ; ld a, [hli]   (this entry's threshold)
    inc esi                                   ; DexRatingsTable is FLAT .data (program image),
                                              ; NOT emulated GB memory - no ebp bias here.
    mov bh, al                                ; ld b, a   (B = BH, register map)
    mov al, [ebp + hDexRatingNumMonsOwned]    ; ldh a, [hDexRatingNumMonsOwned]
    cmp al, bh                                ; cp b
    jb .foundRating                           ; jr c, .foundRating (unsigned: owned < threshold)
    add esi, 4                                ; inc hl / inc hl (port: entries carry a flat
                                              ; 32-bit `dd` pointer, not pret's 16-bit `dw` —
                                              ; skip 4 bytes, not 2; see DexRatingsTable below)
    jmp .findRating

.foundRating:
    mov esi, [esi]                            ; ld a, [hli] / ld h, [hl] / ld l, a — the GB
                                              ; reconstructs a 16-bit pointer byte-by-byte;
                                              ; the port's dd entry is a single 32-bit flat
                                              ; load (same value, native width)
    CheckAndResetEventA EVENT_HALL_OF_FAME_DEX_RATING
    jnz .hallOfFame                           ; jr nz, .hallOfFame

    push esi                                  ; push hl
    mov esi, DexCompletionText                ; ld hl, DexCompletionText
    call PrintText
    pop esi                                   ; pop hl
    call PrintText
    call PlayPokedexRatingSfx                 ; farcall PlayPokedexRatingSfx (flat: no bank)
    jmp WaitForTextScrollButtonPress          ; jp WaitForTextScrollButtonPress

.hallOfFame:
    mov edx, wDexRatingNumMonsSeen            ; ld de, wDexRatingNumMonsSeen
    mov al, [ebp + hDexRatingNumMonsSeen]     ; ldh a, [hDexRatingNumMonsSeen]
    mov [ebp + edx], al                       ; ld [de], a
    inc edx
    mov al, [ebp + hDexRatingNumMonsOwned]    ; ldh a, [hDexRatingNumMonsOwned]
    mov [ebp + edx], al                       ; ld [de], a
    inc edx

; DEVIATION{class=data-model; pret=engine/events/pokedex_rating.asm:DisplayDexRating; behavior=the loop below copies the WHOLE flattened text stream into wDexRatingText where the GB copies only the 4-byte TX_FAR command that points at it, so the copied byte count is 37-76 instead of 5; evidence=the port has no ROM banks, so gen_pokedex_rating_text.py flattens each text_far wrapper into its literal bytes and PrintText consumes a flat stream (src/home/window.asm:110) - the printed result is identical, only the intermediate encoding differs; lifetime=permanent, inherent to the port's flat TX_FAR model}
; Bound check (the reason this is safe, not merely different): pret's union at
; wDexRatingNumMonsSeen spans 180 bytes (ram/wram.asm, shared with
; wNPCMovementDirections ds 180), wDexRatingText sits at +2, and the longest
; band stream is DexRatingText_Own50To59 at 76 bytes -- 76 <= 178. Regenerate
; assets/pokedex_rating_text.inc and re-check that bound if pret's text changes.
.copyRatingTextLoop:
    mov al, [esi]                             ; ld a, [hli]  (flat text stream - PrintText's
    inc esi                                   ; own In: contract is a flat pointer, so no ebp)
    cmp al, TX_END                            ; cp '@'  ('@' is charmap-encoded to $50,
                                              ; constants/charmap.asm: charmap "@", $50 —
                                              ; NOT ascii 0x40; TX_END is the same $50)
    je .doneCopying                           ; jr z, .doneCopying
    mov [ebp + edx], al                       ; ld [de], a
    inc edx
    jmp .copyRatingTextLoop

.doneCopying:
    mov [ebp + edx], al                       ; ld [de], a   (writes the terminator byte itself)
    ret

; ---------------------------------------------------------------------------
; DexRatingsTable — pret ref: same file. Owned-count-banded dispatch table:
; pret's `dbw threshold, TextLabel` (RGBDS: 1-byte threshold + 2-byte
; bank-relative pointer) becomes {db threshold; dd TextLabel} here — a flat
; 32-bit pointer, per this port's flat-memory model (no banks; see every
; other hand-written pointer table in dos_port/src/data/, e.g.
; MoveEffectPointerTable: "pret's dw (bank-relative) becomes dd (flat DPMI
; linear)"). Only ever read by .findRating above (never executed), so it
; lives in .data like its siblings.
;
; Boundaries taken verbatim from pret (constants/pokedex_constants.asm:
; NUM_POKEMON EQU 151 — not defined anywhere in this port's include/ or
; assets/, so its one use below is the literal 152, per the same convention
; oaks_aide.asm uses for OAKS_AIDE_* — do not invent a port constant for a
; single call site). .findRating's `cp b` / `jr c` is an UNSIGNED compare
; against the threshold, so band N is "fewer than threshold(N)", i.e. the
; boundaries below read as: owned 0-9 -> Own0To9, 10-19 -> Own10To19, ...,
; 140-149 -> Own140To149, 150-151 -> Own150To151.
; ---------------------------------------------------------------------------
section .data

DexRatingsTable:
    db 10
    dd DexRatingText_Own0To9
    db 20
    dd DexRatingText_Own10To19
    db 30
    dd DexRatingText_Own20To29
    db 40
    dd DexRatingText_Own30To39
    db 50
    dd DexRatingText_Own40To49
    db 60
    dd DexRatingText_Own50To59
    db 70
    dd DexRatingText_Own60To69
    db 80
    dd DexRatingText_Own70To79
    db 90
    dd DexRatingText_Own80To89
    db 100
    dd DexRatingText_Own90To99
    db 110
    dd DexRatingText_Own100To109
    db 120
    dd DexRatingText_Own110To119
    db 130
    dd DexRatingText_Own120To129
    db 140
    dd DexRatingText_Own130To139
    db 150
    dd DexRatingText_Own140To149
    db 152                                    ; NUM_POKEMON + 1 (151 + 1)
    dd DexRatingText_Own150To151
