#!/usr/bin/env python3
"""gen_badge_maps.py — generate dos_port/assets/badge_maps.inc (Tier 1 data).

pret data/maps/badge_maps.asm defines MapBadgeFlags.
Emits the table into assets/badge_maps.inc so it is recognized as generated Tier-1
data and included where needed.

DO NOT EDIT the output by hand — re-run this generator.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "dos_port" / "assets" / "badge_maps.inc"


def main() -> int:
    out = [
        "; badge_maps.inc — generated by tools/generators/gen_badge_maps.py.",
        "; DO NOT EDIT BY HAND.",
        "; Map badge flags table (pret data/maps/badge_maps.asm).",
        "; section .data (see link.ld).",
        "",
        '%include "assets/map_dims.inc"',
        '%include "assets/script_constants.inc"',
        "",
        "section .data",
        "align 4",
        "",
        "global MapBadgeFlags",
        "MapBadgeFlags:",
        "    db PEWTER_GYM,    1 << BIT_BOULDERBADGE",
        "    db CERULEAN_GYM,  1 << BIT_CASCADEBADGE",
        "    db VERMILION_GYM, 1 << BIT_THUNDERBADGE",
        "    db CELADON_GYM,   1 << BIT_RAINBOWBADGE",
        "    db FUCHSIA_GYM,   1 << BIT_SOULBADGE",
        "    db SAFFRON_GYM,   1 << BIT_MARSHBADGE",
        "    db CINNABAR_GYM,  1 << BIT_VOLCANOBADGE",
        "    db VIRIDIAN_GYM,  1 << BIT_EARTHBADGE",
        "    db 0xFF ; -1 end",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
