#!/usr/bin/env python3
"""gen_map_scripts.py — generate dos_port/assets/map_scripts.inc from pret source.

Emits the per-map script dispatch table (script engine plan, Stage 5):

  MapScriptPointers:  NUM_MAPS flat (dd) pointers, indexed by wCurMap. RunMapScript
                      calls MapScriptPointers[wCurMap] every overworld frame. Maps
                      without a ported _Script default to DefaultMapScript (a no-op);
                      a small SCRIPT_OVERRIDES registry names the ported ones (the
                      same pattern as gen_npc_dialogs' SCRIPT_OVERRIDES and the flat
                      EvosMovesPointerTable / WildDataPointers tables).

Run from repo root (or dos_port/); paths resolve relative to the repo root.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"

# map const name -> ported _Script label. Default (absent) -> DefaultMapScript.
# Extend as per-map scripts are translated (script engine milestones).
SCRIPT_OVERRIDES = {
    "PALLET_TOWN": "PalletTown_Script",
}


def parse_map_order():
    """Ordered list of map const names from constants/map_constants.asm (= wCurMap)."""
    maps = []
    for line in (ROOT / "constants/map_constants.asm").read_text().splitlines():
        m = re.match(r"\s*map_const\s+(\w+)\s*,", line)
        if m:
            maps.append(m.group(1))
    return maps


def main():
    maps = parse_map_order()
    unknown = set(SCRIPT_OVERRIDES) - set(maps)
    if unknown:
        sys.exit(f"gen_map_scripts: SCRIPT_OVERRIDES names unknown maps: {sorted(unknown)}")

    out = []
    out.append("; AUTO-GENERATED by tools/generators/gen_map_scripts.py — do not edit.")
    out.append("; Per-map script dispatch (script engine plan, Stage 5).")
    out.append(f"; MapScriptPointers: {len(maps)} flat (dd) pointers, indexed by wCurMap.")
    out.append("")
    out.append("MapScriptPointers:")
    for i, name in enumerate(maps):
        label = SCRIPT_OVERRIDES.get(name, "DefaultMapScript")
        out.append(f"    dd {label:<22} ; 0x{i:02X} {name}")
    out.append("")

    dst = ASSETS / "map_scripts.inc"
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(out) + "\n")
    n_real = len(SCRIPT_OVERRIDES)
    print(f"wrote {dst} (MapScriptPointers {len(maps)} entries, "
          f"{n_real} ported script(s), rest DefaultMapScript)")


if __name__ == "__main__":
    main()
