#!/usr/bin/env python3
"""gen_battle_transition_arcs.py — regenerate the battle-transition circle-wipe
arc tables for the port's 40x25 canvas.

pret's BattleTransition_CircleData1-5 / HalfCircle1-2 tables are hand-drawn
20x18 wedge data consumed by BattleTransition_Circle_Sub3. The port's canvas is
40x25, so the tables are regenerated (Tier-1 data): 10 wedges per half circle
(HALF_CIRCLE_STEPS, keeping the GB's step count and timing), each wedge k being
the angle bin [k*18deg, (k+1)*18deg) sweeping counterclockwise from 3 o'clock.
Angles are computed in DISPLAY space (cell y scaled by 1.2 — 320x200 on a 4:3
monitor) about center (20.0, 12.5), so the wipe looks circular on screen.
HalfCircle1 = bins 0-9 (top half), HalfCircle2 = bins 10-19 (bottom half),
paired k / k+10 for DoubleCircle's two opposed arms.

Encoding is pret's Circle_Sub3 format, unchanged: per row a run byte, then a
separator byte (skip amount, 0 = none, $ff = end); RIGHT-quadrant wedges write
incrementing x and skip decrementing (LEFT mirrored); rows are ordered
edge->center (HalfCircle1 steps +SCREEN_WIDTH, HalfCircle2 -SCREEN_WIDTH).
The port entry struct is: quadrant byte + 32-bit flat data pointer + 32-bit GB
tilemap offset (BT_ARC_ENTRY_SIZE = 9; pret's `ld bc, 5`).

The generator EMBEDS a Sub3 emulator as a self-check: every entry is emulated
and asserted to reproduce exactly its wedge's cell set, and the union of all 20
wedges must be the full 1000-cell canvas.
"""
import math
import os
import sys

W, H = 40, 25
CX, CY = 20.0, 12.5
ASPECT = 1.2          # display-space y scale (320x200 on a 4:3 monitor)
NWEDGE = 20
W_TILEMAP = 0xC3A0    # must match include/gb_memmap.inc

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "assets",
                   "battle_transition_arcs.inc")


def bin_of(x, y):
    dx = (x + 0.5) - CX
    dy = (CY - (y + 0.5)) * ASPECT          # screen-up positive => CCW from 3 o'clock
    ang = math.degrees(math.atan2(dy, dx)) % 360.0
    return int(ang // (360.0 / NWEDGE)) % NWEDGE


def build_entries():
    cells = {}
    for y in range(H):
        for x in range(W):
            cells.setdefault(bin_of(x, y), []).append((x, y))

    entries = []
    for k in range(NWEDGE):
        cs = cells.get(k)
        assert cs, f"wedge {k} is empty"
        right = k <= 4 or k >= 15           # right half of the screen
        tophalf = k < 10                    # HalfCircle1 (+SW row step)
        rows = {}
        for (x, y) in cs:
            rows.setdefault(y, []).append(x)
        for y, xs in rows.items():
            xs.sort()
            assert xs == list(range(xs[0], xs[0] + len(xs))), \
                f"wedge {k} row {y} not one contiguous interval"
        order = sorted(rows) if tophalf else sorted(rows, reverse=True)
        assert order == list(range(order[0], order[-1] + 1)) or \
               order == list(range(order[0], order[-1] - 1, -1)), \
            f"wedge {k} rows not consecutive"
        data = []
        start = None
        prev = None
        for y in order:
            xs = rows[y]
            sx = xs[0] if right else xs[-1]     # run start (write toward the edge dir)
            run = len(xs)
            assert 0 < run <= W
            if prev is None:
                start = (sx, y)
            else:
                skip = (prev - sx) if right else (sx - prev)
                assert 0 <= skip < 0xFF, f"wedge {k} bad skip {skip}"
                data.append(skip)
            data.append(run)
            prev = sx
        data.append(0xFF)
        entries.append(dict(k=k, right=right, tophalf=tophalf, start=start,
                            data=data, cells=set(cs)))
    return entries


def emulate(e):
    """pret BattleTransition_Circle_Sub3, exactly."""
    x, y = e["start"]
    written = set()
    d = e["data"]
    i = 0
    while True:
        run = d[i]; i += 1
        row_x = x
        for _ in range(run):
            assert 0 <= x < W and 0 <= y < H, \
                f"wedge {e['k']}: OOB write at {(x, y)}"
            written.add((x, y))
            x = x + 1 if e["right"] else x - 1
        x = row_x                                 # pop hl
        y = y + 1 if e["tophalf"] else y - 1      # +/-SCREEN_WIDTH
        sep = d[i]; i += 1
        if sep == 0xFF:
            return written
        if sep:
            x = x - sep if e["right"] else x + sep


def main():
    entries = build_entries()
    total = set()
    nbytes = 0
    for e in entries:
        w = emulate(e)
        assert w == e["cells"], f"wedge {e['k']}: emulation != wedge cell set"
        total |= w
        nbytes += len(e["data"])
    assert len(total) == W * H, f"union covers {len(total)}/{W * H} cells"

    out = []
    out.append("; DO NOT EDIT BY HAND — generated by "
               "tools/generators/gen_battle_transition_arcs.py")
    out.append("; 40x25 circle-wipe arc tables (pret Circle_Sub3 encoding); see the")
    out.append("; generator docstring. Self-checked: per-wedge emulation matches, union")
    out.append(f"; = {W * H}/{W * H} cells, {nbytes} data bytes.")
    out.append("HALF_CIRCLE_STEPS equ 10           ; pret's `SCREEN_WIDTH / 2` was a 20x18 collision")
    out.append("BT_ARC_ENTRY_SIZE equ 9            ; db quadrant + dd data + dd coord (pret: 5)")
    out.append("CIRCLE_LEFT       equ 0")
    out.append("CIRCLE_RIGHT      equ 1")
    for name, half in (("BattleTransition_HalfCircle1", entries[0:10]),
                       ("BattleTransition_HalfCircle2", entries[10:20])):
        out.append(f"{name}:")
        for e in half:
            sx, sy = e["start"]
            quad = "CIRCLE_RIGHT" if e["right"] else "CIRCLE_LEFT"
            out.append(f"    db {quad}")
            out.append(f"    dd BattleTransition_ArcData{e['k']}")
            out.append(f"    dd {sy} * 40 + {sx} + 0x{W_TILEMAP:04X}  ; ({sx},{sy})")
    for e in entries:
        bs = ", ".join(f"0x{b:02X}" for b in e["data"])
        out.append(f"BattleTransition_ArcData{e['k']}: db {bs}")
    out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"gen_battle_transition_arcs: {len(entries)} wedges, {nbytes} data bytes "
          f"-> {os.path.relpath(OUT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
