#!/usr/bin/env python3
"""Generate the Tier-1 pikapic (Pikachu front-pic facial animation) data.

Deterministic transcription of four read-only pret sources:

  gfx/pikachu.asm                        -> assets/pikachu_pic_gfx.inc
  data/pikachu/pikachu_pic_tilemaps.asm  -> assets/pikachu_pic_tilemaps.inc
  data/pikachu/pikachu_pic_objects.asm   -> assets/pikachu_pic_objects.inc
  data/pikachu/pikachu_pic_animation.asm -> assets/pikachu_pic_animation.inc

One generated .inc per pret source file, because a Tier-1 table's placement is
its carrier's placement and a carrier sits at exactly one mirrored pret path
(faithfulness-review skill, "aux_misplaced").

The port carriers that %include these are:
  dos_port/src/gfx/pikachu.asm
  dos_port/src/data/pikachu/pikachu_pic_tilemaps.asm
  dos_port/src/data/pikachu/pikachu_pic_objects.asm
  dos_port/src/data/pikachu/pikachu_pic_animation.asm

TWO PROJECTIONS ARE APPLIED, both forced by the flat 32-bit model and both
annotated at the consuming routine in
dos_port/src/engine/pikachu/pikachu_pic_animation.asm:

  * every pret `dw <label>` pointer table becomes `dd` (flat program-image
    pointer, not a 16-bit GB address).  This changes the TABLE STRIDE, so the
    engine indexes PikaPicAnimPointers / PikaPicAnimBGFramesPointers /
    PikaPicTilemapPointers by *4 where pret uses *2.
  * PikaPicAnimGFXHeaders is 8 bytes per record (db size, db bank, dw len,
    dd ptr) where pret uses 4 (db size, dba pointer).  The extra `len` is the
    blob's byte length, which the port needs to stage a compressed .pic into
    the GB-space PIC_STAGE scratch before UncompressSpriteData can read it.

Everything else — the animation bytecode, the frame lists, the tilemaps, the
graphics — is byte-for-byte what rgbasm would emit.

Run from the repo root:
  python3 dos_port/tools/generators/gen_pikachu_pic.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PRET_GFX = ROOT / "gfx" / "pikachu.asm"
PRET_TILEMAPS = ROOT / "data" / "pikachu" / "pikachu_pic_tilemaps.asm"
PRET_OBJECTS = ROOT / "data" / "pikachu" / "pikachu_pic_objects.asm"
PRET_ANIM = ROOT / "data" / "pikachu" / "pikachu_pic_animation.asm"
OUTDIR = ROOT / "dos_port" / "assets"

HEADER = (
    "; DO NOT EDIT BY HAND — generated by tools/generators/gen_pikachu_pic.py\n"
    "; Source: pret {src}\n"
)

# pikapic command opcodes, in the const_def order of macros/pikachu.asm.
CMD_NOP = 0x00
CMD_WRITEBYTE = 0x01
CMD_LOADGFX = 0x02
CMD_ANIMATION = 0x03
CMD_NOP4 = 0x04
CMD_NOP5 = 0x05
CMD_DELETEOBJECT = 0x06
CMD_NOP7 = 0x07
CMD_NOP8 = 0x08
CMD_JUMP = 0x09
CMD_SETDURATION = 0x0A
CMD_CRY = 0x0B
CMD_THUNDERBOLT = 0x0C
CMD_WAITBGMAP = 0x0D
CMD_RET = 0x0E


def strip(line: str) -> str:
    """Drop an rgbasm end-of-line comment and trailing whitespace."""
    return line.split(";")[0].rstrip()


def num(tok: str) -> int:
    """rgbasm integer literal -> int (handles $hex, %binary, decimal, -1)."""
    tok = tok.strip()
    neg = tok.startswith("-")
    if neg:
        tok = tok[1:]
    if tok.startswith("$"):
        v = int(tok[1:], 16)
    elif tok.startswith("%"):
        v = int(tok[1:], 2)
    else:
        v = int(tok, 10)
    if neg:
        v = (-v) & 0xFF
    return v


def db_rows(data: bytes, per_row: int = 16, indent: str = "    ") -> list[str]:
    out = []
    for i in range(0, len(data), per_row):
        chunk = data[i:i + per_row]
        out.append(indent + "db " + ", ".join(f"0x{b:02X}" for b in chunk))
    return out


# ---------------------------------------------------------------------------
# 1. gfx/pikachu.asm — the raw 2bpp / compressed .pic blobs
# ---------------------------------------------------------------------------
def gen_gfx() -> dict[str, int]:
    """Emit the graphics blobs. Returns {label: byte length}."""
    text = PRET_GFX.read_text()
    pairs = re.findall(r'^(\w+)::\s*\nINCBIN "([^"]+)"', text, re.M)
    if not pairs:
        raise SystemExit("gen_pikachu_pic: no INCBIN pairs in gfx/pikachu.asm")

    lengths: dict[str, int] = {}
    lines = [HEADER.format(src="gfx/pikachu.asm")]
    for label, relpath in pairs:
        blob = (ROOT / relpath).read_bytes()
        lengths[label] = len(blob)
        lines.append(f"; {relpath} ({len(blob)} bytes)")
        lines.append(f"{label}:")
        lines.extend(db_rows(blob))
        lines.append(f"{label}_LEN equ $ - {label}")
        lines.append("")
    (OUTDIR / "pikachu_pic_gfx.inc").write_text("\n".join(lines) + "\n")

    # Declaration side-files: the blob labels are DEFINED by src/gfx/pikachu.asm
    # and REFERENCED by src/data/pikachu/pikachu_pic_animation.asm
    # (PikaPicAnimGFXHeaders), so each carrier needs the matching directive list.
    hdr = HEADER.format(src="gfx/pikachu.asm")
    (OUTDIR / "pikachu_pic_gfx_globals.inc").write_text(
        hdr + "\n".join(f"global {lbl}" for lbl, _ in pairs) + "\n")
    (OUTDIR / "pikachu_pic_gfx_externs.inc").write_text(
        hdr + "\n".join(f"extern {lbl}" for lbl, _ in pairs) + "\n")
    return lengths


# ---------------------------------------------------------------------------
# 2. data/pikachu/pikachu_pic_tilemaps.asm
# ---------------------------------------------------------------------------
def gen_tilemaps() -> list[str]:
    """Emit PikaPicTilemapPointers + the tilemap bodies. Returns the pointer order."""
    lines_in = PRET_TILEMAPS.read_text().splitlines()

    order: list[str] = []
    body: list[str] = []
    in_table = False
    for raw in lines_in:
        line = strip(raw)
        if not line.strip():
            continue
        if line.startswith("MACRO") or line.strip() == "ENDM" or line.startswith("\\1_id"):
            continue
        if line.strip() == "dw \\1":
            continue
        if line.startswith("PikaPicTilemapPointers:"):
            in_table = True
            continue
        m = re.match(r"\s*pikatilemap_def\s+(\w+)", line)
        if m:
            assert in_table
            order.append(m.group(1))
            continue
        in_table = False
        body.append(line)

    out = [HEADER.format(src="data/pikachu/pikachu_pic_tilemaps.asm")]
    out.append("; PROJECTION: pret `dw` -> `dd` (flat pointers); stride 2 -> 4.")
    out.append("PikaPicTilemapPointers:")
    for lbl in order:
        out.append(f"    dd {lbl}")
    out.append("")
    for line in body:
        m = re.match(r"^(\w+):", line)
        if m:
            out.append(f"{m.group(1)}:")
            continue
        m = re.match(r"\s*db\s+(.*)$", line)
        if m:
            vals = [num(t) for t in m.group(1).split(",")]
            out.append("    db " + ", ".join(f"0x{v & 0xFF:02X}" for v in vals))
            continue
        raise SystemExit(f"gen_pikachu_pic: unhandled tilemap line: {line!r}")
    (OUTDIR / "pikachu_pic_tilemaps.inc").write_text("\n".join(out) + "\n")
    return order


# ---------------------------------------------------------------------------
# 3. data/pikachu/pikachu_pic_objects.asm
# ---------------------------------------------------------------------------
def gen_objects(tilemap_order: list[str]) -> list[str]:
    """Emit PikaPicAnimBGFramesPointers + the frame lists. Returns the pointer order."""
    tm_index = {lbl: i for i, lbl in enumerate(tilemap_order)}
    lines_in = PRET_OBJECTS.read_text().splitlines()

    order: list[str] = []
    out = [HEADER.format(src="data/pikachu/pikachu_pic_objects.asm")]
    out.append("; PROJECTION: pret `dw` -> `dd` (flat pointers); stride 2 -> 4.")
    body: list[str] = []
    in_table = False
    for raw in lines_in:
        line = strip(raw)
        if not line.strip():
            continue
        if (line.startswith("MACRO") or line.strip() == "ENDM"
                or line.startswith("\\1_id") or line.strip() == "dw \\1"
                or line.startswith("DEF ") or "\\1" in line or "\\2" in line):
            continue
        if line.startswith("PikaPicAnimBGFramesPointers:"):
            in_table = True
            continue
        m = re.match(r"\s*pikaanim_def\s+(\w+)", line)
        if m:
            assert in_table
            order.append(m.group(1))
            continue
        in_table = False

        m = re.match(r"^(\w+):", line)
        if m:
            body.append(f"{m.group(1)}:")
            continue
        m = re.match(r"\s*pikaframe\s+(\w+)\s*,\s*(-?\w+)", line)
        if m:
            idx = tm_index[m.group(1)]
            body.append(f"    db 0x{idx:02X}, 0x{num(m.group(2)):02X}"
                        f"    ; {m.group(1)}, {num(m.group(2))}")
            continue
        m = re.match(r"\s*pikaframedelay\s+(-?\w+)", line)
        if m:
            body.append(f"    db 0x00, 0x{num(m.group(1)):02X}    ; delay")
            continue
        if line.strip() == "pikaframeend":
            body.append("    db 0xE0")
            continue
        raise SystemExit(f"gen_pikachu_pic: unhandled objects line: {line!r}")

    out.append("PikaPicAnimBGFramesPointers:")
    for lbl in order:
        out.append(f"    dd {lbl}")
    out.append("")
    out.extend(body)
    (OUTDIR / "pikachu_pic_objects.inc").write_text("\n".join(out) + "\n")
    return order


# ---------------------------------------------------------------------------
# 4. data/pikachu/pikachu_pic_animation.asm
# ---------------------------------------------------------------------------
def gen_animation(frames_order: list[str], gfx_lengths: dict[str, int]) -> None:
    fr_index = {lbl: i for i, lbl in enumerate(frames_order)}
    lines_in = PRET_ANIM.read_text().splitlines()

    # -- pass 1: PikaPicAnimGFXHeaders (needed to resolve pikapic_loadgfx) ----
    gfx_records: list[tuple[int, int, str | None]] = []   # (size, bank, label|None)
    gfx_index: dict[str, int] = {}
    for raw in lines_in:
        line = strip(raw)
        m = re.match(r"\s*pikapicanimgfx\s+(-?\d+)\s*,\s*(.+)$", line)
        if not m:
            continue
        size = num(m.group(1))
        rest = [t.strip() for t in m.group(2).split(",")]
        if len(rest) == 1:
            gfx_index[rest[0]] = len(gfx_records)
            gfx_records.append((size, 0, rest[0]))
        else:
            bank = num(rest[0])
            addr = rest[1]
            assert addr == "NULL", addr
            gfx_records.append((size, bank, None))

    # -- pass 2: the animation scripts --------------------------------------
    out = [HEADER.format(src="data/pikachu/pikachu_pic_animation.asm")]
    out.append("; PROJECTION: pret `dw` -> `dd` for PikaPicAnimPointers and for the")
    out.append("; pikapic_jump operand; PikaPicAnimGFXHeaders is 8 bytes per record.")
    script_order: list[str] = []
    body: list[str] = []
    loop_seq = 0
    in_gfx_table = False
    in_ptr_table = False
    for raw in lines_in:
        line = strip(raw)
        if not line.strip():
            continue
        s = line.strip()
        if (s.startswith("MACRO") or s == "ENDM" or s.startswith("IF ")
                or s.startswith("ELSE") or s.startswith("ENDC")
                or s.startswith("\\2_id") or s.startswith("db \\1")
                or s.startswith("dba \\2") or s.startswith("dbw \\2")):
            continue
        if s.startswith("PikaPicAnimPointers:"):
            in_ptr_table = True
            continue
        m = re.match(r"pikapic_def\s+(\w+)", s)
        if m:
            assert in_ptr_table
            script_order.append(m.group(1))
            continue
        in_ptr_table = False
        if s.startswith("PikaPicAnimGFXHeaders:"):
            in_gfx_table = True
            continue
        if s.startswith("pikapicanimgfx"):
            assert in_gfx_table
            continue
        in_gfx_table = False

        m = re.match(r"^(\w+):", line)
        if m:
            body.append(f"{m.group(1)}:")
            continue
        m = re.match(r"pikapic_setduration\s+(-?\w+)", s)
        if m:
            body.append(f"    db 0x{CMD_SETDURATION:02X}\n    dw {num(m.group(1))}")
            continue
        m = re.match(r"pikapic_loadgfx\s+(\w+)", s)
        if m:
            body.append(f"    db 0x{CMD_LOADGFX:02X}, "
                        f"0x{gfx_index[m.group(1)]:02X}    ; {m.group(1)}")
            continue
        m = re.match(r"pikapic_animation\s+(\w+)\s*,\s*(\S+)\s*,\s*(\S+)\s*,\s*(\S+)", s)
        if m:
            body.append(
                f"    db 0x{CMD_ANIMATION:02X}, 0x{fr_index[m.group(1)]:02X}, 0x00, "
                f"0x{num(m.group(2)):02X}, 0x{num(m.group(3)):02X}, "
                f"0x{num(m.group(4)):02X}    ; {m.group(1)}")
            continue
        m = re.match(r"pikapic_writebyte\s+(-?\w+)", s)
        if m:
            body.append(f"    db 0x{CMD_WRITEBYTE:02X}, 0x{num(m.group(1)):02X}")
            continue
        m = re.match(r"pikapic_cry(?:\s+(\w+))?$", s)
        if m:
            if m.group(1) is None:
                body.append(f"    db 0x{CMD_CRY:02X}, 0xFF")
            else:
                cry = m.group(1)
                n = int(re.match(r"PikachuCry(\d+)$", cry).group(1)) - 1
                body.append(f"    db 0x{CMD_CRY:02X}, 0x{n:02X}    ; {cry}")
            continue
        if s == "pikapic_waitbgmap":
            body.append(f"    db 0x{CMD_WAITBGMAP:02X}")
            continue
        if s == "pikapic_thunderbolt":
            body.append(f"    db 0x{CMD_THUNDERBOLT:02X}")
            continue
        if s == "pikapic_ret":
            body.append(f"    db 0x{CMD_RET:02X}")
            continue
        if s == "pikapic_looptofinish":
            lbl = f".pikapic_loop{loop_seq}"
            loop_seq += 1
            body.append(f"{lbl}:")
            body.append(f"    db 0x{CMD_WAITBGMAP:02X}")
            body.append(f"    db 0x{CMD_JUMP:02X}\n    dd {lbl}")
            continue
        m = re.match(r"db\s+(-?\d+)\s*,\s*(%[01]+|\$[0-9a-fA-F]+|-?\d+)$", s)
        if m:      # PikaPicAnimThunderboltPals rows
            body.append(f"    db 0x{num(m.group(1)):02X}, 0x{num(m.group(2)):02X}")
            continue
        m = re.match(r"db\s+(-?\d+)$", s)
        if m:      # the pals terminator, `db -1`
            body.append(f"    db 0x{num(m.group(1)):02X}")
            continue
        raise SystemExit(f"gen_pikachu_pic: unhandled animation line: {line!r}")

    # PikaPicAnimPointers is NOT emitted here: pret defines it in the ENGINE
    # file (engine/pikachu/pikachu_pic_animation.asm:171), so the port's copy is
    # a hand-written flat `dd` table in the mirrored engine .asm.  Its order is
    # PikaPicAnimScript0..29, i.e. index == script number.
    assert not script_order, script_order
    out.extend(body)
    out.append("")
    out.append("; record: db size (tiles, 0xFF = compressed), db bank, dw byte length,")
    out.append(";         dd flat pointer.  8 bytes per record.")
    out.append("PikaPicAnimGFXHeaders:")
    for size, bank, label in gfx_records:
        if label is None:
            out.append(f"    db 0x{size & 0xFF:02X}, 0x{bank:02X}\n    dw 0\n    dd 0")
        else:
            out.append(f"    db 0x{size & 0xFF:02X}, 0x00\n"
                       f"    dw {gfx_lengths.get(label, 0)}\n"
                       f"    dd {label}")
    out.append("PIKAPIC_GFX_HEADER_SIZE equ 8")
    (OUTDIR / "pikachu_pic_animation.inc").write_text("\n".join(out) + "\n")


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    gfx_lengths = gen_gfx()
    # PikachuSprite lives in gfx/sprites/pikachu.2bpp (carried by
    # src/engine/gfx/mon_icons.asm), not in gfx/pikachu.asm; its GFX header
    # entry is an uncompressed 24-tile copy, so no staged length is needed.
    gfx_lengths.setdefault("PikachuSprite", 24 * 16)
    tilemaps = gen_tilemaps()
    frames = gen_objects(tilemaps)
    gen_animation(frames, gfx_lengths)
    print(f"gen_pikachu_pic: {len(gfx_lengths)} graphics, "
          f"{len(tilemaps)} tilemaps, {len(frames)} frame lists")


if __name__ == "__main__":
    main()
