#!/usr/bin/env python3
"""gen_gym_names.py — generate dos_port/assets/gym_names.inc.

The eight gyms each carry two inline strings in their pret map script:

    .CityName:
        db "CELADON CITY@"
    .LeaderName:
        db "ERIKA@"

read by `LoadGymLeaderAndCityName`. They are human-rendered text, so by the
project's two-tier rule they are Tier-1 DATA and must be produced by a generator
rather than hand-encoded as charmap hex — and the sm83xlat transpiler refuses to
encode them itself (`inline-text-db`), which is that rule working.

WHY MACROS RATHER THAN LABELS. The pret labels are LOCAL (`CeladonGym_Script.
CityName`), scoped to their script's global label, and a local label cannot be a
NASM global that other files extern. Emitting a macro instead lets the transpiled
script keep pret's own local label and pull only the BYTES from here:

    .CityName:
        TEXT_CeladonGym_Script_CityName

so the label structure stays line-for-line with pret, no symbol is defined twice
across the 224 script files, and the transpiler still owns no charmap knowledge.
Macros emit nothing until invoked, so including this everywhere costs nothing.

This also writes tools/sm83xlat/tables/text_assets.json — the map from pret label
to macro name that the transpiler reads. Generating both from ONE table here is
what keeps them from drifting apart.

Run from repo root or dos_port/.
"""
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
TABLES = ROOT / "dos_port" / "tools" / "sm83xlat" / "tables"
TERMINATOR = 0x50  # '@'

# (pret script file, pret parent label). The parent is the script's own global
# label, which is NOT simply the map name — CinnabarGym's is
# CinnabarGymSetMapAndTiles. The STRINGS are not listed here on purpose: they are
# read out of the pret source below, so this generator cannot disagree with the
# disassembly it is mirroring.
GYMS = [
    ("scripts/PewterGym.asm",    "PewterGym_Script"),
    ("scripts/CeruleanGym.asm",  "CeruleanGym_Script"),
    ("scripts/VermilionGym.asm", "VermilionGym_Script"),
    ("scripts/CeladonGym.asm",   "CeladonGym_Script"),
    ("scripts/FuchsiaGym.asm",   "FuchsiaGym_Script"),
    ("scripts/SaffronGym.asm",   "SaffronGym_Script"),
    ("scripts/CinnabarGym.asm",  "CinnabarGymSetMapAndTiles"),
    ("scripts/ViridianGym.asm",  "ViridianGym_Script"),
]

LOCALS = ("CityName", "LeaderName")


def _macro(parent: str, local: str) -> str:
    return f"TEXT_{parent}_{local}"


def _read_string(path: Path, local: str) -> str:
    """The `db "..."` immediately following `.<local>:` in a pret script.

    Deliberately strict: exactly one quoted db on the next non-blank line, ending
    in the '@' terminator. Anything else means the source moved and this
    generator must be looked at rather than silently emitting the wrong bytes.
    """
    lines = path.read_text(encoding="utf-8").splitlines()
    for i, ln in enumerate(lines):
        if ln.strip().rstrip(":") != "." + local or not ln.strip().endswith(":"):
            continue
        for nxt in lines[i + 1:]:
            if not nxt.strip():
                continue
            body = nxt.strip()
            if not body.startswith('db "') or not body.endswith('"'):
                raise SystemExit(
                    f"{path}:{i + 2}: expected a single quoted db after "
                    f".{local}, got: {body!r}")
            text = body[4:-1]
            if not text.endswith("@"):
                raise SystemExit(f"{path}: .{local} is not '@'-terminated: {text!r}")
            return text[:-1]
        raise SystemExit(f"{path}: nothing follows .{local}")
    raise SystemExit(f"{path}: no .{local} label found")


def main() -> int:
    lines = [
        "; gym_names.inc — generated by tools/generators/gen_gym_names.py.",
        "; DO NOT EDIT BY HAND.",
        ";",
        "; The .CityName / .LeaderName strings of the eight gym map scripts, GB-charmap",
        "; encoded via the unicode_converter submodule (gb_text.encode) and",
        "; '@'-terminated ($50). Read by LoadGymLeaderAndCityName.",
        ";",
        "; Macros, not labels: the pret labels are LOCAL to each script's global label,",
        "; so the transpiled script keeps pret's own `.CityName:` and invokes the macro",
        "; for the bytes. Nothing here emits anything until invoked.",
        "",
        "%ifndef GYM_NAMES_INC",
        "%define GYM_NAMES_INC",
        "",
    ]
    mapping = {}
    for path, parent in GYMS:
        for local in LOCALS:
            text = _read_string(ROOT / path, local)
            data = gb_text.encode(text) + [TERMINATOR]
            hexs = ", ".join(f"0x{b:02X}" for b in data)
            name = _macro(parent, local)
            mapping[f"{parent}.{local}"] = name
            lines.append(f"; pret: {path}:{parent}.{local}")
            lines.append(f"%macro {name} 0")
            lines.append(f'    db {hexs}   ; "{text}@"')
            lines.append("%endmacro")
            lines.append("")
    lines.append("%endif ; GYM_NAMES_INC")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "gym_names.inc"
    dst.write_text("\n".join(lines) + "\n")

    TABLES.mkdir(parents=True, exist_ok=True)
    tbl = TABLES / "text_assets.json"
    tbl.write_text(json.dumps({
        "_comment": [
            "pret label -> NASM macro that emits its bytes. WRITTEN BY",
            "tools/generators/gen_gym_names.py; do not hand-edit, and do not add a",
            "row whose macro no generator emits — the transpiler trusts this map",
            "and would emit a call to a macro that does not exist.",
            "",
            "Consumed by sm83xlat/emit.py: a quoted `db` under one of these labels",
            "lowers to the macro instead of bailing inline-text-db.",
        ],
        "include": "assets/gym_names.inc",
        "labels": mapping,
    }, indent=1) + "\n")

    print(f"wrote {dst} ({len(mapping)} macros) and {tbl}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
