#!/usr/bin/env python3
"""gen_pikachu_text.py — generate dos_port/assets/pikachu_text.inc (Tier 1 data).

One label: `ExpressionText`, the debug-mode message
StarterPikachuEmotionCommand_nop2 prints in Red's bedroom ("This expression is
No. <n>."). pret wraps it as `text_far _ExpressionText` in
engine/pikachu/pikachu_emotions.asm with the body in data/text/text_3.asm; the
body carries a `text_decimal wExpressionNumber, 1, 2` (TX_NUM), which
gen_battle_text's parser already resolves against gb_memmap.inc.

Reuses gen_battle_text.py's charmap/memmap/far-text machinery and emits the
label as one flattened, self-terminating stream — the port's flat TX_FAR model —
plus the `{ptr, len}` `<Label>_ref` pair the other text generators emit.

Carrier: dos_port/src/engine/pikachu/pikachu_emotions.asm (the pret mirror path,
which is where the `ExpressionText` label belongs).

DO NOT EDIT the output by hand — re-run this generator. Run from repo root or
dos_port/.
"""
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "dos_port" / "assets" / "pikachu_text.inc"

PIKACHU_SRC = ["engine/pikachu/pikachu_emotions.asm"]

WANT = {"ExpressionText"}


def existing_labels() -> set:
    """Labels already emitted elsewhere — never define one global twice."""
    out = set()
    assets = ROOT / "dos_port" / "assets"
    for inc in assets.glob("*.inc"):
        if inc.name == OUT.name:
            continue
        out |= set(re.findall(r"^global (\w+)$", inc.read_text(), re.M))
    return out


def main() -> int:
    charmap = gbt.load_charmap()
    memmap = gbt.load_memmap()
    far_db = gbt.collect_far(charmap, memmap)

    gbt.BATTLE_SRC = PIKACHU_SRC         # retarget the wrapper collector
    wrappers = gbt.collect_wrappers(charmap, memmap, far_db)

    missing = WANT - set(wrappers)
    if missing:
        raise SystemExit(
            f"gen_pikachu_text: expected labels missing from scan: {sorted(missing)}")

    skip = existing_labels()
    labels = sorted(WANT - skip)
    if not labels:
        raise SystemExit("gen_pikachu_text: every wanted label is already emitted elsewhere")

    out = [
        "; pikachu_text.inc — generated by tools/generators/gen_pikachu_text.py. DO NOT EDIT BY HAND.",
        "; Pikachu emotion-command message streams (pret engine/pikachu/pikachu_emotions.asm",
        f"; wrappers), text_far flattened. {len(labels)} label(s). section .data (see link.ld).",
        "",
        "section .data",
        "",
    ]
    for label in labels:
        b = wrappers[label]
        out.append(f"global {label}")
        out.append(f"{label}:")
        for i in range(0, len(b), 16):
            out.append("    db " + ", ".join(f"0x{x:02X}" for x in b[i:i + 16]))
        out.append(f"global {label}_ref")
        out.append(f"{label}_ref: dd {label}, {len(b)}   ; flat ptr + byte count")
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}: {len(labels)} label(s), "
          + ", ".join(f"{k}={len(wrappers[k])}B" for k in labels))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
