#!/usr/bin/env python3
"""gen_super_rod.py — generate dos_port/assets/super_rod.inc and
dos_port/assets/good_rod.inc from pret source.

super_rod.inc holds SuperRodFishingSlots (data/wild/super_rod.asm): one row per
fishing map,

    db MAPID, species, level, species, level, species, level, species, level

= 9 bytes/row (map id + 4 (species, level) pairs), 0xFF-terminated.
good_rod.inc holds GoodRodMons (data/wild/good_rod.asm): 2 rows of

    db level, species          ; NOTE the reversed order vs super_rod

exactly as pret stores them (ItemUseGoodRod reads level first). Species are
resolved to their Gen-1 INTERNAL index (constants/pokemon_constants.asm order),
exactly as gen_wild_encounters.py does, so ReadSuperRodData /
GenerateRandomFishingEncounter / ItemUseGoodRod read the same bytes as the
original ROM.

Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]          # repo root
ASSETS = ROOT / "dos_port" / "assets"


def parse_consts(rel_path: str) -> dict:
    """Parse an rgbds const_def/const enum file into {NAME: value}."""
    out, val = {}, 0
    for line in (ROOT / rel_path).read_text().splitlines():
        s = line.split(";", 1)[0].strip()
        if not s:
            continue
        m = re.match(r"const_def(?:\s+(-?\w+))?$", s)
        if m:
            val = int(m.group(1)) if m.group(1) else 0
            continue
        m = re.match(r"const_next\s+(-?\w+)$", s)
        if m:
            val = int(m.group(1))
            continue
        m = re.match(r"const_skip(?:\s+(\w+))?$", s)
        if m:
            val += int(m.group(1)) if m.group(1) else 1
            continue
        m = re.match(r"const\s+(\w+)$", s)
        if m:
            out[m.group(1)] = val
            val += 1
    return out


def parse_maps() -> dict:
    """Map constant name -> id from constants/map_constants.asm (map_const macro)."""
    out, val = {}, 0
    for line in (ROOT / "constants/map_constants.asm").read_text().splitlines():
        s = line.split(";", 1)[0].strip()
        m = re.match(r"const_def(?:\s+(-?\d+))?$", s)
        if m:
            val = int(m.group(1)) if m.group(1) else 0
            continue
        m = re.match(r"map_const\s+(\w+)\s*,", s)
        if m:
            out[m.group(1)] = val
            val += 1
    return out


def main() -> int:
    species = parse_consts("constants/pokemon_constants.asm")
    maps = parse_maps()

    rows = []
    for raw in (ROOT / "data/wild/super_rod.asm").read_text().splitlines():
        s = raw.split(";", 1)[0].strip()
        m = re.match(r"db\s+(.*)$", s)
        if not m:
            continue
        toks = [t.strip() for t in m.group(1).split(",")]
        if toks == ["-1"]:
            break
        if len(toks) != 9:
            sys.exit(f"gen_super_rod: expected 9 tokens, got {len(toks)}: {raw!r}")
        row = [maps[toks[0]]]                       # map id
        for i in range(1, 9, 2):
            row.append(species[toks[i]] & 0xFF)     # internal-index species
            row.append(int(toks[i + 1], 0) & 0xFF)  # level
        rows.append(row)

    out = [
        "; super_rod.inc — generated by tools/generators/gen_super_rod.py. DO NOT EDIT BY HAND.",
        f"; SuperRodFishingSlots: {len(rows)} maps, each = db map_id, then 4 x",
        "; (internal-index species, level); 0xFF-terminated. ReadSuperRodData scans",
        "; this by map id (9-byte stride); GenerateRandomFishingEncounter picks a pair.",
        "",
        "SuperRodFishingSlots:",
    ]
    for row in rows:
        out.append("    db " + ", ".join(str(b) for b in row))
    out.append("    db 0xFF")
    out.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "super_rod.inc"
    dst.write_text("\n".join(out) + "\n")
    print(f"wrote {dst} (SuperRodFishingSlots {len(rows)} maps, "
          f"{len(rows) * 9 + 1} bytes)")

    # --- good_rod.inc: GoodRodMons (data/wild/good_rod.asm), db level, species ---
    good = []
    for raw in (ROOT / "data/wild/good_rod.asm").read_text().splitlines():
        s = raw.split(";", 1)[0].strip()
        m = re.match(r"db\s+(.*)$", s)
        if not m:
            continue
        toks = [t.strip() for t in m.group(1).split(",")]
        if len(toks) != 2:
            sys.exit(f"gen_super_rod: good_rod expected 2 tokens: {raw!r}")
        good.append((int(toks[0], 0) & 0xFF, species[toks[1]] & 0xFF))
    if len(good) != 2:
        sys.exit(f"gen_super_rod: good_rod expected 2 rows, got {len(good)}")
    gout = [
        "; good_rod.inc — generated by tools/generators/gen_super_rod.py. DO NOT EDIT BY HAND.",
        "; GoodRodMons (pret data/wild/good_rod.asm): db level, species (internal",
        "; index) — LEVEL FIRST, reversed vs super_rod.inc, as ItemUseGoodRod reads it.",
        "",
        "GoodRodMons:",
    ]
    for level, spec in good:
        gout.append(f"    db {level}, {spec}")
    gout.append("")
    gdst = ASSETS / "good_rod.inc"
    gdst.write_text("\n".join(gout) + "\n")
    print(f"wrote {gdst} (GoodRodMons {len(good)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
