#!/usr/bin/env python3
"""Generate dos_port/assets/trainer_pics.inc — every trainer battle sprite
(compressed .pic) + the class->pic pointer table + base prize money.

Mirrors pret data/trainers/pic_pointers_money.asm (TrainerPicAndMoneyPointers): one
entry per trainer class (YOUNGSTER = $01, ...), each = (pic pointer, base money).
The .pic blobs are the SAME compressed format the port's mon-pic decompressor
(src/gfx/uncompress.asm) decodes, so a trainer sprite loads exactly like a mon pic.

Sources (read-only pret):
  gfx/pics.asm                          — "<Label>:: INCBIN gfx/trainers/<f>.pic"
  data/trainers/pic_pointers_money.asm  — class-ordered `pic_money <Label>, <money>`

Emits (data only; a Tier-2 wrapper .asm supplies section/globals):
  trnpic_<name>:        incbin "../gfx/trainers/<name>.pic"   (one per UNIQUE pic)
  TrainerPicPointers:   flat dd per class (index = trainer class - 1)
  TrainerBaseMoney:     bcd3 (3 bytes, big-endian BCD) per class

DO NOT EDIT the generated .inc by hand.  Run from repo root:
  python3 dos_port/tools/generators/gen_trainer_pics.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent.parent
PICS_ASM = ROOT / "gfx" / "pics.asm"
TABLE_ASM = ROOT / "data" / "trainers" / "pic_pointers_money.asm"
DST = ROOT / "dos_port" / "assets" / "trainer_pics.inc"


def blob_label(pic_file):
    stem = Path(pic_file).name[:-4]                 # strip ".pic"
    return "trnpic_" + re.sub(r"[^a-z0-9]", "_", stem.lower())


def bcd3(n):
    s = f"{int(n):06d}"
    return [(int(s[0]) << 4) | int(s[1]),
            (int(s[2]) << 4) | int(s[3]),
            (int(s[4]) << 4) | int(s[5])]


def main():
    # label -> repo-relative .pic file. Bare "Label::" lines (no INCBIN) are aliases
    # for the next INCBIN'd label (e.g. ChiefPic:: reuses ScientistPic's sprite).
    label_file = {}
    pending = []
    for line in PICS_ASM.read_text().splitlines():
        m = re.match(r'\s*(\w+)::\s*INCBIN\s*"(gfx/trainers/[^"]+\.pic)"\s*$', line)
        if m:
            label_file[m.group(1)] = m.group(2)
            for p in pending:
                label_file[p] = m.group(2)
            pending = []
            continue
        bare = re.match(r'\s*(\w+)::\s*$', line)
        if bare:
            pending.append(bare.group(1))          # alias; resolve at next INCBIN
        elif re.search(r'INCBIN', line):
            pending = []                            # non-trainer pic — drop pending
    if not label_file:
        sys.exit("no trainer pic INCBINs parsed from gfx/pics.asm")

    # class-ordered (pic label, base money)
    entries = [(m.group(1), int(m.group(2)))
               for m in re.finditer(r'pic_money\s+(\w+),\s*(\d+)', TABLE_ASM.read_text())]
    if not entries:
        sys.exit("no pic_money entries parsed")

    # unique pic blobs in first-seen order
    uniq, seen = [], set()
    for label, _ in entries:
        f = label_file.get(label)
        if f is None:
            sys.exit(f"pic label {label} has no .pic file in gfx/pics.asm")
        bl = blob_label(f)
        if bl not in seen:
            seen.add(bl)
            uniq.append((bl, f))

    out = [
        "; trainer_pics.inc — generated by dos_port/tools/generators/gen_trainer_pics.py.",
        "; DO NOT EDIT BY HAND.  Trainer battle sprites (compressed .pic, decoded by",
        "; src/gfx/uncompress.asm) + class->pic pointer table + base prize money.",
        f"; {len(uniq)} unique pics, {len(entries)} classes (TrainerPicPointers index = class-1).",
        "",
    ]
    for bl, f in uniq:
        out.append(f'{bl}: incbin "../{f}"')
    out += ["", "TrainerPicPointers:   ; flat dd, index = (trainer class - 1)"]
    for label, _ in entries:
        out.append(f"    dd {blob_label(label_file[label])}")
    out += ["", "TrainerBaseMoney:   ; bcd3 (big-endian BCD, 3 bytes) per class"]
    for label, money in entries:
        b = bcd3(money)
        out.append(f"    db 0x{b[0]:02X}, 0x{b[1]:02X}, 0x{b[2]:02X}   ; {money}")
    out += [
        "",
        "; player character (Yellow/Red) battle sprites — front (trainer card / link",
        "; opponent view) and back (the sprite that slides in on the player's side at the",
        "; start of a battle, before the first mon is sent out). PlayerPicBack is scaled",
        "; like a mon back pic (ScaleSpriteByTwo).",
        'PlayerPicFront: incbin "../gfx/player/red.pic"',
        'PlayerPicBack:  incbin "../gfx/player/redb.pic"',
        "",
    ]

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out) + "\n")
    print(f"wrote {DST} ({len(uniq)} pics, {len(entries)} classes)")


if __name__ == "__main__":
    main()
