#!/usr/bin/env python3
"""gen_alphabets.py — generate dos_port/assets/alphabets.inc (menus S7, package C).

Tier-1 data for the naming screen (engine/menus/naming_screen.asm). Emits, as a
deterministic function of the read-only pret source:

  UpperCaseAlphabet / LowerCaseAlphabet
      The letter-grid rows from data/text/alphabets.asm, GB-charmap encoded
      (parsed straight from constants/charmap.asm, greedy longest-match so the
      multi-char tokens <PK>/<MN>/<DOT>/<ED> resolve). Each blob ends with the
      case-toggle label + '@' ($50), exactly as pret lays them out.
  ALPHABET_UPPER_SIZE / ALPHABET_LOWER_SIZE   equ byte counts of each blob.

  alphabet_ed_tile
      gfx/font/ED.1bpp (8 bytes, the '<ED>' toggle glyph) expanded 1bpp->2bpp the
      same way LoadFontTilePatterns expands the font: each source byte duplicated
      into both bitplanes (colors 0/3). 16 bytes -> a plain 2bpp VRAM tile the C
      worker's LoadEDTile copies straight into its vChars slot.
  ALPHABET_ED_TILE_SIZE  equ 16   (2bpp tile size)
  ALPHABET_ED_CHAR       equ 0xF0 (charmap "<ED>" — its font tile index)

Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
CHARMAP = ROOT / "constants" / "charmap.asm"
ALPHABETS = ROOT / "data" / "text" / "alphabets.asm"
ED_1BPP = ROOT / "gfx" / "font" / "ED.1bpp"

TERMINATOR = 0x50  # '@'


def load_charmap() -> dict:
    """Parse constants/charmap.asm -> {token_string: byte}. Handles quoted
    tokens that themselves contain a comma (e.g. ","). Returns the map with keys
    sorted-longest-first handled by the greedy encoder, not here."""
    cmap = {}
    pat = re.compile(r'charmap\s+"((?:[^"\\]|\\.)*)",\s*\$([0-9a-fA-F]+)')
    for line in CHARMAP.read_text(encoding="utf-8").splitlines():
        # Do NOT strip ';' comments naively — ';' is itself a charmap token.
        if not line.lstrip().startswith("charmap"):
            continue
        m = pat.search(line)
        if m:
            cmap[m.group(1)] = int(m.group(2), 16)
    if not cmap:
        raise SystemExit(f"no charmap entries parsed from {CHARMAP}")
    return cmap


def encode(s: str, cmap: dict) -> list:
    """Greedy longest-match charmap encode of a db-string. Raises on any char
    that is not covered by a charmap token."""
    keys = sorted(cmap, key=len, reverse=True)
    out = []
    i = 0
    while i < len(s):
        for k in keys:
            if k and s.startswith(k, i):
                out.append(cmap[k])
                i += len(k)
                break
        else:
            raise SystemExit(f"unmapped char {s[i]!r} at {i} in {s!r}")
    return out


def load_alphabet_blob(label: str, cmap: dict) -> list:
    """Extract the db "..." rows following `label:` in alphabets.asm and encode
    them into one contiguous byte blob (pret keeps them under one label)."""
    lines = ALPHABETS.read_text(encoding="utf-8").splitlines()
    blob = []
    collecting = False
    for line in lines:
        stripped = line.strip()
        if stripped == f"{label}:":
            collecting = True
            continue
        if collecting:
            m = re.match(r'db\s+"((?:[^"\\]|\\.)*)"', stripped)
            if m:
                blob += encode(m.group(1), cmap)
                continue
            # a new label (or blank/other) ends this alphabet
            if stripped.endswith(":") or stripped == "":
                if blob:
                    break
                continue
            break
    if not blob:
        raise SystemExit(f"no rows collected for {label} in {ALPHABETS}")
    return blob


def expand_1bpp_to_2bpp(data: bytes) -> list:
    """Mirror LoadFontTilePatterns: duplicate each 1bpp byte into both planes."""
    out = []
    for b in data:
        out += [b, b]
    return out


def db_lines(name: str, data: list, comment: str) -> list:
    out = [f"{name}:  ; {comment}"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.append("    db " + ", ".join(f"0x{x:02X}" for x in chunk))
    return out


def main() -> int:
    cmap = load_charmap()
    upper = load_alphabet_blob("UpperCaseAlphabet", cmap)
    lower = load_alphabet_blob("LowerCaseAlphabet", cmap)
    ed_raw = ED_1BPP.read_bytes()
    if len(ed_raw) != 8:
        raise SystemExit(f"{ED_1BPP} expected 8 bytes, got {len(ed_raw)}")
    ed_2bpp = expand_1bpp_to_2bpp(ed_raw)

    out = [
        "; alphabets.inc — generated by tools/generators/gen_alphabets.py. DO NOT EDIT BY HAND.",
        "; Naming-screen letter grids + the <ED> toggle tile (menus S7, package C).",
        "; Source: data/text/alphabets.asm, constants/charmap.asm, gfx/font/ED.1bpp.",
        "",
        f"ALPHABET_UPPER_SIZE equ {len(upper)}",
        f"ALPHABET_LOWER_SIZE equ {len(lower)}",
        f"ALPHABET_ED_TILE_SIZE equ {len(ed_2bpp)}",
        "ALPHABET_ED_CHAR equ 0xF0   ; charmap \"<ED>\" font tile index",
        "",
    ]
    out += db_lines("UpperCaseAlphabet", upper,
                    "letters + symbols grid, then 'lower case@' toggle")
    out.append("")
    out += db_lines("LowerCaseAlphabet", lower,
                    "letters + symbols grid, then 'UPPER CASE@' toggle")
    out.append("")
    out += db_lines("alphabet_ed_tile", ed_2bpp,
                    "ED.1bpp expanded 1bpp->2bpp (LoadFontTilePatterns convention)")
    out.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "alphabets.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst}: upper={len(upper)}B lower={len(lower)}B ed={len(ed_2bpp)}B")
    return 0


if __name__ == "__main__":
    sys.exit(main())
