#!/usr/bin/env python3
"""gen_slots_text.py — generate dos_port/assets/slots_text.inc (Tier 1 data).

The slot machine engine (src/engine/slots/slot_machine.asm) prints messages
through the unified text engine (PrintText → TextCommandProcessor) and uses
plain string buffers for multipliers and payouts (PlaceString / CopyData).

Emits, in section .data:
  * The 9 text_far message bodies from data/text/text_2.asm:
      _PlaySlotMachineText
      _OutOfCoinsSlotMachineText
      _BetHowManySlotMachineText
      _StartSlotMachineText
      _NotEnoughCoinsSlotMachineText
      _OneMoreGoSlotMachineText
      _LinedUpText
      _NotThisTimeText
      _YeahText
  * The 5 plain string labels (pret byte layout + charmap encoded):
      CoinMultiplierSlotMachineText ("×3<NEXT>×2<NEXT>×1@")
      SlotReward300Text ("300@")
      SlotReward100Text ("100@")
      SlotReward8Text ("8@")
      SlotReward15Text ("15@")

DO NOT EDIT the output by hand — re-run this generator.
Run from repo root or dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "dos_port" / "assets" / "slots_text.inc"

SLOTS_FAR = [
    "_PlaySlotMachineText",
    "_OutOfCoinsSlotMachineText",
    "_BetHowManySlotMachineText",
    "_StartSlotMachineText",
    "_NotEnoughCoinsSlotMachineText",
    "_OneMoreGoSlotMachineText",
    "_LinedUpText",
    "_NotThisTimeText",
    "_YeahText",
]

# Plain charmap-encoded strings in pret engine/slots/slot_machine.asm:
# CoinMultiplierSlotMachineText: db "×3" / next "×2" / next "×1@"
# SlotReward*Text: db "<N>@"
SLOTS_STRINGS = [
    ("CoinMultiplierSlotMachineText", ["×3", "<NEXT>", "×2", "<NEXT>", "×1@"]),
    ("SlotReward300Text", ["300@"]),
    ("SlotReward100Text", ["100@"]),
    ("SlotReward8Text", ["8@"]),
    ("SlotReward15Text", ["15@"]),
]


def encode_parts(parts: list, cm: list) -> list:
    out = []
    for p in parts:
        if p == "<NEXT>":
            out.append(0x4E)
        else:
            out.extend(gbt.encode(p, cm))
    return out


def main() -> int:
    cm = gbt.load_charmap()
    mem = gbt.load_memmap()
    far = gbt.collect_far(cm, mem)

    lines = [
        "; slots_text.inc — generated by tools/generators/gen_slots_text.py. DO NOT EDIT BY HAND.",
        "; Slot machine message bodies (data/text/text_2.asm) and plain text strings.",
        "; section .data so labels land in a loaded data section (see link.ld).",
        "",
        "section .data",
        "",
    ]

    # Declare globals for plain string labels defined in this data asset
    for label, _ in SLOTS_STRINGS:
        lines.append(f"global {label}")
    lines.append("")

    # Emit far text streams
    for label in SLOTS_FAR:
        if label not in far:
            sys.stderr.write(f"gen_slots_text: missing far label {label}\n")
            return 1
        data = far[label]
        rows = [
            "    db " + ", ".join(f"0x{b:02X}" for b in data[k:k + 16])
            for k in range(0, len(data), 16)
        ]
        lines.append(f"{label}:\n" + "\n".join(rows))

    lines.append("")
    lines.append("; --- Plain string constants (PlaceString / CopyData) ---")
    for label, parts in SLOTS_STRINGS:
        encoded = encode_parts(parts, cm)
        lines.append(f"{label}: db " + ", ".join(f"0x{x:02X}" for x in encoded))

    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(SLOTS_FAR)} far labels, {len(SLOTS_STRINGS)} strings)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
