#!/usr/bin/env python3
"""gen_trainer_names.py — generate dos_port/assets/trainer_names.inc from pret.

Emits TrainerNames: NUM_TRAINERS (47) **variable-length**, '@'-terminated ($50)
records in trainer-class order, GB-charmap encoded — exactly as pret's `li`
macro over data/trainers/names.asm (which expands to `db <text>, "@"`).

Trainer class NOBODY ($00) has no entry (the list starts at YOUNGSTER, $01);
GetName/GetTrainerName_ index it 1-based via [wTrainerClass] directly (see
dos_port/src/home/names.asm GetName "types 2-7" walk and
dos_port/src/engine/battle/get_trainer_name.asm), counting $50 terminators —
same non-padded walk as MoveNames, not the fixed-width AddNTimes path used for
MonsterNames. Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
NUM_TRAINERS = 47
TERM = 0x50                  # '@' terminator
TRAINER_NAME_MAX = 12        # TRAINER_NAME_LENGTH - 1 (list_start bound; pret data/trainers/names.asm)


def load_charmap(path: Path) -> list:
    cm = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s+charmap\s+"((?:[^"\\]|\\.)*)",\s*\$([0-9a-fA-F]+)', line)
        if m:
            cm.append((m.group(1), int(m.group(2), 16)))
    cm.sort(key=lambda x: -len(x[0]))      # longest-match first
    return cm


def encode(s: str, charmap: list) -> bytes:
    out, i = [], 0
    while i < len(s):
        for key, val in charmap:
            if key and s[i:].startswith(key):
                out.append(val)
                i += len(key)
                break
        else:
            raise ValueError(f"Unrecognised char at {i}: {s[i:i+4]!r}")
    return bytes(out)


def main() -> int:
    charmap = load_charmap(ROOT / "constants/charmap.asm")
    names = []
    for line in (ROOT / "data/trainers/names.asm").read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s*li\s+"((?:[^"\\]|\\.)*)"', line)
        if m:
            names.append(m.group(1))
    if len(names) != NUM_TRAINERS:
        print(f"expected {NUM_TRAINERS} names, got {len(names)}", file=sys.stderr)
        return 1

    out = [
        "; trainer_names.inc — generated by tools/generators/gen_trainer_names.py. DO NOT EDIT BY HAND.",
        f"; TrainerNames: {NUM_TRAINERS} variable-length '@'-terminated names, trainer-class order",
        "; (1-based: index 1 = YOUNGSTER ... index 47 = LANCE; class NOBODY=$00 has no entry).",
        "; Walked by GetName (counts $50 terminators); NOT fixed-width.",
        "",
        "global TrainerNames",
        "",
        "TrainerNames:",
    ]
    total = 0
    for i, nm in enumerate(names):
        enc = encode(nm, charmap)
        if len(enc) > TRAINER_NAME_MAX:
            print(f"name too long ({len(enc)} > {TRAINER_NAME_MAX}): {nm!r}", file=sys.stderr)
            return 1
        rec = enc + bytes([TERM])
        total += len(rec)
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in rec) + f"    ; trainer class {i + 1}  {nm}")
    out += ["TrainerNames_end:", ""]

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "trainer_names.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} (TrainerNames {len(names)} names, {total} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
