#!/usr/bin/env python3
"""gen_school_blackboard_text.py — generate dos_port/assets/school_blackboard_text.inc.

Tier-1 data for pret `engine/events/hidden_events/school_blackboard.asm`:

  * Three PlaceString glyph runs (pret `db`/`next` sequences, GB-charmap encoded
    via gb_text.encode — the START-menu-label pattern in gen_menu_strings.py):
    HowToLinkText, StatusAilmentText1, StatusAilmentText2.
  * Twelve `text_far` stream bodies (pret data/text/text_2.asm), flattened via
    gen_battle_text.collect_far — the same authoritative parser every other
    far-text generator uses (worked single-wrapper example: gen_pikachu_text.py):
    LinkCableHelpText1/2, LinkCableInfoText1/2/3, ViridianSchoolBlackboardText1/2,
    ViridianBlackboardSleepText/PoisonText/PrlzText/BurnText/FrozenText.

Carrier: dos_port/src/engine/events/hidden_events/school_blackboard.asm, which
%includes this file directly inside its own `section .data` (no `global`/`extern`
needed — every label here is referenced only by that one file, exactly as
assets/map_text/<map>.inc is %included by its one map script). The `_Xxx` far
body names are the exact pret data labels; the wrappers (`LinkCableHelpText1:
text_far _LinkCableHelpText1 / text_end`) stay Tier-2 code in the .asm.

DO NOT EDIT the output by hand — re-run this generator. Run from repo root or
dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text                      # noqa: E402
import gen_battle_text as gbt       # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "dos_port" / "assets" / "school_blackboard_text.inc"

NEXT = 0x4E     # "<NEXT>" — line break
TERM = 0x50     # "@"      — string terminator

# (label, parts) — a part is a str (-> gb_text.encode) or an int (raw tile byte).
MENU_STRINGS = [
    ("HowToLinkText",                     # pret: db "HOW TO LINK" next "COLOSSEUM"
     ["HOW TO LINK", NEXT, "COLOSSEUM", NEXT,       # next "TRADE CENTER" next
      "TRADE CENTER", NEXT, "STOP READING", TERM]), # "STOP READING@"
    ("StatusAilmentText1",                # pret: db " SLP" next " PSN" next " PAR@"
     [" SLP", NEXT, " PSN", NEXT, " PAR", TERM]),
    ("StatusAilmentText2",                # pret: db " BRN" next " FRZ" next " QUIT@"
     [" BRN", NEXT, " FRZ", NEXT, " QUIT", TERM]),
]

# The twelve text_far wrapper bodies, pret data/text/text_2.asm. Names exactly as
# pret's `_Foo` labels (leading underscore is part of the pret name).
FAR_LABELS = [
    "_LinkCableHelpText1",
    "_LinkCableHelpText2",
    "_LinkCableInfoText1",
    "_LinkCableInfoText2",
    "_LinkCableInfoText3",
    "_ViridianSchoolBlackboardText1",
    "_ViridianSchoolBlackboardText2",
    "_ViridianBlackboardSleepText",
    "_ViridianBlackboardPoisonText",
    "_ViridianBlackboardPrlzText",
    "_ViridianBlackboardBurnText",
    "_ViridianBlackboardFrozenText",
]


def encode_parts(parts):
    out = []
    for p in parts:
        if isinstance(p, int):
            out.append(p)
        else:
            out.extend(gb_text.encode(p))
    return out


def main() -> int:
    far = gbt.collect_far(gbt.load_charmap(), gbt.load_memmap())
    missing = [l for l in FAR_LABELS if l not in far]
    if missing:
        sys.exit(f"gen_school_blackboard_text: missing far label(s): {missing}")

    out = [
        "; school_blackboard_text.inc — generated by",
        "; tools/generators/gen_school_blackboard_text.py. DO NOT EDIT BY HAND.",
        "; Tier-1 data for pret engine/events/hidden_events/school_blackboard.asm:",
        "; three PlaceString glyph runs + twelve text_far stream bodies (pret",
        "; data/text/text_2.asm). %included by",
        "; src/engine/events/hidden_events/school_blackboard.asm inside section .data.",
        "",
    ]

    for label, parts in MENU_STRINGS:
        b = encode_parts(parts)
        hexs = ", ".join(f"0x{x:02X}" for x in b)
        out.append(f"{label}: db {hexs}")

    for label in FAR_LABELS:
        data = far[label]
        rows = [
            "    db " + ", ".join(f"0x{b:02X}" for b in data[k:k + 16])
            for k in range(0, len(data), 16)
        ]
        out.append(f"{label}:\n" + "\n".join(rows))

    out.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}: {len(MENU_STRINGS)} menu string(s) + {len(FAR_LABELS)} far label(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
