#!/usr/bin/env python3
"""gen_list_menu_strings.py — generate dos_port/assets/list_menu_strings.inc.

The three strings of pret home/list_menu.asm — ListMenuCancelText ("CANCEL@"),
InitialQuantityText ("×01@") and SpacesBetweenQuantityAndPriceText ("      @") —
GB-charmap encoded through the unicode_converter submodule (gb_text.encode)
instead of hand-written charmap hex. Consumed by src/home/list_menu.asm via
%include.

All three are pure single-char strings ('×' $F1 and the digits '0'/'1' $F6/$F7
are in the charmap), so nothing here needs the raw-byte escape hatch that
gen_textbox_strings.py uses for <NEXT>/<PK>/<MN>.

Run from repo root or dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
TERMINATOR = 0x50  # '@'

# (NASM label, text, pret ref) — mirrors home/list_menu.asm exactly.
STRINGS = [
    ("ListMenuCancelText", "CANCEL", "home/list_menu.asm:ListMenuCancelText"),
    ("InitialQuantityText", "×01", "home/list_menu.asm:InitialQuantityText"),
    ("SpacesBetweenQuantityAndPriceText", "      ",
     "home/list_menu.asm:SpacesBetweenQuantityAndPriceText"),
]


def main() -> int:
    lines = [
        "; list_menu_strings.inc — generated by tools/generators/gen_list_menu_strings.py.",
        "; DO NOT EDIT BY HAND.",
        ";",
        "; The list-menu strings of pret home/list_menu.asm, GB-charmap encoded via the",
        "; unicode_converter submodule (gb_text.encode) and '@'-terminated ($50).",
        "",
    ]
    for label, text, ref in STRINGS:
        data = gb_text.encode(text) + [TERMINATOR]
        hexs = ", ".join(f"0x{b:02X}" for b in data)
        lines.append(f"; pret: {ref}")
        lines.append(f'{label}: db {hexs}   ; "{text}@"')
        lines.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "list_menu_strings.inc"
    dst.write_text("\n".join(lines))
    print(f"wrote {dst} ({len(STRINGS)} labels)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
