#!/usr/bin/env python3
"""gen_hidden_items_text.py — generate dos_port/assets/hidden_items_text.inc
(Tier 1 data).

pret engine/events/hidden_items.asm's FoundHiddenItemText carries a text_far
intro (`_FoundHiddenItemText`, data/text/text_2.asm) followed by a real
text_asm code tail (give the item, set the obtained flag, play SFX). That
label is one of gen_predef_text.py's NOT_DATA entries -- it is a predef_code
TextPredefs row ($26), so the port's carrier
(dos_port/src/engine/events/hidden_items.asm) calls PrintText on the far body
explicitly instead of keeping it as a leading stream byte (same reasoning as
CinnabarGymQuizCorrectText's standalone far body, gen_cinnabar_gym_quiz_text.py).

This generator emits ONLY the underscore-prefixed far body,
`_FoundHiddenItemText`, as a standalone raw-byte label -- the hand-written
carrier needs a real flat pointer to it ahead of its text_asm code tail.

Carrier: dos_port/src/engine/events/hidden_items.asm (the pret mirror path).

DO NOT EDIT the output by hand — re-run this generator. Run from repo root or
dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "dos_port" / "assets" / "hidden_items_text.inc"

FAR_WANT = {"_FoundHiddenItemText"}


def main() -> int:
    charmap = gbt.load_charmap()
    memmap = gbt.load_memmap()
    far_db = gbt.collect_far(charmap, memmap)

    missing_far = FAR_WANT - set(far_db)
    if missing_far:
        raise SystemExit(
            f"gen_hidden_items_text: expected far labels missing: {sorted(missing_far)}")

    out = [
        "; hidden_items_text.inc — generated by tools/generators/gen_hidden_items_text.py.",
        "; DO NOT EDIT BY HAND.",
        "; FoundHiddenItemText's far intro (pret data/text/text_2.asm:",
        "; _FoundHiddenItemText), the standalone far body the hand-written carrier",
        "; (src/engine/events/hidden_items.asm) needs ahead of its text_asm code tail.",
        "; section .data (see link.ld).",
        "",
        "section .data",
        "",
    ]
    for label in sorted(FAR_WANT):
        b = far_db[label]
        out.append(f"global {label}")
        out.append(f"{label}:")
        for i in range(0, len(b), 16):
            out.append("    db " + ", ".join(f"0x{x:02X}" for x in b[i:i + 16]))
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}: {len(FAR_WANT)} far label(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
