#!/usr/bin/env python3
"""Generate ``assets/bg_map_attributes.inc`` from pret ``data/cgb/bg_map_attributes.asm``.

Tier-1 data: a deterministic function of the read-only pret source. The port
consumes the decoded attribute payloads, not pret's VDMA packet wrapper.

Table format, derived from ``engine/gfx/bg_map_attributes.asm:LoadBGMapAttributes``::

    base+0        count byte -> rVDMA_LEN; transfers ((count & $7F) + 1) * 16 bytes
    base+1..2     little-endian offset `de`
    base+3..15    padding
    base+16       payload #1, VDMAed to vBGMap0
    base+3+de     payload #2, VDMAed to vBGMap1

Each payload is a 32-byte-per-row window of the 32x32 BG map, matching the port's
``GB_TILEMAP0`` / ``GB_TILEMAP1`` layout byte for byte. The standard
``db $23 / dw $000d`` prologue makes ``base+3+de == base+16``, so both transfers
read the same bytes; only ``BGMapAttributes_TitleScreen`` and
``BGMapAttributes_Unknown13`` carry a distinct vBGMap1 payload.

Measured invariant, asserted below: bits 3-7 of every attribute byte are zero
across all 13 tables -- no VRAM-bank bit, no X/Y flip, no BG-priority. The port
therefore carries a 2-bit palette index, which is what ``tile_pal`` already holds.
"""
from __future__ import annotations

from pathlib import Path
import re

HERE = Path(__file__).resolve().parent
TOOLS = HERE.parent
PRET = TOOLS.parent.parent / "data" / "cgb" / "bg_map_attributes.asm"
OUT = TOOLS.parent / "assets" / "bg_map_attributes.inc"

# pret engine/gfx/bg_map_attributes.asm:BGMapAttributesPointers, in order. The
# port keeps pret's label names; this is the dispatch order, not a new ordering.
POINTER_ORDER = [
    "Unknown1", "Unknown2", "GameFreakIntro", "TrainerCard", "PartyMenu",
    "NidorinoIntro", "TitleScreen", "Slots", "Pokedex", "StatusScreen",
    "Battle", "WholeScreen", "Unknown13",
]


def parse(path: Path) -> dict[str, list[int]]:
    """Flatten each BGMapAttributes_* table to its raw bytes."""
    tables: dict[str, list[int]] = {}
    cur: str | None = None
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        m = re.match(r"^(BGMapAttributes_\w+):$", line)
        if m:
            cur = m.group(1)
            tables[cur] = []
            continue
        if cur is None:
            continue
        m = re.match(r"^db\s+(.*)$", line)
        if m:
            tables[cur] += [int(t.strip().lstrip("$"), 16) for t in m.group(1).split(",")]
            continue
        m = re.match(r"^dw\s+(.*)$", line)
        if m:
            for tok in m.group(1).split(","):
                v = int(tok.strip().lstrip("$"), 16)
                tables[cur] += [v & 0xFF, v >> 8]
            continue
        raise SystemExit(f"gen_bg_attributes: unparsed line in {cur}: {line!r}")
    return tables


def decode(name: str, raw: list[int]) -> tuple[list[int], list[int]]:
    """Return the (vBGMap0, vBGMap1) attribute payloads for one table."""
    count = raw[0]
    off = raw[1] | (raw[2] << 8)
    nbytes = ((count & 0x7F) + 1) * 16
    p0 = raw[16:16 + nbytes]
    p1 = raw[3 + off:3 + off + nbytes]
    for payload, which in ((p0, "vBGMap0"), (p1, "vBGMap1")):
        if len(payload) != nbytes:
            raise SystemExit(f"gen_bg_attributes: {name} {which} truncated "
                             f"({len(payload)} of {nbytes} bytes)")
        stray = {b for b in payload if b & 0xF8}
        if stray:
            # The port models a 2-bit palette index only. A table that set the
            # bank/flip/priority bits would silently lose them here, so fail loudly
            # rather than generate data the runtime cannot represent.
            raise SystemExit(f"gen_bg_attributes: {name} {which} sets bits 3-7 "
                             f"({sorted(hex(b) for b in stray)}); the port's "
                             f"tile_pal carries only a 2-bit palette index")
    return p0, p1


def emit_bytes(label: str, payload: list[int]) -> list[str]:
    lines = [f"{label}:"]
    for start in range(0, len(payload), 32):
        lines.append("    db " + ", ".join(str(b) for b in payload[start:start + 32]))
    return lines


def emit() -> str:
    tables = parse(PRET)
    missing = [n for n in POINTER_ORDER if f"BGMapAttributes_{n}" not in tables]
    if missing:
        raise SystemExit(f"gen_bg_attributes: pret source is missing {missing}")

    lines = [
        "; DO NOT EDIT BY HAND — generated by tools/generators/gen_bg_attributes.py",
        "; Source: data/cgb/bg_map_attributes.asm (pret, read-only).",
        ";",
        "; Per-cell CGB BG attribute payloads, decoded out of pret's VDMA packet",
        "; wrapper. Each payload is 32 bytes per row and lines up with the port's",
        "; GB_TILEMAP0 / GB_TILEMAP1 byte for byte. Values are a 2-bit palette",
        "; index (0-3); the generator asserts bits 3-7 are clear tree-wide.",
        "",
        f"BG_ATTR_TABLE_COUNT equ {len(POINTER_ORDER)}",
        "",
        "; The BGMapAttributesPointers dispatch table is NOT emitted here: a table of",
        "; addresses is code, not data (project-conventions, two-tier rule), so it is",
        "; hand-written in src/engine/gfx/bg_map_attributes.asm and references these",
        "; labels. Emitting it here also made the .inc a second provider of the pret",
        "; label, which lint_pret_labels reports as local_shadow.",
    ]

    for name in POINTER_ORDER:
        label = f"BGMapAttributes_{name}"
        p0, p1 = decode(label, tables[label])
        rows = len(p0) // 32
        lines.append(f"; {label} — {len(p0)} bytes / {rows} rows"
                     f"{'' if p0 == p1 else ' (vBGMap1 payload differs)'}")
        # Header the runtime reads: row count, then the vBGMap0 payload, then
        # vBGMap1's. Screens whose two payloads agree share one copy.
        lines.append(f"{label}:")
        lines.append(f"    dd {rows}")
        lines.append(f"    dd {label}_map0, {label}_map1")
        lines.append("")
        lines += emit_bytes(f"{label}_map0", p0)
        if p0 == p1:
            lines.append(f"{label}_map1 equ {label}_map0")
        else:
            lines += emit_bytes(f"{label}_map1", p1)
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(emit())


if __name__ == "__main__":
    main()
