#!/usr/bin/env python3
"""gen_textbox_strings.py — generate dos_port/assets/textbox_strings.inc.

The menu strings of pret data/text_boxes.asm (plus PokemonMenuEntries and
CurrencyString from engine/menus/text_box.asm), GB-charmap encoded through the
unicode_converter submodule (gb_text.encode) instead of hand-written charmap hex.
Consumed by src/engine/menus/text_box.asm via %include.

Two things gb_text.encode deliberately cannot do (see its docstring: it is a
strict single-char mapper), so the generator handles them the way the project
convention prescribes — as named raw bytes emitted BETWEEN encoded text runs:

  <NEXT> ($4E)  the line separator pret writes as the `next` macro
  <PK> <MN>     ($E1/$E2) the two-tile "Pk"/"Mn" glyph pair in BattleMenuText

Everything else — including '×' ($F1) and '¥' ($F0) — round-trips through the
single-char charmap and is encoded, never hand-numbered.

The JP-only strings of data/text_boxes.asm (JapaneseMochimonoText,
JapaneseSaveMessageText, JapaneseSpeedOptionsText, JapaneseMainMenuText,
JapaneseAhText, JapanesePokedexMenu) are NOT emitted: the EN port ships no JP
text-box templates, so nothing references them (see the DEVIATION note in
src/engine/menus/text_box.asm).

Run from repo root or dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"

TERMINATOR = 0x50  # '@'
NEXT = 0x4E        # <NEXT>
PK = 0xE1          # <PK>
MN = 0xE2          # <MN>


class Raw:
    """A control/glyph byte the single-char converter cannot map."""

    def __init__(self, value, name):
        self.value = value
        self.name = name


NEXT_TOK = Raw(NEXT, "<NEXT>")
PK_TOK = Raw(PK, "<PK>")
MN_TOK = Raw(MN, "<MN>")
END = Raw(TERMINATOR, "@")

# (NASM label, [segments], pret source comment). A str segment is encoded; a Raw
# segment is emitted verbatim. Mirrors pret data/text_boxes.asm exactly, including
# BuySellQuitText's stray unused "@".
STRINGS = [
    ("BuySellQuitText",
     ["BUY", NEXT_TOK, "SELL", NEXT_TOK, "QUIT", END, END],
     'db "BUY" / next "SELL" / next "QUIT@" + the unused stray "@"'),
    ("UseTossText",
     ["USE", NEXT_TOK, "TOSS", END],
     'db "USE" / next "TOSS@"'),
    ("MoneyText",
     ["MONEY", END],
     'db "MONEY@"'),
    ("BattleMenuText",
     ["FIGHT ", PK_TOK, MN_TOK, NEXT_TOK, "ITEM  RUN", END],
     'db "FIGHT <PK><MN>" / next "ITEM  RUN@"'),
    ("SafariZoneBattleMenuText",
     ["BALL×       BAIT", NEXT_TOK, "THROW ROCK  RUN", END],
     'db "BALL×       BAIT" / next "THROW ROCK  RUN@"'),
    ("SwitchStatsCancelText",
     ["SWITCH", NEXT_TOK, "STATS", NEXT_TOK, "CANCEL", END],
     'db "SWITCH" / next "STATS" / next "CANCEL@"'),
    # engine/menus/text_box.asm (not data/text_boxes.asm)
    ("PokemonMenuEntries",
     ["STATS", NEXT_TOK, "SWITCH", NEXT_TOK, "CANCEL", END],
     'db "STATS" / next "SWITCH" / next "CANCEL@"'),
    ("CurrencyString",
     ["      ¥", END],
     'db "      ¥@" (unreferenced in pret; kept so the port mirrors it)'),
]


def emit(segments):
    """[segments] -> (list[int] bytes, human-readable rendering)."""
    out = []
    shown = []
    for seg in segments:
        if isinstance(seg, Raw):
            out.append(seg.value)
            shown.append(seg.name)
        else:
            out.extend(gb_text.encode(seg))
            shown.append(seg)
    return out, "".join(shown)


def main() -> int:
    lines = [
        "; textbox_strings.inc — generated by tools/generators/gen_textbox_strings.py.",
        "; DO NOT EDIT BY HAND.",
        ";",
        "; Text-box menu strings of pret data/text_boxes.asm (+ PokemonMenuEntries and",
        "; CurrencyString from engine/menus/text_box.asm), GB-charmap encoded via the",
        "; unicode_converter submodule (gb_text.encode). <NEXT> ($4E) and <PK>/<MN>",
        "; ($E1/$E2) are control/glyph bytes the single-char converter cannot map, so",
        "; they are emitted as named raw bytes between the encoded runs.",
        ";",
        "; The JP-only strings are not emitted — the EN port ships no JP text-box",
        "; templates, so nothing references them.",
        "",
    ]
    for label, segments, pretsrc in STRINGS:
        data, shown = emit(segments)
        hexs = ", ".join(f"0x{b:02X}" for b in data)
        lines.append(f"; pret: {pretsrc}")
        lines.append(f"{label}: db {hexs}   ; {shown}")
        lines.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "textbox_strings.inc"
    dst.write_text("\n".join(lines))
    print(f"wrote {dst} ({len(STRINGS)} labels)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
