#!/usr/bin/env python3
"""gen_yes_no_strings.py — generate dos_port/assets/yes_no_strings.inc.

The two-option menu option strings of pret data/yes_no_menu_strings.asm
(TwoOptionMenuStrings), GB-charmap encoded through the unicode_converter
submodule (gb_text.encode) instead of hand-written charmap hex. Consumed by
src/home/yes_no.asm via %include.

Shape note — why nine strings and not seven:
pret stores each menu as ONE string with a `next` ($4E) between the two options,
e.g. `db "YES" / next "NO@"`, and PlaceString's <NEXT> handler advances
2 * SCREEN_WIDTH (hUILayoutFlags BIT_SINGLE_SPACED_LINES is clear here — nothing
in the two-option path sets it). The port places the two options with two separate
place_flat_str calls, two rows apart, which is the same rendering; so the options
are emitted as individual '@'-terminated strings and each menu names its pair.
The doubled row step lives in the .asm, not here.

Run from repo root or dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
TERMINATOR = 0x50  # '@'

# (NASM label, text). The distinct options across all 8 TwoOptionMenuStrings
# entries; menus pair them up in TwoOptionMenuDesc (src/home/yes_no.asm).
STRINGS = [
    ("str_yes", "YES"),
    ("str_no", "NO"),
    ("str_north", "NORTH"),
    ("str_west", "WEST"),
    ("str_south", "SOUTH"),
    ("str_east", "EAST"),
    ("str_trade", "TRADE"),
    ("str_cancel", "CANCEL"),
    ("str_heal", "HEAL"),
]


def main() -> int:
    lines = [
        "; yes_no_strings.inc — generated by tools/generators/gen_yes_no_strings.py.",
        "; DO NOT EDIT BY HAND.",
        ";",
        "; Two-option menu options from pret data/yes_no_menu_strings.asm, GB-charmap",
        "; encoded via the unicode_converter submodule (gb_text.encode) and",
        "; '@'-terminated ($50). pret joins each pair with a `next` ($4E); the port places",
        "; the two options separately, two rows apart — see TwoOptionMenuDesc.",
        "",
    ]
    for label, text in STRINGS:
        data = gb_text.encode(text) + [TERMINATOR]
        hexs = ", ".join(f"0x{b:02X}" for b in data)
        lines.append(f'{label}: db {hexs}   ; "{text}@"')

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "yes_no_strings.inc"
    dst.write_text("\n".join(lines) + "\n")
    print(f"wrote {dst} ({len(STRINGS)} labels)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
