#!/usr/bin/env python3
"""gen_used_move_text.py — generate dos_port/assets/used_move_text.inc (Tier 1 data).

pret's "<USER> used <MOVE>!" line (engine/battle/used_move_text.asm) is a CHAIN of
four text_asm-bearing wrappers — UsedMoveText, UsedMove1Text, UsedMove2Text and
MoveNameText — each of which opens with `text_far _XxxText` and then splices real
code into the stream. The wrappers themselves are Tier-2 code (they hold the
grammar/obedience logic), so they live in src/engine/battle/used_move_text.asm;
their far payloads are Tier-1 data and must be generated, exactly as
gen_trainer_text.py does for _TrainerNameText.

gen_battle_text.py cannot emit them: it flattens `text_far` INTO its wrapper and
skips any wrapper carrying a text_asm, so these five payloads have no other home.

Reuses gen_battle_text.py's charmap / memmap / text-macro parser verbatim.
Emits, in section .data, each far label with pret's exact byte stream
(_MoveNameText's `text_ram wStringBuffer` resolves to the port's gb_memmap.inc
offset, so the runtime prints the move name GetCurrentMove staged there).

DO NOT EDIT the output by hand — re-run this generator.
Run from repo root or dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "dos_port" / "assets" / "used_move_text.inc"

# Far labels consumed by src/engine/battle/used_move_text.asm (data/text/text_2.asm).
USED_MOVE_FAR = [
    "_ActorNameText",     # "<USER>@"                    — UsedMoveText
    "_UsedMove1Text",     # <LINE>"used @"               — UsedMove1Text
    "_UsedMove2Text",     # <LINE>"used @"               — UsedMove2Text
    "_UsedInsteadText",   # "instead,"<CONT>             — UsedMoveText_CheckObedience
    "_MoveNameText",      # text_ram wStringBuffer "@"   — MoveNameText
    # ADJACENCY IS LOAD-BEARING, not tidiness. _MoveNameText ends with `text "@"`
    # and NO text_end, so TextCommand_START leaves the stream pointer ONE PAST the
    # '@' — i.e. on whatever byte follows in ROM — and the far run BLEEDS into
    # _EndUsedMove1Text, prints "!" and terminates on its <DONE>. That is how pret's
    # sentence actually ends, and it is why MoveNameText's grammar-table hook and
    # GetMoveGrammar's result are dead in the English ROM (pret's own comment:
    # "this serves no purpose"). Emitting _MoveNameText last would run the port off
    # the end of this .inc instead — measured 2026-08-23 as a hard crash in all 16
    # move-using golden scenarios. Keep pret's data/text/text_2.asm order.
    "_EndUsedMove1Text",
    "_EndUsedMove2Text",
    "_EndUsedMove3Text",
    "_EndUsedMove4Text",
    "_EndUsedMove5Text",
]


def main() -> int:
    far = gbt.collect_far(gbt.load_charmap(), gbt.load_memmap())
    out = [
        "; used_move_text.inc — generated by tools/generators/gen_used_move_text.py. DO NOT EDIT BY HAND.",
        "; FAR streams of pret's used-move text chain (data/text/text_2.asm), flattened",
        "; via gen_battle_text.collect_far. %included by",
        "; src/engine/battle/used_move_text.asm inside section .data so the labels never",
        "; land in an orphaned section (link.ld).",
        "",
    ]
    for label in USED_MOVE_FAR:
        if label not in far:
            sys.stderr.write(f"gen_used_move_text: missing far label {label}\n")
            return 1
        rows = [
            "    db " + ", ".join(f"0x{b:02X}" for b in far[label][k:k + 16])
            for k in range(0, len(far[label]), 16)
        ]
        out.append(f"{label}:\n" + "\n".join(rows))
    out.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({len(USED_MOVE_FAR)} far labels)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
