#!/usr/bin/env python3
"""gen_hidden_coin_coords.py — generate dos_port/assets/hidden_coin_coords.inc.

Emits the Gen-1 Yellow HiddenCoinCoords table (Game Corner hidden-coin tiles),
the sibling of HiddenItemCoords (tools/generators/gen_hidden_item_coords.py) --
same shape, same source layout, different pret table.

pret keeps this table in data/events/hidden_coins.asm, where the `hidden_coin`
macro is `db \\1, \\3, \\2` -- i.e. it SWAPS the source x,y args and stores each
3-byte row as `db map_id, y, x`. FindHiddenItemOrCoinsIndex
(engine/events/hidden_items.asm, dos_port/src/engine/events/hidden_items.asm)
scans it with the same {map, y, x} triple stride 3, matching wCurMap, then y,
then x. This generator preserves the stored byte order map_id, y, x exactly --
same convention gen_hidden_item_coords.py already established for
HiddenItemCoords.

The table is a FLAT program-.data array, `db -1` terminated. Map consts are
resolved to numeric ids here (reusing gen_hidden_events.parse_map_ids) because
the port's includes do not define the pret map constant set.

Run from repo root (or dos_port/); paths resolve relative to the repo root.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_hidden_events as ghe  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
SRC = ROOT / "data/events/hidden_coins.asm"


def parse_coords():
    """Return [(map_name, y, x), ...] in source (= flag-bit) order.

    Source line: `hidden_coin MAP, x, y` (comment says "map id, x, y"); the pret
    macro stores map, y, x -- we keep the source args labelled x,y and emit in
    the stored map,y,x order below.
    """
    rows = []
    for line in SRC.read_text().splitlines():
        m = re.match(r"\s*hidden_coin\s+(\w+)\s*,\s*(\d+)\s*,\s*(\d+)", line)
        if m:
            name, x, y = m.group(1), int(m.group(2)), int(m.group(3))
            rows.append((name, y, x))
    return rows


def main():
    map_ids = ghe.parse_map_ids()
    rows = parse_coords()

    unknown = [n for (n, _y, _x) in rows if n not in map_ids]
    if unknown:
        sys.exit(f"gen_hidden_coin_coords: unknown maps: {sorted(set(unknown))}")

    out = []
    out.append("; AUTO-GENERATED by tools/generators/gen_hidden_coin_coords.py — do not edit.")
    out.append("; Gen-1 Yellow HiddenCoinCoords table (Game Corner hidden-coin tiles).")
    out.append("; Source: data/events/hidden_coins.asm (read-only pret spec).")
    out.append(";")
    out.append("; Row = db map_id, y, x  (3-byte stride; pret's `hidden_coin` macro swaps")
    out.append(";       the source x,y args to store map,y,x). `db -1` terminates.")
    out.append("; FindHiddenItemOrCoinsIndex (dos_port/src/engine/events/hidden_items.asm)")
    out.append("; scans it, matching wCurMap then y then x.")
    out.append("")
    out.append("global HiddenCoinCoords")
    out.append("HiddenCoinCoords:")
    for (name, y, x) in rows:
        out.append(f"    db 0x{map_ids[name]:02X}, {y:>3}, {x:>3}   ; {name}")
    out.append("    db 0xFF                         ; -1 end")
    out.append("")

    dst = ASSETS / "hidden_coin_coords.inc"
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(out) + "\n")
    print(f"wrote {dst} (HiddenCoinCoords {len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
