#!/usr/bin/env python3
"""gen_book_or_sculpture_text.py — generate dos_port/assets/book_or_sculpture_text.inc (Tier 1 data).

Generates:
  PokemonBooksText, DiglettSculptureText
  (flattened text streams from pret engine/events/hidden_events/book_or_sculpture.asm
  referencing data/text/text_2.asm).

DO NOT EDIT the output by hand — re-run this generator. Run from repo root or
dos_port/.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "dos_port" / "assets" / "book_or_sculpture_text.inc"

SRC_FILES = ["engine/events/hidden_events/book_or_sculpture.asm"]
WANT = {"PokemonBooksText", "DiglettSculptureText"}


def main() -> int:
    charmap = gbt.load_charmap()
    memmap = gbt.load_memmap()
    far_db = gbt.collect_far(charmap, memmap)

    gbt.BATTLE_SRC = SRC_FILES
    wrappers = gbt.collect_wrappers(charmap, memmap, far_db)

    missing = WANT - set(wrappers)
    if missing:
        raise SystemExit(
            f"gen_book_or_sculpture_text: expected labels missing from scan: {sorted(missing)}")

    labels = sorted(WANT)

    out = [
        "; book_or_sculpture_text.inc — generated by tools/generators/gen_book_or_sculpture_text.py. DO NOT EDIT BY HAND.",
        "; Book or sculpture text streams.",
        "; Source: engine/events/hidden_events/book_or_sculpture.asm.",
        "",
        "section .data",
        "align 4",
        "",
    ]

    for label in labels:
        b = wrappers[label]
        out.append(f"global {label}")
        out.append(f"{label}:")
        for i in range(0, len(b), 16):
            out.append("    db " + ", ".join(f"0x{x:02X}" for x in b[i:i + 16]))
        out.append(f"global {label}_ref")
        out.append(f"{label}_ref: dd {label}, {len(b)}   ; flat ptr + byte count")
        out.append(f"{label}_len equ {len(b)}")
        out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}: {len(labels)} label(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
