#!/usr/bin/env python3
"""gen_give_pokemon_text.py — generate dos_port/assets/give_pokemon_text.inc (Tier 1 data).

Labels in pret engine/events/give_pokemon.asm:
  GotMonText              -> _GotMonText ("<PLAYER> got <MON>!") + jingle
  SentToBoxText           -> _SentToBoxText ("There's no more room for #MON! ...")
  BoxIsFullText           -> _BoxIsFullText ("There's no more room for #MON! ...")
  UnknownTerminator_f6794 -> text_end ($50)

pret wraps these as text_far-wrapped labels in engine/events/give_pokemon.asm,
with the bodies in data/text/text_8.asm. GotMonText also carries a sound_get_item_1
command.

Reuses gen_battle_text.py's charmap/memmap/macro parser and points it at the give_pokemon
source, emitting each label as a flattened, self-terminating stream plus a
{ptr, len} <Label>_ref pair.

Carrier: dos_port/src/engine/events/give_pokemon.asm (the pret mirror path).

DO NOT EDIT the output by hand — re-run this generator. Run from repo root or
dos_port/.
"""
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "dos_port" / "assets" / "give_pokemon_text.inc"

GIVE_POKEMON_SRC = ["engine/events/give_pokemon.asm"]

WANT = {"GotMonText", "SentToBoxText", "BoxIsFullText", "UnknownTerminator_f6794"}


def existing_labels() -> set:
    """Labels already emitted elsewhere — never define one global twice."""
    out = set()
    assets = ROOT / "dos_port" / "assets"
    for inc in assets.glob("*.inc"):
        if inc.name == OUT.name:
            continue
        out |= set(re.findall(r"^global (\w+)$", inc.read_text(), re.M))
    return out


def main() -> int:
    charmap = gbt.load_charmap()
    memmap = gbt.load_memmap()
    far_db = gbt.collect_far(charmap, memmap)

    gbt.BATTLE_SRC = GIVE_POKEMON_SRC
    wrappers = gbt.collect_wrappers(charmap, memmap, far_db)

    # UnknownTerminator_f6794 is just text_end
    if "UnknownTerminator_f6794" not in wrappers:
        wrappers["UnknownTerminator_f6794"] = [gbt.TX_END]

    missing = WANT - set(wrappers)
    if missing:
        raise SystemExit(
            f"gen_give_pokemon_text: expected labels missing from scan: {sorted(missing)}")

    skip = existing_labels()
    labels = sorted(WANT - skip)
    if not labels:
        raise SystemExit("gen_give_pokemon_text: every wanted label is already emitted elsewhere")

    out = [
        "; give_pokemon_text.inc — generated by tools/generators/gen_give_pokemon_text.py. DO NOT EDIT BY HAND.",
        "; GivePokemon message streams (pret engine/events/give_pokemon.asm wrappers),",
        f"; text_far flattened. {len(labels)} label(s). section .data (see link.ld).",
        "",
        "section .data",
        "",
    ]
    for label in labels:
        b = wrappers[label]
        out.append(f"global {label}")
        out.append(f"{label}:")
        for i in range(0, len(b), 16):
            out.append("    db " + ", ".join(f"0x{x:02X}" for x in b[i:i + 16]))
        out.append(f"global {label}_ref")
        out.append(f"{label}_ref: dd {label}, {len(b)}   ; flat ptr + byte count")
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}: {len(labels)} label(s), "
          + ", ".join(f"{k}={len(wrappers[k])}B" for k in labels))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
