#!/usr/bin/env python3
"""gen_trainer_names.py — generate dos_port/assets/trainer_names.inc from pret.

Emits TrainerNames: NUM_TRAINERS (47) **variable-length**, '@'-terminated ($50)
records in trainer-class order, GB-charmap encoded — exactly as pret's `li`
macro over data/trainers/names.asm (which expands to `db <text>, "@"`).

Trainer class NOBODY ($00) has no entry (the list starts at YOUNGSTER, $01);
GetName/GetTrainerName_ index it 1-based via [wTrainerClass] directly (see
dos_port/src/home/names.asm GetName "types 2-7" walk and
dos_port/src/engine/battle/get_trainer_name.asm), counting $50 terminators —
same non-padded walk as MoveNames, not the fixed-width AddNTimes path used for
MonsterNames. Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
NUM_TRAINERS = 47
TERM = 0x50                  # '@' terminator
TRAINER_NAME_MAX = 12        # TRAINER_NAME_LENGTH - 1 (list_start bound; pret data/trainers/names.asm)


def load_charmap(path: Path) -> list:
    cm = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s+charmap\s+"((?:[^"\\]|\\.)*)",\s*\$([0-9a-fA-F]+)', line)
        if m:
            cm.append((m.group(1), int(m.group(2), 16)))
    cm.sort(key=lambda x: -len(x[0]))      # longest-match first
    return cm


def encode(s: str, charmap: list) -> bytes:
    out, i = [], 0
    while i < len(s):
        for key, val in charmap:
            if key and s[i:].startswith(key):
                out.append(val)
                i += len(key)
                break
        else:
            raise ValueError(f"Unrecognised char at {i}: {s[i:i+4]!r}")
    return bytes(out)


def _generate_trainer_name_pointers(charmap: list) -> int:
    """Generate assets/trainer_name_pointers.inc from data/trainers/name_pointers.asm.

    47 rows: fixed strings as dd <label> where <label> db <encoded> 0x50;
    wTrainerName rows as dd 0xFFFFFFFF marker (flat model WRAM/ROM split).
    """
    src = ROOT / "data/trainers/name_pointers.asm"
    text = src.read_text(encoding="utf-8")
    # Parse dw rows in TrainerNamePointers order
    rows = []  # 'wTrainerName' or '.YoungsterName' etc
    in_table = False
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("TrainerNamePointers:"):
            in_table = True
            continue
        if not in_table:
            continue
        if s.startswith("assert_table_length"):
            break
        m = re.match(r"dw\s+(\.?\w+)", s)
        if m:
            rows.append(m.group(1))
    if len(rows) != NUM_TRAINERS:
        print(f"TrainerNamePointers: expected {NUM_TRAINERS} rows, got {len(rows)}", file=sys.stderr)
        return 1
    # Parse fixed string defs: .Label: db "STRING@"
    fixed_map = {}
    for line in text.splitlines():
        m = re.match(r'\.(\w+):\s+db\s+"((?:[^"\\]|\\.)*)"', line)
        if m:
            label = m.group(1)
            raw = m.group(2)
            # Strip trailing @ terminator if present (pret includes it in db)
            if raw.endswith("@"):
                raw = raw[:-1]
            fixed_map[label] = raw
    # Build inc
    out = [
        "; trainer_name_pointers.inc — generated by tools/generators/gen_trainer_names.py. DO NOT EDIT BY HAND.",
        "; Faithful port of pret data/trainers/name_pointers.asm TrainerNamePointers (47 rows).",
        "; Fixed rows: dd <label> where <label> db <charmap> 0x50; wTrainerName rows: dd 0xFFFFFFFF marker.",
        "; Marker encodes WRAM pointer wTrainerName — flat model cannot hold a WRAM addr as flat ptr.",
        "; SaveTrainerName indexes this table inline (stride 4, not pret's dw*2) and copies via .CopyCharacter.",
        "",
        "global TrainerNamePointers",
        "",
        "TrainerNamePointers:",
    ]
    fixed_labels_used = set()
    for i, entry in enumerate(rows):
        if entry == "wTrainerName":
            out.append(f"    dd 0xFFFFFFFF  ; {i+1:2d} wTrainerName (runtime)")
        else:
            # entry like .YoungsterName
            bare = entry.lstrip(".")
            if bare not in fixed_map:
                print(f"TrainerNamePointers: fixed label {entry} has no db string", file=sys.stderr)
                return 1
            out.append(f"    dd {bare}  ; {i+1:2d} {bare}")
            fixed_labels_used.add(bare)
    out.append("")
    # Emit fixed strings (charmap-encoded + 0x50)
    for bare in sorted(fixed_labels_used):
        raw = fixed_map[bare]
        enc = encode(raw, charmap)
        rec = enc + bytes([TERM])
        out.append(f"{bare}:")
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in rec) + f"  ; \"{raw}@\"")
    out.append("")
    out.append(f"    ; assert_table_length NUM_TRAINERS ({NUM_TRAINERS})")
    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "trainer_name_pointers.inc"
    dst.write_text("\n".join(out) + "\n")
    print(f"wrote {dst} (TrainerNamePointers {len(rows)} rows, {len(fixed_labels_used)} fixed strings)")
    return 0


def main() -> int:
    charmap = load_charmap(ROOT / "constants/charmap.asm")
    names = []
    for line in (ROOT / "data/trainers/names.asm").read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s*li\s+"((?:[^"\\]|\\.)*)"', line)
        if m:
            names.append(m.group(1))
    if len(names) != NUM_TRAINERS:
        print(f"expected {NUM_TRAINERS} names, got {len(names)}", file=sys.stderr)
        return 1

    out = [
        "; trainer_names.inc — generated by tools/generators/gen_trainer_names.py. DO NOT EDIT BY HAND.",
        f"; TrainerNames: {NUM_TRAINERS} variable-length '@'-terminated names, trainer-class order",
        "; (1-based: index 1 = YOUNGSTER ... index 47 = LANCE; class NOBODY=$00 has no entry).",
        "; Walked by GetName (counts $50 terminators); NOT fixed-width.",
        "",
        "global TrainerNames",
        "",
        "TrainerNames:",
    ]
    total = 0
    for i, nm in enumerate(names):
        enc = encode(nm, charmap)
        if len(enc) > TRAINER_NAME_MAX:
            print(f"name too long ({len(enc)} > {TRAINER_NAME_MAX}): {nm!r}", file=sys.stderr)
            return 1
        rec = enc + bytes([TERM])
        total += len(rec)
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in rec) + f"    ; trainer class {i + 1}  {nm}")
    out += ["TrainerNames_end:", ""]

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "trainer_names.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} (TrainerNames {len(names)} names, {total} bytes)")
    rc = _generate_trainer_name_pointers(charmap)
    if rc != 0:
        return rc
    return 0


if __name__ == "__main__":
    sys.exit(main())
