#!/usr/bin/env python3
"""gen_evos_moves.py — generate dos_port/assets/evos_moves.inc from pret source.

Emits the evolution + level-up-learnset data consumed by GetMonLearnset /
WriteMonMoves / (later) evolution:

  EvosMovesPointerTable: 190 (NUM_POKEMON_INDEXES) flat pointers, internal-index
    order. NOTE the DOS divergence: pret stores 16-bit `dw` bank pointers; the
    flat port stores 32-bit `dd` program-image labels, so GetMonLearnset indexes
    it x4 and reads a 32-bit pointer.
  <Mon>EvosMoves: per-mon blob — evolution entries, db 0, (level,move) learnset
    pairs, db 0 — byte-identical to pret (just the operands resolved to bytes).

Each db operand is resolved against a merged constant table (EVOLVE_*, species
internal indexes, items, move ids); bare numbers stay numeric. Run from repo
root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
SRC = ROOT / "data/pokemon/evos_moves.asm"
NUM_POKEMON_INDEXES = 190


def parse_consts(rel_path: str) -> dict:
    out, val = {}, 0
    for line in (ROOT / rel_path).read_text().splitlines():
        s = line.split(";", 1)[0].strip()
        if not s:
            continue
        m = re.match(r"const_def(?:\s+(-?\w+))?$", s)
        if m:
            val = int(m.group(1)) if m.group(1) else 0
            continue
        m = re.match(r"const_next\s+(-?\w+)$", s)
        if m:
            val = int(m.group(1), 0)
            continue
        m = re.match(r"const_skip(?:\s+(\w+))?$", s)
        if m:
            val += int(m.group(1), 0) if m.group(1) else 1
            continue
        m = re.match(r"const\s+(\w+)$", s)
        if m:
            out[m.group(1)] = val
            val += 1
    return out


def build_consts() -> dict:
    merged = {}
    sources = [
        ("constants/pokemon_data_constants.asm", "evolve"),   # EVOLVE_*
        ("constants/pokemon_constants.asm",      "species"),
        ("constants/item_constants.asm",         "item"),
        ("constants/move_constants.asm",         "move"),
    ]
    for path, _ in sources:
        for name, val in parse_consts(path).items():
            # First definition wins; warn on a real value collision only.
            if name in merged and merged[name] != val:
                print(f"WARNING: const collision {name}: {merged[name]} vs {val}",
                      file=sys.stderr)
            merged.setdefault(name, val)
    return merged


def resolve(tok: str, consts: dict) -> int:
    tok = tok.strip()
    if tok in consts:
        return consts[tok]
    if tok.startswith("$"):
        return int(tok[1:], 16)
    return int(tok, 0)


def main() -> int:
    consts = build_consts()
    lines = SRC.read_text().splitlines()

    # Pass 1: ordered pointer-table labels (the `dw <Label>` block).
    order = []
    in_table = False
    for line in lines:
        s = line.split(";", 1)[0].strip()
        if s == "EvosMovesPointerTable:":
            in_table = True
            continue
        if in_table:
            m = re.match(r"dw\s+(\w+)$", s)
            if m:
                order.append(m.group(1))
            elif s and not s.startswith("table_width") and not s.startswith("assert_table"):
                break
    if len(order) != NUM_POKEMON_INDEXES:
        print(f"expected {NUM_POKEMON_INDEXES} pointers, got {len(order)}", file=sys.stderr)
        return 1

    # Pass 2: each <Label>: blob -> resolved bytes.
    blobs = {}
    cur = None
    for line in lines:
        s = line.split(";", 1)[0].strip()
        if not s:
            continue
        m = re.match(r"(\w+):$", s)
        if m and (m.group(1) in order or m.group(1).endswith("EvosMoves")):
            cur = m.group(1)
            blobs.setdefault(cur, bytearray())
            continue
        if cur is None:
            continue
        m = re.match(r"db\s+(.+)$", s)
        if m:
            for tok in m.group(1).split(","):
                blobs[cur].append(resolve(tok, consts) & 0xFF)
        else:
            cur = None  # left the data blobs (e.g. INCLUDE / next section)

    missing = [lbl for lbl in order if lbl not in blobs]
    if missing:
        print(f"missing blobs: {missing[:5]}...", file=sys.stderr)
        return 1

    out = [
        "; evos_moves.inc — generated by tools/generators/gen_evos_moves.py. DO NOT EDIT BY HAND.",
        f"; EvosMovesPointerTable: {NUM_POKEMON_INDEXES} flat (dd) pointers, internal-index order.",
        "; Per-mon blob: evolution entries, db 0, (level,move) learnset pairs, db 0.",
        "",
        "EvosMovesPointerTable:",
    ]
    for lbl in order:
        out.append(f"    dd {lbl}")
    out.append("")
    for lbl in order:
        b = blobs[lbl]
        out.append(f"{lbl}:")
        out.append("    db " + ", ".join(f"0x{x:02X}" for x in b))
    out.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "evos_moves.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst} (EvosMovesPointerTable {len(order)} entries, "
          f"{sum(len(b) for b in blobs.values())} data bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
