#!/usr/bin/env python3
"""Generate the NASM constants the translated map scripts reference by name.

Input:  constants/toggle_constants.asm    TOGGLE_*   (toggleable-object ids)
        constants/pokemon_constants.asm   species
        constants/item_constants.asm      items, FLOOR_*, badges-as-items
        constants/script_constants.asm    TRADE_FOR_*, script misc
        constants/ram_constants.asm       BIT_* (badge / status bit indices)
Output: dos_port/assets/script_constants.inc

WHY THIS EXISTS. pret writes `lb bc, TM_BUBBLEBEAM, 1`, `ld a, TOGGLE_OLD_MAN_1`,
`set BIT_THUNDERBADGE, [hl]` — never a bare literal. The one-shot transpiler
resolved those names to numbers, which assembles identically but leaves a reader
unable to check a line against the disassembly without doing arithmetic. These
constants let the emitted scripts carry pret's own names.

Mirrors macros/const.asm semantics, as gen_event_constants.py does:
  const_def [start=0] [inc=1]   reset counter
  const NAME                    NAME = counter; counter += inc
  const_skip [N=1]              counter += inc*N
  const_next X                  counter = X
plus item_constants.asm's `add_hm` / `add_tm` and `DEF NAME EQU OTHER` aliases.

Names already defined in include/gb_constants.inc are SKIPPED, so this file never
shadows a hand-maintained constant (NASM would take the first definition and the
duplicate would drift silently).

Run from dos_port/ or the repo root:
    python3 tools/generators/gen_script_constants.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent.parent
DOS = Path(__file__).resolve().parent.parent.parent
OUT = DOS / "assets" / "script_constants.inc"
GB_CONSTANTS = DOS / "include" / "gb_constants.inc"

# (pret file, section title) in emission order
SOURCES = [
    ("toggle_constants.asm", "Toggleable-object ids (wToggleableObjectIndex; Hide/ShowObject)"),
    ("pokemon_constants.asm", "Species ids (internal Gen-1 index order)"),
    ("item_constants.asm", "Items, elevator floors, badge-as-item ids"),
    ("script_constants.asm", "Script constants (in-game trades, script misc)"),
    ("ram_constants.asm", "Bit indices in WRAM flag bytes"),
    ("pikachu_emotion_constants.asm", "Pikachu map/spawn bit indices"),
]


def parse_num(tok):
    tok = tok.strip()
    if tok.startswith('$'):
        return int(tok[1:], 16)
    if tok.startswith('%'):
        return int(tok[1:], 2)
    return int(tok, 0)


def parse(path):
    """Return [(name, value)] in source order for one pret constants file."""
    value, inc = 0, 1
    out = []
    seen = {}
    for raw in path.read_text(encoding='utf-8').splitlines():
        line = raw.split(';', 1)[0].strip()
        if not line:
            continue
        m = re.match(r"const_def(?:\s+(\S+?))?(?:\s*,\s*(\S+))?$", line)
        if m:
            value = parse_num(m.group(1)) if m.group(1) else 0
            inc = parse_num(m.group(2)) if m.group(2) else 1
            continue
        m = re.match(r"const_next\s+(\S+)$", line)
        if m:
            value = parse_num(m.group(1))
            continue
        m = re.match(r"const_skip(?:\s+(\S+))?$", line)
        if m:
            value += inc * (parse_num(m.group(1)) if m.group(1) else 1)
            continue
        m = re.match(r"const\s+(\w+)", line)
        if m:
            out.append((m.group(1), value)); seen[m.group(1)] = value
            value += inc
            continue
        m = re.match(r"add_(hm|tm)\s+(\w+)$", line)
        if m:
            n = "%s_%s" % (m.group(1).upper(), m.group(2))
            out.append((n, value)); seen[n] = value
            value += 1
            continue
        # `DEF NAME EQU OTHER` aliases (SAFARI_BAIT EQU BOULDERBADGE, ...)
        m = re.match(r"DEF\s+(\w+)\s+EQU\s+(\w+)$", line)
        if m and m.group(2) in seen:
            out.append((m.group(1), seen[m.group(2)])); seen[m.group(1)] = seen[m.group(2)]
            continue
        # `DEF BIT_FOO EQU 3` — plain numeric bit indices
        m = re.match(r"DEF\s+(\w+)\s+EQU\s+(\$?\w+)$", line)
        if m:
            try:
                out.append((m.group(1), parse_num(m.group(2)))); seen[m.group(1)] = out[-1][1]
            except ValueError:
                pass
    return out


def main():
    # both spellings: gb_constants.inc is %define now (an equ emits a COFF symbol
    # into every including object), but older/hand entries may still be equ.
    _gc = GB_CONSTANTS.read_text(encoding='utf-8')
    already = set(re.findall(r"^\s*([A-Z][A-Z0-9_]*)\s+equ\b", _gc, re.M)) \
            | set(re.findall(r"^\s*%define\s+([A-Z][A-Z0-9_]*)\b", _gc, re.M))
    lines = [
        "; AUTO-GENERATED by dos_port/tools/generators/gen_script_constants.py — DO NOT EDIT.",
        "; pret constant names for the translated map scripts, so a line can be checked",
        "; against the disassembly without resolving numbers by hand.",
        ";",
        "; Names already in include/gb_constants.inc are omitted here on purpose — that",
        "; file wins, and a duplicate definition would be free to drift out of step.",
        "",
        "%ifndef SCRIPT_CONSTANTS_INC",
        "%define SCRIPT_CONSTANTS_INC",
        "",
    ]
    emitted, total = set(), 0
    for fn, title in SOURCES:
        src = ROOT / "constants" / fn
        if not src.exists():
            sys.exit("missing pret source: %s" % src)
        rows = [(n, v) for n, v in parse(src)
                if n not in already and n not in emitted]
        if not rows:
            continue
        lines.append("; --- %s" % title)
        lines.append("; constants/%s" % fn)
        width = max(len(n) for n, _ in rows)
        for n, v in rows:
            emitted.add(n)
            # %define, not equ -- see the header note; equ would emit a COFF symbol
            # into every object that includes this file.
            lines.append("%%define %-*s 0x%02X" % (width, n, v))
            total += 1
        lines.append("")
    lines.append("%endif ; SCRIPT_CONSTANTS_INC")
    OUT.write_text("\n".join(lines) + "\n", encoding='utf-8')
    print("gen_script_constants.py: %d constants -> %s"
          % (total, OUT.relative_to(DOS.parent)))


if __name__ == "__main__":
    main()
