#!/usr/bin/env python3
"""gen_battle_anim_data.py — Tier-1 battle animation data for the DOS port.

Parses the read-only pret sources:
  constants/move_constants.asm            move ids + the anim-id tail (SHOWPIC_ANIM..BAIT_ANIM)
  constants/move_animation_constants.asm  SE_* / SUBANIM_* / SUBANIMTYPE_* / FRAMEBLOCK_* /
                                          BASECOORD_* / FRAMEBLOCKMODE_* / FIRST_SE_ID / NUM_*
  constants/battle_anim_constants.asm     ANIMATIONTYPE_*
  constants/hardware.inc                  OAM_* attribute flag values (dbsprite attrs)
  data/moves/animations.asm               AttackAnimationPointers + per-anim command streams
  data/battle_anims/subanimations.asm     SubanimationPointers + subanim bodies
  data/battle_anims/frame_blocks.asm      FrameBlockPointers + frame block bodies
  data/battle_anims/base_coords.asm       FrameBlockBaseCoords
  data/moves/sfx.asm                      MoveSoundTable (SFX_* names stay symbolic; resolved at
                                          assembly time against assets/audio_constants.inc)

Emits:
  assets/battle_anim_constants.inc  equ-only (include-guarded, includable anywhere;
                                    gb_constants.inc pulls it in for TOSS_ANIM etc.)
  assets/battle_anim_data.inc       dd flat pointer tables + db bodies, GB-space raw.
                                    Carrier: src/engine/battle/animations.asm (section .data).

All coordinate/delta bytes are pret's GB-space values, byte-for-byte: the port's
battle-frame projection (+80,+24 px / BCOORD +10,+3) is applied by CODE at
publication, never baked into this data (docs/current_plan_battle_animations.md).

Command stream encoding (consumed by PlayAnimation):
  subanimation:   db (tileset << 6) | delay, sound_move_id - 1, subanim_id   (first byte < FIRST_SE_ID)
  special effect: db se_id, sound_move_id - 1                                 (se_id >= FIRST_SE_ID)
  terminator:     db $FF

Self-checks (always run): every parsed count vs its pret NUM_* constant, every
symbolic reference resolved, every stream terminated, every frame block's entry
count vs its header byte.
Cross-check (automatic when the golden worktree is present, forced by --verify):
byte-compares every encoded body against the sha1-verified golden ROM through
pokeyellow.sym. Pointer tables are excluded (dw ROM addrs vs dd flat), and
MoveSoundTable rows compare their pitch/tempo columns only (the SFX id column is
emitted symbolically).
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DOS_PORT = os.path.normpath(os.path.join(HERE, "..", ".."))
REPO = os.path.normpath(os.path.join(DOS_PORT, ".."))
GOLDEN = os.path.join(os.path.dirname(REPO), os.path.basename(REPO) + "-pret-golden")

OUT_CONST = os.path.join(DOS_PORT, "assets", "battle_anim_constants.inc")
OUT_DATA = os.path.join(DOS_PORT, "assets", "battle_anim_data.inc")

HEADER = (
    "; DO NOT EDIT BY HAND — generated by tools/generators/gen_battle_anim_data.py\n"
    "; Source of truth: pret data/moves/animations.asm, data/battle_anims/*.asm,\n"
    "; data/moves/sfx.asm, constants/move*_constants.asm (see the generator docstring).\n"
)


def strip_comment(line):
    return line.split(";", 1)[0].rstrip()


def parse_num(tok):
    tok = tok.strip()
    neg = tok.startswith("-")
    if neg:
        tok = tok[1:].strip()
    if tok.startswith("$"):
        v = int(tok[1:], 16)
    elif tok.startswith("%"):
        v = int(tok[1:], 2)
    else:
        v = int(tok, 10)
    return -v if neg else v


class ConstTable:
    """Minimal evaluator for pret's const_def/const/const_skip/DEF..EQU machinery."""

    def __init__(self):
        self.values = {}

    def feed_file(self, path):
        cv = None
        for raw in open(path, encoding="utf-8"):
            line = strip_comment(raw).strip()
            if not line:
                continue
            m = re.match(r"const_def(?:\s+(.+))?$", line)
            if m:
                cv = parse_num(m.group(1)) if m.group(1) else 0
                continue
            m = re.match(r"const_skip(?:\s+(.+))?$", line)
            if m:
                cv += parse_num(m.group(1)) if m.group(1) else 1
                continue
            m = re.match(r"const\s+(\w+)$", line)
            if m:
                self.values[m.group(1)] = cv
                cv += 1
                continue
            m = re.match(r"DEF\s+(\w+)\s+EQU\s+const_value\s*-\s*1$", line)
            if m:
                self.values[m.group(1)] = cv - 1
                continue
            m = re.match(r"DEF\s+(\w+)\s+EQU\s+const_value$", line)
            if m:
                self.values[m.group(1)] = cv
                continue
            m = re.match(r"DEF\s+(\w+)\s+EQU\s+([$%]?[0-9A-Fa-f]+)$", line)
            if m:
                self.values[m.group(1)] = parse_num(m.group(2))
                continue
            # anything else (macros, other DEF expressions) is irrelevant here
        return self


def parse_oam_flags(path):
    bits = {}
    flags = {}
    for raw in open(path, encoding="utf-8"):
        line = strip_comment(raw).strip().lower()
        m = re.match(r"def\s+(b_oam_\w+)\s+equ\s+(\d+)$", line)
        if m:
            bits[m.group(1).upper()] = int(m.group(2))
            continue
        m = re.match(r"def\s+(oam_\w+)\s+equ\s+1\s*<<\s*(b_oam_\w+)$", line)
        if m:
            flags[m.group(1).upper()] = 1 << bits[m.group(2).upper()]
    return flags


def resolve_attr(tok, oam_flags):
    total = 0
    for part in tok.split("|"):
        part = part.strip()
        if not part:
            continue
        if part in oam_flags:
            total |= oam_flags[part]
        else:
            total |= parse_num(part)
    return total


def parse_pointer_table(lines, i, expect_label, stop_assert):
    """Parse `Name:` / table_width / dw entries. assert_table_length markers are
    collected as (name, entries_so_far); parsing stops after `stop_assert`.
    Returns (entries, i_after, asserts)."""
    assert strip_comment(lines[i]).strip() == expect_label + ":", (
        f"expected {expect_label}: at line {i + 1}, got {lines[i]!r}")
    i += 1
    entries = []
    asserts = []
    while i < len(lines):
        line = strip_comment(lines[i]).strip()
        i += 1
        if not line or line.startswith("table_width"):
            continue
        m = re.match(r"dw\s+(\w+)$", line)
        if m:
            entries.append(m.group(1))
            continue
        m = re.match(r"assert_table_length\s+(\w+)$", line)
        if m:
            asserts.append((m.group(1), len(entries)))
            if m.group(1) == stop_assert:
                break
            continue
        raise SystemExit(f"unexpected line in {expect_label}: {line!r}")
    assert asserts and asserts[-1][0] == stop_assert, (
        f"{expect_label}: never reached assert_table_length {stop_assert}")
    return entries, i, asserts


def parse_anim_streams(path, consts):
    lines = open(path, encoding="utf-8").read().splitlines()
    # find pointer table
    start = next(i for i, l in enumerate(lines)
                 if strip_comment(l).strip() == "AttackAnimationPointers:")
    entries, i, asserts = parse_pointer_table(lines, start, "AttackAnimationPointers",
                                          "NUM_ATTACK_ANIMS")
    anim_asserts = dict(asserts)
    bodies = {}       # label -> bytearray (aliases share the object)
    order = []        # (labels_tuple) in file order
    comments = {}     # label -> [comment per emitted db line]
    open_labels = []
    in_macro = False
    for raw in lines[i:]:
        line = strip_comment(raw).strip()
        if not line:
            continue
        if line.startswith("MACRO"):
            in_macro = True
            continue
        if line == "ENDM":
            in_macro = False
            continue
        if in_macro:
            continue
        m = re.match(r"(\w+):$", line)
        if m:
            lbl = m.group(1)
            if open_labels and bodies[open_labels[-1]]:
                open_labels = []
            if not open_labels:
                order.append([])
            open_labels.append(lbl)
            order[-1].append(lbl)
            body = bodies[open_labels[0]] if len(open_labels) > 1 else bytearray()
            bodies[lbl] = body
            comments[lbl] = comments[open_labels[0]] if len(open_labels) > 1 else []
            continue
        m = re.match(r"battle_anim\s+(.+)$", line)
        if m:
            args = [a.strip() for a in m.group(1).split(",")]
            body = bodies[open_labels[0]]
            cmt = comments[open_labels[0]]
            snd = consts.values[args[0]]
            if len(args) == 4:
                sub = consts.values[args[1]]
                tileset = parse_num(args[2])
                delay = parse_num(args[3])
                first = (tileset << 6) | delay
                assert first < consts.values["FIRST_SE_ID"], (
                    f"subanim first byte {first:#x} collides with SE space in {open_labels}")
                body += bytes([first, (snd - 1) & 0xFF, sub])
                cmt.append(f"battle_anim {', '.join(args)}")
            elif len(args) == 2:
                se = consts.values[args[1]]
                assert se >= consts.values["FIRST_SE_ID"], (
                    f"special-effect id {se:#x} below FIRST_SE_ID in {open_labels}")
                body += bytes([se, (snd - 1) & 0xFF])
                cmt.append(f"battle_anim {', '.join(args)}")
            else:
                raise SystemExit(f"battle_anim arity {len(args)}: {line!r}")
            continue
        if line == "db -1":
            bodies[open_labels[0]].append(0xFF)
            comments[open_labels[0]].append("end")
            continue
        raise SystemExit(f"unexpected line in animation streams: {line!r}")
    return entries, order, bodies, comments, anim_asserts


def parse_subanims(path, consts):
    lines = open(path, encoding="utf-8").read().splitlines()
    start = next(i for i, l in enumerate(lines)
                 if strip_comment(l).strip() == "SubanimationPointers:")
    entries, i, _ = parse_pointer_table(lines, start, "SubanimationPointers", "NUM_SUBANIMS")
    bodies = {}
    order = []
    in_macro = False
    cur = None
    for raw in lines[i:]:
        line = strip_comment(raw).strip()
        if not line:
            continue
        if line.startswith("MACRO"):
            in_macro = True
            continue
        if line == "ENDM":
            in_macro = False
            continue
        if in_macro:
            continue
        m = re.match(r"(\w+):$", line)
        if m:
            cur = m.group(1)
            bodies[cur] = bytearray()
            order.append(cur)
            continue
        m = re.match(r"subanim\s+(\w+)\s*,\s*(\d+)$", line)
        if m:
            t = consts.values[m.group(1)]
            n = int(m.group(2))
            bodies[cur].append((t << 5) | n)
            continue
        m = re.match(r"db\s+(\w+)\s*,\s*(\w+)\s*,\s*(\w+)$", line)
        if m:
            fb, bc, mode = (consts.values[m.group(k)] for k in (1, 2, 3))
            bodies[cur] += bytes([fb, bc, mode])
            continue
        raise SystemExit(f"unexpected line in subanimations: {line!r}")
    for lbl, body in bodies.items():
        n = body[0] & 0x1F
        assert len(body) == 1 + 3 * n, f"{lbl}: header count {n} vs {len(body)} bytes"
    return entries, order, bodies


def parse_frame_blocks(path, oam_flags):
    lines = open(path, encoding="utf-8").read().splitlines()
    start = next(i for i, l in enumerate(lines)
                 if strip_comment(l).strip() == "FrameBlockPointers:")
    entries, i, _ = parse_pointer_table(lines, start, "FrameBlockPointers", "NUM_FRAMEBLOCKS")
    bodies = {}
    order = []
    cur = None
    for raw in lines[i:]:
        line = strip_comment(raw).strip()
        if not line or line.startswith("INCLUDE"):
            continue
        m = re.match(r"(\w+):$", line)
        if m:
            cur = m.group(1)
            if cur == "FrameBlockBaseCoords":  # INCLUDEd file parsed separately
                cur = None
                continue
            bodies[cur] = bytearray()
            order.append(cur)
            continue
        if cur is None:
            continue
        m = re.match(r"db\s+([$%]?[0-9A-Fa-f]+)$", line)
        if m:
            bodies[cur].append(parse_num(m.group(1)))
            continue
        m = re.match(r"dbsprite\s+(.+)$", line)
        if m:
            a = [x.strip() for x in m.group(1).split(",")]
            xt, yt, xp, yp = (parse_num(v) for v in a[:4])
            vt = parse_num(a[4])
            at = resolve_attr(a[5], oam_flags)
            bodies[cur] += bytes([(yt * 8 + yp) & 0xFF, (xt * 8 + xp) & 0xFF,
                                  vt & 0xFF, at & 0xFF])
            continue
        raise SystemExit(f"unexpected line in frame blocks: {line!r}")
    for lbl, body in bodies.items():
        n = body[0]
        # >= not ==: pret's FrameBlock62 declares 15 entries but carries 16 — the
        # 16th is dead ROM bytes DrawFrameBlock never reads. Emit them anyway for
        # byte fidelity.
        assert len(body) >= 1 + 4 * n, f"{lbl}: header count {n} vs {len(body)} bytes"
    return entries, order, bodies


def parse_base_coords(path):
    rows = []
    for raw in open(path, encoding="utf-8"):
        line = strip_comment(raw).strip()
        m = re.match(r"db\s+([$%]?[0-9A-Fa-f]+)\s*,\s*([$%]?[0-9A-Fa-f]+)$", line)
        if m:
            rows.append((parse_num(m.group(1)), parse_num(m.group(2))))
    return rows


def parse_move_sounds(path):
    rows = []
    for raw in open(path, encoding="utf-8"):
        stripped = strip_comment(raw).strip()
        m = re.match(r"db\s+(SFX_\w+)\s*,\s*([$%]?[0-9A-Fa-f]+)\s*,\s*([$%]?[0-9A-Fa-f]+)$",
                     stripped)
        if m:
            comment = raw.split(";", 1)[1].strip() if ";" in raw else ""
            rows.append((m.group(1), parse_num(m.group(2)), parse_num(m.group(3)), comment))
    return rows


def rom_offset(sym_line):
    bank_s, addr_s = sym_line.split(":")
    bank, addr = int(bank_s, 16), int(addr_s, 16)
    if addr < 0x4000:
        return addr
    return bank * 0x4000 + (addr - 0x4000)


def load_sym(path):
    syms = {}
    for raw in open(path, encoding="utf-8"):
        parts = raw.split(";", 1)[0].split()
        if len(parts) == 2 and ":" in parts[0]:
            syms.setdefault(parts[1], parts[0])
    return syms


def verify_against_rom(named_bodies, sound_rows, sound_addr_label):
    """Byte-compare encoded bodies with the golden ROM. Returns (checked, failed)."""
    rom_path = os.path.join(GOLDEN, "pokeyellow.gbc")
    sym_path = os.path.join(GOLDEN, "pokeyellow.sym")
    rom = open(rom_path, "rb").read()
    syms = load_sym(sym_path)
    checked = failed = 0
    for label, body in named_bodies:
        if label not in syms:
            print(f"  VERIFY SKIP {label}: not in pokeyellow.sym")
            continue
        off = rom_offset(syms[label])
        actual = rom[off:off + len(body)]
        checked += 1
        if actual != bytes(body):
            failed += 1
            for k, (a, b) in enumerate(zip(actual, bytes(body))):
                if a != b:
                    print(f"  VERIFY FAIL {label}+{k}: rom {a:#04x} != gen {b:#04x}")
                    break
    # MoveSoundTable: compare pitch/tempo columns only (col 0 is symbolic)
    if sound_addr_label in syms:
        off = rom_offset(syms[sound_addr_label])
        for r, (_, pitch, tempo, _) in enumerate(sound_rows):
            checked += 1
            if rom[off + 3 * r + 1] != pitch or rom[off + 3 * r + 2] != tempo:
                failed += 1
                print(f"  VERIFY FAIL MoveSoundTable row {r}: "
                      f"rom ({rom[off + 3 * r + 1]:#04x},{rom[off + 3 * r + 2]:#04x})"
                      f" != gen ({pitch:#04x},{tempo:#04x})")
    return checked, failed


def main():
    force_verify = "--verify" in sys.argv

    consts = ConstTable()
    consts.feed_file(os.path.join(REPO, "constants", "move_constants.asm"))
    consts.feed_file(os.path.join(REPO, "constants", "move_animation_constants.asm"))
    consts.feed_file(os.path.join(REPO, "constants", "battle_anim_constants.asm"))
    oam_flags = parse_oam_flags(os.path.join(REPO, "constants", "hardware.inc"))

    (anim_entries, anim_order, anim_bodies, anim_comments,
     anim_asserts) = parse_anim_streams(
        os.path.join(REPO, "data", "moves", "animations.asm"), consts)
    sub_entries, sub_order, sub_bodies = parse_subanims(
        os.path.join(REPO, "data", "battle_anims", "subanimations.asm"), consts)
    fb_entries, fb_order, fb_bodies = parse_frame_blocks(
        os.path.join(REPO, "data", "battle_anims", "frame_blocks.asm"), oam_flags)
    base_coords = parse_base_coords(
        os.path.join(REPO, "data", "battle_anims", "base_coords.asm"))
    sound_rows = parse_move_sounds(os.path.join(REPO, "data", "moves", "sfx.asm"))

    v = consts.values
    # --- self-checks -------------------------------------------------------
    assert len(anim_entries) == v["NUM_ATTACK_ANIMS"], (
        len(anim_entries), v["NUM_ATTACK_ANIMS"])
    assert anim_asserts.get("NUM_ATTACKS") == v["NUM_ATTACKS"], anim_asserts
    assert len(sub_entries) == v["NUM_SUBANIMS"], (len(sub_entries), v["NUM_SUBANIMS"])
    assert len(fb_entries) == v["NUM_FRAMEBLOCKS"], (len(fb_entries), v["NUM_FRAMEBLOCKS"])
    assert len(base_coords) == v["NUM_BASECOORDS"], (len(base_coords), v["NUM_BASECOORDS"])
    # NUM_ATTACKS asserted rows + one unlabeled trailing row pret keeps after the
    # assert_table_length marker (dead ROM bytes; kept for byte fidelity).
    assert len(sound_rows) == v["NUM_ATTACKS"] + 1, (len(sound_rows), v["NUM_ATTACKS"])
    for e in anim_entries:
        assert e in anim_bodies, f"AttackAnimationPointers row {e} has no body"
        assert anim_bodies[e] and anim_bodies[e][-1] == 0xFF, f"{e}: unterminated stream"
    for e in sub_entries:
        assert e in sub_bodies, f"SubanimationPointers row {e} has no body"
    for e in fb_entries:
        assert e in fb_bodies, f"FrameBlockPointers row {e} has no body"
    # every subanim's frame-block/base-coord ids are in range
    for lbl in sub_order:
        body = sub_bodies[lbl]
        for k in range(body[0] & 0x1F):
            fb, bc, mode = body[1 + 3 * k:4 + 3 * k]
            assert fb < v["NUM_FRAMEBLOCKS"], f"{lbl}: frame block {fb:#x} out of range"
            assert bc < v["NUM_BASECOORDS"], f"{lbl}: base coord {bc:#x} out of range"
            assert mode <= 4, f"{lbl}: frame block mode {mode}"

    # --- constants inc -----------------------------------------------------
    lines = [HEADER,
             "%ifndef BATTLE_ANIM_CONSTANTS_INC",
             "%define BATTLE_ANIM_CONSTANTS_INC",
             "",
             "; PlayAnimation command-space split (constants/move_animation_constants.asm)",
             f"FIRST_SE_ID             equ 0x{v['FIRST_SE_ID']:02X}"]
    lines.append("\n; special-effect command ids")
    for name, val in sorted(((n, x) for n, x in v.items() if n.startswith("SE_")),
                            key=lambda p: p[1]):
        lines.append(f"{name:<34} equ 0x{val:02X}")
    lines.append("\n; subanimation types (header byte bits 5-7)")
    for name, val in sorted(((n, x) for n, x in v.items() if n.startswith("SUBANIMTYPE_")),
                            key=lambda p: p[1]):
        lines.append(f"{name:<34} equ {val}")
    lines.append("\n; frame block modes (wFBMode)")
    for name, val in sorted(((n, x) for n, x in v.items() if n.startswith("FRAMEBLOCKMODE_")),
                            key=lambda p: p[1]):
        lines.append(f"{name:<34} equ {val}")
    lines.append("\n; wAnimationType values (constants/battle_anim_constants.asm)")
    for name, val in sorted(((n, x) for n, x in v.items() if n.startswith("ANIMATIONTYPE_")),
                            key=lambda p: p[1]):
        lines.append(f"{name:<45} equ {val}")
    lines.append("\n; anim-id tail: moves double as animation ids (constants/move_constants.asm)")
    tail_names = [n for n in v if n.endswith("_ANIM") or re.fullmatch(r"ANIM_[0-9A-F]{2}", n)]
    for name, val in sorted(((n, v[n]) for n in tail_names), key=lambda p: p[1]):
        lines.append(f"{name:<34} equ 0x{val:02X}")
    lines.append("\n; table sizes")
    for name in ("NUM_ATTACKS", "NUM_ATTACK_ANIMS", "NUM_SUBANIMS", "NUM_FRAMEBLOCKS",
                 "NUM_BASECOORDS"):
        lines.append(f"{name:<34} equ {v[name]}")
    lines += ["", "%endif ; BATTLE_ANIM_CONSTANTS_INC", ""]
    const_text = "\n".join(lines)

    # --- data inc ----------------------------------------------------------
    d = [HEADER,
         "; GB-space raw data: the battle-frame projection is applied by code at",
         "; publication (PublishProjectedOAM / BCOORD), never baked in here.",
         "",
         "; --- animation command streams (pret data/moves/animations.asm) ---",
         "; row i = animation id i+1 (PlayAnimation does `dec a` before indexing)",
         "AttackAnimationPointers:"]
    d += [f"    dd {e}" for e in anim_entries]
    d.append("")
    for labels in anim_order:
        body = anim_bodies[labels[0]]
        cmts = anim_comments[labels[0]]
        d += [f"{l}:" for l in labels]
        pos = 0
        for c in cmts:
            n = 1 if c == "end" else (2 if body[pos] >= v["FIRST_SE_ID"] else 3)
            chunk = ", ".join(f"0x{b:02X}" for b in body[pos:pos + n])
            d.append(f"    db {chunk:<18}; {c}")
            pos += n
        assert pos == len(body), f"{labels[0]}: comment walk {pos} != {len(body)}"
        d.append("")
    d += ["; --- subanimations (pret data/battle_anims/subanimations.asm) ---",
          "SubanimationPointers:"]
    d += [f"    dd {e}" for e in sub_entries]
    d.append("")
    for lbl in sub_order:
        body = sub_bodies[lbl]
        d.append(f"{lbl}:")
        d.append(f"    db 0x{body[0]:02X}                ; type {body[0] >> 5}, count {body[0] & 0x1F}")
        for k in range(body[0] & 0x1F):
            fb, bc, mode = body[1 + 3 * k:4 + 3 * k]
            d.append(f"    db 0x{fb:02X}, 0x{bc:02X}, 0x{mode:02X}    ; frame block, base coord, mode")
        d.append("")
    d += ["; --- frame blocks (pret data/battle_anims/frame_blocks.asm) ---",
          "; entry: db Y, X, tile-offset, attr  (GB OAM deltas; base tile added by DrawFrameBlock)",
          "FrameBlockPointers:"]
    d += [f"    dd {e}" for e in fb_entries]
    d.append("")
    for lbl in fb_order:
        body = fb_bodies[lbl]
        d.append(f"{lbl}:")
        d.append(f"    db {body[0]}")
        for k in range((len(body) - 1) // 4):
            y, x, t, a = body[1 + 4 * k:5 + 4 * k]
            dead = "    ; dead entry beyond header count (pret ROM bytes)" if k >= body[0] else ""
            d.append(f"    db 0x{y:02X}, 0x{x:02X}, 0x{t:02X}, 0x{a:02X}{dead}")
        d.append("")
    d += ["; --- frame block base coordinates (GB pixel pairs, Y then X) ---",
          "FrameBlockBaseCoords:"]
    for idx, (y, x) in enumerate(base_coords):
        d.append(f"    db 0x{y:02X}, 0x{x:02X}    ; BASECOORD_{idx:02X}")
    d += ["",
          "; --- move sound table (pret data/moves/sfx.asm): SFX id, pitch mod, tempo mod ---",
          "; SFX_* resolve against assets/audio_constants.inc (carrier must include it first)",
          "MoveSoundTable:"]
    for name, pitch, tempo, cmt in sound_rows:
        d.append(f"    db {name + ',':<26} 0x{pitch:02X}, 0x{tempo:02X}    ; {cmt}")
    d.append("")
    data_text = "\n".join(d)

    # --- ROM cross-check ---------------------------------------------------
    have_golden = (os.path.exists(os.path.join(GOLDEN, "pokeyellow.gbc"))
                   and os.path.exists(os.path.join(GOLDEN, "pokeyellow.sym")))
    if force_verify and not have_golden:
        raise SystemExit(f"--verify: golden worktree not found at {GOLDEN}")
    if have_golden:
        named = ([(l[0], anim_bodies[l[0]]) for l in anim_order]
                 + [(l, sub_bodies[l]) for l in sub_order]
                 + [(l, fb_bodies[l]) for l in fb_order]
                 + [("FrameBlockBaseCoords",
                     bytes(b for yx in base_coords for b in yx))])
        checked, failed = verify_against_rom(named, sound_rows, "MoveSoundTable")
        if failed:
            raise SystemExit(f"ROM cross-check FAILED: {failed}/{checked} bodies diverge")
        print(f"gen_battle_anim_data: ROM cross-check OK ({checked} bodies byte-identical)")
    else:
        print("gen_battle_anim_data: golden worktree absent — ROM cross-check skipped "
              "(self-checks only)")

    with open(OUT_CONST, "w", encoding="utf-8") as f:
        f.write(const_text)
    with open(OUT_DATA, "w", encoding="utf-8") as f:
        f.write(data_text)
    stream_bytes = sum(len(anim_bodies[l[0]]) for l in anim_order)
    print(f"gen_battle_anim_data: {len(anim_entries)} anim rows ({stream_bytes} stream bytes), "
          f"{len(sub_entries)} subanims, {len(fb_entries)} frame blocks, "
          f"{len(base_coords)} base coords, {len(sound_rows)} sound rows -> "
          f"{os.path.relpath(OUT_CONST, DOS_PORT)}, {os.path.relpath(OUT_DATA, DOS_PORT)}")


if __name__ == "__main__":
    main()
