#!/usr/bin/env python3
"""gen_debug_boot_names.py — generate dos_port/assets/debug_boot_names.inc.

pret's debug new-game names (data at DebugNewGamePlayerName / DebugNewGameRivalName,
constants/... "NINTEN@" / "SONY@"). PrepareTitleScreen and PrepareOakSpeech both copy
NAME_LENGTH (11) bytes starting at DebugNewGamePlayerName into W_PLAYER_NAME and again
from DebugNewGameRivalName into W_RIVAL_NAME. Because "NINTEN@" is only 7 bytes and
"SONY@" 5, the 11-byte player copy DELIBERATELY OVERRUNS into the rival string, so
wPlayerName holds "NINTEN@SONY" on hardware; the rival copy then overruns into a
6-byte '@' tail. The three labels must therefore stay CONTIGUOUS and at pret's exact
lengths — the golden caught the padded-to-11 version as wrong
(want 8d888d93848d50928e8d98 / got 8d888d93848d5050505050).

This emits that one contiguous block, charmap-encoded through gb_text (the '@'
terminators + tail inserted explicitly, 0x50). Exported under BOTH pret's
DebugNewGame* names and the port's Debug* aliases (title.asm / oak_speech.asm ref).

DO NOT EDIT the output by hand — re-run this generator.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gb_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "dos_port" / "assets" / "debug_boot_names.inc"

TERM = 0x50   # charmap "@"
PLAYER = "NINTEN"
RIVAL = "SONY"
TAIL = 6      # '@' bytes covering the rival copy's 11-byte overrun


def db(data: list) -> str:
    return "    db " + ", ".join(f"0x{x:02X}" for x in data)


def main() -> int:
    out = [
        "; debug_boot_names.inc — generated by tools/generators/gen_debug_boot_names.py.",
        "; DO NOT EDIT BY HAND.",
        "; pret debug new-game names. The three labels MUST stay contiguous: the",
        "; NAME_LENGTH(11) copies deliberately overrun (wPlayerName = \"NINTEN@SONY\").",
        "",
        "section .data",
        "",
        "global DebugNewGamePlayerName",
        "global DebugPlayerName",
        "DebugNewGamePlayerName:",
        "DebugPlayerName:",
        db(gb_text.encode(PLAYER) + [TERM]) + f'   ; "{PLAYER}@"',
        "global DebugNewGameRivalName",
        "global DebugRivalName",
        "DebugNewGameRivalName:",
        "DebugRivalName:",
        db(gb_text.encode(RIVAL) + [TERM]) + f'   ; "{RIVAL}@"',
        "global DebugNameTail",
        "DebugNameTail:",
        db([TERM] * TAIL) + "   ; covers the rival copy's 11-byte overrun",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} (player {PLAYER!r}, rival {RIVAL!r})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
