#!/usr/bin/env python3
"""gen_map_songs.py — generate dos_port/assets/map_songs.inc.

MapSongBanks: the per-map (music sound id, music ROM bank) table pret keeps in
data/maps/songs.asm, indexed by map id (wCurMap). LoadMapHeader loads the two
bytes into wMapMusicSoundID / wMapMusicROMBank; PlayDefaultMusic then plays that
song on map entry / connection crossing.

This is Tier-1 data (a deterministic function of the read-only pret source +
the generated MUSIC_* / MUSIC_*_BANK enums — zero hand-authored information), so
it is generated, never hand-written. Each pret row is `db MUSIC_X, BANK(Music_X)`;
the port has no ROM banks to BANK()-evaluate, so the bank is the generated
constant MUSIC_X_BANK (audio_constants.inc). The col-1 id and col-2 song name
correspond for every row (verified), so MUSIC_X_BANK is the faithful bank.

Consumed via %include by src/engine/overworld/overworld.asm (LoadMapHeader).
Run from repo root or dos_port/.
"""
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "data" / "maps" / "songs.asm"
OUT = ROOT / "dos_port" / "assets" / "map_songs.inc"

ROW = re.compile(r'^\s*db\s+(MUSIC_[A-Z0-9_]+)\s*,\s*BANK\(Music_\w+\)\s*(?:;\s*(.*))?$')


def main() -> int:
    rows = []
    for line in SRC.read_text().splitlines():
        m = ROW.match(line)
        if m:
            rows.append((m.group(1), (m.group(2) or "").strip()))
    if not rows:
        print(f"gen_map_songs: no rows parsed from {SRC}", file=sys.stderr)
        return 1

    out = [
        "; map_songs.inc — generated by tools/generators/gen_map_songs.py. DO NOT EDIT BY HAND.",
        "; MapSongBanks: per-map (music sound id, music ROM bank), indexed by map id.",
        "; pret: data/maps/songs.asm. Bank = MUSIC_*_BANK (flat model; see generator).",
        "",
        "MapSongBanks:",
    ]
    for music_id, comment in rows:
        tail = f"    ; {comment}" if comment else ""
        out.append(f"    db {music_id}, {music_id}_BANK{tail}")
    out.append("")
    out.append(f"MapSongBanks_END:   ; {len(rows)} maps (pret NUM_MAPS)")
    out.append("")

    OUT.write_text("\n".join(out))
    print(f"gen_map_songs: wrote {OUT} ({len(rows)} maps)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
