#!/usr/bin/env python3
"""gen_indigo_plateau_statues_text.py — generate dos_port/assets/indigo_plateau_statues_text.inc (Tier 1 data).

pret engine/events/hidden_events/indigo_plateau_statues.asm carries 3 text_far
wrapper labels (IndigoPlateauStatuesText1..3). Reuses gen_battle_text.py's
charmap/memmap/far-text machinery, same shape as gen_pikachu_text.py:

  * The 3 pure wrappers are flattened directly under their own name (the
    port's flat TX_FAR model — no indirection needed when nothing follows
    text_end).

Carrier: dos_port/src/engine/events/hidden_events/indigo_plateau_statues.asm (the
pret mirror path).

DO NOT EDIT the output by hand — re-run this generator. Run from repo root or
dos_port/.
"""
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "dos_port" / "assets" / "indigo_plateau_statues_text.inc"

STATUES_SRC = ["engine/events/hidden_events/indigo_plateau_statues.asm"]

WRAPPER_WANT = {
    "IndigoPlateauStatuesText1",
    "IndigoPlateauStatuesText2",
    "IndigoPlateauStatuesText3",
}


def existing_labels() -> set:
    """Labels already emitted elsewhere — never define one global twice."""
    out = set()
    assets = ROOT / "dos_port" / "assets"
    for inc in assets.glob("*.inc"):
        if inc.name == OUT.name:
            continue
        out |= set(re.findall(r"^global (\w+)$", inc.read_text(), re.M))
    return out


def main() -> int:
    charmap = gbt.load_charmap()
    memmap = gbt.load_memmap()
    far_db = gbt.collect_far(charmap, memmap)

    gbt.BATTLE_SRC = STATUES_SRC  # retarget the wrapper collector
    wrappers = gbt.collect_wrappers(charmap, memmap, far_db)

    missing_wrap = WRAPPER_WANT - set(wrappers)
    if missing_wrap:
        raise SystemExit(
            f"gen_indigo_plateau_statues_text: expected wrappers missing from scan: {sorted(missing_wrap)}"
        )

    skip = existing_labels()
    wrap_labels = sorted(WRAPPER_WANT - skip)
    if not wrap_labels:
        raise SystemExit("gen_indigo_plateau_statues_text: every wanted label is already emitted elsewhere")

    out = [
        "; indigo_plateau_statues_text.inc — generated by tools/generators/gen_indigo_plateau_statues_text.py.",
        "; DO NOT EDIT BY HAND.",
        "; Indigo Plateau statues message streams (pret",
        "; engine/events/hidden_events/indigo_plateau_statues.asm), text_far flattened.",
        "; section .data (see link.ld).",
        "",
        "section .data",
        "",
    ]
    for label in wrap_labels:
        b = wrappers[label]
        out.append(f"global {label}")
        out.append(f"{label}:")
        for i in range(0, len(b), 16):
            out.append("    db " + ", ".join(f"0x{x:02X}" for x in b[i:i + 16]))
        out.append(f"global {label}_ref")
        out.append(f"{label}_ref: dd {label}, {len(b)}   ; flat ptr + byte count")
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}: {len(wrap_labels)} wrapper(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
