#!/usr/bin/env python3
"""gen_effect_categories.py — generate dos_port/assets/effect_categories.inc.

Faithful translation of the move-effect category lists in data/battle/:
  ResidualEffects1        (residual_effects_1.asm)
  ResidualEffects2        (residual_effects_2.asm)
  SpecialEffects + SpecialEffectsCont (special_effects.asm; fallthrough, one term)
  AlwaysHappenSideEffects (always_happen_effects.asm)
  SetDamageEffects        (set_damage_effects.asm)

Each is a $FF-terminated byte list of move-effect ids (the second value of the
Moves table). Effect ids are resolved from constants/move_effect_constants.asm so
the lists stay in sync with the enum.

These are DATA ONLY (no MoveEffectPointerTable — its handler pointers would dangle
until the effect handlers are ported). The battle engine scans them linearly.

Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"

SOURCES = [
    "residual_effects_1.asm",
    "residual_effects_2.asm",
    "special_effects.asm",
    "always_happen_effects.asm",
    "set_damage_effects.asm",
]


def load_effect_constants(path: Path) -> dict:
    vals, val = {}, 0
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.split(";", 1)[0].strip()
        m = re.match(r'const_def\s*(-?\d+)?$', s)
        if m:
            val = int(m.group(1)) if m.group(1) else 0
            continue
        if s == "const_skip" or s.startswith("const_skip"):
            val += 1
            continue
        m = re.match(r'const\s+(\w+)', s)
        if m:
            vals[m.group(1)] = val
            val += 1
    return vals


def main() -> int:
    consts = load_effect_constants(ROOT / "constants/move_effect_constants.asm")

    out = [
        "; effect_categories.inc — generated by tools/generators/gen_effect_categories.py. DO NOT EDIT.",
        "; Move-effect category lists from data/battle/*.asm; $FF-terminated; DATA ONLY",
        "; (no MoveEffectPointerTable — handler pointers would dangle). Scanned linearly.",
    ]
    for fname in SOURCES:
        out.append("")
        for line in (ROOT / "data/battle" / fname).read_text(encoding="utf-8").splitlines():
            stripped = line.split(";", 1)[0].rstrip()
            s = stripped.strip()
            if not s:
                continue
            if s.endswith(":"):                     # label (e.g. SpecialEffectsCont:)
                out.append(s)
                continue
            m = re.match(r'db\s+(-?\w+)\s*$', s)
            if not m:
                continue
            tok = m.group(1)
            if tok in ("-1", "$ff", "$FF"):
                out.append("    db 0xFF    ; end")
            elif tok in consts:
                out.append(f"    db 0x{consts[tok]:02X}    ; {tok}")
            else:
                raise ValueError(f"unknown effect constant {tok!r} in {fname}")

    out.append("")
    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "effect_categories.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
