#!/usr/bin/env python3
"""gen_dakutens.py — generate dos_port/assets/dakutens.inc.

Tier-1 data for engine/menus/naming_screen.asm:DakutensAndHandakutens — the
kana -> voiced-kana (dakuten) and -> semi-voiced (handakuten) substitution
tables pret keeps in data/text/dakutens.asm.

Each table is a flat list of 2-byte pairs {plain, voiced} terminated by $FF,
searched by IsInArray with a stride of 2. The kana are charmap-encoded from
constants/charmap.asm, which carries the full kana set even in the English
build, so the bytes come out identical to pret's.

Carrier: dos_port/src/data/text/dakutens.asm (the pret path mirror).
Run from repo root or dos_port/.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_alphabets import load_charmap, encode, db_lines  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
DAKUTENS = ROOT / "data" / "text" / "dakutens.asm"

TERMINATOR = 0xFF  # pret: db -1


def load_table(label: str, cmap: dict) -> list:
    """Collect the `db "..", ".."` rows under `label:` in dakutens.asm, encode
    them, and append the $FF terminator pret writes as `db -1`."""
    blob = []
    collecting = False
    for line in DAKUTENS.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped == f"{label}:":
            collecting = True
            continue
        if not collecting:
            continue
        if stripped.startswith("db -1"):
            blob.append(TERMINATOR)
            break
        if stripped.startswith("db "):
            for m in re.finditer(r'"((?:[^"\\]|\\.)*)"', stripped):
                pair = encode(m.group(1), cmap)
                if len(pair) != 2:
                    raise SystemExit(
                        f"{label}: expected a 2-char pair, got {m.group(1)!r}")
                blob += pair
            continue
        if stripped.endswith(":") and blob:
            raise SystemExit(f"{label}: hit {stripped} before the -1 terminator")
    if not blob or blob[-1] != TERMINATOR:
        raise SystemExit(f"no terminated table collected for {label} in {DAKUTENS}")
    return blob


def main() -> int:
    cmap = load_charmap()
    dakutens = load_table("Dakutens", cmap)
    handakutens = load_table("Handakutens", cmap)

    out = [
        "; dakutens.inc — generated by tools/generators/gen_dakutens.py. DO NOT EDIT BY HAND.",
        "; Kana voicing substitution tables for the naming screen.",
        "; Source: data/text/dakutens.asm, constants/charmap.asm.",
        "; Layout: {plain, voiced} byte pairs, $FF-terminated (IsInArray stride 2).",
        "",
    ]
    out += db_lines("Dakutens", dakutens,
                    "kana -> dakuten (voiced) pairs, $FF end")
    out.append("")
    out += db_lines("Handakutens", handakutens,
                    "kana -> handakuten (semi-voiced) pairs, $FF end")
    out.append("")

    ASSETS.mkdir(parents=True, exist_ok=True)
    dst = ASSETS / "dakutens.inc"
    dst.write_text("\n".join(out))
    print(f"wrote {dst}: dakutens={len(dakutens)}B handakutens={len(handakutens)}B")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
