#!/usr/bin/env python3
"""gen_map_text.py — generate dos_port/assets/map_text/<map>.inc (Tier 1 data).

The 992 `_XxxText` far streams the translated map scripts reference: pret's
text/*.asm, GB-charmap encoded. By the two-tier rule these are DATA and belong to
a generator, never to hand-written `db 0x..` in a .asm.

ONE FILE PER MAP, INCLUDED BY THAT MAP'S OWN SCRIPT. Every one of the 992 labels
is referenced by exactly one port script (measured), and pret keeps a map's text
in text/<Map>.asm beside its scripts/<Map>.asm. So the stream is emitted next to
the only code that uses it, which mirrors pret, needs no `extern`, and makes a
duplicate definition impossible. A central text blob would have done none of that.

THE BYTES ARE READ OUT OF PRET, never transcribed — the parser is
gen_battle_text's, reused verbatim (same model as gen_trainer_text /
gen_item_text). A generator that CAN disagree with the disassembly it mirrors
will eventually do so silently, and a wrong glyph is invisible to every gate.

Labels whose body is not pure data (text_asm tails, vc_patch, …) are NOT emitted:
gen_battle_text.collect_far drops them, so they keep their `extern` and stay
visibly missing rather than being half-invented here.

Run from repo root or dos_port/.
"""
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
DOS = ROOT / "dos_port"
SCRIPTS = DOS / "src" / "scripts"
OUTDIR = DOS / "assets" / "map_text"

# pret keeps map text in text/*.asm; data/text/text_*.asm holds the shared
# engine streams a map stream may `text_far` into, so both are in scope.
gbt.TEXT_SRC = (sorted((ROOT / "text").glob("*.asm"))
                + sorted((ROOT / "data" / "text").glob("text_*.asm")))


def port_defined():
    """Every symbol already defined in the port, EXCLUDING what we generate here.

    Without this a label that some other file already defines would be emitted a
    second time and collide at link. Most far streams are `_Foo`, but pret does not
    use that prefix consistently -- MelanieText1, FanClubChairPrintText1 and 21
    others are plain names -- so the filter cannot be "starts with an underscore".
    """
    seen = set()
    for root in (DOS / "src", DOS / "assets"):
        for dp, _, fs in os.walk(root):
            if Path(dp) == OUTDIR:
                continue
            for f in fs:
                if not f.endswith((".asm", ".inc")):
                    continue
                txt = (Path(dp) / f).read_text(encoding="utf-8", errors="ignore")
                seen |= set(re.findall(r"^([A-Za-z_]\w*):", txt, re.M))
                seen |= set(re.findall(r"^global +([A-Za-z_]\w*)", txt, re.M))
    return seen


def wanted(defined, far):
    """port script stem -> [far labels it REFERENCES], in first-use order.

    Keyed on references, not on `extern` lines, so the generator is IDEMPOTENT: once
    a stream is emitted the script no longer externs it, and an extern-keyed scan
    would drop it on the next run and silently empty the .inc. Comment lines are
    stripped first so a label named in prose (or inside a BAIL banner, which quotes
    pret verbatim) is not mistaken for a use.
    """
    out = {}
    for p in sorted(SCRIPTS.glob("*.asm")):
        code = "\n".join(l.split(";", 1)[0] for l in p.read_text(encoding="utf-8").splitlines())
        seen, labels = set(), []
        for tok in re.findall(r"\b[A-Za-z_]\w*\b", code):
            if tok in far and tok not in defined and tok not in seen:
                seen.add(tok)
                labels.append(tok)
        if labels:
            out[p.stem] = labels
    return out


def main() -> int:
    far = gbt.collect_far(gbt.load_charmap(), gbt.load_memmap())
    OUTDIR.mkdir(parents=True, exist_ok=True)
    defined = port_defined()
    files = labels = skipped = 0
    missing = []
    for stem, want in sorted(wanted(defined, far).items()):
        have = [l for l in want if l in far]
        skipped += len(want) - len(have)
        missing += [l for l in want if l not in far]
        if not have:
            continue
        body = [
            "; %s.inc — generated by tools/generators/gen_map_text.py. DO NOT EDIT." % stem,
            "; Far text streams for this map, from pret text/. %%included by",
            "; src/scripts/%s.asm inside section .data." % stem,
            "",
        ]
        for label in have:
            data = far[label]
            rows = ["    db " + ", ".join("0x%02X" % b for b in data[k:k + 16])
                    for k in range(0, len(data), 16)]
            body.append("%s:\n%s" % (label, "\n".join(rows)))
            labels += 1
        (OUTDIR / ("%s.inc" % stem)).write_text("\n".join(body) + "\n", encoding="utf-8")
        files += 1
    print("gen_map_text.py: %d labels -> %d file(s) in %s"
          % (labels, files, OUTDIR.relative_to(ROOT)))
    if skipped:
        print("  %d label(s) not emitted (body is not pure data — they keep their extern)"
              % skipped)
        for m in missing[:8]:
            print("     ", m)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
