#!/usr/bin/env python3
"""gen_map_text.py — generate dos_port/assets/map_text/<map>.inc (Tier 1 data).

The 992 `_XxxText` far streams the translated map scripts reference: pret's
text/*.asm, GB-charmap encoded. By the two-tier rule these are DATA and belong to
a generator, never to hand-written `db 0x..` in a .asm.

ONE FILE PER MAP, INCLUDED BY THAT MAP'S OWN SCRIPT. Every one of the 992 labels
is referenced by exactly one port script (measured), and pret keeps a map's text
in text/<Map>.asm beside its scripts/<Map>.asm. So the stream is emitted next to
the only code that uses it, which mirrors pret, needs no `extern`, and makes a
duplicate definition impossible. A central text blob would have done none of that.

THE BYTES ARE READ OUT OF PRET, never transcribed — the parser is
gen_battle_text's, reused verbatim (same model as gen_trainer_text /
gen_item_text). A generator that CAN disagree with the disassembly it mirrors
will eventually do so silently, and a wrong glyph is invisible to every gate.

Labels whose body is not pure data (text_asm tails, vc_patch, …) are NOT emitted:
gen_battle_text.collect_far drops them, so they keep their `extern` and stay
visibly missing rather than being half-invented here.

Run from repo root or dos_port/.
"""
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_battle_text as gbt  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
DOS = ROOT / "dos_port"
SCRIPTS = DOS / "src" / "scripts"
OUTDIR = DOS / "assets" / "map_text"

# pret keeps map text in text/*.asm; data/text/text_*.asm holds the shared
# engine streams a map stream may `text_far` into, so both are in scope.
gbt.TEXT_SRC = (sorted((ROOT / "text").glob("*.asm"))
                + sorted((ROOT / "data" / "text").glob("text_*.asm")))


def wanted():
    """port script stem -> [labels it externs that start with '_'], in file order."""
    out = {}
    for p in sorted(SCRIPTS.glob("*.asm")):
        labels = re.findall(r"^extern +(_\w+)", p.read_text(encoding="utf-8"), re.M)
        if labels:
            out[p.stem] = labels
    return out


def main() -> int:
    far = gbt.collect_far(gbt.load_charmap(), gbt.load_memmap())
    OUTDIR.mkdir(parents=True, exist_ok=True)
    files = labels = skipped = 0
    missing = []
    for stem, want in sorted(wanted().items()):
        have = [l for l in want if l in far]
        skipped += len(want) - len(have)
        missing += [l for l in want if l not in far]
        if not have:
            continue
        body = [
            "; %s.inc — generated by tools/generators/gen_map_text.py. DO NOT EDIT." % stem,
            "; Far text streams for this map, from pret text/. %%included by",
            "; src/scripts/%s.asm inside section .data." % stem,
            "",
        ]
        for label in have:
            data = far[label]
            rows = ["    db " + ", ".join("0x%02X" % b for b in data[k:k + 16])
                    for k in range(0, len(data), 16)]
            body.append("%s:\n%s" % (label, "\n".join(rows)))
            labels += 1
        (OUTDIR / ("%s.inc" % stem)).write_text("\n".join(body) + "\n", encoding="utf-8")
        files += 1
    print("gen_map_text.py: %d labels -> %d file(s) in %s"
          % (labels, files, OUTDIR.relative_to(ROOT)))
    if skipped:
        print("  %d label(s) not emitted (body is not pure data — they keep their extern)"
              % skipped)
        for m in missing[:8]:
            print("     ", m)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
