#!/usr/bin/env python3
"""gen_map_scripts.py — generate dos_port/assets/map_scripts.inc from pret source.

Emits the per-map script dispatch table (script engine plan, Stage 5):

  MapScriptPointers:  NUM_MAPS flat (dd) pointers, indexed by wCurMap. RunMapScript
                      calls MapScriptPointers[wCurMap] every overworld frame. Maps
                      without a ported _Script default to DefaultMapScript (a no-op);
                      a small SCRIPT_OVERRIDES registry names the ported ones (the
                      same pattern as gen_npc_dialogs' SCRIPT_OVERRIDES and the flat
                      EvosMovesPointerTable / WildDataPointers tables).

Run from repo root (or dos_port/); paths resolve relative to the repo root.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
SCRIPTS_DIR = ROOT / "dos_port" / "src" / "scripts"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_map_script_tables as mst  # noqa: E402  (sibling generator)

# map const name -> ported _Script label override.
SCRIPT_OVERRIDES = {
    "PALLET_TOWN": "PalletTown_Script",
}
DRIVER_LABEL = "TrainerMapScript"


def parse_map_order():
    """Ordered list of map const names from constants/map_constants.asm (= wCurMap)."""
    maps = []
    for line in (ROOT / "constants/map_constants.asm").read_text().splitlines():
        m = re.match(r"\s*map_const\s+(\w+)\s*,", line)
        if m:
            maps.append(m.group(1))
    return maps


def discover_available_scripts():
    """Map cleaned script name -> exact global label name from dos_port/src/scripts/*.asm."""
    scripts = {}
    for asm_file in SCRIPTS_DIR.glob("*.asm"):
        for line in asm_file.read_text().splitlines():
            m = re.match(r"\s*global\s+([A-Za-z0-9_]+_Script)\b", line)
            if m:
                label = m.group(1)
                cleaned = label.replace("_", "").lower()
                scripts[cleaned] = label
    return scripts


def main():
    maps = parse_map_order()
    available_scripts = discover_available_scripts()
    wired_standard = dict.fromkeys(mst.WIRED_MAPS, DRIVER_LABEL)

    dispatch = {}
    notes = {}
    for name in maps:
        if name in wired_standard:
            dispatch[name] = DRIVER_LABEL
            notes[name] = "  ; driver + MapScriptParams row"
        elif name in SCRIPT_OVERRIDES:
            dispatch[name] = SCRIPT_OVERRIDES[name]
            notes[name] = "  ; hand-ported override"
        else:
            cleaned = name.replace("_", "").lower() + "script"
            if cleaned in available_scripts:
                dispatch[name] = available_scripts[cleaned]
                notes[name] = "  ; ported _Script"
            else:
                dispatch[name] = "DefaultMapScript"
                notes[name] = "  ; default fallback"

    # Collect all unique target labels to emit externs
    all_labels = sorted(set(dispatch.values()) | {"DefaultMapScript", DRIVER_LABEL})

    out = []
    out.append("; AUTO-GENERATED by tools/generators/gen_map_scripts.py — do not edit.")
    out.append("; Per-map script dispatch (script engine plan, Stage 5).")
    out.append(f"; MapScriptPointers: {len(maps)} flat (dd) pointers, indexed by wCurMap.")
    out.append("")
    out.append("; ── script entry points ──────────────────────────────────────────")
    for lbl in all_labels:
        out.append(f"extern {lbl}")
    out.append("")
    out.append("MapScriptPointers:")
    for i, name in enumerate(maps):
        label = dispatch[name]
        note = notes.get(name, "")
        out.append(f"    dd {label:<35} ; 0x{i:02X} {name}{note}")
    out.append("")

    dst = ASSETS / "map_scripts.inc"
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(out) + "\n")

    ported_count = sum(1 for l in dispatch.values() if l not in ("DefaultMapScript", DRIVER_LABEL))
    driver_count = sum(1 for l in dispatch.values() if l == DRIVER_LABEL)
    default_count = sum(1 for l in dispatch.values() if l == "DefaultMapScript")
    print(f"wrote {dst} (MapScriptPointers {len(maps)} entries: "
          f"{ported_count} ported _Script(s), "
          f"{driver_count} driver-wired, "
          f"{default_count} DefaultMapScript)")


if __name__ == "__main__":
    main()
