#!/usr/bin/env python3
"""Generate dos_port/assets/ledge_shadow.inc — the ledge-hop shadow sprite.

Faithful to pret engine/overworld/ledges.asm:

    LedgeHoppingShadow:
        INCBIN "gfx/overworld/shadow.1bpp"
    LedgeHoppingShadowEnd:

    LedgeHoppingShadowOAM:
        dbsprite  9, 11,  0,  0, $ff, 0
        dbsprite 10, 11,  0,  0, $ff, OAM_XFLIP
    LedgeHoppingShadowOAMEnd:

`dbsprite x, y, xpix, ypix, tile, attrs` (pret macros/gfx.asm) expands to
    db (y * TILE_WIDTH) % $100 + ypix, (x * TILE_WIDTH) % $100 + xpix, tile, attrs
i.e. the standard OAM byte convention (screen row + 16 / column + 8 already folded
into the tile coordinates the macro is given).  Both entries name vChars1 tile $ff,
the slot LoadHoppingShadowOAM expands shadow.1bpp into.

This is Tier-1 machine output: a deterministic passthrough of pret's .1bpp blob
plus the two OAM records derived from pret's own dbsprite arguments.  It holds no
hand-authored information, so rerunning is idempotent.

Run from the repo root:
  python3 dos_port/tools/generators/gen_ledge_shadow.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "gfx" / "overworld" / "shadow.1bpp"
DST = ROOT / "dos_port" / "assets" / "ledge_shadow.inc"

TILE_1BPP = 8       # bytes per 1bpp 8x8 tile
TILE_WIDTH = 8      # px
OAM_XFLIP = 0x20    # constants/hardware.inc

# pret's dbsprite arguments, verbatim: (x tile, y tile, x pixel, y pixel, tile, attrs)
SPRITES = [
    (9,  11, 0, 0, 0xFF, 0),
    (10, 11, 0, 0, 0xFF, OAM_XFLIP),
]


def dbsprite(x, y, xpix, ypix, tile, attrs):
    return [(y * TILE_WIDTH) % 0x100 + ypix,
            (x * TILE_WIDTH) % 0x100 + xpix,
            tile, attrs]


def main():
    data = SRC.read_bytes()
    if len(data) % TILE_1BPP:
        raise SystemExit(f"{SRC}: {len(data)} bytes is not a whole number of 1bpp tiles")
    ntiles = len(data) // TILE_1BPP

    out = []
    out.append("; ledge_shadow.inc — generated by dos_port/tools/generators/gen_ledge_shadow.py.")
    out.append("; DO NOT EDIT BY HAND.  Ledge-hop shadow sprite: pret gfx/overworld/shadow.1bpp")
    out.append("; and the two dbsprite OAM records from engine/overworld/ledges.asm.")
    out.append(f"LEDGE_SHADOW_TILES     equ {ntiles}")
    out.append("")
    out.append("LedgeHoppingShadow:")
    for t in range(ntiles):
        row = data[t * TILE_1BPP:(t + 1) * TILE_1BPP]
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in row))
    out.append("LedgeHoppingShadowEnd:")
    out.append("")
    out.append("LedgeHoppingShadowOAM:")
    for s in SPRITES:
        rec = dbsprite(*s)
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in rec)
                   + f"    ; dbsprite {s[0]}, {s[1]}, {s[2]}, {s[3]}, ${s[4]:02x}, {s[5]:#04x}")
    out.append("LedgeHoppingShadowOAMEnd:")
    out.append("")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out) + "\n")
    print(f"wrote {DST}: {ntiles} 1bpp tile(s), {len(SPRITES)} OAM records")


if __name__ == "__main__":
    main()
