#!/usr/bin/env python3
"""Generate dos_port/assets/badge_tiles.inc — the gym-leader face + badge tiles
for the player status (trainer card) screen, from pret's already-2bpp graphics.

Faithful to pret engine/menus/draw_badges.asm:
  GymLeaderFaceAndBadgeTileGraphics: INCBIN "gfx/trainer_card/badges.2bpp"
The blob is a flat run of 8x8 2bpp tiles. Each of the NUM_BADGES (8) gym leaders
contributes a 2x2 face followed by a 2x2 badge (8 tiles per leader), so the sheet
is 8 leaders * 8 tiles = 64 tiles. DrawBadges indexes them by the VRAM tile ids in
.FaceBadgeTiles (face $20,$28,..$58; "+4" reaches the owned-badge graphic), i.e. a
contiguous 64-tile block starting at tile $20 in whatever vChars slot the loader
picks. This generator only carries the pixels; the id math stays in draw_badges.asm.

This is Tier-1 machine output: a deterministic passthrough of the pret .2bpp, no
hand-authored information. Rerunning is idempotent.

Output (NASM, .data):
  GymLeaderFaceAndBadgeTileGraphics:   64 tiles * 16 bytes, in sheet order.
      (pret's own label for this INCBIN — the port keeps it, per the
      preserve-pret-labels rule; it used to be emitted as `badge_face_tiles`,
      a port invention, which is why translation.db read the pret label as
      `missing`.)
  BADGE_TILE_BYTES  equ 16          ; bytes per 2bpp 8x8 tile
  BADGE_FACE_TILE_COUNT equ 64      ; total tiles in the sheet

Requires nothing beyond the stdlib. Run from the repo root:
  python3 dos_port/tools/generators/gen_badge_tiles.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "gfx" / "trainer_card" / "badges.2bpp"
DST = ROOT / "dos_port" / "assets" / "badge_tiles.inc"

TILE = 16  # bytes per 2bpp 8x8 tile


def num_badges() -> int:
    """NUM_BADGES from constants/ram_constants.asm (const enum position)."""
    val = 0
    for line in (ROOT / "constants" / "ram_constants.asm").read_text().splitlines():
        s = line.split(";", 1)[0].strip()
        if re.match(r"const_def", s):
            val = 0
            continue
        if re.match(r"const\s+\w+$", s):
            if s.split()[1] == "NUM_BADGES" or "NUM_BADGES EQU const_value" in s:
                break
            val += 1
        m = re.match(r"DEF\s+NUM_BADGES\s+EQU\s+const_value", s)
        if m:
            break
    return val


def main():
    data = SRC.read_bytes()
    if len(data) % TILE:
        raise SystemExit(f"{SRC}: {len(data)} bytes is not a whole number of tiles")
    count = len(data) // TILE

    # Sanity: pret lays out face+badge (8 tiles) per gym leader.
    nb = num_badges()
    if nb and count != nb * 8:
        raise SystemExit(f"{SRC}: expected {nb*8} tiles (NUM_BADGES={nb} * 8), got {count}")

    out = []
    out.append("; badge_tiles.inc — generated by dos_port/tools/generators/gen_badge_tiles.py.")
    out.append("; DO NOT EDIT BY HAND.  Gym-leader face + badge tiles (2bpp) for the")
    out.append("; trainer-card status screen (pret gfx/trainer_card/badges.2bpp).")
    out.append(f"BADGE_TILE_BYTES      equ {TILE}")
    out.append(f"BADGE_FACE_TILE_COUNT equ {count}")
    out.append("")
    out.append("; pret ref: engine/menus/draw_badges.asm:GymLeaderFaceAndBadgeTileGraphics")
    out.append(';   INCBIN "gfx/trainer_card/badges.2bpp"')
    out.append("GymLeaderFaceAndBadgeTileGraphics:")
    for t in range(count):
        row = data[t * TILE:(t + 1) * TILE]
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in row))
    out.append("")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out) + "\n")
    print(f"wrote {DST}: {count} tiles ({len(data)} bytes)")


if __name__ == "__main__":
    main()
