#!/usr/bin/env python3
"""Generate dos_port/assets/trade_tiles.inc — the trade-animation tile graphics
(link cable, Game Boy pics, cable ball) that pret's LoadTradingGFXAndMonNames
loads into VRAM, from pret's already-2bpp graphics.

Pattern: tools/generators/gen_trainer_card_tiles.py — deterministic passthrough
of pret .2bpp, no hand-authored information; rerunning is idempotent.

Faithful to pret gfx/trade.asm:

    TradingAnimationGraphics:
    INCBIN "gfx/trade/game_boy.2bpp"
    INCBIN "gfx/trade/link_cable.2bpp"
    TradingAnimationGraphicsEnd:

    TradingAnimationGraphics2: INCBIN "gfx/trade/cable_ball.2bpp"
    TradingAnimationGraphics2End:

engine/movie/trade.asm's LoadTradingGFXAndMonNames copies both incbins of
TradingAnimationGraphics in ONE FarCopyData call (`ld bc,
TradingAnimationGraphicsEnd - TradingAnimationGraphics`), so game_boy.2bpp and
link_cable.2bpp must land CONTIGUOUSLY here exactly as pret's gfx/trade.asm lays
them — this file concatenates them into one `TradingAnimationGraphics` blob and
exports the combined tile count as an equate, so the port's translated
LoadTradingGFXAndMonNames reproduces pret's single copy instead of inventing two.
TradingAnimationGraphics2 (cable_ball.2bpp) is the separate second blob pret
loads with its own FarCopyData call.

NOTE: gfx/trade/game_boy.2bpp is built with `--remove-duplicates`
(root Makefile: `gfx/trade/game_boy.2bpp: tools/gfx += --remove-duplicates`), so
its tile count is LESS than (width/8)*(height/8) of game_boy.png — the
accompanying game_boy.tilemap (already ported verbatim as GameBoyTiles in
dos_port/src/data/tilemaps.asm) maps grid cells to the deduped tile indices.
This generator does not touch that tilemap; it only emits the raw 2bpp tile
bytes CopyVideoData loads into vChars2/vSprites.

Run from the repo root or dos_port/:
  python3 dos_port/tools/generators/gen_trade_tiles.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
TRADE_GFX = ROOT / "gfx" / "trade"
DST = ROOT / "dos_port" / "assets" / "trade_tiles.inc"

TILE = 16  # bytes per 2bpp 8x8 tile


def read_tiles(path: Path) -> bytes:
    data = path.read_bytes()
    if len(data) % TILE:
        raise SystemExit(f"{path}: {len(data)} bytes is not a whole number of tiles")
    return data


def emit(out, label, data):
    out.append(f"{label}:")
    for t in range(len(data) // TILE):
        row = data[t * TILE:(t + 1) * TILE]
        out.append("    db " + ", ".join(f"0x{b:02X}" for b in row))
    out.append("")


def main() -> int:
    game_boy = read_tiles(TRADE_GFX / "game_boy.2bpp")
    link_cable = read_tiles(TRADE_GFX / "link_cable.2bpp")
    cable_ball = read_tiles(TRADE_GFX / "cable_ball.2bpp")

    combined = game_boy + link_cable
    combined_count = len(combined) // TILE
    ball_count = len(cable_ball) // TILE

    out = []
    out.append("; trade_tiles.inc — generated by tools/generators/gen_trade_tiles.py.")
    out.append("; DO NOT EDIT BY HAND. Trade-animation tile graphics (2bpp), passed through")
    out.append("; from pret gfx/trade/{game_boy,link_cable,cable_ball}.2bpp.")
    out.append("; Carrier: dos_port/src/engine/movie/trade.asm (%includes this, section .data).")
    out.append(f"TRADE_TILE_BYTES              equ {TILE}")
    out.append(f"TRADING_ANIM_GFX_TILE_COUNT   equ {combined_count}   ; game_boy.2bpp + link_cable.2bpp, contiguous")
    out.append(f"TRADING_ANIM_GFX2_TILE_COUNT  equ {ball_count}   ; cable_ball.2bpp")
    out.append("")
    out.append("global TradingAnimationGraphics")
    out.append("global TradingAnimationGraphics2")
    out.append("; TradingAnimationGraphics = game_boy.2bpp + link_cable.2bpp, CONTIGUOUS —")
    out.append("; pret's gfx/trade.asm lays them adjacent and LoadTradingGFXAndMonNames copies")
    out.append("; both in one FarCopyData call. Do not insert anything between them.")
    emit(out, "TradingAnimationGraphics", combined)
    out.append("; TradingAnimationGraphics2 = cable_ball.2bpp, pret's separate second blob.")
    emit(out, "TradingAnimationGraphics2", cable_ball)

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out) + "\n")
    print(f"wrote {DST}: TradingAnimationGraphics={combined_count} tiles "
          f"(game_boy={len(game_boy)//TILE}+link_cable={len(link_cable)//TILE}), "
          f"TradingAnimationGraphics2={ball_count} tiles")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
