#!/usr/bin/env python3
"""Generate dos_port/assets/pokedex_tiles.inc — the pokédex interface tiles.

Faithful to pret engine/gfx/load_pokedex_tiles.asm:LoadPokedexTilePatterns:
  PokedexTileGraphics ($12 = 18 tiles, gfx/pokedex/pokedex.2bpp)
      -> vChars2 tile $60   (the dex frame/line tiles + the ' " height glyphs)

PokeballTileGraphics is NOT emitted here any more: it is a pret label from
engine/battle/draw_hud_pokeball_gfx.asm, so the mirror rule puts it in
dos_port/src/engine/battle/draw_hud_pokeball_gfx.asm (the full 4-tile incbin,
as pret has it); load_pokedex_tiles.asm externs it and still copies 1 tile.

Tier-1 machine output: a deterministic passthrough of the rgbgfx-rendered
.2bpp build artifacts (rendered by the root `make`; the PNGs are the committed
sources). Same pattern as gen_emotes.py / gen_badge_tiles.py.

Run from anywhere: python3 dos_port/tools/generators/gen_pokedex_tiles.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent.parent
DEX_2BPP = ROOT / "gfx" / "pokedex" / "pokedex.2bpp"
BALLS_2BPP = ROOT / "gfx" / "battle" / "balls.2bpp"
DST = ROOT / "dos_port" / "assets" / "pokedex_tiles.inc"

TILE_SIZE = 16
DEX_TILES = 18          # (PokedexTileGraphicsEnd - PokedexTileGraphics) / 16


def db_lines(data: bytes) -> list[str]:
    return ["    db " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
            for i in range(0, len(data), 16)]


def main() -> None:
    dex = DEX_2BPP.read_bytes()
    if len(dex) != DEX_TILES * TILE_SIZE:
        raise SystemExit(f"{DEX_2BPP}: expected {DEX_TILES * TILE_SIZE} bytes "
                         f"({DEX_TILES} tiles), got {len(dex)} — rerun the root make")
    out = [
        "; pokedex_tiles.inc — generated by dos_port/tools/generators/gen_pokedex_tiles.py.",
        "; DO NOT EDIT BY HAND.",
        "; PokedexTileGraphics: 18 tiles (gfx/pokedex/pokedex.2bpp) -> vChars2 $60.",
        "; pret ref: engine/gfx/load_pokedex_tiles.asm:LoadPokedexTilePatterns.",
        "; (PokeballTileGraphics lives in src/engine/battle/draw_hud_pokeball_gfx.asm,",
        ";  its pret mirror; the pokedex externs it and copies tile 0.)",
        "",
        "PokedexTileGraphics:",
        *db_lines(dex),
        "PokedexTileGraphicsEnd:",
        "POKEDEX_TILE_GFX_SIZE equ PokedexTileGraphicsEnd - PokedexTileGraphics",
        "",
        "POKEBALL_TILE_SIZE equ 16",
        "",
    ]
    DST.write_text("\n".join(out) + "\n")
    print(f"wrote {DST} ({len(dex)} bytes)")


if __name__ == "__main__":
    main()
