#!/usr/bin/env python3
"""stage0.py — parse & probe pret's `scripts/`, and report the work queue.

Stage 0 of docs/current_plan_script_transpiler.md. It emits no x86 and builds no
IR. It parses all 251 files and reports what would have to be decided before any
of them could be lowered.

ACCEPTANCE (both must hold, and the exit code is the gate):
  * zero parse errors across all 251 files — a parse failure is a tool bug, not
    a bail, so this exits non-zero on the first one;
  * a reason-code histogram with a named site behind every bucket.

Outputs (all under dos_port/tools/sm83xlat/):
    coverage.md          the human report — the work queue and the go/no-go
    tables/probe.json    the same data, machine-readable
    tables/callees.json  distinct call targets, site counts, port-defined flag

Usage:
    python3 dos_port/tools/sm83xlat/stage0.py
    python3 dos_port/tools/sm83xlat/stage0.py --report      # print, write nothing
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import lexer      # noqa: E402
import probe      # noqa: E402


def _pct(n: int, d: int) -> str:
    return f"{100.0 * n / d:.1f}%" if d else "n/a"


def build_report(res: probe.ProbeResult, root: Path) -> str:
    L = []
    a = L.append
    total = res.imperative

    a("# sm83xlat Stage 0 — parse & probe\n")
    a("Generated by `dos_port/tools/sm83xlat/stage0.py`. Every number here is a\n"
      "measurement over pret's `scripts/*.asm` at the SHA recorded below; re-run\n"
      "the tool rather than quoting this file as an invariant.\n")
    a(f"- pret root: `{root}`")
    a(f"- files parsed: **{res.files}** / 251")
    a(f"- physical lines: **{res.total_lines}**")
    a("- parse errors: **0** (Stage 0 acceptance — a parse failure is a tool bug,\n"
      "  never a bail, so this run would have exited non-zero instead)\n")

    a("## What the corpus is made of\n")
    a("The headline 'imperative lines' figure depends entirely on where the line\n"
      "is drawn between code and data, so the decomposition is given rather than\n"
      "a bare total.\n")
    a("| category | lines |")
    a("|---|---|")
    a(f"| SM83 instructions | {res.insn_lines} |")
    a(f"| code-emitting macros (event / predef / farcall / coord / lb) | {res.code_macro_lines} |")
    a(f"| **imperative total (the two above)** | **{res.imperative}** |")
    a(f"| data macros (text stream, tables, db/dw) | {res.data_lines} |")
    a(f"| assembler control (EXPORT / ASSERT / vc_patch / IF...) | {res.control_lines} |")
    a(f"| items inside a false `IF DEF(...)` branch, parsed but dead | {res.inactive_items} |")
    a("")
    a(f"`text_asm` bodies (the data→code seam): **{res.text_asm_bodies}**\n")
    if res.includes:
        a("`INCLUDE` directives — these pull in code that is NOT this tool's output:\n")
        for inc in sorted(set(res.includes)):
            a(f"- `{inc}` (engine/ code; already ported, not re-emitted here)")
        a("")

    a("## Reason-code histogram — THE WORK QUEUE\n")
    a("One bucket per imperative site, assigned by a fixed priority so the\n"
      "histogram sums to the site count. `ok` means the form is in the ISA/macro\n"
      "table, every symbol resolves, and the lowering is fixed by the register\n"
      "map alone. It does **not** mean 'already correct' — flag exactness is a\n"
      "dataflow property and is Stage 2's gate, reported below as a census.\n")
    a("| reason | sites | share | distinct |")
    a("|---|---:|---:|---:|")
    for reason, n in res.histogram.most_common():
        distinct = ""
        if reason == probe.R_UNKNOWN_CALLEE:
            distinct = str(len(res.callees))
        elif reason == probe.R_UNRESOLVED_SYM:
            distinct = str(len(res.unresolved_symbols))
        a(f"| `{reason}` | {n} | {_pct(n, total)} | {distinct} |")
    a(f"| **total** | **{total}** | | |")
    a("")

    ok = res.histogram.get(probe.OK, 0)
    a(f"**Mechanically lowerable today: {ok} / {total} ({_pct(ok, total)}).**\n")

    a("## `unknown-callee-abi` — the largest bucket, as predicted\n")
    a("The plan budgets this rather than discovering it at Stage 5, and the number\n"
      "that matters is not the site count but the **distinct callee count**: that\n"
      "is the size of `abi.json`. `abi.json` is fail-closed and currently empty by\n"
      "construction, so every external transfer is an open question — this bucket\n"
      "shrinks as the table is populated, and the shrink rate is the tool's\n"
      "progress metric through Stages 1–3.\n")
    defined = sum(1 for t in res.callees if res.callee_defined.get(t))
    a(f"- distinct callees: **{len(res.callees)}**")
    a(f"- of those, already defined somewhere under `dos_port/src`: **{defined}** "
      f"({_pct(defined, len(res.callees))})")
    a(f"- not yet defined in the port: **{len(res.callees) - defined}**\n")
    a("Top 25 by call-site count (`defined` = the port already has a symbol of\n"
      "that name; it does **not** mean the contract has been checked):\n")
    a("| callee | sites | defined in port |")
    a("|---|---:|---|")
    for name, n in res.callees.most_common(25):
        a(f"| `{name}` | {n} | {'yes' if res.callee_defined.get(name) else 'no'} |")
    a("")

    a("## Branch census — Stage 2's acceptance gate\n")
    a("Every conditional branch, bucketed by how far back the instruction that\n"
      "wrote the flag it reads is. Measured here with a purely local backward\n"
      f"walk over at most {probe.CENSUS_WINDOW} items, with no CFG and no join\n"
      "points — deliberately, so that the dataflow engine Stage 2 builds is an\n"
      "**independent** measurement of the same quantity. Two measurements sharing\n"
      "machinery would agree for reasons unrelated to either being right.\n")
    tot_br = sum(v for k, v in res.branch_census.items() if not k.startswith("("))
    a("| bucket | branches | share | meaning |")
    a("|---|---:|---:|---|")
    meanings = {
        "adjacent": "the immediately preceding instruction writes the flag",
        "separated": "a writer is in range, only flag-transparent items between",
        "callee-flag-contract": "the nearest candidate is a CALL — the flag comes "
                                "from a callee's contract, so this is the abi.json "
                                "question wearing a different hat",
        "cross-block": "no straight-line predecessor (an unconditional transfer "
                       "intervenes, or the window ran out)",
        "unmodelled-producer": "the walk hit an item whose flag effect is not "
                               "modelled — should be zero",
    }
    for key in ("adjacent", "separated", "callee-flag-contract", "cross-block",
                "unmodelled-producer"):
        n = res.branch_census.get(key, 0)
        a(f"| {key} | {n} | {_pct(n, tot_br)} | {meanings[key]} |")
    a(f"| **total** | **{tot_br}** | | |")
    a("")
    inter = res.branch_census.get("(of those, a label intervenes)", 0)
    a(f"Of the {res.branch_census.get('adjacent', 0) + res.branch_census.get('separated', 0)} "
      f"branches with a producer in range, **{inter}** have a label between the\n"
      "producer and the branch — i.e. another path can enter in between, so the\n"
      "producer is not guaranteed to be the one that ran. Those are genuine CFG\n"
      "questions rather than straight-line ones, and the local walk cannot settle\n"
      "them; they are listed in `tables/probe.json`.\n")

    a("### The plan's quoted proportions do NOT reproduce — read this before "
      "using them as Stage 2's gate\n")
    a("The plan states Stage 2's acceptance as reproducing **48.4 / 20.5 / 31.1**\n"
      "over 920 branches. Decomposed against this run:\n")
    a(f"- **The branch COUNT reproduces exactly.** 920 = {tot_br} active + 7 that\n"
      "  sit inside `IF DEF(_DEBUG)` blocks (one `ret nz` per debug hook, in 7\n"
      "  files) and are therefore not in the build. Nothing is missing.")
    a("- **The proportions do not.** Under the definitions above this run reads\n"
      f"  {_pct(res.branch_census.get('adjacent', 0), tot_br)} / "
      f"{_pct(res.branch_census.get('separated', 0), tot_br)} / "
      f"{_pct(res.branch_census.get('cross-block', 0), tot_br)}, with a fourth\n"
      "  bucket (`callee-flag-contract`) the quoted figures have no slot for.")
    crude_tot = sum(res.branch_census_crude.values())
    a("- A deliberately CRUDER re-bucketing — only a bare SM83 instruction counts\n"
      "  as a producer, macros and calls skipped as if transparent, no\n"
      "  unconditional-transfer stop — lands at "
      f"{_pct(res.branch_census_crude.get('adjacent', 0), crude_tot)} / "
      f"{_pct(res.branch_census_crude.get('separated', 0), crude_tot)} / "
      f"{_pct(res.branch_census_crude.get('cross-block', 0), crude_tot)}. That is\n"
      "  the same family as the quoted figures and matches on `adjacent`, so the\n"
      "  original measurement was probably of this shape — but it is **not**\n"
      "  reproduced, and this is not a claim that it has been identified.\n")
    a("**Consequence for the plan:** the quoted proportions cannot serve as Stage\n"
      "2's acceptance gate, because the definition behind them was never recorded\n"
      "and a gate against an unreproducible number gates nothing. The gate should\n"
      "be restated as: the Stage 2 dataflow engine reproduces the census in the\n"
      "table above, whose definitions are written down, on a corpus whose branch\n"
      "count is independently confirmed at 913 active / 920 total.\n")
    a("The definitional gap is itself the finding. `call` is the crux: treating it\n"
      "as flag-transparent lets a walk read straight through `call GiveItem` and\n"
      "credit some earlier `cp` with the CF that `jr nc` actually takes from the\n"
      f"callee. {res.branch_census.get('callee-flag-contract', 0)} branches read a\n"
      "flag that way, and each one is an `abi.json` row, not a distance.\n")

    a("## Pointer domain — the first of the two hazards with no textual tell\n")
    a("`ld hl, wCurrentMapScriptFlags` puts a **GB** address in ESI, dereferenced\n"
      "`[ebp+esi]`. `ld hl, .Text` puts a **HOST** address in ESI, dereferenced\n"
      "`[esi]`. The two lines are textually identical in shape, so a reviewer\n"
      "diffing pret against output sees nothing wrong either way — which is why\n"
      "the classification is reported per site rather than asserted as clean.\n")
    pd_total = sum(res.pointer_domain.values())
    a("| domain at the `ld r16, imm` site | sites |")
    a("|---|---:|")
    for k, n in res.pointer_domain.most_common():
        a(f"| {k} | {n} |")
    a(f"| **total** | **{pd_total}** |")
    a("")
    amb = res.pointer_domain.get("AMBIGUOUS (name is in both namespaces)", 0)
    unk = res.pointer_domain.get("UNKNOWN", 0)
    a(f"**{amb} ambiguous, {unk} unknown.** Every other site is decided by which\n"
      "namespace the name lives in, which is a name-level fact and does not need\n"
      "dataflow. What still does need it: the domain of a pointer that has been\n"
      "*moved* (`ld d, h` / `ld e, l`) or arrived in a register from a callee.\n"
      "Those are Stage 2 propagation, not Stage 0 classification, and this table\n"
      "says nothing about them.\n")

    a("## Data-side classification\n")
    a("| class | lines |")
    a("|---|---:|")
    for k, n in res.data_histogram.most_common():
        a(f"| `{k}` | {n} |")
    a("")
    if res.inline_text_sites:
        a(f"**`inline-text-db`: {len(res.inline_text_sites)} sites.** These are pret\n"
          "violating its own text/-vs-scripts/ split — glyph bytes inside a script.\n"
          "They must be routed into a generator, never emitted as `db` bytes: a\n"
          "transpiler is a very efficient way to commit the port's most-repeated\n"
          "Tier-1 violation several hundred times in one commit.\n")
        for s in res.inline_text_sites:
            a(f"- `{s.where}` — `{s.text}`")
        a("")

    a("## Bail sites by file (top 20)\n")
    a("| file | imperative | ok | bails |")
    a("|---|---:|---:|---:|")
    rows = []
    for path, ctr in res.per_file.items():
        tot = sum(ctr.values())
        rows.append((tot - ctr.get(probe.OK, 0), path, tot, ctr.get(probe.OK, 0)))
    for bails, path, tot, okn in sorted(rows, reverse=True)[:20]:
        a(f"| `{path}` | {tot} | {okn} | {bails} |")
    a("")

    return "\n".join(L) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--report", action="store_true",
                    help="print the report, write nothing")
    ap.add_argument("--root", type=Path, default=HERE.parents[2],
                    help="pret repository root (default: the port's parent tree)")
    args = ap.parse_args(argv)

    root = args.root.resolve()
    port = root / "dos_port"

    try:
        res = probe.probe(root, port)
    except lexer.LexError as exc:
        # Stage 0 acceptance is zero parse errors. This is the gate.
        print(f"PARSE ERROR (tool bug, not a bail): {exc}", file=sys.stderr)
        return 2

    report = build_report(res, root)
    if args.report:
        print(report)
        return 0

    (HERE / "coverage.md").write_text(report)
    tables = HERE / "tables"
    tables.mkdir(exist_ok=True)
    (tables / "probe.json").write_text(json.dumps({
        "_comment": "sm83xlat Stage 0 probe. Regenerate with stage0.py.",
        "files": res.files,
        "total_lines": res.total_lines,
        "imperative": res.imperative,
        "insn_lines": res.insn_lines,
        "code_macro_lines": res.code_macro_lines,
        "data_lines": res.data_lines,
        "control_lines": res.control_lines,
        "inactive_items": res.inactive_items,
        "text_asm_bodies": res.text_asm_bodies,
        "histogram": dict(res.histogram),
        "branch_census": dict(res.branch_census),
        "branch_census_crude": dict(res.branch_census_crude),
        "branch_detail": res.branch_detail,
        "data_histogram": dict(res.data_histogram),
        "mnemonics": dict(res.mnemonics),
        "macro_uses": dict(res.macro_uses),
        "unresolved_symbols": dict(res.unresolved_symbols),
        "pointer_domain": dict(res.pointer_domain),
        "per_file": {k: dict(v) for k, v in res.per_file.items()},
        "sites": [vars(s) for s in res.sites],
        "inline_text_sites": [vars(s) for s in res.inline_text_sites],
        "includes": sorted(set(res.includes)),
    }, indent=1, sort_keys=False))
    (tables / "callees.json").write_text(json.dumps({
        "_comment": ("Distinct control-transfer targets in pret scripts/. "
                     "`defined_in_port` means a symbol of that name exists under "
                     "dos_port/src — NOT that its ABI has been checked. This file "
                     "is the work list for abi.json, which is fail-closed."),
        "distinct": len(res.callees),
        "callees": {
            name: {
                "sites": n,
                "defined_in_port": res.callee_defined.get(name, False),
                "by_form": dict(res.callee_kind.get(name, {})),
            }
            for name, n in res.callees.most_common()
        },
    }, indent=1))

    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
