#!/usr/bin/env python3
"""gen_tandy_tables.py — SN76489 attenuation tables for the Tandy shim.

The SN76489's 4-bit attenuator is logarithmic (2 dB per step, 15 = off),
while the GB's channel DAC is linear in the 4-bit envelope volume and the
3-bit NR50 master volume scales terminals linearly as (v+1)/8. These
tables convert the GB's linear levels into SN attenuation steps:

    env vol v (1..15):   att = round(20*log10(15/v) / 2)   [0 -> off]
    NR50 m   (0..7):     att = round(20*log10(8/(m+1)) / 2)
    NR32 wave level:     mute / 100% / 50% / 25% -> off / 0 / 3 / 6
                         (-6 dB and -12 dB in 2 dB steps)

Output: assets/tandy_tables.inc (Tier-1 generated data — DO NOT EDIT).
"""
import math
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "assets" / "tandy_tables.inc"


def db_steps(ratio: float) -> int:
    """dB of *ratio* expressed in 2 dB attenuator steps, clamped to 0..15."""
    return max(0, min(15, round(20 * math.log10(ratio) / 2)))


vol = [15] + [db_steps(15 / v) for v in range(1, 16)]
master = [db_steps(8 / (m + 1)) for m in range(8)]
wave = [15, 0, 3, 6]

with OUT.open("w") as f:
    f.write("; tandy_tables.inc — generated by tools/audio/gen_tandy_tables.py\n")
    f.write("; DO NOT EDIT BY HAND. GB linear volume -> SN76489 2 dB att steps.\n\n")
    f.write("TandyVolTable:        ; GB envelope volume 0-15\n")
    f.write("    db " + ", ".join(str(v) for v in vol) + "\n\n")
    f.write("TandyMasterAttTable:  ; NR50 per-terminal volume 0-7 (extra att)\n")
    f.write("    db " + ", ".join(str(v) for v in master) + "\n\n")
    f.write("TandyWaveLevelAtt:    ; NR32 output level 0-3 (mute/100%/50%/25%)\n")
    f.write("    db " + ", ".join(str(v) for v in wave) + "\n")

print(f"wrote {OUT}: vol={vol} master={master} wave={wave}")
