#!/usr/bin/env python3
"""gen_sfx_data.py — compile tools/audio/sfx/*.yaml into assets/sfx_data.inc.

Output: assets/sfx_data.inc (Tier-1 generated data, DO NOT EDIT BY HAND).
Scans tools/audio/sfx/*.yaml for patch assignments and volume scalings,
mapping them by numeric SFX ID and hardware channel (0-3) for the OPL shim.
"""

from __future__ import annotations

import re
from pathlib import Path
import sys
import yaml

ROOT = Path(__file__).resolve().parents[2]
SFX_DIR = Path(__file__).resolve().parent / "sfx"
CONST_INC = ROOT / "assets" / "audio_constants.inc"
OUT_INC = ROOT / "assets" / "sfx_data.inc"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_opl_patches import PATCH_ORDER


def load_sfx_constants() -> dict[str, int]:
    """Parse audio_constants.inc for SFX_* equ values."""
    constants = {}
    pattern = re.compile(r"^(SFX_\w+)\s+equ\s+(0x[0-9A-Fa-f]+|\d+)")
    with open(CONST_INC, "r", encoding="utf-8") as f:
        for line in f:
            m = pattern.match(line.strip())
            if m:
                name = m.group(1).upper()
                val_str = m.group(2)
                val = int(val_str, 16) if val_str.startswith("0x") else int(val_str)
                constants[name] = val
    return constants


def main():
    sfx_ids = load_sfx_constants()
    patch_indices = {name: idx for idx, name in enumerate(PATCH_ORDER)}

    rows: list[tuple[int, int, int, int, str, str]] = []

    if SFX_DIR.exists():
        for ypath in sorted(SFX_DIR.glob("*.yaml")):
            try:
                with open(ypath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
            except Exception as e:
                print(f"Warning: failed to parse {ypath.name}: {e}", file=sys.stderr)
                continue

            if not isinstance(data, dict):
                continue

            sfx_name = data.get("sfx")
            if not sfx_name:
                continue

            sfx_name_upper = sfx_name.upper()
            if sfx_name_upper not in sfx_ids:
                print(f"Warning: {ypath.name}: unknown SFX constant {sfx_name}", file=sys.stderr)
                continue

            sfx_id = sfx_ids[sfx_name_upper]
            channels = data.get("channels", {})
            for ch_num, ch_data in channels.items():
                try:
                    ch_int = int(ch_num)
                except ValueError:
                    continue

                # Map software channel (5-8) to hardware channel (0-3)
                hw_ch = ch_int - 5 if ch_int >= 5 else ch_int
                if not (0 <= hw_ch <= 3):
                    continue

                patch_name = ch_data.get("patch")
                if patch_name not in patch_indices:
                    print(f"Warning: {ypath.name}: unknown patch {patch_name}", file=sys.stderr)
                    continue

                patch_idx = patch_indices[patch_name]
                vol = int(ch_data.get("volume", 100))
                rows.append((sfx_id, hw_ch, patch_idx, vol, sfx_name_upper, patch_name))

    # Sort by sfx_id then hw_ch
    rows.sort(key=lambda r: (r[0], r[1]))

    lines = [
        "; sfx_data.inc — generated by tools/audio/gen_sfx_data.py. DO NOT EDIT BY HAND.",
        ";",
        "; OplSfxPatches: lookup table for SFX patch & volume overrides.",
        "; Format per entry: db sfx_id, hw_ch (0-3), patch_idx, volume_pct (0-255)",
        "; Terminated with 0xFF.",
        "",
        "OplSfxPatches:",
    ]

    for sfx_id, hw_ch, patch_idx, vol, sfx_name, patch_name in rows:
        lines.append(
            f"    db 0x{sfx_id:02X}, {hw_ch}, {patch_idx}, {vol}  "
            f"; {sfx_name} ch{hw_ch+5} -> {patch_name} (vol {vol}%)"
        )
    lines.append("    db 0xFF  ; sentinel")
    lines.append("")

    with open(OUT_INC, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"sfx_data.inc: {len(rows)} SFX channel overrides written to {OUT_INC.name}")


if __name__ == "__main__":
    main()
