#!/usr/bin/env python3
"""midi_to_stream.py — .mid → 60 Hz frame-delta flat streams (Phase B).

Compiles the SMFs generated by gb_to_midi.py (assets/midi/<target>/*.mid)
into assets/music_streams.inc for the DOS MPU-401 driver: running status
pre-resolved (every message carries its status byte), deltas in frames, loop
point baked in — no SMF parsing at runtime.

Stream format (consumed by src/audio/mpu401.asm):
    header:  dw loop_off        ; byte offset of the loop point measured from
                                ; the first op byte; 0xFFFF = song plays once
    ops:     0x00-0x7F          ; wait N frames (N >= 1)
             0x80-0xEF          ; MIDI message: status + data bytes (2 data
                                ; bytes, or 1 for 0xCn program / 0xDn pressure)
             0xF0               ; end of stream: stop playback
             0xF1               ; end of stream: jump to loop_off

Only the fixed timing model gb_to_midi.py emits is accepted (division 60,
tempo 1,000,000 µs/quarter → 1 tick = 1 frame); anything else raises.

Sound IDs are positional per bank and COLLIDE across banks (Music_Cities2 and
Music_Credits are both id 199 in different banks), exactly like the engine's
(id, bank) addressing — so four pointer tables are emitted, one per audio
bank slot, each indexed by the full 8-bit sound id:
    MidiStreamTable_Bank1..4:  256 dd entries; 0 = no stream for that id.
The driver picks the table from wAudioROMBank like DetermineAudioFunction.
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pret_audio import AudioROM  # noqa: E402
from gen_audio_data import parse_music_constants, sound_id  # noqa: E402
from gen_mt32_patches import (  # noqa: E402
    load_custom_timbres, custom_patch_record, factory_patch_record, patch_sysex
)
from mt32_presets import _norm  # noqa: E402
import yaml  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "dos_port" / "assets"
AUDIO_DIR = ROOT / "dos_port" / "tools" / "audio"
OVERRIDES_DIR = AUDIO_DIR / "overrides"
ENHANCE_DIR = AUDIO_DIR / "enhancements"

DIVISION = 60
TEMPO_USEC = 1_000_000
END_STOP = 0xF0
END_LOOP = 0xF1


# ---------------------------------------------------------------------------
# Minimal SMF reader (accepts exactly what gb_to_midi.py writes)
# ---------------------------------------------------------------------------
def read_vlq(data: bytes, pos: int) -> tuple[int, int]:
    val = 0
    while True:
        b = data[pos]
        pos += 1
        val = (val << 7) | (b & 0x7F)
        if not b & 0x80:
            return val, pos


def parse_midi(path: Path):
    """Returns (events, loop_start, end): events = [(tick, msg bytes)]."""
    data = path.read_bytes()
    if data[:4] != b"MThd":
        raise ValueError(f"{path.name}: not an SMF")
    fmt, ntrk, div = struct.unpack(">HHH", data[8:14])
    if div != DIVISION:
        raise ValueError(f"{path.name}: division {div}, expected {DIVISION}")

    events: list[tuple[int, int, bytes]] = []   # (tick, order, msg)
    loop_start = None
    end = None
    tempo_seen = None
    pos = 14
    for _ in range(ntrk):
        if data[pos:pos + 4] != b"MTrk":
            raise ValueError(f"{path.name}: bad track chunk")
        length = struct.unpack(">I", data[pos + 4:pos + 8])[0]
        p, trk_end = pos + 8, pos + 8 + length
        tick = 0
        running = None
        while p < trk_end:
            delta, p = read_vlq(data, p)
            tick += delta
            status = data[p]
            if status == 0xFF:
                mtype = data[p + 1]
                mlen, p2 = read_vlq(data, p + 2)
                payload = data[p2:p2 + mlen]
                p = p2 + mlen
                if mtype == 0x51:
                    tempo_seen = int.from_bytes(payload, "big")
                elif mtype == 0x06 and payload == b"loopStart":
                    loop_start = tick
                elif mtype == 0x06 and payload == b"loopEnd":
                    end = tick
                continue
            if status in (0xF0, 0xF7):
                raise ValueError(f"{path.name}: unexpected sysex in stream")
            if status & 0x80:
                running = status
                p += 1
            elif running is None:
                raise ValueError(f"{path.name}: dangling data byte")
            else:
                status = running
            ndata = 1 if status & 0xF0 in (0xC0, 0xD0) else 2
            msg = bytes((status,)) + data[p:p + ndata]
            p += ndata
            kind = status & 0xF0
            order = (0 if kind == 0x80 or (kind == 0x90 and msg[2] == 0)
                     else 2 if kind == 0x90 else 1)
            events.append((tick, order, msg))
        pos = trk_end

    if tempo_seen != TEMPO_USEC:
        raise ValueError(f"{path.name}: tempo {tempo_seen}, "
                         f"expected {TEMPO_USEC} (1 tick = 1 frame)")
    if end is None:
        raise ValueError(f"{path.name}: no loopEnd marker")
    events.sort(key=lambda e: (e[0], e[1]))
    return [(t, m) for t, _, m in events], loop_start, end


# ---------------------------------------------------------------------------
# Stream assembly
# ---------------------------------------------------------------------------
def build_stream(events, loop_start, end) -> tuple[bytes, int]:
    """Returns (ops bytes, loop_off). loop_off = 0xFFFF when no loop."""
    ops = bytearray()
    loop_off = 0xFFFF
    frame = 0

    def wait_until(target):
        nonlocal frame
        while frame < target:
            step = min(target - frame, 0x7F)
            ops.append(step)
            frame += step

    def is_off(msg):
        kind = msg[0] & 0xF0
        return kind == 0x80 or (kind == 0x90 and msg[2] == 0)

    for tick, msg in events:
        if tick >= end:
            # note-offs land exactly on the end tick (gb_to_midi clamps
            # sustains there); dropping them would leak one voice per loop
            # pass on the MT-32, so they play right before the end op
            if tick == end and is_off(msg):
                wait_until(end)
                ops += msg
            continue
        if loop_start is not None and loop_off == 0xFFFF and tick >= loop_start:
            wait_until(loop_start)      # byte boundary exactly on the loop frame
            loop_off = len(ops)
        wait_until(tick)
        ops += msg
    if loop_start is not None and loop_off == 0xFFFF:
        wait_until(loop_start)
        loop_off = len(ops)
    wait_until(end)
    ops.append(END_LOOP if loop_start is not None else END_STOP)
    if len(ops) > 0xFFFE:
        raise ValueError(f"stream too large for dw loop_off ({len(ops)} bytes)")
    return bytes(ops), loop_off


def find_song_custom_patches(label: str, custom_timbres: dict[str, dict]) -> list[tuple[int, int]]:
    """Returns sorted list of (patch_num, timbre_index) for custom timbres used by song."""
    used_timbres: set[str] = set()

    # 1. Overrides
    ov_path = OVERRIDES_DIR / f"{label}.yaml"
    if ov_path.exists():
        try:
            data = yaml.safe_load(ov_path.read_text()) or {}
            chs = data.get("channels", {}) or {}
            for _, ch in chs.items():
                if not isinstance(ch, dict):
                    continue
                for k in ("mt32_program", "program"):
                    val = ch.get(k)
                    if isinstance(val, str) and _norm(val) in custom_timbres:
                        used_timbres.add(_norm(val))
                for sw in ch.get("switches", []) or []:
                    if isinstance(sw, dict):
                        for k in ("mt32_program", "program"):
                            val = sw.get(k)
                            if isinstance(val, str) and _norm(val) in custom_timbres:
                                used_timbres.add(_norm(val))
        except Exception:
            pass

    # 2. Enhancements
    enh_path = ENHANCE_DIR / f"{label}.yaml"
    if enh_path.exists():
        try:
            data = yaml.safe_load(enh_path.read_text()) or {}
            chs = data.get("channels", []) or []
            for ch in chs:
                if not isinstance(ch, dict):
                    continue
                for k in ("mt32_patch", "mt32_program", "program"):
                    val = ch.get(k)
                    if isinstance(val, str) and _norm(val) in custom_timbres:
                        used_timbres.add(_norm(val))
                for sw in ch.get("switches", []) or []:
                    if isinstance(sw, dict):
                        for k in ("mt32_patch", "mt32_program", "program"):
                            val = sw.get(k)
                            if isinstance(val, str) and _norm(val) in custom_timbres:
                                used_timbres.add(_norm(val))
        except Exception:
            pass

    patches = []
    for norm in sorted(used_timbres):
        t = custom_timbres[norm]
        patches.append((t["patch"], t["index"]))
    patches.sort(key=lambda p: p[0])
    return patches


def build_song_sysex(patches: list[tuple[int, int]]) -> tuple[list[bytes], list[bytes]]:
    if not patches:
        return [], []
    setup_msgs = [patch_sysex(p, custom_patch_record(idx)) for p, idx in patches]
    cleanup_msgs = [patch_sysex(p, factory_patch_record(p)) for p, idx in patches]
    return setup_msgs, cleanup_msgs


def emit_inc(streams: dict[str, tuple[bytes, int]],
             table: dict[int, dict[int, str]],
             banks: list[int],
             song_sysex: dict[str, tuple[list[bytes], list[bytes]]],
             prefix: str = "Midi") -> str:
    inc_name = "imfc_streams.inc" if prefix == "Imfc" else "music_streams.inc"
    driver_name = "src/audio/imfc.asm" if prefix == "Imfc" else "src/audio/mpu401.asm"
    lines = [f"; {inc_name} — generated by tools/audio/midi_to_stream.py."
             " DO NOT EDIT BY HAND.",
             ";",
             f"; Flat 60 Hz MIDI streams for {driver_name}.",
             "; Per stream: dw loop_off (from first op byte; 0xFFFF = play"
             " once), then ops:",
             ";   00-7F wait N frames | 80-EF MIDI msg (status + 1-2 data)",
             ";   F0 end: stop        | F1 end: jump to loop_off",
             ";",
             f"; {prefix}StreamTable_BankN: 256 dd per audio bank slot, indexed by",
             "; sound id (ids collide across banks — pick the table from",
             "; wAudioROMBank, as DetermineAudioFunction picks engines).",
             ""]
    stream_prefix = "Imfc" if prefix == "Imfc" else "Midi"
    setup_prefix = "Imfc" if prefix == "Imfc" else "Mt32"
    for slot, bank in enumerate(banks, 1):
        lines.append(f"{stream_prefix}StreamTable_Bank{slot}:  ; GB bank ${bank:02x}")
        by_id = table.get(bank, {})
        for base in range(0, 256, 8):
            row = ", ".join(
                (f"{stream_prefix}Stream_{by_id[i]}" if i in by_id else "0")
                for i in range(base, base + 8))
            lines.append(f"    dd {row}")
        lines.append("")

    lines.append("; ---------------------------------------------------------------------------")
    lines.append(f"; {setup_prefix} per-song custom patch setup tables (0 = no custom patches used)")
    lines.append("; ---------------------------------------------------------------------------")
    for slot, bank in enumerate(banks, 1):
        lines.append(f"{setup_prefix}SongSetupTable_Bank{slot}:  ; GB bank ${bank:02x}")
        by_id = table.get(bank, {})
        for base in range(0, 256, 8):
            row = ", ".join(
                (f"{setup_prefix}Setup_{by_id[i]}" if (i in by_id and by_id[i] in song_sysex and song_sysex[by_id[i]][0]) else "0")
                for i in range(base, base + 8))
            lines.append(f"    dd {row}")
        lines.append("")

    lines.append("; ---------------------------------------------------------------------------")
    lines.append(f"; {setup_prefix} per-song factory patch cleanup tables (0 = no custom patches to restore)")
    lines.append("; ---------------------------------------------------------------------------")
    for slot, bank in enumerate(banks, 1):
        lines.append(f"{setup_prefix}SongCleanupTable_Bank{slot}:  ; GB bank ${bank:02x}")
        by_id = table.get(bank, {})
        for base in range(0, 256, 8):
            row = ", ".join(
                (f"{setup_prefix}Cleanup_{by_id[i]}" if (i in by_id and by_id[i] in song_sysex and song_sysex[by_id[i]][1]) else "0")
                for i in range(base, base + 8))
            lines.append(f"    dd {row}")
        lines.append("")

    total = 0
    for label, (ops, loop_off) in sorted(streams.items()):
        total += len(ops) + 2
        lines.append(f"{stream_prefix}Stream_{label}:  ; {len(ops)} bytes")
        lines.append(f"    dw 0x{loop_off:04X}")
        for i in range(0, len(ops), 16):
            row = ", ".join(f"0x{b:02X}" for b in ops[i:i + 16])
            lines.append(f"    db {row}")
        lines.append("")

    lines.append("; ===========================================================================")
    lines.append(f"; {setup_prefix} On-the-fly Patch Setup & Cleanup SysEx blobs")
    lines.append("; Length-prefixed SysEx messages; dw 0 terminates each list.")
    lines.append("; ===========================================================================")
    for label, (setup_msgs, cleanup_msgs) in sorted(song_sysex.items()):
        if setup_msgs:
            lines.append(f"{setup_prefix}Setup_{label}:")
            for msg in setup_msgs:
                lines.append(f"    dw {len(msg)}")
                for i in range(0, len(msg), 16):
                    row = ", ".join(f"0x{b:02X}" for b in msg[i:i + 16])
                    lines.append(f"    db {row}")
            lines.append("    dw 0")
            lines.append("")
        if cleanup_msgs:
            lines.append(f"{setup_prefix}Cleanup_{label}:")
            for msg in cleanup_msgs:
                lines.append(f"    dw {len(msg)}")
                for i in range(0, len(msg), 16):
                    row = ", ".join(f"0x{b:02X}" for b in msg[i:i + 16])
                    lines.append(f"    db {row}")
            lines.append("    dw 0")
            lines.append("")

    lines.append(f"; total stream bytes: {total}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--target", choices=("mt32", "gm", "imfc"), default="mt32")
    args = ap.parse_args()

    rom = AudioROM(ROOT)
    consts, _ = parse_music_constants()
    music_labels = {lbl for name, lbl in consts.items()
                    if name.startswith("MUSIC_") and lbl in rom.symtab}

    custom_timbres = load_custom_timbres() if args.target == "mt32" else {}

    midi_dir = ASSETS / "midi" / args.target
    streams: dict[str, tuple[bytes, int]] = {}
    table: dict[int, dict[int, str]] = {}
    song_sysex: dict[str, tuple[list[bytes], list[bytes]]] = {}

    for path in sorted(midi_dir.glob("*.mid")):
        label = path.stem
        if label not in music_labels:
            raise ValueError(f"{path.name}: not a known music header label")
        events, loop_start, end = parse_midi(path)
        ops, loop_off = build_stream(events, loop_start, end)
        streams[label] = (ops, loop_off)
        bank = rom.sym_bank[label]
        table.setdefault(bank, {})[sound_id(rom, label)] = label

        if args.target == "mt32" and custom_timbres:
            patches = find_song_custom_patches(label, custom_timbres)
            if patches:
                setup_msgs, cleanup_msgs = build_song_sysex(patches)
                song_sysex[label] = (setup_msgs, cleanup_msgs)

    prefix = "Imfc" if args.target == "imfc" else "Midi"
    out_file = ASSETS / ("imfc_streams.inc" if args.target == "imfc" else "music_streams.inc")
    out_file.write_text(emit_inc(streams, table, rom.banks(), song_sysex, prefix=prefix))
    total = sum(len(o) + 2 for o, _ in streams.values())
    n_custom = len(song_sysex)
    print(f"{out_file.name}: {len(streams)} streams ({n_custom} custom patch tracks), {total} bytes")


if __name__ == "__main__":
    main()
