#!/usr/bin/env python3
"""test_audio_data.py — byte-compare generated audio data against the ROM.

Proves that pret_audio.py + gen_audio_data.py produce exactly the bytes
RGBDS produces, which is the trust foundation for the whole audio pipeline
(engine data blobs now, the MIDI tooling in Phase B).

Usage:
    python3 tools/audio/test_audio_data.py [path/to/pokeyellow.gbc]

The ROM must be a pristine pret pokeyellow build (sha1 in roms.sha1 at the
repo root). The repo root itself no longer links as a GB ROM (the port
enlarged WRAM arrays in ram/wram.asm), so build the golden ROM from a
worktree at the pret merge-base, e.g.:

    git worktree add /tmp/pret-golden $(git merge-base HEAD upstream/master)
    make -C /tmp/pret-golden pokeyellow.gbc     # needs rgbds 1.0.1

Checks:
  1. ROM sha1 matches the pret-verified hash.
  2. Every generated byte of the four bank images matches the ROM.
  3. Data-section extents match the golden link map (vendored below).
  4. CryData matches the ROM bytes at its vendored location.
  5. Cross-bank SFX ID parity (same name, same positional ID in every bank
     that carries it) — the property the shared ID space depends on.
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pret_audio import AudioROM, BANK_BASE, VENDORED_SYMBOLS  # noqa: E402
from gen_audio_data import parse_music_constants, parse_cry_data, sound_id  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]

GOLDEN_SHA1 = "cc7d03262ebfaf2f06772c1a480c7d9d5f4a38e1"  # pokeyellow.gbc

# Golden data-section extents (start, end inclusive) from the pristine
# build's pokeyellow.map at merge-base 7caf2e09.
GOLDEN_EXTENTS = {
    ("Sound Effect Headers 1", 0x02): (0x4000, 0x422D),
    ("Music Headers 1", 0x02): (0x422E, 0x42FC),
    ("Sound Effects 1", 0x02): (0x42FD, 0x5063),
    ("Music 1", 0x02): (0x5A16, 0x7EC6),
    ("Sound Effect Headers 2", 0x08): (0x4000, 0x42BD),
    ("Music Headers 2", 0x08): (0x42BE, 0x42FC),
    ("Sound Effects 2", 0x08): (0x42FD, 0x531D),
    ("Music 2", 0x08): (0x5B9A, 0x77BC),
    ("Sound Effect Headers 3", 0x1F): (0x4000, 0x4248),
    ("Music Headers 3", 0x1F): (0x4249, 0x42F9),
    ("Sound Effects 3", 0x1F): (0x42FA, 0x50D5),
    ("Music 3", 0x1F): (0x5221, 0x785F),
    ("Sound Effect Headers 4", 0x20): (0x4000, 0x41CA),
    ("Music Headers 4", 0x20): (0x41CB, 0x41EB),
    ("Sound Effects 4", 0x20): (0x41EC, 0x4F13),
    # Music 4's golden section runs to $7FFF, but the tail beyond the last
    # data byte is the release-only garbage INCBIN — compare data end only.
}
MUSIC4_START = 0x6CE8


def fail(msg: str) -> None:
    print(f"FAIL: {msg}")
    sys.exit(1)


def main() -> None:
    if len(sys.argv) > 1:
        rom_path = Path(sys.argv[1])
    else:
        rom_path = ROOT / "pokeyellow.gbc"
    if not rom_path.exists():
        print(__doc__)
        fail(f"golden ROM not found at {rom_path}")
    rom_bytes = rom_path.read_bytes()

    # 1. sha1
    sha = hashlib.sha1(rom_bytes).hexdigest()
    if sha != GOLDEN_SHA1:
        fail(f"ROM sha1 {sha} != pret-verified {GOLDEN_SHA1}")
    print(f"ok: ROM sha1 {sha}")

    audio = AudioROM(ROOT)

    # 2. bank image byte-compare
    total = 0
    for bank in audio.banks():
        img, mask = audio.render_bank(bank)
        gold = rom_bytes[bank * 0x4000:(bank + 1) * 0x4000]
        mismatches = [
            i for i in range(len(img)) if mask[i] and img[i] != gold[i]
        ]
        if mismatches:
            i = mismatches[0]
            fail(f"bank ${bank:02x}: {len(mismatches)} mismatches; first at "
                 f"${BANK_BASE + i:04x} (gen {img[i]:02x} rom {gold[i]:02x})")
        total += sum(mask)
    print(f"ok: {total} generated bytes match the ROM across "
          f"{len(audio.banks())} banks")

    # 3. section extents
    for sec in audio.sections:
        key = (sec.name, sec.bank)
        if key in GOLDEN_EXTENTS:
            start, end = GOLDEN_EXTENTS[key]
            if (sec.start, sec.end - 1) != (start, end):
                fail(f"{sec.name}: ${sec.start:04x}-${sec.end - 1:04x} != "
                     f"golden ${start:04x}-${end:04x}")
        elif sec.name == "Music 4":
            if sec.start != MUSIC4_START:
                fail(f"Music 4 starts at ${sec.start:04x} != ${MUSIC4_START:04x}")
    print("ok: data-section extents match the golden link map")

    # 4. CryData
    consts, _ = parse_music_constants()
    ids = {n: sound_id(audio, l) for n, l in consts.items()
           if l in audio.symtab}
    cries = parse_cry_data(ids)
    bank, addr = VENDORED_SYMBOLS["CryData"]
    off = bank * 0x4000 + (addr - BANK_BASE)
    gen = b"".join(bytes((b, p, ln)) for b, p, ln, _ in cries)
    if rom_bytes[off:off + len(gen)] != gen:
        fail("CryData does not match the ROM")
    print(f"ok: CryData ({len(cries)} species, {len(gen)} bytes) matches")

    # 5. cross-bank SFX ID parity
    header_ranges = {
        (sec.bank, sec.start, sec.end)
        for sec in audio.sections if "Headers" in sec.name
    }

    def in_headers(bank: int, addr: int) -> bool:
        return any(b == bank and s <= addr < e for b, s, e in header_ranges)

    groups: dict[str, dict[int, int]] = {}
    for label, addr in audio.symtab.items():
        m = re.match(r"^(SFX_\w+)_([1-4])$", label)
        if not m or not in_headers(audio.sym_bank[label], addr):
            continue
        groups.setdefault(m.group(1), {})[int(m.group(2))] = \
            (addr - BANK_BASE) // 3
    bad = {name: by_bank for name, by_bank in groups.items()
           if len(set(by_bank.values())) > 1}
    if bad:
        fail(f"SFX ID parity broken: {bad}")
    print(f"ok: SFX ID parity holds for {len(groups)} cross-bank names")

    print("PASS")


if __name__ == "__main__":
    main()
