; BluesHouse.asm — translated from pret scripts/BluesHouse.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"


global BluesHouseDaisyBagFullText
global BluesHouseDaisyOfferMapText
global BluesHouseDaisyRivalAtLabText
global BluesHouseDaisySittingText
global BluesHouseDaisyUseMapText
global BluesHouseDaisyWalkingText
global BluesHouseDefaultScript
global BluesHouseNoopScript
global BluesHouseTownMapText
global BluesHouse_Script
global BluesHouse_ScriptPointers
global BluesHouse_TextPointers
global GotMapText

extern CallFunctionInTable
extern EnableAutoTextBoxDrawing
extern GiveItem
extern HideObject
extern PrintText
extern TextScriptEnd

; Script constants — pret defines these via dw_const in this file.
SCRIPT_BLUESHOUSE_NOOP                         equ 1

; pret RAM symbols gb_memmap.inc does not carry. Addresses are rgblink's,
; read from pokeyellow.sym — not inferred.
wBluesHouseCurScript                           equ 0xD5F2

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/blues_house, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/blues_house.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
BluesHouse_Script:
    call EnableAutoTextBoxDrawing
    mov esi, BluesHouse_ScriptPointers
    xor al, al
    call CallFunctionInTable
    ret

%assign event_byte -1
%assign event_byte_a -1
BluesHouse_ScriptPointers:
    dd BluesHouseDefaultScript
    dd BluesHouseNoopScript

%assign event_byte -1
%assign event_byte_a -1
BluesHouseDefaultScript:
    SetEvent EVENT_ENTERED_BLUES_HOUSE
    mov al, SCRIPT_BLUESHOUSE_NOOP
    mov [ebp + wBluesHouseCurScript], al
BluesHouseNoopScript:
    ret

%assign event_byte -1
%assign event_byte_a -1
BluesHouse_TextPointers:
    dd BluesHouseDaisySittingText
    dd BluesHouseDaisyWalkingText
    dd BluesHouseTownMapText

%assign event_byte -1
%assign event_byte_a -1
BluesHouseDaisySittingText:
    CheckEvent EVENT_GOT_TOWN_MAP
    jnz .got_town_map
    CheckEvent EVENT_GOT_POKEDEX
    jnz .give_town_map
    mov esi, BluesHouseDaisyRivalAtLabText
    call PrintText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.give_town_map:
    mov esi, BluesHouseDaisyOfferMapText
    call PrintText
    mov bx, (TOWN_MAP << 8) | (1)   ; pret: lb bc, TOWN_MAP, 1 (BluesHouse.asm:39)
    call GiveItem
    jae .bag_full
    mov al, TOGGLE_TOWN_MAP
    mov [ebp + wToggleableObjectIndex], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call HideObject
    mov esi, GotMapText
    call PrintText
    SetEvent EVENT_GOT_TOWN_MAP
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.got_town_map:
    mov esi, BluesHouseDaisyUseMapText
    call PrintText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.bag_full:
    mov esi, BluesHouseDaisyBagFullText
    call PrintText
.done:
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
BluesHouseDaisyRivalAtLabText:
    text_far _BluesHouseDaisyRivalAtLabText
    text_end
BluesHouseDaisyOfferMapText:
    text_far _BluesHouseDaisyOfferMapText
    text_end
GotMapText:
    text_far _GotMapText
    sound_get_key_item
    text_end
BluesHouseDaisyBagFullText:
    text_far _BluesHouseDaisyBagFullText
    text_end
BluesHouseDaisyUseMapText:
    text_far _BluesHouseDaisyUseMapText
    text_end
BluesHouseDaisyWalkingText:
    text_far _BluesHouseDaisyWalkingText
    text_end
BluesHouseTownMapText:
    text_far _BluesHouseTownMapText
    text_end
