; CeladonMart3F.asm — translated from pret scripts/CeladonMart3F.asm, scripts/CeladonMart3F_2.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"

global CeladonMart3FClerkText
global CeladonMart3FCurrentFloorSignText
global CeladonMart3FFightingGameText
global CeladonMart3FGameBoyKid1Text
global CeladonMart3FGameBoyKid2Text
global CeladonMart3FGameBoyKid3Text
global CeladonMart3FLittleBoyText
global CeladonMart3FPokemonPosterText
global CeladonMart3FPrintClerkText
global CeladonMart3FPuzzleGameText
global CeladonMart3FRPGText
global CeladonMart3FSNESText
global CeladonMart3FSportsGameText
global CeladonMart3F_Script
global CeladonMart3F_TextPointers

extern Bankswitch
extern EnableAutoTextBoxDrawing
extern GiveItem
extern PrintText
extern TextScriptEnd

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/celadon_mart_3f, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/CeladonMart3F.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
CeladonMart3F_Script:
    jmp EnableAutoTextBoxDrawing

%assign event_byte -1
%assign event_byte_a -1
CeladonMart3F_TextPointers:
    dd CeladonMart3FClerkText
    dd CeladonMart3FGameBoyKid1Text
    dd CeladonMart3FGameBoyKid2Text
    dd CeladonMart3FGameBoyKid3Text
    dd CeladonMart3FLittleBoyText
    dd CeladonMart3FSNESText
    dd CeladonMart3FRPGText
    dd CeladonMart3FSNESText
    dd CeladonMart3FSportsGameText
    dd CeladonMart3FSNESText
    dd CeladonMart3FPuzzleGameText
    dd CeladonMart3FSNESText
    dd CeladonMart3FFightingGameText
    dd CeladonMart3FCurrentFloorSignText
    dd CeladonMart3FPokemonPosterText
    dd CeladonMart3FPokemonPosterText
    dd CeladonMart3FPokemonPosterText

%assign event_byte -1
%assign event_byte_a -1
CeladonMart3FClerkText:
; DEVIATION{class=banking; pret=macros/farcall.asm:callfar; behavior=bank switch dropped, call goes straight to the target; evidence=the DPMI model is flat so every routine is always addressable, and Bankswitch has no port counterpart; lifetime=permanent}
    call CeladonMart3FPrintClerkText
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
CeladonMart3FGameBoyKid1Text:
    text_far _CeladonMart3FGameBoyKid1Text
    text_end
CeladonMart3FGameBoyKid2Text:
    text_far _CeladonMart3FGameBoyKid2Text
    text_end
CeladonMart3FGameBoyKid3Text:
    text_far _CeladonMart3FGameBoyKid3Text
    text_end
CeladonMart3FLittleBoyText:
    text_far _CeladonMart3FLittleBoyText
    text_end
CeladonMart3FSNESText:
    text_far _CeladonMart3FSNESText
    text_end
CeladonMart3FRPGText:
    text_far _CeladonMart3FRPGText
    text_end
CeladonMart3FSportsGameText:
    text_far _CeladonMart3FSportsGameText
    text_end
CeladonMart3FPuzzleGameText:
    text_far _CeladonMart3FPuzzleGameText
    text_end
CeladonMart3FFightingGameText:
    text_far _CeladonMart3FFightingGameText
    text_end
CeladonMart3FCurrentFloorSignText:
    text_far _CeladonMart3FCurrentFloorSignText
    text_end
CeladonMart3FPokemonPosterText:
    text_far _CeladonMart3FPokemonPosterText
    text_end

%assign event_byte -1
%assign event_byte_a -1
CeladonMart3FPrintClerkText:
    CheckEvent EVENT_GOT_TM18
    jnz .got_item
    mov esi, .TM18PreReceiveText
    call PrintText
    mov bx, (TM_COUNTER << 8) | (1)   ; pret: lb bc, TM_COUNTER, 1  (TM18 = $DA)
    call GiveItem
    jae .bag_full
    SetEvent EVENT_GOT_TM18
    mov esi, .ReceivedTM18Text
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.bag_full:
    mov esi, .TM18NoRoomText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.got_item:
    mov esi, .TM18ExplanationText
.done:
    call PrintText
    ret

%assign event_byte -1
%assign event_byte_a -1
.TM18PreReceiveText:
    text_far _CeladonMart3FClerkTM18PreReceiveText
    text_end
.ReceivedTM18Text:
    text_far _CeladonMart3FClerkReceivedTM18Text
    sound_get_item_1
    text_end
.TM18ExplanationText:
    text_far _CeladonMart3FClerkTM18ExplanationText
    text_end
.TM18NoRoomText:
    text_far _CeladonMart3FClerkTM18NoRoomText
    text_end
