; CopycatsHouse2F.asm — translated from pret scripts/CopycatsHouse2F.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"

global CopycatsHouse2FCopycatText
global CopycatsHouse2FDoduoText
global CopycatsHouse2FPCText
global CopycatsHouse2FRareDollText
global CopycatsHouse2FSNESText
global CopycatsHouse2F_Script
global CopycatsHouse2F_TextPointers

extern Bankswitch
extern EnableAutoTextBoxDrawing
extern GiveItem
extern IsItemInBag
extern PrintText
extern RemoveItemByID
extern TextScriptEnd

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/copycats_house_2f, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/copycats_house_2f.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
CopycatsHouse2F_Script:
    jmp EnableAutoTextBoxDrawing

%assign event_byte -1
%assign event_byte_a -1
CopycatsHouse2F_TextPointers:
    dd CopycatsHouse2FCopycatText
    dd CopycatsHouse2FDoduoText
    dd CopycatsHouse2FRareDollText
    dd CopycatsHouse2FRareDollText
    dd CopycatsHouse2FRareDollText
    dd CopycatsHouse2FSNESText
    dd CopycatsHouse2FPCText

%assign event_byte -1
%assign event_byte_a -1
CopycatsHouse2FCopycatText:
    CheckEvent EVENT_GOT_TM31
    jnz .got_item
    mov al, 1
    mov [ebp + wDoNotWaitForButtonPressAfterDisplayingText], al
    mov esi, .DoYouLikePokemonText
    call PrintText
    mov bh, POKE_DOLL
    call IsItemInBag
    jz .done
    mov esi, .TM31PreReceiveText
    call PrintText
    mov bx, (TM_MIMIC << 8) | (1)   ; pret: lb bc, TM_MIMIC, 1  (TM31 = $E7)
    call GiveItem
    jae .bag_full
    mov esi, .ReceivedTM31Text
    call PrintText
    mov al, POKE_DOLL
    mov [ebp + hItemToRemoveID], al
; DEVIATION{class=banking; pret=macros/farcall.asm:farcall; behavior=bank switch dropped, call goes straight to the target; evidence=the DPMI model is flat so every routine is always addressable, and Bankswitch has no port counterpart; lifetime=permanent}
    call RemoveItemByID
    SetEvent EVENT_GOT_TM31
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.bag_full:
    mov esi, .TM31NoRoomText
    call PrintText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.got_item:
    mov esi, .TM31Explanation2Text
    call PrintText
.done:
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.DoYouLikePokemonText:
    text_far _CopycatsHouse2FCopycatDoYouLikePokemonText
    text_end
.TM31PreReceiveText:
    text_far _CopycatsHouse2FCopycatTM31PreReceiveText
    text_end
.ReceivedTM31Text:
    text_far _CopycatsHouse2FCopycatReceivedTM31Text
    sound_get_item_1
.TM31Explanation1Text:
    text_far _CopycatsHouse2FCopycatTM31Explanation1Text
    text_waitbutton
    text_end
.TM31Explanation2Text:
    text_far _CopycatsHouse2FCopycatTM31Explanation2Text
    text_end
.TM31NoRoomText:
    text_far _CopycatsHouse2FCopycatTM31NoRoomText
    text_waitbutton
    text_end
CopycatsHouse2FDoduoText:
    text_far _CopycatsHouse2FDoduoText
    text_end
CopycatsHouse2FRareDollText:
    text_far _CopycatsHouse2FRareDollText
    text_end
CopycatsHouse2FSNESText:
    text_far _CopycatsHouse2FSNESText
    text_end

%assign event_byte -1
%assign event_byte_a -1
CopycatsHouse2FPCText:
    mov al, [ebp + wSpritePlayerStateData1FacingDirection]
    cmp al, SPRITE_FACING_UP
    mov esi, .CantSeeText
    jnz .notUp
    mov esi, .MySecretsText
.notUp:
    call PrintText
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.MySecretsText:
    text_far _CopycatsHouse2FPCMySecretsText
    text_end
.CantSeeText:
    text_far _CopycatsHouse2FPCCantSeeText
    text_end
