; MrPsychicsHouse.asm — translated from pret scripts/MrPsychicsHouse.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"

global MrPsychicsHouseMrPsychicText
global MrPsychicsHouse_Script
global MrPsychicsHouse_TextPointers

extern EnableAutoTextBoxDrawing
extern GiveItem
extern PrintText
extern TextScriptEnd

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/mr_psychics_house, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/mr_psychics_house.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
MrPsychicsHouse_Script:
    jmp EnableAutoTextBoxDrawing

%assign event_byte -1
%assign event_byte_a -1
MrPsychicsHouse_TextPointers:
    dd MrPsychicsHouseMrPsychicText

%assign event_byte -1
%assign event_byte_a -1
MrPsychicsHouseMrPsychicText:
    CheckEvent EVENT_GOT_TM29
    jnz .got_item
    mov esi, .YouWantedThisText
    call PrintText
    mov bx, (TM_PSYCHIC_M << 8) | (1)   ; pret: lb bc, TM_PSYCHIC_M, 1  (TM29 = $E5)
    call GiveItem
    jae .bag_full
    mov esi, .ReceivedTM29Text
    call PrintText
    SetEvent EVENT_GOT_TM29
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.bag_full:
    mov esi, .TM29NoRoomText
    call PrintText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.got_item:
    mov esi, .TM29ExplanationText
    call PrintText
.done:
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.YouWantedThisText:
    text_far _MrPsychicsHouseMrPsychicYouWantedThisText
    text_end
.ReceivedTM29Text:
    text_far _MrPsychicsHouseMrPsychicReceivedTM29Text
    sound_get_item_1
    text_end
.TM29ExplanationText:
    text_far _MrPsychicsHouseMrPsychicTM29ExplanationText
    text_end
.TM29NoRoomText:
    text_far _MrPsychicsHouseMrPsychicTM29NoRoomText
    text_end
