; NameRatersHouse.asm — translated from pret scripts/NameRatersHouse.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"


global NameRatersHouseCheckMonOTScript
global NameRatersHouseNameRaterText
global NameRatersHouseYesNoScript
global NameRatersHouse_Script
global NameRatersHouse_TextPointers

extern AddNTimes
extern Bankswitch
extern DisplayNameRaterScreen
extern DisplayPartyMenu
extern EnableAutoTextBoxDrawing
extern GBPalWhiteOutWithDelay3
extern GetPartyMonName2
extern LoadGBPal
extern PrintText
extern RestoreScreenTilesAndReloadTilePatterns
extern SaveScreenTilesToBuffer2
extern TextScriptEnd
extern YesNoChoice

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/name_raters_house, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/name_raters_house.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
NameRatersHouse_Script:
    jmp EnableAutoTextBoxDrawing

%assign event_byte -1
%assign event_byte_a -1
NameRatersHouseYesNoScript:
    call PrintText
    call YesNoChoice
    mov al, [ebp + wCurrentMenuItem]
    test al, al
    ret

%assign event_byte -1
%assign event_byte_a -1
NameRatersHouseCheckMonOTScript:
    mov esi, wPartyMonOT
    mov bx, NAME_LENGTH
    mov al, [ebp + wWhichPokemon]
    call AddNTimes
    mov edx, wPlayerName
    mov bl, NAME_LENGTH
    call .check_match_loop
    jb .no_match
    mov esi, wPartyMon1OTID
    mov bx, PARTYMON_STRUCT_LENGTH
    mov al, [ebp + wWhichPokemon]
    call AddNTimes
    mov edx, wPlayerID
    mov bl, 0x2
.check_match_loop:
    mov al, [ebp + edx]
    cmp al, [ebp + esi]
    jnz .no_match
    inc esi
    inc edx
    dec bl
    jnz .check_match_loop
    and al, al
    ret

%assign event_byte -1
%assign event_byte_a -1
.no_match:
    stc
    ret

%assign event_byte -1
%assign event_byte_a -1
NameRatersHouse_TextPointers:
    dd NameRatersHouseNameRaterText

%assign event_byte -1
%assign event_byte_a -1
NameRatersHouseNameRaterText:
    call SaveScreenTilesToBuffer2
    mov esi, .WantMeToRateText
    call NameRatersHouseYesNoScript
    jnz .did_not_rename
    mov esi, .WhichPokemonText
    call PrintText
    xor al, al
    mov [ebp + wPartyMenuTypeOrMessageID], al
    mov [ebp + wUpdateSpritesEnabled], al
    mov [ebp + wMenuItemToSwap], al
    call DisplayPartyMenu
    pushfd
    push eax
    call GBPalWhiteOutWithDelay3
    call RestoreScreenTilesAndReloadTilePatterns
    call LoadGBPal
    pop eax
    popfd
    jb .did_not_rename
    call GetPartyMonName2
    call NameRatersHouseCheckMonOTScript
    mov esi, .ATrulyImpeccableNameText
    jb .done
    mov esi, .GiveItANiceNameText
    call NameRatersHouseYesNoScript
    jnz .did_not_rename
    mov esi, .WhatShouldWeNameItText
    call PrintText
; DEVIATION{class=banking; pret=macros/farcall.asm:farcall; behavior=bank switch dropped, call goes straight to the target; evidence=the DPMI model is flat so every routine is always addressable, and Bankswitch has no port counterpart; lifetime=permanent}
    call DisplayNameRaterScreen
    jb .did_not_rename
    mov esi, .PokemonHasBeenRenamedText
.done:
    call PrintText
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.did_not_rename:
    mov esi, .ComeAnyTimeYouLikeText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.WantMeToRateText:
    text_far _NameRatersHouseNameRaterWantMeToRateText
    text_end
.WhichPokemonText:
    text_far _NameRatersHouseNameRaterWhichPokemonText
    text_end
.GiveItANiceNameText:
    text_far _NameRatersHouseNameRaterGiveItANiceNameText
    text_end
.WhatShouldWeNameItText:
    text_far _NameRatersHouseNameRaterWhatShouldWeNameItText
    text_end
.PokemonHasBeenRenamedText:
    text_far _NameRatersHouseNameRaterPokemonHasBeenRenamedText
    text_end
.ComeAnyTimeYouLikeText:
    text_far _NameRatersHouseNameRaterComeAnyTimeYouLikeText
    text_end
.ATrulyImpeccableNameText:
    text_far _NameRatersHouseNameRaterATrulyImpeccableNameText
    text_end
