; PewterSpeechHouse.asm — translated from pret scripts/PewterSpeechHouse.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"

global PewterSpeechHouseGamblerText
global PewterSpeechHouseYoungsterText
global PewterSpeechHouse_Script
global PewterSpeechHouse_TextPointers

extern EnableAutoTextBoxDrawing

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/pewter_speech_house, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/pewter_speech_house.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
PewterSpeechHouse_Script:
    jmp EnableAutoTextBoxDrawing

%assign event_byte -1
%assign event_byte_a -1
PewterSpeechHouse_TextPointers:
    dd PewterSpeechHouseGamblerText
    dd PewterSpeechHouseYoungsterText
PewterSpeechHouseGamblerText:
    text_far _PewterSpeechHouseGamblerText
    text_end
PewterSpeechHouseYoungsterText:
    text_far _PewterSpeechHouseYoungsterText
    text_end
