; PewterGym.asm — translated from pret scripts/PewterGym.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"

%include "assets/script_strings.inc"
%include "assets/trainer_headers.inc"

global PewterGymBrockPostBattle
global PewterGymBrockReceivedBoulderBadgeText
global PewterGymBrockText
global PewterGymBrockWaitTakeThisText
global PewterGymCooltrainerMText
global PewterGymGuideAdviceText
global PewterGymGuideBeginAdviceText
global PewterGymGuideFreeServiceText
global PewterGymGuidePostBattleText
global PewterGymGuidePreAdviceText
global PewterGymGuideText
global PewterGymReceivedTM34Text
global PewterGymResetScripts
global PewterGymScriptReceiveTM34
global PewterGymTM34NoRoomText
global PewterGymText_5c41c
global PewterGym_Script
global PewterGym_ScriptPointers

extern CheckFightingMapTrainers
extern DisableWaitingAfterTextDisplay   ; NOT YET DEFINED IN THE PORT
extern DisplayEnemyTrainerTextAndStartBattle
extern DisplayTextID
extern EnableAutoTextBoxDrawing
extern EndTrainerBattle
extern EngageMapTrainer
extern ExecuteCurMapScriptInTable
extern GiveItem
extern HideObject
extern InitBattleEnemyParameters
extern LoadGymLeaderAndCityName
extern PewterGymCooltrainerMBattleText
extern PewterGymTrainerHeader0
extern PewterGymTrainerHeaders
extern PewterGym_TextPointers   ; NOT YET DEFINED IN THE PORT
extern PrintText
extern SaveEndBattleTextPointers
extern TalkToTrainer
extern TextScriptEnd
extern YesNoChoice

; Script constants — pret defines these via dw_const in this file.
SCRIPT_PEWTERGYM_BROCK_POST_BATTLE             equ 3
TEXT_PEWTERGYM_BROCK_WAIT_TAKE_THIS            equ 4
TEXT_PEWTERGYM_RECEIVED_TM34                   equ 5
TEXT_PEWTERGYM_TM34_NO_ROOM                    equ 6

; pret RAM symbols gb_memmap.inc does not carry. Addresses are rgblink's,
; read from pokeyellow.sym — not inferred.
wBeatGymFlags                                  equ 0xD729
wPewterGymCurScript                            equ 0xD5FB
wPikachuSpawnStateFlags                        equ 0xD471

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/pewter_gym, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/pewter_gym.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
PewterGym_Script:
    mov esi, wCurrentMapScriptFlags
    test byte [ebp + esi], (1 << (BIT_CUR_MAP_LOADED_2))
    pushfd    ; SM83 form writes no flags
        and byte [ebp + esi], ~(1 << (BIT_CUR_MAP_LOADED_2)) & 0xFF
    popfd
    jz .sk_5
        call .LoadNames
.sk_5:
    call EnableAutoTextBoxDrawing
    mov esi, PewterGymTrainerHeaders
    mov edi, PewterGym_ScriptPointers   ; pret: ld de, PewterGym_ScriptPointers — ExecuteCurMapScriptInTable takes it in EDI
    mov al, [ebp + wPewterGymCurScript]
    call ExecuteCurMapScriptInTable
    mov [ebp + wPewterGymCurScript], al
    ret

%assign event_byte -1
%assign event_byte_a -1
.LoadNames:
    mov esi, .CityName
    mov edx, .LeaderName   ; pret: ld de, .LeaderName — LoadGymLeaderAndCityName takes it in EDX
    call LoadGymLeaderAndCityName
    ret

%assign event_byte -1
%assign event_byte_a -1
.CityName:
    TEXT_PewterGym_Script_CityName
.LeaderName:
    TEXT_PewterGym_Script_LeaderName

%assign event_byte -1
%assign event_byte_a -1
PewterGymResetScripts:
    xor al, al
    mov [ebp + wJoyIgnore], al
    mov [ebp + wPewterGymCurScript], al
    mov [ebp + wCurMapScript], al
    ret

%assign event_byte -1
%assign event_byte_a -1
PewterGym_ScriptPointers:
    dd CheckFightingMapTrainers
    dd DisplayEnemyTrainerTextAndStartBattle
    dd EndTrainerBattle
    dd PewterGymBrockPostBattle

%assign event_byte -1
%assign event_byte_a -1
PewterGymBrockPostBattle:
    mov al, [ebp + wIsInBattle]
    cmp al, 0xff
    jz PewterGymResetScripts
    mov al, PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
PewterGymScriptReceiveTM34:
    mov al, TEXT_PEWTERGYM_BROCK_WAIT_TAKE_THIS
    mov [ebp + hTextID], al
    call DisplayTextID
    pushfd    ; SM83 form writes no flags
        SetEvent EVENT_BEAT_BROCK
    popfd
    mov bx, (TM_BIDE << 8) | (1)   ; pret: lb bc, TM_BIDE, 1  (TM34 = $EA)
    call GiveItem
    jae .BagFull
    mov al, TEXT_PEWTERGYM_RECEIVED_TM34
    mov [ebp + hTextID], al
    call DisplayTextID
    SetEvent EVENT_GOT_TM34
    jmp .gymVictory

%assign event_byte -1
%assign event_byte_a -1
.BagFull:
    mov al, TEXT_PEWTERGYM_TM34_NO_ROOM
    mov [ebp + hTextID], al
    call DisplayTextID
.gymVictory:
    mov esi, wObtainedBadges
    or byte [ebp + esi], (1 << (BIT_BOULDERBADGE))
    mov esi, wBeatGymFlags
    or byte [ebp + esi], (1 << (BIT_BOULDERBADGE))
    mov al, TOGGLE_GYM_GUY
    mov [ebp + wToggleableObjectIndex], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call HideObject
    mov al, TOGGLE_ROUTE_22_RIVAL_1
    mov [ebp + wToggleableObjectIndex], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call HideObject
    ResetEvents EVENT_1ST_ROUTE22_RIVAL_BATTLE, EVENT_ROUTE22_RIVAL_WANTS_BATTLE
    SetEvent EVENT_BEAT_PEWTER_GYM_TRAINER_0
    jmp PewterGymResetScripts

; PewterGym_TextPointers (scripts/PewterGym.asm:85-97) — not re-emitted: PewterGymTrainerHeaders is already defined in assets/trainer_headers.inc.

%assign event_byte -1
%assign event_byte_a -1
PewterGymBrockText:
    CheckEvent EVENT_BEAT_BROCK
    jz .beforeBeat
    CheckEventReuseA EVENT_GOT_TM34
    jnz .afterBeat
    jnz .sk_105
        call PewterGymScriptReceiveTM34
.sk_105:
    call DisableWaitingAfterTextDisplay
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.afterBeat:
    mov esi, .PostBattleAdviceText
    call PrintText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.beforeBeat:
    mov esi, .PreBattleText
    call PrintText
    mov esi, wStatusFlags3
    or byte [ebp + esi], (1 << (BIT_TALKED_TO_TRAINER))
    or byte [ebp + esi], (1 << (BIT_PRINT_END_BATTLE_TEXT))
    mov esi, PewterGymBrockReceivedBoulderBadgeText
    mov edx, PewterGymBrockReceivedBoulderBadgeText   ; pret: ld de, PewterGymBrockReceivedBoulderBadgeText — SaveEndBattleTextPointers takes it in EDX
    call SaveEndBattleTextPointers
    mov al, [ebp + hSpriteIndex]
    mov [ebp + wSpriteIndex], al
    call EngageMapTrainer
    call InitBattleEnemyParameters
    mov al, 0x1
    mov [ebp + wGymLeaderNo], al
    xor al, al
    mov [ebp + hJoyHeld], al
    mov al, SCRIPT_PEWTERGYM_BROCK_POST_BATTLE
    mov [ebp + wPewterGymCurScript], al
    mov [ebp + wCurMapScript], al
.done:
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.PreBattleText:
    text_far _PewterGymBrockPreBattleText
    text_end
.PostBattleAdviceText:
    text_far _PewterGymBrockPostBattleAdviceText
    text_end
PewterGymBrockWaitTakeThisText:
    text_far _PewterGymBrockWaitTakeThisText
    text_end
PewterGymReceivedTM34Text:
    text_far _PewterGymReceivedTM34Text
    sound_get_item_1
    text_far _TM34ExplanationText
    text_end
PewterGymTM34NoRoomText:
    text_far _PewterGymTM34NoRoomText
    text_end
PewterGymBrockReceivedBoulderBadgeText:
    text_far _PewterGymBrockReceivedBoulderBadgeText
    sound_get_item_1
    text_far _PewterGymBrockBoulderBadgeInfoText
    text_end

%assign event_byte -1
%assign event_byte_a -1
PewterGymCooltrainerMText:
    mov esi, PewterGymTrainerHeader0
    call TalkToTrainer
    jmp TextScriptEnd

; PewterGymCooltrainerMBattleText (scripts/PewterGym.asm:170-179) — not re-emitted: PewterGymCooltrainerMBattleText is already defined in assets/trainer_headers.inc.

%assign event_byte -1
%assign event_byte_a -1
PewterGymGuideText:
    mov al, [ebp + wBeatGymFlags]
    test al, (1 << (BIT_BOULDERBADGE))
    jnz .afterBeat
    mov esi, PewterGymGuidePreAdviceText
    call PrintText
    call YesNoChoice
    mov al, [ebp + wCurrentMenuItem]
    test al, al
    jnz .PewterGymGuideBeginAdviceText
    mov al, [ebp + wPikachuSpawnStateFlags]
    test al, (1 << (BIT_PIKACHU_SPAWN_STARTER))
    jnz .asm_5c3fa
    mov esi, PewterGymGuideBeginAdviceText
    call PrintText
    jmp .PewterGymGuideAdviceText

%assign event_byte -1
%assign event_byte_a -1
.PewterGymGuideBeginAdviceText:
    mov esi, PewterGymGuideFreeServiceText
    call PrintText
.PewterGymGuideAdviceText:
    mov esi, PewterGymGuideAdviceText
    call PrintText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.afterBeat:
    mov esi, PewterGymGuidePostBattleText
    call PrintText
.done:
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.asm_5c3fa:
    mov esi, PewterGymText_5c41c
    call PrintText
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
PewterGymGuidePreAdviceText:
    text_far _PewterGymGuidePreAdviceText
    text_end
PewterGymGuideBeginAdviceText:
    text_far _PewterGymGuideBeginAdviceText
    text_end
PewterGymGuideAdviceText:
    text_far _PewterGymGuideAdviceText
    text_end
PewterGymGuideFreeServiceText:
    text_far _PewterGymGuideFreeServiceText
    text_end
PewterGymGuidePostBattleText:
    text_far _PewterGymGuidePostBattleText
    text_end
PewterGymText_5c41c:
    text_far _PewterGymGuyText
    text_end
