; PokemonTower7F.asm — translated from pret scripts/PokemonTower7F.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"

%include "assets/audio_constants.inc"
%include "assets/map_dims.inc"

global PokemonTower7FScript0
global PokemonTower7FJessieJamesEndBattleText
global PokemonTower7FJessieJamesText
global PokemonTower7FMovementData_60d7a
global PokemonTower7FMovementData_60d7b
global PokemonTower7FMrFujiText
global PokemonTower7FScript1
global PokemonTower7FScript10
global PokemonTower7FScript2
global PokemonTower7FScript3
global PokemonTower7FScript4
global PokemonTower7FScript5
global PokemonTower7FScript6
global PokemonTower7FScript7
global PokemonTower7FScript8
global PokemonTower7FScript9
global PokemonTower7FScript_60d2a
global PokemonTower7FScript_HideObject
global PokemonTower7FScript_ShowObject
global PokemonTower7FSetDefaultScript
global PokemonTower7FSetScript
global PokemonTower7FText4
global PokemonTower7FText5
global PokemonTower7FText6
global PokemonTower7FWarpToMrFujiHouseScript
global PokemonTower7F_Script
global PokemonTower7F_ScriptPointers
global PokemonTower7F_TextPointers

extern CallFunctionInTable
extern Delay3
extern DelayFrames
extern DisplayTextID
extern EmotionBubble
extern EnableAutoTextBoxDrawing
extern GBFadeInFromBlack
extern GBFadeOutToBlack
extern HideObject
extern MoveSprite
extern PlayDefaultMusic
extern PlayMusic
extern PrintText
extern SaveEndBattleTextPointers
extern ShowObject
extern StopAllMusic
extern TextScriptEnd
extern UpdateSprites

; Script constants — pret defines these via dw_const in this file.
SCRIPT_POKEMONTOWER7F_SCRIPT0                  equ 0
SCRIPT_POKEMONTOWER7F_SCRIPT1                  equ 1
SCRIPT_POKEMONTOWER7F_SCRIPT2                  equ 2
SCRIPT_POKEMONTOWER7F_SCRIPT5                  equ 5
SCRIPT_POKEMONTOWER7F_SCRIPT8                  equ 8
SCRIPT_POKEMONTOWER7F_SCRIPT9                  equ 9
SCRIPT_POKEMONTOWER7F_SCRIPT10                 equ 10
SCRIPT_POKEMONTOWER7F_WARP_TO_MR_FUJI_HOUSE    equ 11
TEXT_POKEMONTOWER7F_TEXT4                      equ 4
TEXT_POKEMONTOWER7F_TEXT5                      equ 5
TEXT_POKEMONTOWER7F_TEXT6                      equ 6

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/pokemon_tower_7f, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/pokemon_tower_7f.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7F_Script:
    call EnableAutoTextBoxDrawing
    mov esi, PokemonTower7F_ScriptPointers
    mov al, [ebp + wPokemonTower7FCurScript]
    call CallFunctionInTable
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FSetDefaultScript:
    xor al, al
    mov [ebp + wJoyIgnore], al
PokemonTower7FSetScript:
    mov [ebp + wPokemonTower7FCurScript], al
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7F_ScriptPointers:
    dd PokemonTower7FScript0
    dd PokemonTower7FScript1
    dd PokemonTower7FScript2
    dd PokemonTower7FScript3
    dd PokemonTower7FScript4
    dd PokemonTower7FScript5
    dd PokemonTower7FScript6
    dd PokemonTower7FScript7
    dd PokemonTower7FScript8
    dd PokemonTower7FScript9
    dd PokemonTower7FScript10
    dd PokemonTower7FWarpToMrFujiHouseScript

%assign event_byte -1
%assign event_byte_a -1
; LABEL-DROP REPAIR: the body below is the transpiler's own correct output; it emitted
; NO label for it because pret guards the routine's first lines with IF DEF(_DEBUG)
; and the tool consumed the label with the stripped block. Only the pret label is
; restored. Same mode as the three DefaultScripts fixed in 3b4a7ed48's follow-up.
PokemonTower7FScript0:
    CheckEvent EVENT_BEAT_POKEMONTOWER_7_JESSIE_JAMES
    jnz .sk_36
        call PokemonTower7FScript_60d2a
.sk_36:
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FScript_60d2a:
    mov al, [ebp + wYCoord]
    cmp al, 0xc
    jz .nr_42
        ret
.nr_42:
    ResetEvent EVENT_POKEMONTOWER_7_JESSIE_JAMES_ON_LEFT
    mov al, [ebp + wXCoord]
    cmp al, 0xa
    jz .asm_60d47
    mov al, [ebp + wXCoord]
    cmp al, 0xb
    jz .nr_49
        ret
.nr_49:
    SetEvent EVENT_POKEMONTOWER_7_JESSIE_JAMES_ON_LEFT
.asm_60d47:
    call StopAllMusic
    mov bl, 32
    mov al, MUSIC_MEET_JESSIE_JAMES
    call PlayMusic
    xor al, al
    mov [ebp + hJoyHeld], al
    mov al, PAD_SELECT | PAD_START | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, 65
    call PokemonTower7FScript_ShowObject
    mov al, 66
    call PokemonTower7FScript_ShowObject
    mov al, 0x1
    mov [ebp + wDoNotWaitForButtonPressAfterDisplayingText], al
    mov al, TEXT_POKEMONTOWER7F_TEXT4
    mov [ebp + hTextID], al
    call DisplayTextID
    mov al, PAD_BUTTONS | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, SCRIPT_POKEMONTOWER7F_SCRIPT1
    call PokemonTower7FSetScript
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FMovementData_60d7a:
    db 0x4
PokemonTower7FMovementData_60d7b:
    db 0x4
    db 0x4
    db 0x4
    db 0xFF

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FScript1:
    mov edi, PokemonTower7FMovementData_60d7b   ; pret: ld de, PokemonTower7FMovementData_60d7b — MoveSprite takes it in EDI
    CheckEvent EVENT_POKEMONTOWER_7_JESSIE_JAMES_ON_LEFT
    jz .asm_60d8c
    mov edi, PokemonTower7FMovementData_60d7a   ; pret: ld de, PokemonTower7FMovementData_60d7a — MoveSprite takes it in EDI
.asm_60d8c:
    mov al, 1
    mov [ebp + hSpriteIndex], al
    call MoveSprite
    mov al, PAD_BUTTONS | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, SCRIPT_POKEMONTOWER7F_SCRIPT2
    call PokemonTower7FSetScript
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FScript2:
    mov al, PAD_BUTTONS | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, [ebp + wStatusFlags5]
    test al, (1 << (BIT_SCRIPTED_NPC_MOVEMENT))
    jz .nr_103
        ret
.nr_103:
PokemonTower7FScript3:
    mov al, SPRITE_FACING_DOWN
    mov [ebp + wSprite01StateData1FacingDirection], al
    CheckEvent EVENT_POKEMONTOWER_7_JESSIE_JAMES_ON_LEFT
    jz .asm_60dba
    mov al, SPRITE_FACING_RIGHT
    mov [ebp + wSprite01StateData1FacingDirection], al
.asm_60dba:
    mov al, 0x2
    mov [ebp + wSprite01StateData1MovementStatus], al
PokemonTower7FScript4:
    mov edi, PokemonTower7FMovementData_60d7a   ; pret: ld de, PokemonTower7FMovementData_60d7a — MoveSprite takes it in EDI
    CheckEvent EVENT_POKEMONTOWER_7_JESSIE_JAMES_ON_LEFT
    jz .asm_60dcc
    mov edi, PokemonTower7FMovementData_60d7b   ; pret: ld de, PokemonTower7FMovementData_60d7b — MoveSprite takes it in EDI
.asm_60dcc:
    mov al, 2
    mov [ebp + hSpriteIndex], al
    call MoveSprite
    mov al, PAD_BUTTONS | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, SCRIPT_POKEMONTOWER7F_SCRIPT5
    call PokemonTower7FSetScript
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FScript5:
    mov al, PAD_BUTTONS | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, [ebp + wStatusFlags5]
    test al, (1 << (BIT_SCRIPTED_NPC_MOVEMENT))
    jz .nr_134
        ret
.nr_134:
PokemonTower7FScript6:
    mov al, 0x2
    mov [ebp + wSprite02StateData1MovementStatus], al
    mov al, SPRITE_FACING_LEFT
    mov [ebp + wSprite02StateData1FacingDirection], al
    CheckEvent EVENT_POKEMONTOWER_7_JESSIE_JAMES_ON_LEFT
    jz .asm_60dff
    mov al, SPRITE_FACING_DOWN
    mov [ebp + wSprite02StateData1FacingDirection], al
.asm_60dff:
    call Delay3
    mov al, PAD_SELECT | PAD_START | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, TEXT_POKEMONTOWER7F_TEXT5
    mov [ebp + hTextID], al
    call DisplayTextID
PokemonTower7FScript7:
    mov esi, wStatusFlags3
    or byte [ebp + esi], (1 << (BIT_TALKED_TO_TRAINER))
    or byte [ebp + esi], (1 << (BIT_PRINT_END_BATTLE_TEXT))
    mov esi, PokemonTower7FJessieJamesEndBattleText
    mov edx, PokemonTower7FJessieJamesEndBattleText   ; pret: ld de, PokemonTower7FJessieJamesEndBattleText — SaveEndBattleTextPointers takes it in EDX
    call SaveEndBattleTextPointers
    mov al, OPP_ROCKET
    mov [ebp + wCurOpponent], al
    mov al, 0x2c
    mov [ebp + wTrainerNo], al
    xor al, al
    mov [ebp + hJoyHeld], al
    mov [ebp + wJoyIgnore], al
    mov al, SCRIPT_POKEMONTOWER7F_SCRIPT8
    call PokemonTower7FSetScript
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FScript8:
    mov al, PAD_BUTTONS | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, [ebp + wIsInBattle]
    cmp al, 0xff
    jz PokemonTower7FSetDefaultScript
    mov al, 0x2
    mov [ebp + wSprite01StateData1MovementStatus], al
    mov [ebp + wSprite02StateData1MovementStatus], al
    xor al, al
    mov [ebp + wSprite01StateData1FacingDirection], al
    mov [ebp + wSprite02StateData1FacingDirection], al
    mov al, PAD_SELECT | PAD_START | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, 0x1
    mov [ebp + wDoNotWaitForButtonPressAfterDisplayingText], al
    mov al, TEXT_POKEMONTOWER7F_TEXT6
    mov [ebp + hTextID], al
    call DisplayTextID
    xor al, al
    mov [ebp + wDoNotWaitForButtonPressAfterDisplayingText], al
    call StopAllMusic
    mov bl, 32
    mov al, MUSIC_MEET_JESSIE_JAMES
    call PlayMusic
    mov al, PAD_BUTTONS | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, SCRIPT_POKEMONTOWER7F_SCRIPT9
    call PokemonTower7FSetScript
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FScript9:
    mov al, PAD_BUTTONS | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    call GBFadeOutToBlack
    mov al, 65
    call PokemonTower7FScript_HideObject
    mov al, 66
    call PokemonTower7FScript_HideObject
    call UpdateSprites
    call Delay3
    call GBFadeInFromBlack
    mov al, SCRIPT_POKEMONTOWER7F_SCRIPT10
    call PokemonTower7FSetScript
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FScript10:
    call PlayDefaultMusic
    xor al, al
    mov [ebp + hJoyHeld], al
    mov [ebp + wJoyIgnore], al
    SetEvent EVENT_BEAT_POKEMONTOWER_7_JESSIE_JAMES
    mov al, SCRIPT_POKEMONTOWER7F_SCRIPT0
    call PokemonTower7FSetScript
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FScript_ShowObject:
    mov [ebp + wToggleableObjectIndex], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call ShowObject
    call UpdateSprites
    call Delay3
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FScript_HideObject:
    mov [ebp + wToggleableObjectIndex], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call HideObject
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FWarpToMrFujiHouseScript:
    mov al, PAD_BUTTONS | PAD_CTRL_PAD
    mov [ebp + wJoyIgnore], al
    mov al, TOGGLE_POKEMON_TOWER_7F_MR_FUJI
    mov [ebp + wToggleableObjectIndex], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call HideObject
    mov al, SPRITE_FACING_UP
    mov [ebp + wSpritePlayerStateData1FacingDirection], al
    mov al, MR_FUJIS_HOUSE
    mov [ebp + hWarpDestinationMap], al
    mov al, 0x1
    mov [ebp + wDestinationWarpID], al
    mov al, LAVENDER_TOWN
    mov [ebp + wLastMap], al
    mov esi, wStatusFlags3
    or byte [ebp + esi], (1 << (BIT_WARP_FROM_CUR_SCRIPT))
    mov al, SCRIPT_POKEMONTOWER7F_SCRIPT0
    mov [ebp + wPokemonTower7FCurScript], al
    ret

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7F_TextPointers:
    dd PokemonTower7FJessieJamesText
    dd PokemonTower7FJessieJamesText
    dd PokemonTower7FMrFujiText
    dd PokemonTower7FText4
    dd PokemonTower7FText5
    dd PokemonTower7FText6
PokemonTower7FJessieJamesText:
    text_end
PokemonTower7FText4:
    text_far _PokemonTowerJessieJamesText1

%assign event_byte -1
%assign event_byte_a -1
    mov bl, 10
    call DelayFrames
    mov al, PLAYER_DIR_UP
    mov [ebp + wPlayerMovingDirection], al
    mov al, 0x0
    mov [ebp + wEmotionBubbleSpriteIndex], al
    mov al, EXCLAMATION_BUBBLE
    mov [ebp + wWhichEmotionBubble], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call EmotionBubble
    mov bl, 20
    call DelayFrames
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FText5:
    text_far _PokemonTowerJessieJamesText2
    text_end
PokemonTower7FJessieJamesEndBattleText:
    text_far _PokemonTowerJessieJamesText3
    text_end
PokemonTower7FText6:
    text_far _PokemonTowerJessieJamesText4

%assign event_byte -1
%assign event_byte_a -1
    mov bl, 64
    call DelayFrames
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
PokemonTower7FMrFujiText:
    mov esi, .RescueText
    call PrintText
    SetEvent EVENT_RESCUED_MR_FUJI
    SetEvent EVENT_RESCUED_MR_FUJI_2
    mov al, TOGGLE_MR_FUJIS_HOUSE_MR_FUJI
    mov [ebp + wToggleableObjectIndex], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call ShowObject
    mov al, TOGGLE_SAFFRON_CITY_E
    mov [ebp + wToggleableObjectIndex], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call HideObject
    mov al, TOGGLE_SAFFRON_CITY_F
    mov [ebp + wToggleableObjectIndex], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call ShowObject
    mov al, SCRIPT_POKEMONTOWER7F_WARP_TO_MR_FUJI_HOUSE
    mov [ebp + wPokemonTower7FCurScript], al
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.RescueText:
    text_far _PokemonTower7FMrFujiRescueText
    text_end
