; Route2TradeHouse.asm — translated from pret scripts/Route2TradeHouse.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"

global Route2TradeHouseGameboyKidText
global Route2TradeHouseScientistText
global Route2TradeHouse_Script
global Route2TradeHouse_TextPointers

extern DoInGameTradeDialogue
extern EnableAutoTextBoxDrawing
extern TextScriptEnd
%ifdef DEBUG_TRADE_GOLDEN
extern trade_golden_dump_armed      ; src/debug/debug_dump.asm — consumed by OverworldLoop
%endif

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/route_2_trade_house, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/Route2TradeHouse.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
Route2TradeHouse_Script:
    jmp EnableAutoTextBoxDrawing

%assign event_byte -1
%assign event_byte_a -1
Route2TradeHouse_TextPointers:
    dd Route2TradeHouseScientistText
    dd Route2TradeHouseGameboyKidText
Route2TradeHouseScientistText:
    text_far _Route2TradeHouseScientistText
    text_end

%assign event_byte -1
%assign event_byte_a -1
Route2TradeHouseGameboyKidText:
    mov al, TRADE_FOR_MILES
    mov [ebp + wWhichTrade], al
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call DoInGameTradeDialogue
%ifdef DEBUG_TRADE_GOLDEN
    ; in_game_trade golden photograph: DoInGameTradeDialogue returning means
    ; the whole flow (dialogue, YES/NO confirm, party-menu CLEFAIRY pick,
    ; ConnectCableText, InternalClockTradeAnim, TradedForText, Thanks1Text)
    ; ran — but its tail `jp PrintText` returns with Thanks1Text still ON
    ; SCREEN (measured 2026-08-23: dumping here photographed the open box,
    ; while the mGBA golden dumps after the box is dismissed). So ARM the dump
    ; instead: OverworldLoop's post-interaction A-release path takes the
    ; photograph after hide_window + LoadCurrentMapView — the golden's stable
    ; idle overworld frame.
    mov byte [trade_golden_dump_armed], 1
%endif
    jmp TextScriptEnd
