; SafariZoneSecretHouse.asm — translated from pret scripts/SafariZoneSecretHouse.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"


global SafariZoneSecretHouseFishingGuruText
global SafariZoneSecretHouse_Script
global SafariZoneSecretHouse_TextPointers

extern EnableAutoTextBoxDrawing
extern GiveItem
extern PrintText
extern TextScriptEnd

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/safari_zone_secret_house, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/safari_zone_secret_house.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
SafariZoneSecretHouse_Script:
    jmp EnableAutoTextBoxDrawing

%assign event_byte -1
%assign event_byte_a -1
SafariZoneSecretHouse_TextPointers:
    dd SafariZoneSecretHouseFishingGuruText

%assign event_byte -1
%assign event_byte_a -1
SafariZoneSecretHouseFishingGuruText:
    CheckEvent EVENT_GOT_HM03
    jnz .got_item
    mov esi, .YouHaveWonText
    call PrintText
    mov bx, (HM_SURF << 8) | (1)   ; pret: lb bc, HM_SURF, 1  (HM03 = $C6)
    call GiveItem
    jae .bag_full
    mov esi, .ReceivedHM03Text
    call PrintText
    SetEvent EVENT_GOT_HM03
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.bag_full:
    mov esi, .HM03NoRoomText
    call PrintText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.got_item:
    mov esi, .HM03ExplanationText
    call PrintText
.done:
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.YouHaveWonText:
    text_far _SafariZoneSecretHouseFishingGuruYouHaveWonText
    text_end
.ReceivedHM03Text:
    text_far _SafariZoneSecretHouseFishingGuruReceivedHM03Text
    sound_get_item_1
    text_end
.HM03ExplanationText:
    text_far _SafariZoneSecretHouseFishingGuruHM03ExplanationText
    text_end
.HM03NoRoomText:
    text_far _SafariZoneSecretHouseFishingGuruHM03NoRoomText
    text_end
