; SilphCo4F.asm — translated from pret scripts/SilphCo4F.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"

%include "assets/trainer_headers.inc"

global SilphCo4FGateCallbackScript
global SilphCo4FRocket1Text
global SilphCo4FRocket2Text
global SilphCo4FScientistText
global SilphCo4FSilphWorkerMText
global SilphCo4FUnlockedDoorEventScript
global SilphCo4F_Script
global SilphCo4F_SetCardKeyDoorYScript

extern EnableAutoTextBoxDrawing
extern ExecuteCurMapScriptInTable
extern ReplaceTileBlock
extern SilphCo4FRocket1BattleText
extern SilphCo4FRocket2BattleText
extern SilphCo4FScientistBattleText
extern SilphCo4F_ScriptPointers   ; NOT YET DEFINED IN THE PORT
extern SilphCo4TrainerHeader0
extern SilphCo4TrainerHeader1
extern SilphCo4TrainerHeader2
extern SilphCo4TrainerHeaders
extern SilphCo6FBeatGiovanniPrintDEOrPrintHLScript
extern TalkToTrainer
extern TextScriptEnd

; pret RAM symbols gb_memmap.inc does not carry. Addresses are rgblink's,
; read from pokeyellow.sym — not inferred.
hUnlockedSilphCoDoors                          equ 0xFFE0
wSilphCo4FCurScript                            equ 0xD644

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/silph_co_4f, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/silph_co_4f.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
SilphCo4F_Script:
    call SilphCo4FGateCallbackScript
    call EnableAutoTextBoxDrawing
    mov esi, SilphCo4TrainerHeaders
    mov edi, SilphCo4F_ScriptPointers   ; pret: ld de, SilphCo4F_ScriptPointers — ExecuteCurMapScriptInTable takes it in EDI
    mov al, [ebp + wSilphCo4FCurScript]
    call ExecuteCurMapScriptInTable
    mov [ebp + wSilphCo4FCurScript], al
    ret

%assign event_byte -1
%assign event_byte_a -1
SilphCo4FGateCallbackScript:
    mov esi, wCurrentMapScriptFlags
    test byte [ebp + esi], (1 << (BIT_CUR_MAP_LOADED_1))
    pushfd    ; SM83 form writes no flags
        and byte [ebp + esi], ~(1 << (BIT_CUR_MAP_LOADED_1)) & 0xFF
    popfd
    jnz .nr_15
        ret
.nr_15:
    mov esi, .GateCoordinates
    call SilphCo4F_SetCardKeyDoorYScript
    call SilphCo4FUnlockedDoorEventScript
    CheckEvent EVENT_SILPH_CO_4_UNLOCKED_DOOR1
    jnz .unlock_door1
    pushfd
    push eax
    mov al, 0x54
    mov [ebp + wNewTileBlockID], al
    mov bx, ((6) << 8) | (2)
; DEVIATION{class=banking; pret=macros/predef.asm:predef; behavior=Predef dispatch replaced by a direct call, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    call ReplaceTileBlock
    pop eax
    popfd
.unlock_door1:
    CheckEventAfterBranchReuseA EVENT_SILPH_CO_4_UNLOCKED_DOOR2, EVENT_SILPH_CO_4_UNLOCKED_DOOR1
    jz .nr_29
        ret
.nr_29:
    mov al, 0x54
    mov [ebp + wNewTileBlockID], al
    mov bx, ((4) << 8) | (6)
; DEVIATION{class=banking; pret=macros/predef.asm:predef_jump; behavior=Predef dispatch replaced by a direct jmp, and A is left holding whatever the callee left rather than pret's parent ROM bank; evidence=pret Predef saves hLoadedROMBank with push af and restores it with pop af before returning so A holds a BANK NUMBER on return - not the predef id - and the flat DPMI model has no banks for that value to mean anything, plus dataflow shows no direct read of A after this site; lifetime=retired when PredefPointers is ported}
    jmp ReplaceTileBlock

%assign event_byte -1
%assign event_byte_a -1
.GateCoordinates:
    db 6, 2
    db 4, 6
    db -1

%assign event_byte -1
%assign event_byte_a -1
SilphCo4F_SetCardKeyDoorYScript:
    push esi
    mov esi, wCardKeyDoorY
    mov al, [ebp + esi]
    lea esi, [esi+1]
    mov bh, al
    mov al, [ebp + esi]
    mov bl, al
    xor al, al
    mov [ebp + hUnlockedSilphCoDoors], al
    pop esi
.loop_check_doors:
    mov al, [esi]
    lea esi, [esi+1]
    cmp al, 0xff
    jz .exit_loop
    push esi
    mov esi, hUnlockedSilphCoDoors
    inc byte [ebp + esi]
    pop esi
    cmp al, bh
    jz .check_y_coord
    lea esi, [esi+1]
    jmp .loop_check_doors

%assign event_byte -1
%assign event_byte_a -1
.check_y_coord:
    mov al, [esi]
    lea esi, [esi+1]
    cmp al, bl
    jnz .loop_check_doors
    mov esi, wCardKeyDoorY
    xor al, al
    mov [ebp + esi], al
    lea esi, [esi+1]
    mov [ebp + esi], al
    ret

%assign event_byte -1
%assign event_byte_a -1
.exit_loop:
    xor al, al
    mov [ebp + hUnlockedSilphCoDoors], al
    ret

%assign event_byte -1
%assign event_byte_a -1
SilphCo4FUnlockedDoorEventScript:
    mov esi, wEventFlags + EVENT_BYTE(EVENT_SILPH_CO_4_UNLOCKED_DOOR1)
    %assign event_byte EVENT_BYTE(EVENT_SILPH_CO_4_UNLOCKED_DOOR1)
    mov al, [ebp + hUnlockedSilphCoDoors]
    test al, al
    jnz .nr_80
        ret
.nr_80:
    cmp al, 0x1
    jnz .unlock_door1
    SetEventReuseHL EVENT_SILPH_CO_4_UNLOCKED_DOOR1
    ret

%assign event_byte -1
%assign event_byte_a -1
.unlock_door1:
    SetEventAfterBranchReuseHL EVENT_SILPH_CO_4_UNLOCKED_DOOR2, EVENT_SILPH_CO_4_UNLOCKED_DOOR1
    ret

; SilphCo4F_ScriptPointers (scripts/SilphCo4F.asm:90-113) — not re-emitted: SilphCo4TrainerHeaders is already defined in assets/trainer_headers.inc.

%assign event_byte -1
%assign event_byte_a -1
SilphCo4FSilphWorkerMText:
    mov esi, .ImHidingText
    mov edi, .TeamRocketIsGoneText   ; pret: ld de — callee takes it in EDI (abi.json)
    call SilphCo6FBeatGiovanniPrintDEOrPrintHLScript
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.ImHidingText:
    text_far _SilphCo4FSilphWorkerMImHidingText
    text_end
.TeamRocketIsGoneText:
    text_far _SilphCo4FSilphWorkerMTeamRocketIsGoneText
    text_end

%assign event_byte -1
%assign event_byte_a -1
SilphCo4FRocket1Text:
    mov esi, SilphCo4TrainerHeader0
    call TalkToTrainer
    jmp TextScriptEnd

; SilphCo4FRocket1BattleText (scripts/SilphCo4F.asm:137-146) — not re-emitted: SilphCo4FRocket1BattleText is already defined in assets/trainer_headers.inc.

%assign event_byte -1
%assign event_byte_a -1
SilphCo4FScientistText:
    mov esi, SilphCo4TrainerHeader1
    call TalkToTrainer
    jmp TextScriptEnd

; SilphCo4FScientistBattleText (scripts/SilphCo4F.asm:155-164) — not re-emitted: SilphCo4FScientistBattleText is already defined in assets/trainer_headers.inc.

%assign event_byte -1
%assign event_byte_a -1
SilphCo4FRocket2Text:
    mov esi, SilphCo4TrainerHeader2
    call TalkToTrainer
    jmp TextScriptEnd

; SilphCo4FRocket2BattleText (scripts/SilphCo4F.asm:173-182) — not re-emitted: SilphCo4FRocket2BattleText is already defined in assets/trainer_headers.inc.
