; SSAnneCaptainsRoom.asm — translated from pret scripts/SSAnneCaptainsRoom.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"

%include "assets/audio_constants.inc"

global SSAnneCaptainsRoomCaptainHM01NoRoomText
global SSAnneCaptainsRoomCaptainIFeelMuchBetterText
global SSAnneCaptainsRoomCaptainNotSickAnymoreText
global SSAnneCaptainsRoomCaptainReceivedHM01Text
global SSAnneCaptainsRoomCaptainText
global SSAnneCaptainsRoomEventScript
global SSAnneCaptainsRoomRubCaptainsBackText
global SSAnneCaptainsRoomSeasickBookText
global SSAnneCaptainsRoomTrashText
global SSAnneCaptainsRoom_Script
global SSAnneCaptainsRoom_TextPointers

extern EnableAutoTextBoxDrawing
extern GiveItem
extern PlayDefaultMusic
extern PlaySound
extern PrintText
extern StopAllMusic
extern TextScriptEnd

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/ss_anne_captains_room, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/SSAnneCaptainsRoom.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
SSAnneCaptainsRoom_Script:
    call SSAnneCaptainsRoomEventScript
    jmp EnableAutoTextBoxDrawing

%assign event_byte -1
%assign event_byte_a -1
SSAnneCaptainsRoomEventScript:
    CheckEvent EVENT_GOT_HM01
    jz .nr_7
        ret
.nr_7:
    mov esi, wStatusFlags3
    or byte [ebp + esi], (1 << (BIT_NO_NPC_FACE_PLAYER))
    ret

%assign event_byte -1
%assign event_byte_a -1
SSAnneCaptainsRoom_TextPointers:
    dd SSAnneCaptainsRoomCaptainText
    dd SSAnneCaptainsRoomTrashText
    dd SSAnneCaptainsRoomSeasickBookText

%assign event_byte -1
%assign event_byte_a -1
SSAnneCaptainsRoomCaptainText:
    CheckEvent EVENT_GOT_HM01
    jnz .got_item
    mov esi, SSAnneCaptainsRoomRubCaptainsBackText
    call PrintText
    mov esi, SSAnneCaptainsRoomCaptainIFeelMuchBetterText
    call PrintText
    mov bx, (HM_CUT << 8) | (1)   ; pret: lb bc, HM_CUT, 1  (HM01 = $C4)
    call GiveItem
    jae .bag_full
    mov esi, SSAnneCaptainsRoomCaptainReceivedHM01Text
    call PrintText
    SetEvent EVENT_GOT_HM01
    mov esi, wStatusFlags3
    and byte [ebp + esi], ~(1 << (BIT_NO_NPC_FACE_PLAYER)) & 0xFF
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.bag_full:
    mov esi, SSAnneCaptainsRoomCaptainHM01NoRoomText
    call PrintText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.got_item:
    mov esi, SSAnneCaptainsRoomCaptainNotSickAnymoreText
    call PrintText
.done:
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
SSAnneCaptainsRoomRubCaptainsBackText:
    text_far _SSAnneCaptainsRoomRubCaptainsBackText

%assign event_byte -1
%assign event_byte_a -1
    mov al, [ebp + wAudioROMBank]
    cmp al, 31
    mov [ebp + wAudioSavedROMBank], al
    jnz .not_audio_engine_3
    call StopAllMusic
    mov al, 2
    mov [ebp + wAudioROMBank], al
.not_audio_engine_3:
    mov al, MUSIC_PKMN_HEALED
    mov [ebp + wNewSoundID], al
    call PlaySound
.loop:
    mov al, [ebp + wChannelSoundIDs]
    cmp al, MUSIC_PKMN_HEALED
    jz .loop
    call PlayDefaultMusic
    SetEvent EVENT_RUBBED_CAPTAINS_BACK
    mov esi, wStatusFlags3
    and byte [ebp + esi], ~(1 << (BIT_NO_NPC_FACE_PLAYER)) & 0xFF
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
SSAnneCaptainsRoomCaptainIFeelMuchBetterText:
    text_far _SSAnneCaptainsRoomCaptainIFeelMuchBetterText
    text_end
SSAnneCaptainsRoomCaptainReceivedHM01Text:
    text_far _SSAnneCaptainsRoomCaptainReceivedHM01Text
    sound_get_key_item
    text_end
SSAnneCaptainsRoomCaptainNotSickAnymoreText:
    text_far _SSAnneCaptainsRoomCaptainNotSickAnymoreText
    text_end
SSAnneCaptainsRoomCaptainHM01NoRoomText:
    text_far _SSAnneCaptainsRoomCaptainHM01NoRoomText
    text_end
SSAnneCaptainsRoomTrashText:
    text_far _SSAnneCaptainsRoomTrashText
    text_end
SSAnneCaptainsRoomSeasickBookText:
    text_far _SSAnneCaptainsRoomSeasickBookText
    text_end
