; VermilionDock.asm — translated from pret scripts/VermilionDock.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"

%include "assets/audio_constants.inc"
%include "assets/map_dims.inc"
%include "coords.inc"

global VermilionDockOAMBlock
global VermilionDockUnusedText
global VermilionDock_AnimSmokePuffDriftRight
global VermilionDock_EmitSmokePuff
global VermilionDock_EraseSSAnne
global VermilionDock_Script
global VermilionDock_TextPointers

extern CopyScreenTileBufferToVRAM
extern CopyVideoData
extern Delay3
extern DelayFrames
extern EnableAutoTextBoxDrawing
extern FillMemory
extern LoadPlayerSpriteGraphics
extern LoadSmokeTileFourTimes
extern PlayMusic
extern PlaySound
extern PlaySoundWaitForCurrent
extern StopAllMusic
extern UpdateCGBPal_OBP1
extern VermilionDockSSAnneLeavesScript   ; NOT YET DEFINED IN THE PORT
extern VermilionDock_SyncScrollWithLY   ; NOT YET DEFINED IN THE PORT
extern WriteOAMBlock

; pret RAM symbols gb_memmap.inc does not carry. Addresses are rgblink's,
; read from pokeyellow.sym — not inferred.
wSSAnneSmokeDriftAmount                        equ 0xCD3D
wSSAnneSmokeX                                  equ 0xCD3E
wShadowOAMSprite04XCoord                       equ 0xC311
wSpritePlayerStateData2MovementByte1           equ 0xC206
wVermilionDockTileMapBuffer                    equ 0xCC5B
wVermilionDockTileMapBufferEnd                 equ 0xCD0F

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/vermilion_dock, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/vermilion_dock.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
VermilionDock_Script:
    call EnableAutoTextBoxDrawing
    mov esi, wEventFlags + EVENT_BYTE(EVENT_STARTED_WALKING_OUT_OF_DOCK)
    test byte [ebp + esi], EVENT_MASK(EVENT_STARTED_WALKING_OUT_OF_DOCK)
    jnz .walking_out_of_dock
    CheckEventReuseHL EVENT_GOT_HM01
    jnz .nr_6
        ret
.nr_6:
    mov al, [ebp + wDestinationWarpID]
    cmp al, 0x1
    jz .nr_9
        ret
.nr_9:
    CheckEventReuseHL EVENT_SS_ANNE_LEFT
    jz VermilionDockSSAnneLeavesScript
    SetEventReuseHL EVENT_STARTED_WALKING_OUT_OF_DOCK
    call Delay3
    mov esi, wStatusFlags5
    or byte [ebp + esi], (1 << (BIT_SCRIPTED_MOVEMENT_STATE))
    mov esi, wSimulatedJoypadStatesEnd
    mov al, PAD_UP
    mov [ebp + esi], al
    lea esi, [esi+1]
    mov [ebp + esi], al
    lea esi, [esi+1]
    mov [ebp + esi], al
    mov al, 0x3
    mov [ebp + wSimulatedJoypadStatesIndex], al
    xor al, al
    mov [ebp + wSpritePlayerStateData2MovementByte1], al
    mov [ebp + wOverrideSimulatedJoypadStatesMask], al
    dec al
    mov [ebp + wJoyIgnore], al
    ret

%assign event_byte -1
%assign event_byte_a -1
.walking_out_of_dock:
    CheckEventAfterBranchReuseHL EVENT_WALKED_OUT_OF_DOCK, EVENT_STARTED_WALKING_OUT_OF_DOCK
    jz .nr_31
        ret
.nr_31:
    mov al, [ebp + wSimulatedJoypadStatesIndex]
    test al, al
    jz .nr_34
        ret
.nr_34:
    mov [ebp + wJoyIgnore], al
    SetEventReuseHL EVENT_WALKED_OUT_OF_DOCK
    ret

; ---------------------------------------------------------------------------
; BAIL[screen-coord-projection] VermilionDockSSAnneLeavesScript (scripts/VermilionDock.asm:40-122) — at scripts/VermilionDock.asm:54: hlcoord 0, 10
; NO SYMBOL IS DEFINED for this region. pret source follows, verbatim.
; ---------------------------------------------------------------------------
; PRET| 	SetEventForceReuseHL EVENT_SS_ANNE_LEFT
; PRET| 	ld a, $ff
; PRET| 	ld [wJoyIgnore], a
; PRET| 	call StopAllMusic
; PRET| 	ld c, BANK(Music_Surfing)
; PRET| 	ld a, MUSIC_SURFING
; PRET| 	call PlayMusic
; PRET| 	farcall LoadSmokeTileFourTimes
; PRET| 	xor a
; PRET| 	ld [wSpritePlayerStateData1ImageIndex], a
; PRET| 	ld c, 120
; PRET| 	call DelayFrames
; PRET| 	ld b, HIGH(vBGMap1)
; PRET| 	call CopyScreenTileBufferToVRAM
; PRET| 	hlcoord 0, 10
; PRET| 	ld bc, SCREEN_WIDTH * 6
; PRET| 	ld a, $14 ; water tile
; PRET| 	call FillMemory
; PRET| 	ld a, 1
; PRET| 	ldh [hAutoBGTransferEnabled], a
; PRET| 	call Delay3
; PRET| 	xor a
; PRET| 	ldh [hAutoBGTransferEnabled], a
; PRET| 	ld [wSSAnneSmokeDriftAmount], a
; PRET| 	ldh [rOBP1], a
; PRET| 	call UpdateCGBPal_OBP1
; PRET| 	ld a, 88
; PRET| 	ld [wSSAnneSmokeX], a
; PRET| 	ld hl, wMapViewVRAMPointer
; PRET| 	ld c, [hl]
; PRET| 	inc hl
; PRET| 	ld b, [hl]
; PRET| 	push bc
; PRET| 	push hl
; PRET| 	ld a, SFX_SS_ANNE_HORN
; PRET| 	call PlaySoundWaitForCurrent
; PRET| 	ld a, $ff
; PRET| 	ld [wUpdateSpritesEnabled], a
; PRET| 	ld d, $0
; PRET| 	ld e, $8
; PRET| .shift_columns_up
; PRET| 	ld hl, $2
; PRET| 	add hl, bc
; PRET| 	ld a, l
; PRET| 	ld [wMapViewVRAMPointer], a
; PRET| 	ld a, h
; PRET| 	ld [wMapViewVRAMPointer + 1], a
; PRET| 	push hl
; PRET| 	push de
; PRET| 	call ScheduleEastColumnRedraw
; PRET| 	call VermilionDock_EmitSmokePuff
; PRET| 	pop de
; PRET| 	ld b, $10
; PRET| .smoke_puff_drift_loop
; PRET| 	call VermilionDock_AnimSmokePuffDriftRight
; PRET| 	ld c, $8
; PRET| .delay_between_drifts
; PRET| 	call VermilionDock_SyncScrollWithLY
; PRET| 	dec c
; PRET| 	jr nz, .delay_between_drifts
; PRET| 	inc d
; PRET| 	dec b
; PRET| 	jr nz, .smoke_puff_drift_loop
; PRET| 	pop bc
; PRET| 	dec e
; PRET| 	jr nz, .shift_columns_up
; PRET| 	xor a
; PRET| 	ldh [rWY], a
; PRET| 	ldh [hWY], a
; PRET| 	call VermilionDock_EraseSSAnne
; PRET| 	ld a, $90
; PRET| 	ldh [hWY], a
; PRET| 	ld a, $1
; PRET| 	ld [wUpdateSpritesEnabled], a
; PRET| 	pop hl
; PRET| 	pop bc
; PRET| 	ld [hl], b
; PRET| 	dec hl
; PRET| 	ld [hl], c
; PRET| 	call LoadPlayerSpriteGraphics
; PRET| 	ld hl, wNumberOfWarps
; PRET| 	dec [hl]
; PRET| 	ret

%assign event_byte -1
%assign event_byte_a -1
; NOT a dw->dd pointer table. `ld de, OBJ_SIZE` is the GB OAM entry stride, and
; the port's shadow OAM is the real 4-byte GB layout (gb_memmap.inc:1910
; OAM_ENTRY_SIZE equ 4, wShadowOAM equ 0xC300 "40 sprites x 4 bytes"), so the
; stride carries verbatim — nothing here is doubled.
VermilionDock_AnimSmokePuffDriftRight:
    push ebx                                 ; push bc
    push edx                                 ; push de
    mov esi, wShadowOAMSprite04XCoord
    mov al, [ebp + wSSAnneSmokeDriftAmount]
    ror al, 4                                ; swap a — nibble swap
    mov bl, al                               ; ld c, a
    mov edx, OAM_ENTRY_SIZE                  ; ld de, OBJ_SIZE
.drift_loop:
    inc byte [ebp + esi]
    inc byte [ebp + esi]
    ; add hl, de. EDX's upper 16 bits are zero (the `mov` above), so this is
    ; exactly SM83's 16-bit add; no wrap is reachable — ESI runs from 0xC311 and
    ; the largest count below is 0x80 entries, i.e. up to 0xC511.
    add esi, edx
    ; 8-BIT counter, deliberately: pret is `dec c / jr nz` on the 8-bit C, so a
    ; count of 0 runs 256 times and stops. See the "Preserve Counter WIDTH" rule.
    dec bl
    jnz .drift_loop
    pop edx
    pop ebx
    ret

%assign event_byte -1
%assign event_byte_a -1
VermilionDock_EmitSmokePuff:
    mov al, [ebp + wSSAnneSmokeX]
    sub al, 16
    mov [ebp + wSSAnneSmokeX], al
    mov bl, al
    mov bh, 100
    mov al, [ebp + wSSAnneSmokeDriftAmount]
    inc al
    mov [ebp + wSSAnneSmokeDriftAmount], al
    mov al, 0x1
    mov edx, VermilionDockOAMBlock   ; pret: ld de, VermilionDockOAMBlock — WriteOAMBlock takes it in EDX
    call WriteOAMBlock
    ret

%assign event_byte -1
%assign event_byte_a -1
VermilionDockOAMBlock:
    db 0xfc, OAM_PAL1
    db 0xfd, OAM_PAL1
    db 0xfe, OAM_PAL1
    db 0xff, OAM_PAL1

; ---------------------------------------------------------------------------
; BAIL[hl-half-register-access] VermilionDock_SyncScrollWithLY (scripts/VermilionDock.asm:165-180) — at scripts/VermilionDock.asm:165: `h` is a half of ESI and has no flag-safe 8-bit x86 form
; NO SYMBOL IS DEFINED for this region. pret source follows, verbatim.
; ---------------------------------------------------------------------------
; PRET| 	ld h, d
; PRET| 	ld l, $50
; PRET| 	call .sync_scroll_ly
; PRET| 	ld h, $0
; PRET| 	ld l, $80
; PRET| .sync_scroll_ly
; PRET| 	ldh a, [rLY]
; PRET| 	cp l
; PRET| 	jr nz, .sync_scroll_ly
; PRET| 	ld a, h
; PRET| 	ldh [rSCX], a
; PRET| .wait_for_ly_match
; PRET| 	ldh a, [rLY]
; PRET| 	cp h
; PRET| 	jr z, .wait_for_ly_match
; PRET| 	ret

%assign event_byte -1
%assign event_byte_a -1
; NO PROJECTION IS OWED HERE — the bail's `screen-coord-projection` premise is
; false for `hlbgcoord`. pret's macro (macros/coords.asm) is
; `vBGMap0 + y * TILEMAP_WIDTH + x` and the port's (include/coords.inc:103-118)
; is `GB_TILEMAP0 + y * TILEMAP_WIDTH + x` with TILEMAP_WIDTH = 32 on both sides
; (gb_memmap.inc:1903, :29): this addresses the HARDWARE 32x32 BG map, not the
; 20x18-vs-40x25 screen buffer, so the two expressions are byte-identical.
; `hlowcoord` likewise addresses wOverworldMap, and the port's owcoord is the
; MAP_BORDER-generic form of pret's border-3 literal (coords.inc:136-146).
VermilionDock_EraseSSAnne:
; Fill the area the S.S. Anne occupies in BG map 0 with water tiles.
    mov esi, wVermilionDockTileMapBuffer
    mov bx, wVermilionDockTileMapBufferEnd - wVermilionDockTileMapBuffer
    mov al, 0x14                             ; water tile
    call FillMemory
    hlbgcoord 0, 10
    mov edx, wVermilionDockTileMapBuffer     ; ld de — CopyVideoData takes the source in EDX
    mov bx, ((0) << 8) | (12)                ; lb bc, BANK(wVermilionDockTileMapBuffer), 12 — bank is a flat no-op
    call CopyVideoData

; Replace the blocks of the lower half of the ship with water blocks. This
; leaves the upper half alone, but that doesn't matter because replacing any of
; the blocks is unnecessary because the blocks the ship occupies are south of
; the player and won't be redrawn when the player automatically walks north and
; exits the map. This code could be removed without affecting anything.
    hlowcoord 5, 2, VERMILION_DOCK_WIDTH
    mov al, 0xd                              ; water block
    mov [ebp + esi], al
    lea esi, [esi+1]
    mov [ebp + esi], al
    lea esi, [esi+1]
    mov [ebp + esi], al
    lea esi, [esi+1]
    mov [ebp + esi], al

    mov al, SFX_SS_ANNE_HORN
    call PlaySound
    mov bl, 120                              ; ld c, 120
    call DelayFrames
    ret

%assign event_byte -1
%assign event_byte_a -1
VermilionDock_TextPointers:
    dd VermilionDockUnusedText
VermilionDockUnusedText:
    text_far _VermilionDockUnusedText
    text_end
