; WardensHouse.asm — translated from pret scripts/WardensHouse.asm by dos_port/tools/sm83xlat.
;
; ONE-SHOT OUTPUT, NOW HAND-MAINTAINED. The transpiler ran once at the SHA
; recorded in dos_port/tools/sm83xlat/README.md and is not re-run; this file is
; ordinary Tier-2 source and editing it is the normal way it changes. There is
; deliberately no DO NOT EDIT header.
;
; Every pret label is preserved verbatim so the file stays line-for-line
; cross-referenceable against the disassembly.
;
; Regions the tool could not lower WITH CERTAINTY are reproduced below as
; commented pret source under a `; BAIL[reason]` banner, and define NO symbol —
; so a reference to one is a link error rather than a plausible wrong lowering.

bits 32

%include "gb_memmap.inc"
%include "gb_constants.inc"
%include "gb_text.inc"
%include "events.inc"
%include "assets/event_constants.inc"
%include "assets/script_constants.inc"


global WardensHouseDisplayText
global WardensHouseWardenText
global WardensHouse_Script
global WardensHouse_TextPointers

extern Bankswitch
extern BoulderText   ; NOT YET DEFINED IN THE PORT
extern EnableAutoTextBoxDrawing
extern GiveItem
extern IsItemInBag
extern PickUpItemText
extern PrintText
extern RemoveItemByID
extern TextScriptEnd
extern YesNoChoice

; Script constants — pret defines these via dw_const in this file.
TEXT_WARDENSHOUSE_DISPLAY_LEFT                 equ 4

; Code and data are emitted in pret's SOURCE ORDER, in one section.
; That is not cosmetic: a NASM local label binds to the last
; non-local label above it, so hoisting the text streams into a
; separate section rebound every `.Text` to the wrong parent.
; Far text streams for this map — pret text/wardens_house, generated by
; tools/generators/gen_map_text.py. Defined HERE because every one is used
; only by this script, exactly as pret keeps text/<Map>.asm beside scripts/<Map>.asm.
section .data
%include "assets/map_text/wardens_house.inc"

section .text

%assign event_byte -1
%assign event_byte_a -1
WardensHouse_Script:
    jmp EnableAutoTextBoxDrawing

%assign event_byte -1
%assign event_byte_a -1
WardensHouse_TextPointers:
    dd WardensHouseWardenText
    dd PickUpItemText
    dd BoulderText
    dd WardensHouseDisplayText
    dd WardensHouseDisplayText

%assign event_byte -1
%assign event_byte_a -1
WardensHouseWardenText:
    CheckEvent EVENT_GOT_HM04
    jnz .got_item
    mov bh, GOLD_TEETH
    call IsItemInBag
    jnz .have_gold_teeth
    CheckEvent EVENT_GAVE_GOLD_TEETH
    jnz .gave_gold_teeth
    mov esi, .Gibberish1Text
    call PrintText
    call YesNoChoice
    mov al, [ebp + wCurrentMenuItem]
    test al, al
    mov esi, .Gibberish3Text
    jnz .refused
    mov esi, .Gibberish2Text
.refused:
    call PrintText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.have_gold_teeth:
    mov esi, .GaveTheGoldTeethText
    call PrintText
    mov al, GOLD_TEETH
    mov [ebp + hItemToRemoveID], al
; DEVIATION{class=banking; pret=macros/farcall.asm:farcall; behavior=bank switch dropped, call goes straight to the target; evidence=the DPMI model is flat so every routine is always addressable, and Bankswitch has no port counterpart; lifetime=permanent}
    call RemoveItemByID
    pushfd    ; SM83 form writes no flags
        SetEvent EVENT_GAVE_GOLD_TEETH
    popfd
.gave_gold_teeth:
    mov esi, .ThanksText
    call PrintText
    mov bx, (HM_STRENGTH << 8) | (1)   ; pret: lb bc, HM_STRENGTH, 1  (HM04 = $C7)
    call GiveItem
    jae .bag_full
    mov esi, .ReceivedHM04Text
    call PrintText
    SetEvent EVENT_GOT_HM04
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.got_item:
    mov esi, .HM04ExplanationText
    call PrintText
    jmp .done

%assign event_byte -1
%assign event_byte_a -1
.bag_full:
    mov esi, .HM04NoRoomText
    call PrintText
.done:
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.Gibberish1Text:
    text_far _WardensHouseWardenGibberish1Text
    text_end
.Gibberish2Text:
    text_far _WardensHouseWardenGibberish2Text
    text_end
.Gibberish3Text:
    text_far _WardensHouseWardenGibberish3Text
    text_end
.GaveTheGoldTeethText:
    text_far _WardensHouseWardenGaveTheGoldTeethText
    sound_get_item_1
.PoppedInHisTeethText:
    text_far _WardensHouseWardenTeethPoppedInHisTeethText
    text_end
.ThanksText:
    text_far _WardensHouseWardenThanksText
    text_end
.ReceivedHM04Text:
    text_far _WardensHouseWardenReceivedHM04Text
    sound_get_item_1
    text_end
.HM04ExplanationText:
    text_far _WardensHouseWardenHM04ExplanationText
    text_end
.HM04NoRoomText:
    text_far _WardensHouseWardenHM04NoRoomText
    text_end

%assign event_byte -1
%assign event_byte_a -1
WardensHouseDisplayText:
    mov al, [ebp + hTextID]
    cmp al, TEXT_WARDENSHOUSE_DISPLAY_LEFT
    mov esi, .MerchandiseText
    jnz .print_text
    mov esi, .PhotosAndFossilsText
.print_text:
    call PrintText
    jmp TextScriptEnd

%assign event_byte -1
%assign event_byte_a -1
.PhotosAndFossilsText:
    text_far _WardensHouseDisplayPhotosAndFossilsText
    text_end
.MerchandiseText:
    text_far _WardensHouseDisplayMerchandiseText
    text_end
