; pikachu_pic_objects.asm — mirror of pret data/pikachu/pikachu_pic_objects.asm.
;
; The pikapic frame lists: each entry is `db tilemap index, duration`, a leading
; index of 0 meaning "hold, draw nothing" and $E0 terminating the list.
; LoadPikaPicAnimObjectData walks these through PikaPicAnimBGFramesPointers.
;
; Tier-1 data, generated by tools/generators/gen_pikachu_pic.py.
; DEVIATION{class=data-model; pret=data/pikachu/pikachu_pic_objects.asm:PikaPicAnimBGFramesPointers; behavior=the pointer table holds 32-bit flat program-image pointers with stride 4 instead of pret's 16-bit GB addresses with stride 2; evidence=the port links its data into the DOS program image rather than a 16-bit GB ROM bank so a dw cannot name a table entry, and the consuming routine indexes by 4 to match; lifetime=permanent flat 32-bit memory model}
;
; Build: nasm -f coff -I include/ -I . -o pikachu_pic_objects.o pikachu_pic_objects.asm

bits 32

global PikaPicAnimBGFramesPointers

section .data

%include "assets/pikachu_pic_objects.inc"
