; pikachu_pic_animation.asm — mirror of pret data/pikachu/pikachu_pic_animation.asm.
;
; Three tables:
;   PikaPicAnimThunderboltPals — the BGP flash sequence PikaPicAnimCommand_thunderbolt
;                                walks (db frames, db BGP value, terminated by $FF).
;   PikaPicAnimScript0..29     — the pikapic bytecode, plus the two unreferenced
;                                fall-in scripts Data_fe26b / Data_fe51f pret carries.
;   PikaPicAnimGFXHeaders      — one record per loadable graphic.
;
; Tier-1 data, generated by tools/generators/gen_pikachu_pic.py.
;
; DEVIATION{class=data-model; pret=data/pikachu/pikachu_pic_animation.asm:PikaPicAnimGFXHeaders; behavior=each GFX header record is 8 bytes - db size, db bank, dw byte length, dd flat pointer - where pret uses 4 - db size plus dba - and carries a byte length pret has no field for; evidence=a flat program-image pointer does not fit pret's dw and UncompressSpriteData reads its input stream from EBP-relative GB memory, so a compressed .pic must be staged into PIC_STAGE by length before it can be decoded, a length nothing in the pret record supplies; lifetime=permanent flat 32-bit memory model}
;
; DEVIATION{class=data-model; pret=data/pikachu/pikachu_pic_animation.asm:PikaPicAnimScript0; behavior=the pikapic_jump operand is a 4-byte flat pointer instead of pret's 2-byte GB address; evidence=the scripts live in the DOS program image above the 16-bit GB address space so a dw cannot name a jump target, and PikaPicAnimCommand_jump reads four bytes to match; lifetime=permanent flat 32-bit memory model}
;
; Build: nasm -f coff -I include/ -I . -o pikachu_pic_animation.o pikachu_pic_animation.asm

bits 32

global PikaPicAnimThunderboltPals
global PikaPicAnimGFXHeaders
global PIKAPIC_GFX_HEADER_SIZE
global Data_fe26b
global Data_fe51f
global PikaPicAnimScript0
global PikaPicAnimScript1
global PikaPicAnimScript2
global PikaPicAnimScript3
global PikaPicAnimScript4
global PikaPicAnimScript5
global PikaPicAnimScript6
global PikaPicAnimScript7
global PikaPicAnimScript8
global PikaPicAnimScript9
global PikaPicAnimScript10
global PikaPicAnimScript11
global PikaPicAnimScript12
global PikaPicAnimScript13
global PikaPicAnimScript14
global PikaPicAnimScript15
global PikaPicAnimScript16
global PikaPicAnimScript17
global PikaPicAnimScript18
global PikaPicAnimScript19
global PikaPicAnimScript20
global PikaPicAnimScript21
global PikaPicAnimScript22
global PikaPicAnimScript23
global PikaPicAnimScript24
global PikaPicAnimScript25
global PikaPicAnimScript26
global PikaPicAnimScript27
global PikaPicAnimScript28
global PikaPicAnimScript29

; The graphics blobs live in their own pret-mirrored carrier, src/gfx/pikachu.asm.
%include "assets/pikachu_pic_gfx_externs.inc"
; PikachuSprite: pret gfx/sprites/pikachu.2bpp, carried by engine/gfx/mon_icons.asm.
extern PikachuSprite


section .data

%include "assets/pikachu_pic_animation.inc"
