; pikachu_pic_tilemaps.asm — mirror of pret data/pikachu/pikachu_pic_tilemaps.asm.
;
; The pikapic cel tilemaps: each is `db rows, cols` followed by rows*cols tile
; ids, with $FF meaning "leave this cell alone".  LoadCurPikaPicObjectTilemap
; (src/engine/pikachu/pikachu_pic_animation.asm) indexes PikaPicTilemapPointers.
;
; Tier-1 data, generated by tools/generators/gen_pikachu_pic.py.
; DEVIATION{class=data-model; pret=data/pikachu/pikachu_pic_tilemaps.asm:PikaPicTilemapPointers; behavior=the pointer table holds 32-bit flat program-image pointers with stride 4 instead of pret's 16-bit GB addresses with stride 2; evidence=the port links its data into the DOS program image rather than a 16-bit GB ROM bank so a dw cannot name a table entry, and the consuming routine indexes by 4 to match; lifetime=permanent flat 32-bit memory model}
;
; Build: nasm -f coff -I include/ -I . -o pikachu_pic_tilemaps.o pikachu_pic_tilemaps.asm

bits 32

global PikaPicTilemapPointers

section .data

%include "assets/pikachu_pic_tilemaps.inc"
