; residual_effects_1.asm — move effects applied after damage (list 1). $FF-terminated, scanned linearly.
;
; pret ref: data/battle/residual_effects_1.asm:ResidualEffects1
;
; Generated by tools/generators/gen_effect_categories.py into assets/residual_effects_1.inc (one .inc per pret
; source file). This carrier sits at the mirrored path dos_port/src/data/battle/residual_effects_1.asm; it was
; part of src/data/battle_data.asm until 2026-08-16
; (docs/current_plan_data_path_mirror.md).
;
; Embedded data goes in .data per the linker rule in docs/assembly.md (.rodata has
; no output-section rule and reads back as zero).
bits 32

global ResidualEffects1

section .data

%include "assets/residual_effects_1.inc"
