; stat_mod_names.asm — '@'-terminated stat names, scanned by PrintStatText.
;
; pret ref: data/battle/stat_mod_names.asm:StatModTextStrings
;
; Generated by tools/generators/gen_runtime_strings.py into
; assets/stat_mod_runtime_strings.inc. This carrier sits at the mirrored path dos_port/src/data/battle/stat_mod_names.asm; it was
; part of src/data/battle_data.asm until 2026-08-16
; (docs/current_plan_data_path_mirror.md).
;
; Embedded data goes in .data per the linker rule in docs/assembly.md (.rodata has
; no output-section rule and reads back as zero).
bits 32

global StatModTextStrings

section .data

%include "assets/stat_mod_runtime_strings.inc"
