; title_yellow.asm — the Yellow title-screen graphics/placement half, at its
; pret mirror.
;
; Source: engine/movie/title_yellow.asm (pret/pokeyellow). Started at the
; menu-intro review (2026-07-23) with Bank3D_CopyBox; the rest of the pret
; file's labels (LoadYellowTitleScreenGFX, TitleScreen_PlacePokemonLogo /
; _PlacePikaSpeechBubble / _PlacePikachu, TitleScreenPikachuEyesOAMData) moved
; here from the legacy title module src/movie/title.asm 2026-07-24
; (relocated-labels grind — the split was registered legacy debt in
; tools/pret_label_allowlist.json, now retired). The title-screen driver
; (PrepareTitleScreen/DisplayTitleScreen &c.) is in its own mirror,
; src/engine/movie/title.asm.
;
; The four INCBIN'd tile graphics and three tilemaps pret keeps in this file
; live here too, as their generated flat assets (gen_title_gfx_inc.py).
;
; Build: nasm -f coff -I include/ -I . -o title_yellow.o title_yellow.asm

bits 32

%include "gb_memmap.inc"
%define UI_LAYOUT_EQUATES_ONLY 1
%include "assets/ui_layout_intro.inc"   ; UI_TITLE_* projected surface geometry

extern g_tilecache_dirty             ; ppu/ppu.asm — arm on raw VRAM tile writes
extern PublishProjectedOAM           ; engine/gfx/sprite_oam.asm — ESI=src ECX=n EAX/EBX=offset

; Projected drawing origin (same projection as src/engine/movie/title.asm — see
; the note there): pret's coord(col,row) lands at coord(col+UI_TITLE_COL,
; row+UI_TITLE_ROW) on the port's 40x25 canvas.
TITLE_ORIGIN         equ UI_TITLE_ROW * SCREEN_TILES_W + UI_TITLE_COL

; VRAM tile destination constants
VCHARS1_TILE_70      equ GB_VFONT + 0x70 * 16   ; = $8F00  (Pikachu OBJ sprites)
VCHARS1_TILE_7D      equ GB_VFONT + 0x7D * 16   ; = $8FD0  (logo corner tiles)

; ---------------------------------------------------------------------------
; Data — pret INCBINs the graphics at the end of this file; the port embeds
; the generated flat assets (tools/generators/gen_title_gfx_inc.py).
; ---------------------------------------------------------------------------
section .data
align 4

; Pikachu eye OAM data — 8 sprites × 4 bytes = 32 bytes
; Copied to wShadowOAM by TitleScreen_PlacePikachu.
; (The old "OAM renderer not yet implemented" note here was stale: render_sprites
; has emulated DMG OBJ since the Phase-1 OAM pass. A2.4 routes these records
; through PublishProjectedOAM so they land on the centred cinematic surface.)
TitleScreenPikachuEyesOAMData:
    db 0x60, 0x40, 0xf1, 0x22
    db 0x60, 0x48, 0xf0, 0x22
    db 0x68, 0x40, 0xf3, 0x22
    db 0x68, 0x48, 0xf2, 0x22
    db 0x60, 0x60, 0xf0, 0x02
    db 0x60, 0x68, 0xf1, 0x02
    db 0x68, 0x60, 0xf2, 0x02
    db 0x68, 0x68, 0xf3, 0x02

; Tile graphics and tilemaps (generated by tools/generators/gen_title_gfx_inc.py):
; pret PokemonLogoGraphics / PokemonLogoCornerGraphics / TitlePikachuBGGraphics /
; TitlePikachuOBGraphics INCBINs + the TitleScreenPokemonLogo/PikaBubble/Pikachu
; tilemaps.
%include "assets/pokemon_logo_2bpp.inc"
%include "assets/pokemon_logo_corner_2bpp.inc"
%include "assets/pikachu_bg_2bpp.inc"
%include "assets/pikachu_ob_2bpp.inc"
%include "assets/pokemon_logo_tilemap.inc"
%include "assets/pikachu_tilemap.inc"
%include "assets/pika_bubble_tilemap.inc"

; ---------------------------------------------------------------------------
; Code
; ---------------------------------------------------------------------------
section .text

; ---------------------------------------------------------------------------
; LoadYellowTitleScreenGFX — load all Pokemon Yellow title tile graphics.
; Source: engine/movie/title_yellow.asm:LoadYellowTitleScreenGFX
;
; VRAM layout (signed tile mode, LCDC_DEFAULT=$E3, bit4=0, base $9000):
;   $9000 (vChars2)           ← Pokemon logo main tiles (128 tiles = $800 bytes)
;   $8FD0 (vChars1 tile $7D)  ← Logo corner tiles (3 tiles = $30 bytes)
;   $8800 (vChars1)           ← Pikachu BG tiles (64 tiles = $400 bytes)
;   $8F00 (vChars1 tile $70)  ← Pikachu OBJ sprite tiles (12 tiles = $C0 bytes)
; ---------------------------------------------------------------------------
global LoadYellowTitleScreenGFX
LoadYellowTitleScreenGFX:
    pushad
    mov byte [g_tilecache_dirty], 1     ; VRAM tile data changes → rebuild decode cache

    ; Pokemon logo → vChars2 ($9000), 128 tiles
    lea esi, [pokemon_logo_2bpp]
    lea edi, [ebp + GB_VCHARS2]
    mov ecx, POKEMON_LOGO_2BPP_SIZE
    rep movsb

    ; Logo corner tiles → vChars1 tile $7D ($8FD0), 3 tiles
    lea esi, [pokemon_logo_corner_2bpp]
    lea edi, [ebp + VCHARS1_TILE_7D]
    mov ecx, POKEMON_LOGO_CORNER_2BPP_SIZE
    rep movsb

    ; Pikachu BG tiles → vChars1 ($8800), 64 tiles
    lea esi, [pikachu_bg_2bpp]
    lea edi, [ebp + GB_VFONT]
    mov ecx, PIKACHU_BG_2BPP_SIZE
    rep movsb

    ; Pikachu OBJ sprite tiles → vChars1 tile $70 ($8F00), 12 tiles
    lea esi, [pikachu_ob_2bpp]
    lea edi, [ebp + VCHARS1_TILE_70]
    mov ecx, PIKACHU_OB_2BPP_SIZE
    rep movsb

    popad
    ret

; ---------------------------------------------------------------------------
; TitleScreen_PlacePokemonLogo — copy 16×7 logo tilemap into wTileMap at (2,1).
; Source: engine/movie/title_yellow.asm:TitleScreen_PlacePokemonLogo
; ---------------------------------------------------------------------------
global TitleScreen_PlacePokemonLogo
TitleScreen_PlacePokemonLogo:
    pushad
    lea esi, [pokemon_logo_tilemap]        ; ld de, TitleScreenPokemonLogoTilemap
    ; dest = wTileMap + projected coord(2, 1)
    lea edi, [ebp + W_TILEMAP + TITLE_ORIGIN + 1 * SCREEN_TILES_W + 2]
    mov bh, POKEMON_LOGO_TILEMAP_HEIGHT    ; lb bc, 7, 16
    mov bl, POKEMON_LOGO_TILEMAP_WIDTH
    call Bank3D_CopyBox
    popad
    ret

; ---------------------------------------------------------------------------
; TitleScreen_PlacePikaSpeechBubble — place 7×4 speech bubble at (6,4)
; and overlay two logo tiles at (9,8).
; Source: engine/movie/title_yellow.asm:TitleScreen_PlacePikaSpeechBubble
; ---------------------------------------------------------------------------
global TitleScreen_PlacePikaSpeechBubble
TitleScreen_PlacePikaSpeechBubble:
    pushad

    ; 7×4 bubble tilemap at coord (col=6, row=4)
    lea esi, [pika_bubble_tilemap]        ; ld de, TitleScreenPikaBubbleTilemap
    lea edi, [ebp + W_TILEMAP + TITLE_ORIGIN + 4 * SCREEN_TILES_W + 6]
    mov bh, PIKA_BUBBLE_TILEMAP_HEIGHT    ; lb bc, 4, 7
    mov bl, PIKA_BUBBLE_TILEMAP_WIDTH
    call Bank3D_CopyBox

    ; Two logo-area tiles placed at (9,8) and (10,8)
    ; $64 = logo tile 100 (signed + → vChars2), $65 = logo tile 101
    mov byte [ebp + W_TILEMAP + TITLE_ORIGIN + 8 * SCREEN_TILES_W + 9],  0x64
    mov byte [ebp + W_TILEMAP + TITLE_ORIGIN + 8 * SCREEN_TILES_W + 10], 0x65

    popad
    ret

; ---------------------------------------------------------------------------
; TitleScreen_PlacePikachu — add pikachu tilemap (12×9) to wTileMap at (4,8),
; place tail tiles, and copy eye OAM data to wShadowOAM.
; Source: engine/movie/title_yellow.asm:TitleScreen_PlacePikachu
; ---------------------------------------------------------------------------
global TitleScreen_PlacePikachu
TitleScreen_PlacePikachu:
    pushad

    ; Place 12×9 pikachu tilemap at coord (col=4, row=8)
    lea esi, [pikachu_tilemap]            ; ld de, TitleScreenPikachuTilemap
    lea edi, [ebp + W_TILEMAP + TITLE_ORIGIN + 8 * SCREEN_TILES_W + 4]
    mov bh, PIKACHU_TILEMAP_HEIGHT        ; lb bc, 9, 12
    mov bl, PIKACHU_TILEMAP_WIDTH
    call Bank3D_CopyBox

    ; Place extra tail/overlap tiles at column 16, rows 10-13
    mov byte [ebp + W_TILEMAP + TITLE_ORIGIN + 10 * SCREEN_TILES_W + 16], 0x96
    mov byte [ebp + W_TILEMAP + TITLE_ORIGIN + 11 * SCREEN_TILES_W + 16], 0x9D
    mov byte [ebp + W_TILEMAP + TITLE_ORIGIN + 12 * SCREEN_TILES_W + 16], 0xA7
    mov byte [ebp + W_TILEMAP + TITLE_ORIGIN + 13 * SCREEN_TILES_W + 16], 0xB1

    ; Copy eye OAM data to wShadowOAM (32 bytes = 8 sprites × 4 bytes). The
    ; records stay canonical GB OAM — byte-comparable against a golden — and the
    ; projection lives only in the published DOS coordinates.
    lea esi, [TitleScreenPikachuEyesOAMData]
    lea edi, [ebp + W_SHADOW_OAM]
    mov ecx, 32
    rep movsb

    call TitleScreenPublishEyes

    popad
    ret

; ---------------------------------------------------------------------------
; TitleScreenPublishEyes — put the 8 canonical eye records on the surface.
;
; Port-only helper; no pret counterpart, because on the GB OAM already IS screen
; space. MovieBeginSurface parked wUpdateSpritesEnabled at $FF, so nothing else
; republishes OAM while the cinematic owns the screen — every eye change has to
; come back through here or the compositor keeps drawing the previous frame.
; Global: DoTitleScreenFunction (src/engine/movie/title.asm) republishes after
; each blink-frame mutation.
; ---------------------------------------------------------------------------
global TitleScreenPublishEyes
TitleScreenPublishEyes:
    pushad
    mov esi, W_SHADOW_OAM               ; GB-relative source
    mov ecx, 8                          ; 8 eye records
    mov eax, UI_TITLE_COL * 8           ; projection X = 80
    mov ebx, UI_TITLE_WY                ; projection Y = 24
    call PublishProjectedOAM
    popad
    ret

; ---------------------------------------------------------------------------
; Bank3D_CopyBox — copy a c-wide × b-tall tile box from a flat source into the
; canvas (pret engine/movie/title_yellow.asm:Bank3D_CopyBox; the row step is the
; canvas stride SCREEN_TILES_W instead of pret's SCREEN_WIDTH — the projection).
; In: ESI = flat src (advances through the box), EDI = flat dest (EBP-biased,
;     top-left corner), BH = rows (pret b), BL = cols (pret c).
; Clobbers ECX/ESI/EDI/EBX.
; ---------------------------------------------------------------------------
global Bank3D_CopyBox
Bank3D_CopyBox:
.row:
    movzx ecx, bl                      ; ld c (cols)
    push edi                           ; push hl
    rep movsb                          ; the .col loop
    pop edi                            ; pop hl
    add edi, SCREEN_TILES_W            ; ld bc, SCREEN_WIDTH / add hl, bc
    dec bh                             ; dec b
    jnz .row                           ; jr nz, .row
    ret
