; sgb_packets.asm — SGB packet blobs the port actually reads.
;
; pret ref: data/sgb/sgb_packets.asm:BlkPacket_PartyMenu
;
; Generated by tools/generators/gen_sgb_packets.py into assets/sgb_packets.inc.
; This carrier sits at the mirrored path dos_port/src/data/sgb/sgb_packets.asm so
; the pret data/ label lands where the aux_misplaced rule wants it.
;
; ONLY ONE PACKET, deliberately. The port has no SGB packet SENDER — see the two
; class=HAL deviation annotations on SetPal_PartyMenu and
; LoadOverworldPikachuFrontpicPalettes in src/engine/gfx/palettes.asm, which record
; that it publishes slot palettes directly instead. (Spelled without the keyword on
; purpose: lint_pret_labels parses a line STARTING with an annotation kind as an
; annotation, so a prose cross-reference written the obvious way is a violation.)
; BlkPacket_PartyMenu is here
; because its BYTES are read anyway: InitPartyMenuBlkPacket copies it into
; wPartyMenuBlkPacket, UpdatePartyMenuBlkPacket overwrites the six HP-bar colour
; bytes in place, and HandlePartyHPBarAttributes reads them back at +9 stride 6.
;
; Embedded data goes in .data per the linker rule in docs/assembly.md (.rodata has
; no output-section rule and reads back as zero).
bits 32

; The global is declared HERE, in the .asm, not only in the generated .inc:
; lint_pret_labels scans .asm files, so an extern naming this carrier must find
; the symbol declared in this file or it reports stale_provider. That is also why
; the generated _SIZE equ is NOT exported — see the note in gen_sgb_packets.py.
global BlkPacket_PartyMenu

section .data

%include "assets/sgb_packets.inc"
