; ===========================================================================
; link_ui.asm — link-cable transport-select + connection-book UI. Port-only,
; NO PRET COUNTERPART (link cable plan Stage 5 step 3): the GB has a physical
; cable and never showed a "how will you link" menu or a saved-connection
; book — those only exist because the port has to pick a TRANSPORT (a real
; serial cable has none of that ambiguity) and remember addresses across
; reboots. Every routine/label here is a bespoke lowercase port name except
; the two contractual entry points CableClubNPC calls, which stay mixed-case
; to match the port's other HAL-boundary entry points (NetInit, NetHAL_*).
;
; CONTRACTS THIS FILE CONSUMES (read their own headers, not just this one):
;   kbd_text_edit  — src/input/kbd_text.asm. In: ESI=GB-space dest, BL=max
;                    len, BH=charset class, EDX=GB-space tilemap echo pos.
;                    Out: AL=1 commit / 0 cancel, dest '@'-terminated either
;                    way. IMPORTANT (verified by reading the source, not
;                    assumed): it does NOT seed from the dest's prior content
;                    — .entry unconditionally writes the terminator at offset
;                    0 and zeroes its internal length counter, so every call
;                    starts the field EMPTY. EDIT therefore starts blank too
;                    (see lu_edit_entry) — this is the "empty start is
;                    acceptable" branch the step-3 spec names, not the
;                    in-place-seed branch; reported to root per the spec's
;                    report format.
;   linkbook_load/store/record/loaded/book_image — src/net/link_book.asm.
;   g_net_transport/g_net_com_sel/NetInit — src/net/net_hal.asm.
;   LinkUIStr_* — assets/link_ui_strings.inc (generated by
;                 tools/generators/gen_link_ui_strings.py; two entries this
;                 step added — LinkUIStr_NoPort, LinkUIStr_NotInBuild — plus
;                 LinkUIStr_Com1..4 for the COM-pick menu).
;
; SURFACE / WINDOW MODEL — copied from src/engine/menus/link_menu.asm's
; LinkMenu precedent (its own header names this "WINDOW/CANVAS model"):
;   * A small box is staged into the stride-20 wTileMap scratch (box-relative
;     coords via the LUB() macro below, exactly LinkMenu's LMB()), mirrored
;     into GB_TILEMAP0 (lu_mirror, byte-for-byte LinkMenu's lm_link_mirror),
;     and shown as a SUB-RECT window via add_window (lu_show_window, byte-
;     for-byte LinkMenu's lm_link_show_window) — an OVERLAY appended on top
;     of whatever CableClubNPC's own PrintText dialog already has up, not a
;     full takeover. Box geometry is UI_LINK_MENU's own (assets/
;     ui_layout_menus.inc): 15x10 exterior / 13x8 interior — the SAME window
;     LinkMenu itself uses a moment later in the same call chain, reused
;     rather than inventing new geometry (this step has no sidecar entry to
;     derive one from, and LinkMenu's box is exactly the "small dialog box
;     over the overworld" this UI also wants).
;   * ONE window descriptor is added for this call's entire lifetime
;     (lu_show_window runs exactly once, from LinkTransportSelect); every
;     screen transition after that just redraws the wTileMap scratch and
;     calls lu_mirror again — never add_window again, which would grow
;     g_window_count on every transport<->book round trip.
;   * Three long strings (19/14/19 chars) don't fit the 13-col interior in
;     one line; the generator splits them with an embedded <NEXT> instead of
;     widening the box (see gen_link_ui_strings.py's header for why).
;   * kbd_text_edit's own `.draw` loop runs a self-contained per-frame
;     DelayFrame pump with no knowledge of this file's mirror step, so a
;     naive box-relative (LUB) echo position would only reach the screen
;     once the widget exits (nothing re-mirrors wTileMap->GB_TILEMAP0 while
;     it types). Fix: pass kbd_text_edit a NATIVE tilemap position instead —
;     LUN() below computes GB_TILEMAP0 + row*32 + col directly. Since our
;     box's scratch (0,0) already 1:1-maps onto GB_TILEMAP0 (0,0) via
;     lu_mirror's own blit, a LUN() position is numerically the "same cell"
;     a LUB() position would mirror to — so the field's live echo (and its
;     ClearScreenArea blank + cursor tile) lands directly in the tilemap our
;     window already sources from, no extra mirror call needed while typing.
;     ClearScreenArea's own SCREEN_WIDTH(40)-stride row-advance (see its
;     header in home/copy2.asm) is irrelevant here because kbd_text_edit only
;     ever clears ONE row (BH=1) — no row-advance ever executes.
;   * YesNoChoice (home/yes_no.asm, DELETE's confirm) manages its own
;     wTileMap-origin save/restore AND window save/restore, and its own
;     mirror target is GB_TILEMAP0 row 16 (YN_SROW, text_box.asm) — clear of
;     this file's rows 0-9. So it can be called directly while this file's
;     own window is still up: it draws on top, then fully undoes itself
;     (wTileMap content and window count both restored to what they were),
;     with no coordination needed on this side beyond redrawing next
;     (already the practice on every other screen transition here).
;
; MENU MECHANICS — same wTopMenuItemY/X + wMaxMenuItem + wMenuWatchedKeys +
; wLastMenuItem + menu_item_step + menu_redraw_cb + HandleMenuInput pattern
; LinkMenu uses (home/window.asm). Dispatch here is plain "AL bit tests +
; wCurrentMenuItem compares" — LinkMenu's extra "convert an A on the CANCEL
; row into a synthetic B" step exists only to shape the byte it exchanges
; with a serial peer (link_menu.asm:.asm_f586b) and does not apply: nothing
; here talks to a peer, so a CANCEL row is just an ordinary item that jumps
; to the same place B does.
;
; ADDRESS TEXT STAGING — kbd_text_edit's dest must be a GB-space (EBP-
; relative) offset; book_image (link_book.asm) is flat port-only memory, not
; reachable that way. Text is staged through wStringBuffer (pret ram/
; wram.asm: ds NAME_BUFFER_LENGTH = 20 bytes; PrintStatText's GB-space
; scratch, and the same buffer engine/menus/naming_screen.asm borrows for
; its own unrelated text entry) and only copied into book_image on a
; successful commit. NAME_BUFFER_LENGTH=20 caps the address field at
; LU_ADDR_MAX=19 characters (20 minus the terminator) — enough for common
; addresses ("192.168.1.100:12345" is 19) but NOT the absolute worst case
; ("255.255.255.255:65535" is 21); flagged as an open question in the step-3
; report rather than carving a new port-only WRAM region unilaterally.
;
; Build check: nasm -f coff -I include/ -I . -o /dev/null src/net/link_ui.asm
;              (from dos_port/)
; ===========================================================================

bits 32

%include "gb_memmap.inc"
%include "gb_macros.inc"

%define UI_LAYOUT_EQUATES_ONLY 1
%include "assets/ui_layout_menus.inc"   ; UI_LINK_MENU_* (equates only)

; ---------------------------------------------------------------------------
; Exported symbols
; ---------------------------------------------------------------------------
global LinkTransportSelect
global link_ui_connect_attempt

; ---------------------------------------------------------------------------
; Imported symbols
; ---------------------------------------------------------------------------
extern g_net_transport      ; src/net/net_hal.asm — NET_TRANSPORT_* (0=none)
extern g_net_com_sel        ; src/net/net_hal.asm — 1..4, consumed by NetInit
extern NetInit              ; src/net/net_hal.asm — re-callable (net_hal.asm:196-215):
                             ; no-ops when g_net_com_sel==0, else binds the UART or
                             ; leaves g_net_transport at NONE with no hang if absent.

extern linkbook_load        ; src/net/link_book.asm
extern linkbook_store       ; src/net/link_book.asm
extern linkbook_record      ; src/net/link_book.asm — In: AL=family AH=slot, Out: ESI
extern linkbook_loaded      ; src/net/link_book.asm — byte, 1 once load has run
extern book_image           ; src/net/link_book.asm — flat (NOT GB-space) record array

extern kbd_text_edit        ; src/input/kbd_text.asm

extern TextBoxBorder        ; src/home/text.asm — ESI=top-left, BL=int_w, BH=int_h
extern PlaceString          ; src/home/text.asm — EAX=flat src, ESI=GB-space dest
extern text_row_stride      ; src/home/text.asm — active wTileMap row stride
extern ClearScreenArea       ; src/home/copy2.asm — used only via kbd_text_edit

extern add_window           ; src/ppu/ppu.asm
extern g_window_count       ; src/ppu/ppu.asm

extern HandleMenuInput      ; src/home/window.asm
extern menu_item_step       ; src/home/window.asm
extern menu_redraw_cb       ; src/home/window.asm

extern DelayFrame           ; src/home/vblank.asm
extern DelayFrames          ; src/home/delay.asm — In: BL=frame count

extern YesNoChoice          ; src/home/yes_no.asm — Out: wCurrentMenuItem 0=YES/1=NO

; ---------------------------------------------------------------------------
; Local mirrors of constants that other files declare as plain (non-global)
; `equ` — NASM equ's are not linkable symbols, so a caller cannot `extern`
; them; each consuming file keeps its own copy at the same value (the
; existing convention: USING_INTERNAL_CLOCK etc. are re-equ'd in several
; files rather than shared).
; ---------------------------------------------------------------------------
NET_TRANSPORT_NONE        equ 0     ; src/net/net_hal.asm
LINKBOOK_FAMILY_TCP       equ 0     ; src/net/link_book.asm
LINKBOOK_FAMILY_IPX       equ 1     ; src/net/link_book.asm
LINKBOOK_SLOTS_PER_FAMILY equ 5     ; src/net/link_book.asm
LB_TERM                   equ 0x50  ; '@' — src/net/link_book.asm

; kbd_text.asm's CHARSET_* classes (also plain local equ there).
CHARSET_FREE equ 0
CHARSET_IP   equ 1
CHARSET_HEX  equ 2

; Mirrors src/net/link_book.asm's LBREC struc exactly (offsets only; no
; linkable struc symbol exists to extern). Kept in sync by hand — both files
; are this plan's Stage 5 steps 2/3, authored together.
struc LBREC
    .in_use: resb 1
    .name:   resb 16
    .addr:   resb 10
    .pad:    resb 5
    .size:
endstruc

CHAR_SPACE equ 0x7F         ; ' ' — matches link_menu.asm's own local equ

LU_STRIDE  equ 20           ; wTileMap scratch stride (matches LM_STRIDE)
%define LUB(X,Y)  (wTileMap + (Y) * LU_STRIDE + (X))       ; box-relative (GB-space offset)
%define LUN(X,Y)  (GB_TILEMAP0 + (Y) * 32 + (X))           ; native tilemap cell (GB-space offset)

LU_BOX_W equ 13             ; interior width  (UI_LINK_MENU_GBW - 2)
LU_BOX_H equ 8              ; interior height (UI_LINK_MENU_GBH - 2)

LU_NAME_MAX equ 15          ; chars (LBREC.name is 16 bytes incl. terminator)
LU_ADDR_MAX equ 19          ; chars (wStringBuffer is NAME_BUFFER_LENGTH=20 bytes)

; ---------------------------------------------------------------------------
; BSS — port-only state (flat, no GB WRAM allocation; same convention as
; kbd_text.asm's own per-invocation vars).
; ---------------------------------------------------------------------------
section .bss
align 4
lu_saved_wc:    resd 1      ; g_window_count baseline at LinkTransportSelect entry
lu_name_scratch: resb 16    ; staged NEW/EDIT name, before a record commit
lu_addr_scratch: resb 10    ; parsed binary address, staged before a record commit
lu_family:      resb 1      ; current book screen's family (0 TCP / 1 IPX)
lu_slot:        resb 1      ; record slot (0-4) the record submenu/NEW targets

; ---------------------------------------------------------------------------
; The generated strings (Tier-1 data; DO-NOT-EDIT header inside).
; ---------------------------------------------------------------------------
section .data
%include "assets/link_ui_strings.inc"

section .text

; ===========================================================================
; LinkTransportSelect — Out: AL=1 proceed / AL=0 cancel (player backed all
; the way out). See cable_club_npc.asm's seam for the DEVIATION annotation
; covering this call's insertion into CableClubNPC.
; ===========================================================================
LinkTransportSelect:
    cmp byte [g_net_transport], NET_TRANSPORT_NONE
    jne .already_bound          ; CLI flags/UI already selected a transport —
                                 ; net_hal.asm:109's own comment: the UI never
                                 ; second-guesses a bound link.

    mov eax, [g_window_count]
    mov [lu_saved_wc], eax

    call lu_draw_transport_menu
    call lu_show_window          ; mirrors + add_window, ONCE for this whole call
.transport_loop:
    call HandleMenuInput         ; Out: AL = watched keys pressed
    test al, PAD_B
    jnz .cancel_all
    movzx eax, byte [ebp + wCurrentMenuItem]
    cmp eax, 0
    je .do_serial
    cmp eax, 1
    je .do_ipx
    cmp eax, 2
    je .do_tcp
    jmp .cancel_all              ; item 3 = CANCEL
.do_serial:
    call lu_com_menu             ; Out: AL=1 bound / 0 cancelled-or-failed
    test al, al
    jnz .success
    jmp .redraw_transport
.do_ipx:
    mov bl, LINKBOOK_FAMILY_IPX
    call lu_book_screen
    jmp .redraw_transport
.do_tcp:
    mov bl, LINKBOOK_FAMILY_TCP
    call lu_book_screen
.redraw_transport:
    call lu_draw_transport_menu
    call lu_mirror
    jmp .transport_loop
.cancel_all:
    mov eax, [lu_saved_wc]
    mov [g_window_count], eax
    xor al, al
    ret
.success:
    mov eax, [lu_saved_wc]
    mov [g_window_count], eax
    mov al, 1
    ret
.already_bound:
    mov al, 1
    ret

; ---------------------------------------------------------------------------
; lu_mirror — blit the 15x10 scratch box (wTileMap origin) -> GB_TILEMAP0
; rows 0-9. Byte-for-byte link_menu.asm's lm_link_mirror. Preserves all regs.
; ---------------------------------------------------------------------------
lu_mirror:
    pushad
    xor ebx, ebx
.row:
    imul esi, ebx, LU_STRIDE
    lea esi, [ebp + esi + wTileMap]
    mov edi, ebx
    shl edi, 5                      ; x32 tilemap stride
    lea edi, [ebp + edi + GB_TILEMAP0]
    mov ecx, 15                     ; box width (cols 0-14)
    rep movsb
    inc ebx
    cmp ebx, 10                     ; box height (rows 0-9)
    jb .row
    popad
    ret

; ---------------------------------------------------------------------------
; lu_show_window — append the box as a sub-rect overlay window (called ONCE
; per LinkTransportSelect call; see file header). Byte-for-byte link_menu.asm's
; lm_link_show_window, at UI_LINK_MENU's own geometry.
; ---------------------------------------------------------------------------
lu_show_window:
    call lu_mirror
    mov eax, UI_LINK_MENU_WX
    mov ebx, UI_LINK_MENU_WY
    mov ecx, UI_LINK_MENU_CLIP
    mov edx, UI_LINK_MENU_MAXY
    mov esi, GB_TILEMAP0
    xor edi, edi
    call add_window
    ret

; ===========================================================================
; lu_draw_transport_menu — "HOW WILL YOU LINK?" + SERIAL/IPX/TCP-IP/CANCEL.
; Draws into the scratch and sets menu state; does NOT mirror/show (caller's
; job — see file header on the single add_window call).
; ===========================================================================
lu_draw_transport_menu:
    mov dword [text_row_stride], LU_STRIDE
    mov esi, LUB(0, 0)
    mov bl, LU_BOX_W
    mov bh, LU_BOX_H
    call TextBoxBorder

    mov eax, LinkUIStr_HowWillYouLink
    mov esi, LUB(1, 1)
    call PlaceString

    mov eax, LinkUIStr_Serial
    mov esi, LUB(2, 5)
    call PlaceString
    mov eax, LinkUIStr_IPX
    mov esi, LUB(2, 6)
    call PlaceString
    mov eax, LinkUIStr_TCPIP
    mov esi, LUB(2, 7)
    call PlaceString
    mov eax, LinkUIStr_Cancel
    mov esi, LUB(2, 8)
    call PlaceString

    mov byte [ebp + wTopMenuItemY], 5
    mov byte [ebp + wTopMenuItemX], 1
    mov byte [ebp + wCurrentMenuItem], 0
    mov byte [ebp + wMaxMenuItem], 3
    mov byte [ebp + wMenuWatchedKeys], PAD_A | PAD_B
    mov byte [ebp + wLastMenuItem], 0
    mov dword [menu_item_step], LU_STRIDE
    mov dword [menu_redraw_cb], lu_mirror
    ret

; ===========================================================================
; lu_com_menu — SERIAL sub-menu: COM1..COM4 + CANCEL.
; Out: AL=1 bound (g_net_transport now UART) / AL=0 cancelled or NetInit
; found no UART (error already shown either way the caller redraws the
; TRANSPORT menu, per the step-3 spec: "reopen the transport menu").
; ===========================================================================
lu_com_menu:
    call lu_draw_com_menu
    call lu_mirror
.loop:
    call HandleMenuInput
    test al, PAD_B
    jnz .cancelled
    movzx eax, byte [ebp + wCurrentMenuItem]
    cmp eax, 4
    je .cancelled                ; item 4 = CANCEL
    inc eax                      ; 0..3 -> COM1..COM4 (1..4)
    mov [g_net_com_sel], al
    call NetInit
    cmp byte [g_net_transport], NET_TRANSPORT_NONE
    jne .bound
    mov eax, LinkUIStr_NoPort
    call lu_show_message
    xor al, al
    ret
.bound:
    mov al, 1
    ret
.cancelled:
    xor al, al
    ret

lu_draw_com_menu:
    mov dword [text_row_stride], LU_STRIDE
    mov esi, LUB(0, 0)
    mov bl, LU_BOX_W
    mov bh, LU_BOX_H
    call TextBoxBorder

    mov eax, LinkUIStr_Com1
    mov esi, LUB(2, 1)
    call PlaceString
    mov eax, LinkUIStr_Com2
    mov esi, LUB(2, 2)
    call PlaceString
    mov eax, LinkUIStr_Com3
    mov esi, LUB(2, 3)
    call PlaceString
    mov eax, LinkUIStr_Com4
    mov esi, LUB(2, 4)
    call PlaceString
    mov eax, LinkUIStr_Cancel
    mov esi, LUB(2, 5)
    call PlaceString

    mov byte [ebp + wTopMenuItemY], 1
    mov byte [ebp + wTopMenuItemX], 1
    mov byte [ebp + wCurrentMenuItem], 0
    mov byte [ebp + wMaxMenuItem], 4
    mov byte [ebp + wMenuWatchedKeys], PAD_A | PAD_B
    mov byte [ebp + wLastMenuItem], 0
    mov dword [menu_item_step], LU_STRIDE
    mov dword [menu_redraw_cb], lu_mirror
    ret

; ===========================================================================
; lu_show_message — clear the box, draw EAX's (flat, generator-produced)
; string at (1,1), mirror, hold ~60 frames (1 second), return. Caller
; redraws its own real screen next; this never touches menu state.
; In: EAX = flat string pointer. Clobbers EAX/EBX/ECX/EDX/ESI/EDI.
; ===========================================================================
lu_show_message:
    push eax
    mov dword [text_row_stride], LU_STRIDE
    mov esi, LUB(0, 0)
    mov bl, LU_BOX_W
    mov bh, LU_BOX_H
    call TextBoxBorder
    pop eax
    mov esi, LUB(1, 1)
    call PlaceString
    call lu_mirror
    mov bl, 60
    call DelayFrames
    ret

; ===========================================================================
; lu_book_screen — In: BL = family (LINKBOOK_FAMILY_TCP/IPX). Loops the
; connection-book list until CANCEL/B; every action returns here to redraw.
; Out: none (caller always redraws its own screen — the transport menu —
; regardless of how the book screen exits).
; ===========================================================================
lu_book_screen:
    mov [lu_family], bl
    cmp byte [linkbook_loaded], 0
    jne .have_book
    call linkbook_load           ; lazy: only touched once the book screen opens
.have_book:
.redraw:
    call lu_draw_book_list
    call lu_mirror
.loop:
    call HandleMenuInput
    test al, PAD_B
    jnz .done
    movzx eax, byte [ebp + wCurrentMenuItem]
    cmp eax, 5
    je .row_direct_auto
    cmp eax, 6
    je .row_new
    cmp eax, 7
    je .done                     ; item 7 = CANCEL
    ; items 0-4: a record row
    mov [lu_slot], al
    mov ah, al
    mov al, [lu_family]
    call linkbook_record          ; ESI -> record; preserves EAX (AL still = family)
    cmp byte [esi + LBREC.in_use], 0
    je .loop                      ; EMPTY row selected -> no-op (NEW is the create path)
    call lu_record_menu           ; CONNECT/EDIT/DELETE/CANCEL for this record
    jmp .redraw
.row_direct_auto:
    mov bl, [lu_family]
    mov bh, 0xFF                  ; sentinel: no specific record
    call link_ui_connect_attempt
    jmp .redraw
.row_new:
    call lu_new_entry
    jmp .redraw
.done:
    ret

; ===========================================================================
; lu_draw_book_list — the 8-row book list: 5 records (name or EMPTY), then
; DIRECT (TCP)/AUTO (IPX), NEW, CANCEL. Exactly fills the 8-row interior —
; no header line (unlike the transport/COM menus, which have room to spare).
; ===========================================================================
lu_draw_book_list:
    mov dword [text_row_stride], LU_STRIDE
    mov esi, LUB(0, 0)
    mov bl, LU_BOX_W
    mov bh, LU_BOX_H
    call TextBoxBorder

    xor ebx, ebx
.rec_loop:
    mov ah, bl
    mov al, [lu_family]
    call linkbook_record           ; ESI -> record; preserves EAX; clobbers ECX/EDX only
    cmp byte [esi + LBREC.in_use], 0
    jne .rec_named
    mov eax, LinkUIStr_Empty
    jmp .rec_place
.rec_named:
    lea eax, [esi + LBREC.name]    ; flat pointer (book_image is port-only flat memory)
.rec_place:
    mov ecx, ebx
    inc ecx                        ; row = slot+1 (rows 1..5)
    imul ecx, ecx, LU_STRIDE
    lea esi, [ecx + wTileMap + 2]  ; col 2
    call PlaceString
    inc ebx
    cmp ebx, LINKBOOK_SLOTS_PER_FAMILY
    jb .rec_loop

    cmp byte [lu_family], LINKBOOK_FAMILY_TCP
    jne .row5_auto
    mov eax, LinkUIStr_Direct
    jmp .row5_place
.row5_auto:
    mov eax, LinkUIStr_Auto
.row5_place:
    mov esi, LUB(2, 6)
    call PlaceString

    mov eax, LinkUIStr_New
    mov esi, LUB(2, 7)
    call PlaceString

    mov eax, LinkUIStr_Cancel
    mov esi, LUB(2, 8)
    call PlaceString

    mov byte [ebp + wTopMenuItemY], 1
    mov byte [ebp + wTopMenuItemX], 1
    mov byte [ebp + wCurrentMenuItem], 0
    mov byte [ebp + wMaxMenuItem], 7
    mov byte [ebp + wMenuWatchedKeys], PAD_A | PAD_B
    mov byte [ebp + wLastMenuItem], 0
    mov dword [menu_item_step], LU_STRIDE
    mov dword [menu_redraw_cb], lu_mirror
    ret

; ===========================================================================
; lu_record_menu — per-record CONNECT/EDIT/DELETE/CANCEL submenu. In:
; lu_family/lu_slot already set by the caller (lu_book_screen). Out: none —
; caller always redraws the book list next.
; ===========================================================================
lu_record_menu:
    call lu_draw_record_menu
    call lu_mirror
.loop:
    call HandleMenuInput
    test al, PAD_B
    jnz .back
    movzx eax, byte [ebp + wCurrentMenuItem]
    cmp eax, 0
    je .do_connect
    cmp eax, 1
    je .do_edit
    cmp eax, 2
    je .do_delete
    jmp .back                    ; item 3 = CANCEL
.do_connect:
    mov bl, [lu_family]
    mov bh, [lu_slot]
    call link_ui_connect_attempt
    jmp .back
.do_edit:
    call lu_edit_entry
    jmp .back
.do_delete:
    call lu_delete_entry
.back:
    ret

lu_draw_record_menu:
    mov dword [text_row_stride], LU_STRIDE
    mov esi, LUB(0, 0)
    mov bl, LU_BOX_W
    mov bh, LU_BOX_H
    call TextBoxBorder

    mov eax, LinkUIStr_Connect
    mov esi, LUB(2, 1)
    call PlaceString
    mov eax, LinkUIStr_Edit
    mov esi, LUB(2, 2)
    call PlaceString
    mov eax, LinkUIStr_Delete
    mov esi, LUB(2, 3)
    call PlaceString
    mov eax, LinkUIStr_Cancel
    mov esi, LUB(2, 4)
    call PlaceString

    mov byte [ebp + wTopMenuItemY], 1
    mov byte [ebp + wTopMenuItemX], 1
    mov byte [ebp + wCurrentMenuItem], 0
    mov byte [ebp + wMaxMenuItem], 3
    mov byte [ebp + wMenuWatchedKeys], PAD_A | PAD_B
    mov byte [ebp + wLastMenuItem], 0
    mov dword [menu_item_step], LU_STRIDE
    mov dword [menu_redraw_cb], lu_mirror
    ret

; ===========================================================================
; link_ui_connect_attempt — port-only seam. In: BL = family
; (LINKBOOK_FAMILY_TCP/IPX), BH = record slot (0-4) or 0xFF for the
; DIRECT/AUTO row (no specific record). Stage 5 has no IPX/TCP transport at
; all — this ALWAYS shows "NOT IN THIS BUILD!" and returns; it never
; touches g_net_transport, the UART, or the serial.asm HAL path. Stage 6/7
; are expected to replace this body with a real bind keyed on
; family/slot/g_net_transport, keeping this same entry point and contract
; (In:/Out: as documented here) so lu_book_screen/lu_record_menu need no
; changes. Out: none. Clobbers as a normal internal call.
; ===========================================================================
link_ui_connect_attempt:
    mov eax, LinkUIStr_NotInBuild
    call lu_show_message
    ret

; ===========================================================================
; lu_new_entry — find a free slot in lu_family's book (show FULL! if none),
; then hand off to the shared NEW/EDIT name+address flow.
; ===========================================================================
lu_new_entry:
    xor ebx, ebx
.find_loop:
    mov ah, bl
    mov al, [lu_family]
    call linkbook_record
    cmp byte [esi + LBREC.in_use], 0
    je .found_free
    inc ebx
    cmp ebx, LINKBOOK_SLOTS_PER_FAMILY
    jb .find_loop
    mov eax, LinkUIStr_Full
    call lu_show_message
    ret
.found_free:
    mov [lu_slot], bl
    jmp lu_new_edit_common

; ===========================================================================
; lu_edit_entry — In: lu_family/lu_slot already set (by lu_record_menu, on
; an existing in-use record). Shares the NEW flow's name+address prompts;
; per kbd_text_edit's contract (file header) the fields start EMPTY, not
; pre-seeded with the record's current name/address.
; ===========================================================================
lu_edit_entry:
    ; falls through to the shared flow below

; ---------------------------------------------------------------------------
; lu_new_edit_common — prompt NAME, stage it, then hand off to
; lu_finish_addr_entry (which prompts/parses/commits the ADDRESS and does
; the actual record write). Nothing is written to book_image until BOTH
; fields commit successfully, so a cancel at either prompt leaves the
; record exactly as it was.
; ---------------------------------------------------------------------------
lu_new_edit_common:
    call lu_prompt_name
    test al, al
    jz .cancelled
    lea esi, [ebp + wStringBuffer]
    mov edi, lu_name_scratch
    mov ecx, 16
    rep movsb
    call lu_finish_addr_entry
.cancelled:
    ret

; ===========================================================================
; lu_prompt_name — "NAME?" + kbd_text_edit (free charset, max 15 chars) into
; wStringBuffer. Out: AL = 1 committed / 0 cancelled (kbd_text_edit's own
; contract, passed straight through).
; ===========================================================================
lu_prompt_name:
    mov dword [text_row_stride], LU_STRIDE
    mov esi, LUB(0, 0)
    mov bl, LU_BOX_W
    mov bh, LU_BOX_H
    call TextBoxBorder
    mov eax, LinkUIStr_NamePrompt
    mov esi, LUB(1, 1)
    call PlaceString
    call lu_mirror

    mov esi, wStringBuffer
    mov bl, LU_NAME_MAX
    mov bh, CHARSET_FREE
    mov edx, LUN(1, 3)              ; native tilemap cell -- see file header
    call kbd_text_edit
    ret

; ===========================================================================
; lu_prompt_address — "ADDRESS?" + kbd_text_edit (IP charset for TCP / hex
; charset for IPX, max LU_ADDR_MAX chars) into wStringBuffer. Out: AL = 1
; committed / 0 cancelled.
; ===========================================================================
lu_prompt_address:
    mov dword [text_row_stride], LU_STRIDE
    mov esi, LUB(0, 0)
    mov bl, LU_BOX_W
    mov bh, LU_BOX_H
    call TextBoxBorder
    mov eax, LinkUIStr_AddressPrompt
    mov esi, LUB(1, 1)
    call PlaceString
    call lu_mirror

    mov esi, wStringBuffer
    mov bl, LU_ADDR_MAX
    cmp byte [lu_family], LINKBOOK_FAMILY_TCP
    jne .hex
    mov bh, CHARSET_IP
    jmp .go
.hex:
    mov bh, CHARSET_HEX
.go:
    mov edx, LUN(1, 3)
    call kbd_text_edit
    ret

; ===========================================================================
; lu_finish_addr_entry — prompt+parse+commit the address for lu_slot/
; lu_family, retrying on bad input; lu_name_scratch already holds the staged
; name. Out: none. On success: writes name+addr+in_use into the record,
; calls linkbook_store, shows SAVED!. On cancel: record untouched.
; ===========================================================================
lu_finish_addr_entry:
.retry:
    call lu_prompt_address
    test al, al
    jz .done                        ; cancelled -- nothing was ever written
    cmp byte [lu_family], LINKBOOK_FAMILY_TCP
    jne .parse_ipx
    call lu_parse_tcp_addr          ; Out: CF=1 bad
    jmp .parsed
.parse_ipx:
    call lu_parse_ipx_addr
.parsed:
    jc .bad
    ; --- commit: name, then addr, then in_use+persist (three cheap
    ; linkbook_record calls rather than juggling a saved pointer across two
    ; rep movsb copies) ---
    mov ah, [lu_slot]
    mov al, [lu_family]
    call linkbook_record
    lea edi, [esi + LBREC.name]
    mov esi, lu_name_scratch
    mov ecx, 16
    rep movsb

    mov ah, [lu_slot]
    mov al, [lu_family]
    call linkbook_record
    lea edi, [esi + LBREC.addr]
    mov esi, lu_addr_scratch
    mov ecx, 10
    rep movsb

    mov ah, [lu_slot]
    mov al, [lu_family]
    call linkbook_record
    mov byte [esi + LBREC.in_use], 1
    call linkbook_store
    mov eax, LinkUIStr_Saved
    call lu_show_message
.done:
    ret
.bad:
    mov eax, LinkUIStr_BadAddress
    call lu_show_message
    jmp .retry

; ===========================================================================
; lu_delete_entry — "DELETE?" + YesNoChoice; on YES, zero the record and
; persist. See file header: YesNoChoice is safe to call with this file's
; own window still up (disjoint wTileMap rows / disjoint GB_TILEMAP0 rows).
; ===========================================================================
lu_delete_entry:
    mov dword [text_row_stride], LU_STRIDE
    mov esi, LUB(0, 0)
    mov bl, LU_BOX_W
    mov bh, LU_BOX_H
    call TextBoxBorder
    mov eax, LinkUIStr_DeleteConfirm
    mov esi, LUB(2, 1)
    call PlaceString
    call lu_mirror

    call YesNoChoice
    mov al, [ebp + wCurrentMenuItem]
    test al, al
    jnz .done                       ; chose NO

    mov ah, [lu_slot]
    mov al, [lu_family]
    call linkbook_record
    mov edi, esi
    xor al, al
    mov ecx, LBREC.size
    rep stosb
    call linkbook_store
    mov eax, LinkUIStr_Saved
    call lu_show_message
.done:
    ret

; ===========================================================================
; lu_parse_tcp_addr — parses wStringBuffer ("a.b.c.d:port@", charset-
; restricted to digits/./:) into lu_addr_scratch (10 bytes, TCP layout: 4
; octets big-endian, port big-endian, 4 unused bytes zeroed). Out: CF=0 ok /
; CF=1 bad (bad range, wrong shape, or text left over after the port).
; Clobbers EAX/EBX/ECX/EDX/ESI/EDI.
; ===========================================================================
lu_parse_tcp_addr:
    mov esi, wStringBuffer
    mov edi, lu_addr_scratch
    push edi
    xor eax, eax
    mov ecx, 10
    rep stosb                       ; zero the whole field first (unused tail)
    pop edi

    mov ecx, 4
.octet_loop:
    call lu_read_decimal            ; Out: EAX=value EBX=digit_count CF=1 none
    jc .bad
    test ebx, ebx
    jz .bad
    cmp eax, 255
    ja .bad
    mov [edi], al                   ; lu_addr_scratch is FLAT (not GB-space)
    inc edi
    dec ecx
    jz .after_octets
    cmp byte [ebp + esi], 0xE8      ; '.'
    jne .bad
    inc esi
    jmp .octet_loop
.after_octets:
    cmp byte [ebp + esi], 0x9C      ; ':'
    jne .bad
    inc esi
    call lu_read_decimal            ; port
    jc .bad
    test ebx, ebx
    jz .bad
    cmp eax, 65535
    ja .bad
    cmp byte [ebp + esi], LB_TERM
    jne .bad
    mov ebx, eax
    mov edi, lu_addr_scratch + 4
    mov eax, ebx
    shr eax, 8
    mov [edi], al                   ; port hi
    mov al, bl
    mov [edi + 1], al               ; port lo
    clc
    ret
.bad:
    stc
    ret

; ===========================================================================
; lu_parse_ipx_addr — parses wStringBuffer ("net:node@", charset-restricted
; to hex digits/:) into lu_addr_scratch (10 bytes, IPX layout: 4-byte net
; big-endian, 6-byte node in transmission order). net is 1-8 hex digits
; (<=32 bits), node is 1-12 hex digits (<=48 bits, held as EDX:EBX during
; accumulation via shld). Out: CF=0 ok / CF=1 bad. Clobbers
; EAX/EBX/ECX/EDX/ESI/EDI.
; ===========================================================================
lu_parse_ipx_addr:
    mov esi, wStringBuffer
    xor ebx, ebx
    xor ecx, ecx
.net_loop:
    call lu_hex_nibble               ; In: [ebp+esi]; Out: CF=1 not hex, else AL=nibble
    jc .net_done
    cmp ecx, 8
    jae .bad
    shl ebx, 4
    movzx eax, al
    or ebx, eax
    inc esi
    inc ecx
    jmp .net_loop
.net_done:
    test ecx, ecx
    jz .bad
    cmp byte [ebp + esi], 0x9C       ; ':'
    jne .bad
    inc esi
    mov eax, ebx
    bswap eax
    mov [lu_addr_scratch], eax       ; net, big-endian

    xor edx, edx
    xor ebx, ebx
    xor ecx, ecx
.node_loop:
    call lu_hex_nibble
    jc .node_done
    cmp ecx, 12
    jae .bad
    shld edx, ebx, 4
    shl ebx, 4
    movzx eax, al
    or ebx, eax
    inc esi
    inc ecx
    jmp .node_loop
.node_done:
    test ecx, ecx
    jz .bad
    cmp byte [ebp + esi], LB_TERM
    jne .bad
    and edx, 0xFFFF
    mov ax, dx
    xchg al, ah                      ; AX = node's top 16 bits, big-endian in AL:AH order
    mov [lu_addr_scratch + 4], ax
    mov eax, ebx
    bswap eax
    mov [lu_addr_scratch + 6], eax   ; node's low 32 bits, big-endian
    clc
    ret
.bad:
    stc
    ret

; ---------------------------------------------------------------------------
; lu_read_decimal — accumulate consecutive decimal-digit charmap bytes
; (0xF6-0xFF = '0'-'9') at [ebp+esi]. In: ESI = GB-space text ptr. Out: EAX
; = accumulated value, EBX = digit count, ESI advanced past the digits (left
; on the first non-digit). CF=1 iff EBX==0 (no digits consumed at all).
; No overflow guard: every caller rejects any EAX outside its valid range
; regardless, and the charset filter (kbd_text.asm KbdCharsetRanges_IP)
; already keeps the source to digits/./: so a run long enough to overflow
; EAX can't occur from a field capped at LU_ADDR_MAX characters.
; ---------------------------------------------------------------------------
lu_read_decimal:
    xor eax, eax
    xor ebx, ebx
.loop:
    mov cl, [ebp + esi]
    cmp cl, 0xF6
    jb .done
    cmp cl, 0xFF
    ja .done
    sub cl, 0xF6
    movzx ecx, cl
    imul eax, eax, 10
    add eax, ecx
    inc esi
    inc ebx
    jmp .loop
.done:
    test ebx, ebx
    jz .none
    clc
    ret
.none:
    stc
    ret

; ---------------------------------------------------------------------------
; lu_hex_nibble — In: [ebp+esi] (NOT advanced -- caller advances only on
; acceptance, so a rejected byte is left for the caller's own next check,
; e.g. the ':' separator). Out: CF=1 not a hex-digit charmap byte; else
; CF=0, AL = nibble value 0-15 ('0'-'9' -> 0-9, 'A'-'F' -> 10-15).
; ---------------------------------------------------------------------------
lu_hex_nibble:
    mov al, [ebp + esi]
    cmp al, 0xF6
    jb .try_af
    cmp al, 0xFF
    ja .try_af
    sub al, 0xF6
    clc
    ret
.try_af:
    cmp al, 0x80
    jb .bad
    cmp al, 0x85
    ja .bad
    sub al, 0x80
    add al, 10
    clc
    ret
.bad:
    stc
    ret
